### ISSUE TITLE
Request: Delete old package

### ISSUE THREAD

**Issue by jamisonbryant** [composer/packagist#1000]
Hello,

I am the owner of [syntaxera/cakephp-secureids-plugin](https://packagist.org/packages/syntaxera/cakephp-secureids-plugin). I have recently migrated my code to Gitlab and so would like this package DELETED and replaced with THIS package:

https://gitlab.com/jamisonbryant/cakephp-secureids-plugin

My identity and my ownership of the package can be verified by examining my GitHub profile and the commit history on the package. If additional verification is required, please let me know.

For now, I am SUBMITTING the new package on Packagist, but I don't want my users to become confused and not know which to use. Can you delete the old package, pretty please?

Thanks!

**EDIT:** I have marked the old package as abandoned on Packagist, and pointed it to the new one.

**Comment by alcohol** [comment]
You cannot manually delete a package from packagist.org once it has crossed a certain threshold of downloads. Please reach out to contact@packagist.org for deletion enquiries.
