### ISSUE TITLE
Packagist API total": [number of results]   is incorrect

### ISSUE THREAD

**Issue by naifalshaye** [composer/packagist#1003]
I've been trying to consume your API and I get the response, but the "total": [number of results]  I'm pretty sure 6263 records it's not correct.

How to solve this?

**Comment by stof** [comment]
Please provide more details about how you got the issue. There is not enough info to reproduce the issue here.

**Comment by naifalshaye** [comment]
When sending a GET request to https://packagist.org/search.json with q parameter to search Packagist. 

For example: https://packagist.org/search.json?q=mail
Response:
-------------------------------------------------
{
    "results": [
        {
            "name": "swiftmailer/swiftmailer",
            "description": "Swiftmailer, free feature-rich PHP mailer",
            "url": "https://packagist.org/packages/swiftmailer/swiftmailer",
            "repository": "https://github.com/swiftmailer/swiftmailer",
            "downloads": 108573307,
            "favers": 7921
        },
        {
            "name": "mailgun/mailgun-php",
            "description": "The Mailgun SDK provides methods for all API functions.",
            "url": "https://packagist.org/packages/mailgun/mailgun-php",
            "repository": "https://github.com/mailgun/mailgun-php",
            "downloads": 4536374,
            "favers": 856
        },
        {
            "name": "drewm/mailchimp-api",
            "description": "Super-simple, minimum abstraction MailChimp API v3 wrapper",
            "url": "https://packagist.org/packages/drewm/mailchimp-api",
            "repository": "https://github.com/drewm/mailchimp-api",
            "downloads": 2954329,
            "favers": 1653
        },
        {
            "name": "php-imap/php-imap",
            "description": "Manage mailboxes, filter/get/delete emails in PHP (supports IMAP/POP3/NNTP)",
            "url": "https://packagist.org/packages/php-imap/php-imap",
            "repository": "https://github.com/barbushin/php-imap",
            "downloads": 874760,
            "favers": 995
        },
        {
            "name": "hwi/oauth-bundle",
            "description": "Support for authenticating users using both OAuth1.0a and OAuth2 in Symfony2.",
            "url": "https://packagist.org/packages/hwi/oauth-bundle",
            "repository": "https://github.com/hwi/HWIOAuthBundle",
            "downloads": 5177926,
            "favers": 1865
        },
        {
            "name": "zendframework/zend-mail",
            "description": "Provides generalized functionality to compose and send both text and MIME-compliant multipart e-mail messages",
            "url": "https://packagist.org/packages/zendframework/zend-mail",
            "repository": "https://github.com/zendframework/zend-mail",
            "downloads": 4742120,
            "favers": 76
        },
        {
            "name": "themsaid/laravel-mail-preview",
            "description": "Adds a 'preview' mail driver for testing emails in laravel.",
            "url": "https://packagist.org/packages/themsaid/laravel-mail-preview",
            "repository": "https://github.com/themsaid/laravel-mail-preview",
            "downloads": 135046,
            "favers": 649
        },
        {
            "name": "php-mime-mail-parser/php-mime-mail-parser",
            "description": "A fully tested email parser for PHP 7.1+ (mailparse extension wrapper).",
            "url": "https://packagist.org/packages/php-mime-mail-parser/php-mime-mail-parser",
            "repository": "https://github.com/php-mime-mail-parser/php-mime-mail-parser",
            "downloads": 649852,
            "favers": 470
        },
        {
            "name": "nette/mail",
            "description": "📧 Nette Mail: handy email creation and transfer library for PHP with both text and MIME-compliant support.",
            "url": "https://packagist.org/packages/nette/mail",
            "repository": "https://github.com/nette/mail",
            "downloads": 1883958,
            "favers": 243
        },
        {
            "name": "tightenco/mailthief",
            "description": "A fake Mailer for Laravel applications that takes the pain out of testing mail.",
            "url": "https://packagist.org/packages/tightenco/mailthief",
            "repository": "https://github.com/tightenco/mailthief",
            "downloads": 288173,
            "favers": 658
        },
        {
            "name": "mailjet/mailjet-apiv3-php",
            "description": "PHP wrapper for the Mailjet API",
            "url": "https://packagist.org/packages/mailjet/mailjet-apiv3-php",
            "repository": "https://github.com/mailjet/mailjet-apiv3-php",
            "downloads": 660475,
            "favers": 131
        },
        {
            "name": "fedeisas/laravel-mail-css-inliner",
            "description": "Inline the CSS of your HTML emails using Laravel",
            "url": "https://packagist.org/packages/fedeisas/laravel-mail-css-inliner",
            "repository": "https://github.com/fedeisas/laravel-mail-css-inliner",
            "downloads": 666656,
            "favers": 352
        },
        {
            "name": "yiisoft/yii2-swiftmailer",
            "description": "The SwiftMailer integration for the Yii framework",
            "url": "https://packagist.org/packages/yiisoft/yii2-swiftmailer",
            "repository": "https://github.com/yiisoft/yii2-swiftmailer",
            "downloads": 5387734,
            "favers": 105
        },
        {
            "name": "ddeboer/imap",
            "description": "Object-oriented IMAP for PHP",
            "url": "https://packagist.org/packages/ddeboer/imap",
            "repository": "https://github.com/ddeboer/imap",
            "downloads": 337225,
            "favers": 536
        },
        {
            "name": "spatie/laravel-newsletter",
            "description": "Manage newsletters in Laravel",
            "url": "https://packagist.org/packages/spatie/laravel-newsletter",
            "repository": "https://github.com/spatie/laravel-newsletter",
            "downloads": 717895,
            "favers": 960
        }
    ],
    "total": 6269,
    "next": "https://packagist.org/search.json?q=mail&page=2"
}
-------------------------------------------------
There is a problem with the total.
Total / results per page = pages
6269/15 = 418
So if you try to call the endpoint with page 400 the link should be
https://packagist.org/search.json?q=mail&page=400

Which of course will give 0 results.

**Comment by stof** [comment]
@julienbourdeau any idea why algolia returns a mismatch between the `nbHits` (which is what gets returned in `total` and the actual pagination ?
I tried this search with different pages, and it looks like the search returns 1000 results at most before reaching the end of the pagination (and then returns `nbHits` as 0 for later pages).

**Comment by stof** [comment]
OK, it looks like this is related to the pagination limitations of algolia: https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/how-to/pagination/#pagination-limitations

**Comment by naifalshaye** [comment]
So you will fixe it from your side or there is a solution I can implement?

**Comment by naifalshaye** [comment]
Any updates?

**Comment by stof** [comment]
Well, AFAICT, there is no way to solve that entirely. that's how Algolia work. Packagist could increase the pagination limit, but it will still need to exist.

Maybe it could make sense to cap the number of hits to avoid reporting more than the pagination limit. @julienbourdeau should this be done by Algolia itself ?

**Comment by julienbourdeau** [comment]
Hi,

Yes, Algolia stops paginating after 1,000 results. You can increase this number via the `paginationLimitedTo` settings but it's not recommended since it will have effects on performance.

This limitation exists because we think, in a search use case, you don't look at the 1005th results on page 101. It's most likely not what you are looking for.

If you wan to browse all results, typically to export them, you should use the browse endpoint on Algolia, which doesn't have this limitation. I don't think it's available on packagist.

@naifalshaye Can you tell us a bit more about what you're doing and why you need to access results over 1,000? There might be a good reason to expose a new endpoint.

**Comment by julienbourdeau** [comment]
@stof Yes, you can also return 1,000 if nbHits>1,000 but I don't like it as much. I prefer to get the correct number of results and not being able to access it.

**Comment by naifalshaye** [comment]
I'm just searching Packagist to display results to users to install the package they want. The pagination display all pages which user might try to reach and ended up with no results on this page.

**Comment by julienbourdeau** [comment]
They might, but honestly I don't think this will ever happen. ^^
I'd recommend not changing `paginationLimitedTo` on packagist index config.

We could add pagination details to the response tho:
* current page
* total nb of page
* nb results per page
These details are part of the Algolia response.

**Comment by naifalshaye** [comment]
I totally agree with you. But how I would know the last page that has results to not display any pages after that?

**Comment by stof** [comment]
@julienbourdeau but do these detail take the pagination limit into account or no ?

**Comment by julienbourdeau** [comment]
Yes, it will give you the number of last page accessible by algolia (so to get the 1,000th result).

**Comment by naifalshaye** [comment]
That's would be awesome, thanks

**Comment by alcohol** [comment]
I can't see a user browsing beyond 10 pages, let alone beyond 100. Not really an issue.
