### ISSUE TITLE
Use composer --dry-run to check package success

### ISSUE THREAD

**Issue by beberlei** [composer/packagist#101]
When new releases are detected by packagist it could use `composer install --dry-run` installation to check if all dependencies resolve fine.

**Comment by peter-mw** [comment]
Hello. sorry to bring up an old issue. 

I searched google for [composer check for updates](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=composer%20check%20for%20updates) and i have a question:

Is there a way to check for updates without making any modifications to the `vendor` folder?

**Comment by curry684** [comment]
`composer update --dry-run`

**Comment by peter-mw** [comment]
thanks @curry684
