### ISSUE TITLE
New Mirror Server in India

### ISSUE THREAD

**Issue by varunsridharan** [composer/packagist#1010]
Hi All

Today i created a new mirror server for (https://packagist.org) in india 
the website url is https://packagist.in/ please add this in ur mirrors list.

**Comment by alcohol** [comment]
> If you are interested in running your own mirror, we recommend using Webysther's mirror code to avoid duplicating efforts and then sending us a pull request to get your mirror added to the list above.

**Comment by varunsridharan** [comment]
@alcohol yes i am already using his code
https://github.com/Webysther/packagist-mirror

**Comment by alcohol** [comment]
I think you forgot to read until the end of the sentence..

**Comment by varunsridharan** [comment]
@alcohol oops!! sorry 😀
