### ISSUE TITLE
Packagist is not detecting new versions of my package

### ISSUE THREAD

**Issue by reisraff** [composer/packagist#1011]
my package:

https://packagist.org/packages/reisraff/phulp

<img src="https://i.imgur.com/MhycZ0c.png" />

**Comment by reisraff** [comment]
It was because I did not update the version in compose.json.

sorry for that.

**Comment by stof** [comment]
you should really remove the version from the composer.json. When hosting the package in a VCS reason, having the version explicitly only has drawbacks, no benefits.
