### ISSUE TITLE
[RFC] Two-Factor Authentication

### ISSUE THREAD

**Issue by colinodell** [composer/packagist#1020]
Would you consider implementing two-factor authentication to help protect accounts of package publishers?  I don't have any specific implementation in mind - I just know that other package manager sites (like npm) allow 2FA and it seems like a good security measure.

**Comment by hopeseekr** [comment]
I think I'll go ahead and implement the PR for this, at least using The Time-based One-Time Password algorithm (TOTP), RFC 6238, basically the same thing that's compatible with Google 2FA.

Once I begin in earnest, I'll update this issue. Of course, it'll be in my fork without any guarantee this project will actually merge it.

**Comment by alcohol** [comment]
I think any reasonable PR which introduces 2FA would be welcome. Anything that is compatible with apps such as Google Authenticator (or Authy, preferably) would be good. Definitely not mobile text message based or such as we do not have the resources to work with that.

**Comment by stof** [comment]
a TOTP implementation would support both Google Authenticator and Authy automatically, as they are both TOTP apps (and would also support other TOTP apps)

**Comment by colinodell** [comment]
I've begun working on a TOTP implementation and hope to have that ready for review soon.

Would there be any interest in also allowing email-based 2FA and/or backup codes?

**Comment by stof** [comment]
IMO, backup codes are indeed useful, to prevent locking someone off their account entirely if their phone with the TOTP app gets stolen (and they don't use a TOTP app supporting backup of the config like Authy does).

**Comment by alcohol** [comment]
I don't see why not. QR code should not be leading functionally speaking, it should be an additional feature. As you said, not all apps support QR code as input.

**Comment by colinodell** [comment]
Good call!  I have updated my PR to expose the key: https://github.com/composer/packagist/pull/1031#issuecomment-540543058

**Comment by TheArKaID** [comment]
Umm guys, I lost my 2FA and also my backup code so that I cannot pass the 2FA screen. Is there any other way to log in ? Something like `Reset Password` that sent to the email ?

**Comment by Seldaek** [comment]
@TheArKaID I disabled it for you
