### ISSUE TITLE
Reinsert Deleted Package: The vendor is already taken by someone else

### ISSUE THREAD

**Issue by Sioweb** [composer/packagist#1025]
Good Morning,

we get this information when we try to resubmit a deleted package:

```
The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at oxid-community
```

Its this package: https://github.com/OXIDprojects/oxid-symfony-kernel  

Maybe u could have a look on this please?

Thy & Have a nice day

**Comment by stof** [comment]
From a quick look on packagist, the other `oxid-community/*` packages added on packagist have https://packagist.org/users/oxid-community/ as their maintainer. So only this packagist user is allowed to add the package. Make sure you are logged in as that user, or ask that user to add your account as a maintainer of one of the existing packages, to grant you access to using this vendor name.

**Comment by Sioweb** [comment]
Thy for answere,

yeh the account owner tryed this. We deleted it to rename it from `oxidcommunity` to `oxid-community`, now we cannot add it again.

**Comment by Seldaek** [comment]
@Sioweb the owner of the oxid-community vendor at the moment is the oxid-community account which is registered to Marco.Steinhaeuser@oxid-esales.com - if you can reach out to him and get him to add the package or add you as maintainer that would be the ideal solution here. If you can't resolve it let me know

**Comment by Sioweb** [comment]
Hi @Seldaek,

Marco can't add it - i opened this ticket in representation for him :)

The Story behind was a little bad:

1. I created the package and uploaded it as "sioweb/oxid-kernel".
2. I Deleted the package and gave it to oxid-community / Marco
3. He uploaded it with name "oxidcommunity" (Because i missspelled it)
4. He deleted the package
5. We try to reinstall it with vendorname "oxid-community" and we get the error

Maybe some cache or something's not deleted correctly.

**Comment by Seldaek** [comment]
Are you sure Marco used the right account (oxid-community) to try and submit it? If he got that error about the vendor being taken by someone else it sounds like he wasn't in the right account.. But anyway I added the package to oxid-community's account https://packagist.org/packages/oxid-community/symfony-kernel - so he can then make sure auto-updates are working etc, or grant you access if that's desired.

**Comment by Sioweb** [comment]
Hi @Seldaek 

im sorry for asking again, but it seams Marco has no permissions to this package anymore - he cant update nor add maintainers atm. Even updating (auto-update) from github doesnt work. 

Is there an option we missed, or does something went wrong when u added the package?

THX & Have a nice day

**Comment by Seldaek** [comment]
I'd suggest he does a password reset for the `oxid-community` username (email Marco.Steinhaeuser@oxid-esales.com) to get access again if he lost access..

**Comment by Sioweb** [comment]
He has access, but the buttons Update, Abandon, Delete ... wont appear. Also "Add Maintainier" Plus icon doesnt show up.

**Comment by Seldaek** [comment]
I don't see how that's possible if he is logged into the right account sorry.. Check https://packagist.org/profile/

**Comment by Sioweb** [comment]
His account name is kermie, maybe thats the problem, there is no known oxid-community account.

![Screenshot_2019-08-05 oxid-community symfony-kernel - Packagist (1)](https://user-images.githubusercontent.com/1318048/62468699-fc74c800-b796-11e9-8a41-261fba61f4f9.png)

**Comment by Seldaek** [comment]
There is an oxid-community account linked to his email, if you click on Marco's avatar on that page you will see it links to it (https://packagist.org/users/oxid-community/). Kermie also exists but with another email and it indeed has no access to the oxid-community/* packages. As I said.. use the password reset form to regain access to the account.
