### ISSUE TITLE
[BUG] The update button remains pending and the new release is not added 

### ISSUE THREAD

**Issue by astronati** [composer/packagist#1027]
Today I'm having an issue on https://packagist.org. Pressing UPDATE button the spinner appears on the button and it does not disappear.
The update request is not addressed.

**Comment by kalesh13** [comment]
Looks like packagist is having some crawling issues. I am also experiencing the same. Hope they fix it soon.

**Comment by astronati** [comment]
@kalesh13 do you know if there is any status page or support one?

**Comment by kalesh13** [comment]
I don't know. I've never experienced something like this before. Search the issues for "This package has not been crawled yet, some information is missing." and you will see a closed issue. So, they should be responding to this thread as well.

**Comment by kalesh13** [comment]
Please read this and see if it is helpful https://github.com/composer/packagist/issues/1026#issuecomment-516359419

**Comment by astronati** [comment]
@kalesh13 How should that fix my issue? mmm 🤔

**Comment by Jakiboy** [comment]
unable to update! have the same issue :/

**Comment by SerafimArts** [comment]
Same

### GitHub Webhook

![image](https://user-images.githubusercontent.com/2461257/63641300-93f17a80-c6b4-11e9-8b31-9d1bdb70d434.png)

### Result

![image](https://user-images.githubusercontent.com/2461257/63641306-abc8fe80-c6b4-11e9-941a-50d20c9e17b6.png)

**Comment by kalesh13** [comment]
Looks like, the issue is resolved now.

**Comment by SerafimArts** [comment]
Yep 👍
