### ISSUE TITLE
SITE DOWN

### ISSUE THREAD

**Issue by jaykepeters** [composer/packagist#1028]
502 bad gateway

**Comment by Seldaek** [comment]
If you are still seeing this, please report the IP packagist.org resolves to for you. It makes investigating a lot easier.

**Comment by jaykepeters** [comment]
54.39.172.221

**Comment by allejo** [comment]
```
$ host packagist.org
packagist.org has address 142.44.164.249
packagist.org has IPv6 address 2607:5300:201:2100::7:2273
```

**Comment by jaykepeters** [comment]
Edited my hosts file for now…

Thanks for the help!

**Comment by jaykepeters** [comment]
I should've just did a dig @1.1.1.1 as I usually do when a site is not working properly. I do have Pi-hole on my network, but I have no idea why it resolved to the previously mentioned IP address... I will investigate.

**Comment by Seldaek** [comment]
@jaykepeters what do you mean edited your host file? Also where did 54.39.172.221 come from? I don't see this IP at all in our servers..

As for 142.44.164.249 @allejo it seems to work all fine?

**Comment by jaykepeters** [comment]
I added the 142.x.x.x IP to my hosts file to bypass my local dns resolver so that the web site displays properly. I will get back to you with the source.

**Comment by allejo** [comment]
I was using `1.1.1.1` for my DNS and I kept getting 502s intermittently. Used my regular DNS instead and it seems to be resolving for me now.

**Comment by jaykepeters** [comment]
It seems that some public DNS resolvers are reporting `54.39.172.221` as the IP address of `packagist.org`, including `1.1.1.1` instead of `54.39.172.221`. You can request a domain to be cleared from Cloudflare's cache, but if it's wrong at Cloudflare or Google DNS, something is definitely wrong. See here: https://www.whatsmydns.net/#A/packagist.org

**Comment by jaykepeters** [comment]
```bash
dig packagist.org @1.1.1.1

; <<>> DiG 9.10.6 <<>> packagist.org @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18541
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
;; QUESTION SECTION:
;packagist.org.			IN	A

;; ANSWER SECTION:
packagist.org.		120	IN	A	142.44.164.249

;; Query time: 23 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Sep 08 01:48:25 CDT 2019
;; MSG SIZE  rcvd: 58
```
```bash
dig packagist.org @8.8.8.8

; <<>> DiG 9.10.6 <<>> packagist.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64061
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;packagist.org.			IN	A

;; ANSWER SECTION:
packagist.org.		119	IN	A	142.44.164.249

;; Query time: 43 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Sep 08 01:48:54 CDT 2019
;; MSG SIZE  rcvd: 58
```
```bash
dig packagist.org @9.9.9.9

; <<>> DiG 9.10.6 <<>> packagist.org @9.9.9.9
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14291
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;packagist.org.			IN	A

;; ANSWER SECTION:
packagist.org.		32	IN	A	142.44.164.255

;; Query time: 19 msec
;; SERVER: 9.9.9.9#53(9.9.9.9)
;; WHEN: Sun Sep 08 01:49:42 CDT 2019
;; MSG SIZE  rcvd: 58
```
```bash
dig packagist.org @4.2.2.2

; <<>> DiG 9.10.6 <<>> packagist.org @4.2.2.2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31254
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 8192
;; QUESTION SECTION:
;packagist.org.			IN	A

;; ANSWER SECTION:
packagist.org.		120	IN	A	142.44.164.249

;; Query time: 39 msec
;; SERVER: 4.2.2.2#53(4.2.2.2)
;; WHEN: Sun Sep 08 01:50:01 CDT 2019
;; MSG SIZE  rcvd: 58
```

**Comment by Seldaek** [comment]
Ok found one node with a problem - 54.39.179.221 - which is the latest mirror I added and forgot to add it to some other list so I didn't find the issue earlier.

I still don't see 54.39.172.221 (note 179 vs 172 is the third bit) anywhere.. not in our IP list, and not on https://www.whatsmydns.net/#A/packagist.org - I don't know where you got that IP from.

**Comment by jaykepeters** [comment]
I think that was a typo 

> I still don't see 54.39.172.221 (note 179 vs 172 is the third bit) anywhere.. not in our IP list, and not on https://www.whatsmydns.net/#A/packagist.org - I don't know where you got that IP from.
