### ISSUE TITLE
Abandoned package doesn't return abandoned flag via repo.packagist.com

### ISSUE THREAD

**Issue by glaubinix** [composer/packagist#1032]
Hi,

I noticed that there seems to be something off with the abandoned flag. Potentially in cases where the VCS repository is deleted when setting the abandoned flag.

The text says `This package is abandoned and no longer maintained. The author suggests using the No longer maintained package instead.`

See https://packagist.org/packages/sprov03/laravel-code-generator

<img width="822" alt="Screenshot 2019-10-08 at 19 08 15" src="https://user-images.githubusercontent.com/442056/66421015-01583100-e9ff-11e9-87e8-aebd21d8c985.png">

But the repo endpoint to fetch the package does not return any information that the package is abandoned: https://packagist.org/p/sprov03/laravel-code-generator%24c568972151ce191b0c948e93bb0737603cf7b6b5f8c14c2baec7773b1d830eef.json

**Comment by alcohol** [comment]
I know you can mark a package as abandoned in Packagist too. But if I am not mistaken you can specify it in your `composer.json` as well.

https://github.com/composer/composer/blob/f753c15664c24d95bb64bd99ddc32cb01d1e32b8/res/composer-schema.json#L526-L529

**Comment by glaubinix** [comment]
Then I am unsure what you initial comment was referring to. My original bug report was that the package is marked as abandoned on packagist.org but the provider file doesn't show it as abandoned.

**Comment by alcohol** [comment]
I'm not sure what you mean. http://repo.packagist.org/p/glaubinix/geo-ip.json contains the abandoned property. The other files you linked does not. What the difference is here, I do not know. I do not have access to the packagist.org database, only @Seldaek does. The only difference I can see is that the latter still exists on Github but the former has been entirely deleted.

**Comment by glaubinix** [comment]
I was referring to https://packagist.org/packages/sprov03/laravel-code-generator and https://packagist.org/p/sprov03/laravel-code-generator%24c568972151ce191b0c948e93bb0737603cf7b6b5f8c14c2baec7773b1d830eef.json

**Comment by alcohol** [comment]
Yes, I know. That is what I referred to as "the former".

**Comment by glaubinix** [comment]
Thank you!
