### ISSUE TITLE
Optimization for the README.

### ISSUE THREAD

**Issue by yb199478** [composer/packagist#1034]
**original:**

Run `app/console cache:warmup --env=prod` and `app/console cache:warmup --env=prod` to warmup cache

**should it be:** 

Run `app/console cache:warmup --env=prod` or `app/console cache:warmup --env=dev` to warmup cache

**or:**

Run `app/console cache:warmup --env=prod` to warmup cache

**Comment by Seldaek** [comment]
This is already handled by #1017 so closing - will try and get it merged soon.
