### ISSUE TITLE
Can't require package from packagist

### ISSUE THREAD

**Issue by neelbhanushali** [composer/packagist#1037]
I've uploaded my package on [packagist](https://packagist.org/packages/neelbhanushali/laravel-eloquent-uuid). 

Whenever I require it in my project, I get this error.

![Screenshot 2019-10-26 at 7 32 20 PM](https://user-images.githubusercontent.com/29022906/67620714-5e3d4f00-f827-11e9-8861-f5752ad7ce80.png)

**Comment by asika32764** [comment]
Similar problem here. Update a new version but unable to require it.

```
$ composer require windwalker/framework 3.5.14


  [InvalidArgumentException]
  Could not find package windwalker/framework in a version matching 3.5.14


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

![1B119E3B-0809-4F38-B9A5-F443D3B2802E](https://user-images.githubusercontent.com/1639206/67633802-842e2680-f8ef-11e9-8645-daa99e10b83c.png)

**Comment by omnilight** [comment]
Same problem for my package lamoda/crpt-oms-api-client: in UI I can see new branch (support_for_order_requests_signing) but composer does not see it, as it is not listed in the corresponding json response

**Comment by ebcms** [comment]
Composer has gone wrong

**Comment by inc2734** [comment]
Same problem for my package inc2734/mimizuku-core.

There was a similar problem in the past. Same https://github.com/composer/composer/issues/7603 ?

**Comment by Seldaek** [comment]
This has been resolved, we had an issue with the metadata mirroring over the weekend sorry about that.
