### ISSUE TITLE
Do not list implementations of virtual packages if they are not released yet

### ISSUE THREAD

**Issue by tgalopin** [composer/packagist#1041]
This week-end, I was working with a library requiring an implementation of the virtual package `psr/http-factory-implementation`. I went on the URL: https://packagist.org/providers/psr/http-factory-implementation as proposed by the exception of the library, and I saw guzzlehttp/psr7. 

However, when I installed it, it did not solve my problem. After some investigation, I realized that it's because guzzlehttp/psr7 implements the virtual package only in its version 2, which is not tagged yet. I would argue we should only display packages with a released version providing the virtual package in the "providers page".

**Comment by Seldaek** [comment]
That sounds very personal, and while I'm sorry you had a bad experience, maybe in some cases the opposite would be true. I don't think hiding the info would help overall here.
