### ISSUE TITLE
Readme is not shown to guests 

### ISSUE THREAD

**Issue by vasilevich** [composer/packagist#1043]
Dear packagist developers

I believe your website has a bug:
when I login into your website, 
and access my newly published repository: 
https://packagist.org/packages/vasilevich/currencyconverter
the readme is visible just fine:
![image](https://user-images.githubusercontent.com/1217224/68527867-9bf4aa00-02f4-11ea-8a5b-adf04bef2272.png)

but when I go into icognito mode in my 
browser same page I see this:
![image](https://user-images.githubusercontent.com/1217224/68527880-c0e91d00-02f4-11ea-9f96-6106d49571f5.png)

why the readme is not shown?
and if its a feature and not a bug, its very weird you should atleast warn the user that only as a registered user you can see it.

Thanks.

**Comment by stof** [comment]
This seems even more complex than that. I cannot see that readme even when being logged. However, things are working fine for other packages

**Comment by Seldaek** [comment]
Resolved. This is due to anti-spam measures sometimes new packages get marked and the README is hidden until I go over the review queue..

**Comment by vasilevich** [comment]
@Seldaek I suggest you to put a certain message for the maintainer in the repo itself
for instance:
Readme is not shown to the public yet, awaiting review, estimated between x and y days.

I think this can prevent confusion.
Thank you for your response.

**Comment by ishan-biztech** [comment]
I agree with @vasilevich. This issue seems with my package(https://packagist.org/packages/ishan-biztech/cakephp-xero-oauth2) too.

Is there any timeline on when you can complete this review @Seldaek?

**Comment by Seldaek** [comment]
@ishan-biztech fixed your package.

**Comment by netflie** [comment]
Hi! Here the same problem :( https://packagist.org/packages/netflie/componentes

**Comment by Seldaek** [comment]
@netflie fixed

**Comment by sahilsaggar** [comment]
Took me a while to find this page finally to understand what was happening. It will be a big help if documentation is available for the spam detection and review process. @Seldaek 

Published a new package and it's still pending review https://packagist.org/packages/smsglobal/smsglobal-php

I vote for the idea to display a message to maintainer on the repo.

**Comment by Seldaek** [comment]
@sahilsaggar fixed

**Comment by AmraniCh** [comment]
Hi! I have the same issue here with a library [lazzard/php-ftp-client](https://packagist.org/packages/lazzard/php-ftp-client), I suggest also to leave some message for the maintainer and for the visitors also, thanks!!

**Comment by AmraniCh** [comment]
Hi! I have the same issue here with a library [lazzard/php-ftp-client](https://packagist.org/packages/lazzard/php-ftp-client), I suggest to leave some message for the maintainer and for the visitors also, thanks!! @Seldaek

**Comment by Seldaek** [comment]
@AmraniCh fixed

**Comment by jacobdekeizer** [comment]
Hi @Seldaek! I have the same issue with 2 of my packages: [jacobdekeizer/redjepakketje-client](https://packagist.org/packages/jacobdekeizer/redjepakketje-client) and [jacobdekeizer/ccvshop-client](https://packagist.org/packages/jacobdekeizer/ccvshop-client).

**Comment by Seldaek** [comment]
@jacobdekeizer fixed

**Comment by Seldaek** [comment]
I'll try to resolve it better at some point, but in the meantime please email contact@packagist.org about this in the future, to avoid spamming everyone in this issue.

**Comment by jjanampa** [comment]
Hi! Here the same problem: https://packagist.org/packages/jjanampa/laravel-admin , thanks!! @Seldaek

**Comment by Seldaek** [comment]
@jjanampa fixed

**Comment by robersonfaria** [comment]
Hi! here the same problem: https://packagist.org/packages/robersonfaria/laravel-database-schedule 

@Seldaek Thanks

**Comment by Seldaek** [comment]
@robersonfaria fixed

**Comment by di-zed** [comment]
Hi! Here the same problem: https://packagist.org/packages/dized/module-front-acl
@Seldaek Thanks!

**Comment by Seldaek** [comment]
@di-zed fixed.

**Comment by TheNorthMemory** [comment]
Hi! Here the same problem: https://packagist.org/packages/wechatpay/wechatpay , thanks. @Seldaek

**Comment by Seldaek** [comment]
@TheNorthMemory fixed

**Comment by elemke** [comment]
Same problem here: [ https://packagist.org/packages/elemke/sicoob-pix]( https://packagist.org/packages/elemke/sicoob-pix)

@Seldaek

**Comment by programarivm** [comment]
Hi, here the same problem: https://packagist.org/packages/chesslablab/php-chess

@Seldaek Thanks

**Comment by gyugie** [comment]
Hi, here the same problem https://packagist.org/packages/mootaco/moota-php-sdk
 @Seldaek Thanks...

**Comment by smeghead** [comment]
Hi, here the same problem https://packagist.org/packages/smeghead/php-class-diagram
@Seldaek Thanks...

**Comment by peronh** [comment]
Hi, here the same problem https://packagist.org/packages/peronh/pdf-compress
@Seldaek Thanks...

**Comment by shabayekdes** [comment]
Hi! Here the same problem @Seldaek [https://packagist.org/packages/netflie/componentes](https://packagist.org/packages/shabayek/laravel-payment)
Hope to solve the issue soon
Thanks for your patience :)

**Comment by wmandai** [comment]
Similar issue here @Seldaek https://packagist.org/packages/wmandai/mojagate

Any help is appreciated🙏

**Comment by yookoala** [comment]
Similar issue here @Seldaek https://packagist.org/packages/monogatari-php/remote-storage

Please help to review in the anti-spam queue. Thanks.

**Comment by ajimoti** [comment]
Hi @Seldaek Similar issue here https://packagist.org/packages/bitsika/merchant-sdk-php

Kindly help review

**Comment by mikerockett** [comment]
@Seldaek Is https://packagist.org/packages/rockett/weasyprint in the same boat? I think the very first sync didn't have a readme, then adding it after didn't sync across.

**Comment by ferishili** [comment]
Hi @Seldaek, we've got the same problem here for this package: https://packagist.org/packages/elan-ev/opencast-api
Could you please help us. Thanks in advance!

**Comment by mikerockett** [comment]
Hi @Seldaek – please could you assist with my package linked above? Thanks!

**Comment by Seldaek** [comment]
@mikerockett on GitLab we do not auto-detect the readme path, so you have to either make sure you use the convention (README.md, note yours is lowercased readme.md), or you add it to composer.json as `{"readme":"readme.md"}`

**Comment by mikerockett** [comment]
@Seldaek Ah that's interesting, thanks for clarifying. I’ll try the composer.json change.

**Comment by daniel-jones-deepl** [comment]
Hi @Seldaek, could you please assist with this package: https://packagist.org/packages/deeplcom/deepl-php? Thank you!

**Comment by Seldaek** [comment]
I'm locking this to avoid spamming everyone further, if you need help with something please email contact@packagist.org
