### ISSUE TITLE
CamelCase in Packages naming

### ISSUE THREAD

**Issue by rxu** [composer/packagist#1045]
As per the [Naming conventions](https://packagist.org/about#naming-your-package)
> Note that package names are case-insensitive, but it's encouraged to use a dash (-) as separator instead of CamelCased names.

So it seems to be allowing CamelCased package names. But if I try to submit such a package I get a warning and there's no option to submit.
> The package name rxu/PostsMerging is invalid, it should not contain uppercase characters. We suggest using rxu/posts-merging instead.

**Comment by Seldaek** [comment]
Oh wow that sentence is about 6years outdated or something :) Fixed it, sorry for the confusion.
