### ISSUE TITLE
Archived git-hub repos should prompt to abandon / be automatically abandoned

### ISSUE THREAD

**Issue by hennell-git** [composer/packagist#1055]
I've found a couple of packages now which look fine on packagist, have lots of downloads, stars & reasonable documentation, but when I later look at then on github turn out to be read only - suggesting they've really been 'abandoned' - a situation currently only clear on the github side.

Given packagist already pulls info from github, would it be possible to check the read-only status of packages then do something with that info? I'm not sure if auto-archiving immediately would be appropriate, but it could trigger a message to the registered email of the package to ask them to officially abandon it (thus giving a chance to suggest a replacement) and maybe (after a suitable period of time?) automatically mark it as abandoned it the repo remains read-only?

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/pull/8510
