### ISSUE TITLE
Auto update Badge/icon in search list result view

### ISSUE THREAD

**Issue by bronhy** [composer/packagist#1063]
When we search for packages on packagist.org it would be nice to have and additional badge/icon in the list result which would show if the package is auto updated. This information is pretty important when choosing good and maintained packages.

Currently we have only stars and number of downloads icons.

**Comment by Seldaek** [comment]
I don't see enough value in this as a marker of quality to clutter the UI.. If you really care that much it's now available on the package page (below version list), but generally speaking this doesn't matter all that much.

**Comment by bronhy** [comment]
Well its not a high value thing of course i just thought its useful since you would not have to look at each individual package detail page. 

Thank you for quick feedback. 👍

**Comment by Seldaek** [comment]
Yeah it's a marker of some sort but I'd see the amount of open issues, frequency of releases, last release date and a ton of other things as more important
