### ISSUE TITLE
This package is not auto-updated

### ISSUE THREAD

**Issue by cuveen** [composer/packagist#1066]
My packages did not auto-update. My config is good. I don't know why. Please help me.
Thanks

![image](https://user-images.githubusercontent.com/60683289/73904695-677e9300-48cf-11ea-998d-7e4b136984fd.png)
-------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/60683289/73904708-782f0900-48cf-11ea-830d-45f85b1b2ad5.png)
----------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/60683289/73904726-88df7f00-48cf-11ea-8bcb-a8bb1504223c.png)

**Comment by Seldaek** [comment]
Not sure what is going on here.. The failure code `GitHub user has no admin access to the repository` means we got a 404 while trying to setup the hook.. I don't see why that'd happen but anyway maybe just setup the hook manually if the automated way fails? see https://packagist.org/about#how-to-update-packages

**Comment by cuveen** [comment]
I think. I need manually update every package

**Comment by MCMatters** [comment]
I published a new package a few minutes ago and got the same error. I revoked and gave an access again but nothing changed. On my profile page I see only next message:
`An unexpected error occurred during sync.`

**Comment by Seldaek** [comment]
Ah found a regression I introduced a few days ago, deployed a fix now, please try again.

**Comment by cuveen** [comment]
Yeah. It fixed.
Thank you.
