### ISSUE TITLE
Search bar does not search

### ISSUE THREAD

**Issue by aldumas** [composer/packagist#1071]
When I type a package name in the "Search packages..." text box and hit Enter, I expect the page to update with matching packages, but nothing happens when I press Enter.

I have tried in FF 74.0 64 bit with extensions disabled, Chrome 80.0.3987.149, and a clean install of SeaMonkey 2.53.1.

Sorry if there is already an issue open for this. I did make an effort to search for one but did not find one.

Thank you.

**Comment by Seldaek** [comment]
Maybe check the JS console for errors, files that could not be loaded or something? Because it definitely works here. Might be you have a proxy or ad blocker that blocks the loading of our search JS from algolia (https://cdn.jsdelivr.net/npm/instantsearch.js@2.7.4/dist/instantsearch.min.js)?

**Comment by aldumas** [comment]
You are correct. The JS Console shows an instantsearch.js file not loading. I'm not sure the exact cause, but Firefox was able to download the file after I switched networks. Thanks for your help!
