### ISSUE TITLE
I couldn't commit my package after running in the docker container

### ISSUE THREAD

**Issue by CharesLee** [composer/packagist#1073]
The current service is running in the docker container and it prompts me after submitting my warehouse address

![image](https://user-images.githubusercontent.com/23518280/77719281-e2d30a00-701f-11ea-9757-06d76eff9678.png)

This problem has been bothering me for a few days. I hope you can reply to me as soon as possible. Thanks

**Comment by CharesLee** [comment]
This git repository address is the gogs platform built by our company

**Comment by Seldaek** [comment]
We don't support running the packagist.org codebase on your own infrastructure sorry. If you are looking for private packagist hosting we offer that (SaaS or self-hosted) at https://packagist.com
