### ISSUE TITLE
requirements not updating

### ISSUE THREAD

**Issue by PlaidFoxSG** [composer/packagist#1074]
I've updated my composer.json file many times on github and everything seems to automatically update on Packagist ... except the requirements.  What am I missing?

**Comment by Seldaek** [comment]
Which file/package?

**Comment by PlaidFoxSG** [comment]
https://packagist.org/packages/plaidfoxsg/ticketit7

Cheers,
  Sean

-------------------------------------------------
Sean Glendinning
Nitesco Media: StudentScholarships.org <http://studentscholarships.org/>
Airgom GmbH: Fitness.com <http://fitness.com/>
Plaidfox: PlaidFox.com <https://plaidfox.com>
-------------------------------------------------

**Comment by Seldaek** [comment]
All looks good to me, https://packagist.org/packages/plaidfoxsg/ticketit7#0.2.x-dev has the same as the 0.2 branch's composer.json, and https://packagist.org/packages/plaidfoxsg/ticketit7#3.0.x-dev has the same as the 3.0 branch.. I don't see the problem.
