### ISSUE TITLE
Packagist didn't update package description after it was changed in composer.json

### ISSUE THREAD

**Issue by YaroslawEkimov** [composer/packagist#1085]
So, as you can understand after reading title, I faced problem when I update description and keywords in composer.json and push new tag with this changes. Then I get my keywords successfully updated, but description stayed the same. 
Please can you give some info why it can happen and how to fix this.

**Comment by Seldaek** [comment]
Please give your package name..

**Comment by YaroslawEkimov** [comment]
> Please give your package name..

aspose-words-cloud

**Comment by Seldaek** [comment]
The description looks exactly the same on https://packagist.org/packages/aspose-cloud/aspose-words-cloud and https://github.com/aspose-words-cloud/aspose-words-cloud-php/blob/master/composer.json#L2 - not sure what you are seeing as a problem.

**Comment by YaroslawEkimov** [comment]
> The description looks exactly the same on https://packagist.org/packages/aspose-cloud/aspose-words-cloud and https://github.com/aspose-words-cloud/aspose-words-cloud-php/blob/master/composer.json#L2 - not sure what you are seeing as a problem.

Well, 20.5.0 this tag reference release branch where composer file is changed and contains different description, more over these changes both in description and keywords exist only in release branch. So my question is why packagist took changes in keywords and didn't in desctription

**Comment by Seldaek** [comment]
The keywords are shown for every release, the description is only read from the default branch (master here).
