### ISSUE TITLE
it is not saving image in store url

### ISSUE THREAD

**Issue by MFN-freelancer** [composer/packagist#1086]
I installed ffmpeg and videothumbnail package.
and I tried to do as following.
`VideoThumbnail::createThumbnail(public_path('uploaded_video/oceans.mp4'), public_path('cover_images'),'movie.jpg', 2, 1920, 1080);`
but it is not saving movie.jpg in cover_images folder.
I am using local. my OS is window 10.
please help me.

**Comment by stof** [comment]
This is the issue tracker for the packagist.org website, not for packages you install from packagist.

**Comment by MFN-freelancer** [comment]
what do you mean?
so I can not use this class in laravel?

**Comment by stof** [comment]
You must ask or support in the issue tracker of the package you want to use, not in the issue tracker of the packagist.org website.
I cannot tell you whether you can use this class or no, as I don't know this class.

**Comment by Seldaek** [comment]
Please report it at https://github.com/pawlox/video-thumbnail/issues or whichever is the correct repo url for the package you are using.
