### ISSUE TITLE
Keywords/tags: hyphens and spaces should be considered synonyms (identical content) for search

### ISSUE THREAD

**Issue by marclaporte** [composer/packagist#1091]
For example, these 2 search queries provide different results:

- https://packagist.org/search/?tags=machine-learning
- https://packagist.org/search/?tags=machine%20learning

Most of the time, spaces are used. I didn't find any proposed convention, and most project use spaces.

Related: https://github.com/composer/packagist/issues/894

Thanks!

**Comment by Seldaek** [comment]
Updating the index fully will take a while as packages get reindexed on update, but it'll fix itself in a while..
