### ISSUE TITLE
Not updating package, neither auto or manual

### ISSUE THREAD

**Issue by ekyna** [composer/packagist#1092]
Manual update results in infinite requests.

![image](https://user-images.githubusercontent.com/3483641/85219464-3f865c80-b3a4-11ea-8049-d66b1239f2c6.png)

Webhook is correctly configured.

![image](https://user-images.githubusercontent.com/3483641/85219474-5331c300-b3a4-11ea-9ace-e6b38efff95d.png)

Repo was updated 1 hour ago.

![image](https://user-images.githubusercontent.com/3483641/85219489-778d9f80-b3a4-11ea-9583-1753170a90cc.png)

Maybe it is just temporary ? Or did i miss something ?
Perhaps he do not want to work on sunday (i can understand that ! :smile:)

**Comment by moqiaoduo** [comment]
Me too. I even delete the package and resubmit. It doesn't work.
So I am off duty now. :)

**Comment by mmasiukevich** [comment]
Last evening it stopped updating. Still not working

**Comment by levmorozov** [comment]
Same problem :(

**Comment by Seldaek** [comment]
Sorry we had issues processing background jobs for a while today. It should now be resolved.
