### ISSUE TITLE
Unable to create packages in packagist.org with private GitHub/GitLab repo.

### ISSUE THREAD

**Issue by Sanjeev139** [composer/packagist#1099]
Hi Team,
I have created a private repository for PHP project and now I am trying to create a package inside packagist.org.
I am getting following error -
![image](https://user-images.githubusercontent.com/22133504/87302328-d327f480-c52e-11ea-926e-3206a771c98c.png)

And it is working fine if I make my repository Public. I just wanted to know that packagist.org is only for a public repository or I am doing something wrong.

Please help me out with this.

Thanks
@Sanjeev139

**Comment by vtsykun** [comment]
Hi @Sanjeev139 
packagist.org is for public packages only. But you can use free alternatives: [repman](https://github.com/repman-io/repman ) or self-hosted fork of packagist https://github.com/vtsykun/packeton for private packages

**Comment by Sanjeev139** [comment]
> Hi @Sanjeev139
> packagist.org is for public packages only. But you can use free alternatives: [repman](https://github.com/repman-io/repman) or self-hosted fork of packagist https://github.com/vtsykun/packeton for private packages

Thanks @vtsykun , 
I will look into the solution that you have provided.

**Comment by Seldaek** [comment]
For private packages we offer commercial hosting at https://packagist.com
