### ISSUE TITLE
Are there any branch limitation?

### ISSUE THREAD

**Issue by tobiasbaehr** [composer/packagist#1108]
I believe that the package https://packagist.org/packages/degov/degov has too much branches, so that the processor of packagist.org runs out of memory or something.

The default branch has not the meta information of the composer.json and composer fallbacks to default package type, and without any dependencies. The default branch is at the moment dev-release/8.4.x-dev.

The workaround is to use the update button for the repo. Is there any helpful message in the CI which show us, what is wrong with the package or is the bitbucket -> packagist. Integration/Webhook broken?

**Comment by Seldaek** [comment]
As far as I can tell everything updates fine for the package. Can you describe in more details what you consider is wrong/what you'd expect instead?

**Comment by tobiasbaehr** [comment]
I took a screenshot, picture save more than words :D 

Broken:
<img width="1269" alt="Screenshot 2020-07-29 at 21 51 01" src="https://user-images.githubusercontent.com/105220/88846348-d1745700-d1e5-11ea-9fc6-6456d276d4b9.png">

Looks good:
<img width="1138" alt="Screenshot 2020-07-29 at 21 54 16" src="https://user-images.githubusercontent.com/105220/88846726-519abc80-d1e6-11ea-883b-ccca01f4ab99.png">

**Comment by Seldaek** [comment]
Ok this was just a silly bug on our end actually, due to something we changed a few weeks ago to better support non-standard default branches, nothing to do with your amount of branches.
