### ISSUE TITLE
Cannot find package on packagist but can require it by composer

### ISSUE THREAD

**Issue by feng-yifan** [composer/packagist#1109]
##### Problem
Long time ago I have upload a package named risky/helper.
Now I want to remove it from packagist but I can't find it both in my profile and package browser, but I can still require this package so I delete the package's github repository.
##### Queastion
- Is there any way to remove package risky/helper?
- If so is there any way to remove all package with namespace risky?

And I'm pretty sure no one has tried these packages so this will not affect others
~~I know risky sounds not very stable :(~~

**Comment by stof** [comment]
@Seldaek the `risky/helper` is found in the dumped metadata in Composer 1 format (see https://packagist.org/p/risky/helper.json) but not in the Composer 2 format (https://packagist.org/p2/risky/helper.json is a 404).
So I suspect that this package has already been deleted from Packagist, but that the metadata dumping logic has a bug when dealing with removed packages (then, not sure whether the bug only impacts the 1.x format or whether the removal happened before enabling the new format)

**Comment by Seldaek** [comment]
This is a known issue of v1 metadata that the files never get removed, and it's a bug we are not going to fix at this point. v2 is around the corner and it handles this correctly.

**Comment by feng-yifan** [comment]
> @Seldaek the `risky/helper` is found in the dumped metadata in Composer 1 format (see https://packagist.org/p/risky/helper.json) but not in the Composer 2 format (https://packagist.org/p2/risky/helper.json is a 404).
> So I suspect that this package has already been deleted from Packagist, but that the metadata dumping logic has a bug when dealing with removed packages (then, not sure whether the bug only impacts the 1.x format or whether the removal happened before enabling the new format)

You remind me that I have changed the namespace before, maybe that the reason.

**Comment by feng-yifan** [comment]
> This is a known issue of v1 metadata that the files never get removed, and it's a bug we are not going to fix at this point. v2 is around the corner and it handles this correctly.

Sorry to bother, is there any solutions to stop composer install these packages?

**Comment by Seldaek** [comment]
@feng-yifan I cleaned up the files manually for the risky namespace now.

**Comment by feng-yifan** [comment]
@Seldaek Thanks for your great help!!!
