### ISSUE TITLE
Integration with Travis CI

### ISSUE THREAD

**Issue by simensen** [composer/packagist#111]
It could be a nice way to vet packages when you are searching packagist. Anything that has the green is probably good to go. Anything with red likely won't work. And if nothing at all, you might try to find something that at least has green somewhere on it? :)

Assumes a few things (based on quick IRC conversation):
- Will work for GitHub projects only for now? (Travis CS only works with GitHub currently)
- Will obviously only work for people who have setup Travis (and don't have their own CI)

I'm not sure if this would be making too many assumptions about the environment some people might be coming from. But it might be nice to start thinking about ways to help people make informed decisions about packages found on packagist.

As far as implementation, the thing that made me think about this was seeing this project this morning: https://github.com/l3l0/php-travis-client We could also implement this as the simple image thing they have but it might be nice to have a way to ignore it entirely for projects that don't have travis at all. Also, would be nice to find status on a per-version basis (i.e., build status on tags and branches) instead of just a global "last build" status or "last build on master" status.

**Comment by eddiejaoude** [comment]
:+1: great ideas!!

Any progress on this?
