### ISSUE TITLE
Connot login in website via Github Login

### ISSUE THREAD

**Issue by mathContao** [composer/packagist#1111]
Hello,

I am new at packagist and wanted to use the GitHub Login

The app has the permissions as needed in GitHub
![grafik](https://user-images.githubusercontent.com/1645099/89740186-e1622580-da86-11ea-8a10-a25f364506fd.png)

but I get the warning "Account could not be linked correctly. "
![grafik](https://user-images.githubusercontent.com/1645099/89740196-f0e16e80-da86-11ea-8ce5-7150f75c3c35.png)

**Comment by LupusCoding** [comment]
I've got the same problem today.

**Comment by alterebro** [comment]
Here as well, I have exactly the same problem

**Comment by suhrr** [comment]
i've got the same problem.

**Comment by mathContao** [comment]
I guess it works fine (for me).

**Comment by owlphp** [comment]
Here as well, I have exactly the same problem

**Comment by Seldaek** [comment]
As per #1140 - if you see this message it most likely means you do not have yet a Packagist user, so make sure you first create one with email/password, then you can connect it to your github account on https://packagist.org/profile/edit 

After you do that the github login should work.

**Comment by mfei58** [comment]
I have exactly the same problem yet
