### ISSUE TITLE
Deprecate version (tag)

### ISSUE THREAD

**Issue by andreaslarssen** [composer/packagist#1112]
Sorry if I missed it, but I can not find a way to deprecate a tag. Is there?

Would be nice if you could, and the user would get an alert when running composer commands when having a deprecated tag in composer.json.

**Comment by stof** [comment]
There is no such way today.

Related to https://github.com/composer/composer/issues/9113

**Comment by andreaslarssen** [comment]
@stof are you following me? :smiley: Ok, thanks. Want me to close this?

**Comment by Seldaek** [comment]
Yeah let's close this, the other issue is enough IMO

**Comment by stof** [comment]
@andreaslarssen no. but I'm following this repo :smile:

**Comment by andreaslarssen** [comment]
@stof just a joke, thanks again for your help
