### ISSUE TITLE
This package is not auto-updated

### ISSUE THREAD

**Issue by georgringer** [composer/packagist#1116]
I have published lots of packages and out of nowhere the package This package https://packagist.org/packages/studiomitte/riddle can't be auto-updated and I got no clue why.

1. It worked in the past with the same vendor name
2. composer.json is valid
3. My account is linked, GH hook is enabled
4. Tested also removal + readding the package

thx for helping me out

**Comment by Seldaek** [comment]
What you can try is to delete the hook on github in that repo, and then go to https://packagist.org/trigger-github-sync/ to trigger a re-creation from our side. That hopefully fixes it.

**Comment by georgringer** [comment]
Thx worked out
