### ISSUE TITLE
Add latest release date

### ISSUE THREAD

**Issue by pattisahusiwa** [composer/packagist#1117]
Currently, when we want to know latest release date, we need to go to package homepage (in this case github repository). It would be nice to have similar feature to npmjs's last publish.

**Comment by Seldaek** [comment]
Isn't this enough?

![image](https://user-images.githubusercontent.com/183678/92926236-05c17100-f43c-11ea-978c-a410252306f5.png)

Seems to me like that's by default showing you the last release date which is exactly what you want no?

**Comment by pattisahusiwa** [comment]
Yes, that's what I meant.
