### ISSUE TITLE
need api for submit function

### ISSUE THREAD

**Issue by zqfan** [composer/packagist#1119]
I've already checked the page: https://packagist.org/apidoc  and searched via google, it seems there is no api for submitting a new package.
I'm running a tool which will generate various service sdk for a major cloud vendor, which means it will publish hundreds of repos and there are more repos on the way. If there is no such api for submit a new package, then I must login the packagist site and click the submit button every new repo is landed, which is not convenient, neither efficient. 
Please help, many thanks!

**Comment by stof** [comment]
Actually, there is already a `/api/create-package` endpoint (see https://github.com/composer/packagist/blob/e21c8c8e1a0b422a7d2785ac74f04e6ec1b59fbf/src/Packagist/WebBundle/Controller/ApiController.php#L54 for the implementation) which is missing in the doc.

I suggest doing a PR to update the doc.

**Comment by zqfan** [comment]
@stof thanks a lot, I will do a test and may be a doc pr contribute as well
