### ISSUE TITLE
fail to submit new package because repo not found?

### ISSUE THREAD

**Issue by zqfan** [composer/packagist#1122]
when try to submit a new package via https://packagist.org/packages/submit

repo actually exists, url: https://github.com/tencentcloud-sdk-php/tx-template

error:
Uncaught Exception: [RuntimeException] Failed to execute git clone --mirror 'https://***:***@github.com/tencentcloud-sdk-php/tx-template.git' '/home/composer/.cache/composer/vcs/git-github.com-tencentcloud-sdk-php-tx-template.git/' Cloning into bare repository '/home/composer/.cache/composer/vcs/git-github.com-tencentcloud-sdk-php-tx-template.git'... remote: Repository not found. fatal: repository 'https://github.com/tencentcloud-sdk-php/tx-template.git/' not found

**Comment by stof** [comment]
Looks like this is a private repository, which indeed gets reported as not existing when someone does not have access.

**Comment by zqfan** [comment]
Acceptable.
But it might be good to prompt that repo is not found or it is private.
