### ISSUE TITLE
Warning: Package with name X already exists

### ISSUE THREAD

**Issue by nick-zh** [composer/packagist#1124]
Hey guys
So i am moving one of my packages to a different namespace, when i want to add it on packagist.org i get the following warning:
```
A package with the name old/package already exists.
```
I am pretty sure, before i was able to add it anyway, but now it seems i can't. Any way around this?

**Comment by stof** [comment]
> So i am moving one of my packages to a different namespace

Have you renamed it in the default branch of the repository ? That's where Composer (and so Packagist) takes the package name.

**Comment by nick-zh** [comment]
@stof ah darn, totally forgot, thx man :v:
