### ISSUE TITLE
Accept V.x-dev versions in composer.json

### ISSUE THREAD

**Issue by nicolas-grekas** [composer/packagist#1125]
Right now, packagist compares the `version` field to tags in a strict way: if I put `5.1.x-dev` in `version`, packagist will refuse to publish tag `5.1.42` if the `version` field is not updated to exactly `5.1.42`.

On the other side, composer uses the `version` field to populate the root-version when resolving deps.

On the composer side, this use case is perfect: putting `5.1.x-dev` works perfectly to set the root-version. As you know, when `version` is not set, composer fallback to `COMPOSER_ROOT_VERSION` then to local branches found in vcs (`git`). At least in the case of symfony, these fallbacks don't work well:
- `COMPOSER_ROOT_VERSION` is needless shell manipulation (think about new contributors, but also about checking out a new branch several times a day).
- local branches just don't work, because they don't exist by default on local forks.

About local branches, here is a workflow that highlights the issue:
```sh
git clone git@github.com:symfony/symfony
cd symfony
git checkout -b some-fix-branch origin/3.4
composer up
```

When doing so, composer has no clues about the root-version. This can lead to broken deps. Note that this workflow is not artificial: I personally do not have any 3.4 branch on my local fork, because I never work directly on 3.4. This means composer is always broken for me here. In Travis, we have a very similar situation. We worked around it by scripting the computation of `COMPOSER_ROOT_VERSION`.

Populating the `version` field fixes all these issues on the composer side, but creates a new one on packagist.

I'm therefor kindly asking for relaxing this exact-match rule on packagist. The rule could be: "when `version` ends with `.x-dev`, it's OK if only the major+minor numbers match."

Note that this issue is quite critical for symfony/symfony: our CI is currently broken since we moved away from `master` in favor of `5.x`. We removed all `branch-alias` for `dev-master` and that broke our CI scripts, which need to be able to read the root-version from the source. In order to fix them, we added the version back in the `version` field. And this fixes most of the issues (as explained above).

BUT, we cannot tag any version anymore, because of the current logic in packagist.

Side note: @Seldaek asked me if we shouldn't add a new special `dev-*` branch-alias to tell composer the root-version in the composer.json. While that would allow us to fix our CI scripts, that would leave the root-version unpopulated until a new version of composer is releases and adopted. This looks like a significant drawback that makes me prefer patching packagist instead of composer.

**Comment by stof** [comment]
A solution could be to allow a `root_version` field in composer.json, which would be ignored by composer when loading remote packages (and so be ignored by packagist too), but would be used by Composer when needing to know the root version (composer already has a bunch of root-only fields)

**Comment by stof** [comment]
note that Packagist is not the one introducing that strictness of the `version`. Composer itself does it in the VcsRepository.

**Comment by nicolas-grekas** [comment]
> Packagist is not the one introducing that strictness of the version. Composer itself does it in the VcsRepository

oh, that might be the piece that explains why Jordi might prefer a new special `dev-*` branch-alias (which is strictly equivalent to your `root_version` proposal Stof, isn't it?)

**Comment by stof** [comment]
depends the behavior of `dev-*`. Currently branch aliases are not only used for the root version. They also impact dependency resolution when used as dependencies (to allow `dev-master` to match a `^5.1@dev` constraint) which is actually their original intent.
If the special branch alias is used only at the root, then it is indeed the same result than my proposal. But then, I would prefer keeping it separate from `branch-alias` to avoid confusing (as `branch-alias` is not a root-only field).

**Comment by Seldaek** [comment]
Ok finally got on my laptop.. I tried reproducing and indeed I see the issue. It seems that what happened before is it found the version was dev-master as you had a master branch + some-fix-branch locally, and then it picked the branch-alias for dev-master from the composer.json which was the one of 3.4, so it aliased it as 3.4.x-dev, and all was working.

Now it picks 5.x-dev as the version and as there is on branch alias there it just keeps that as version and things break.

The solution seems to me like I also said yesterday to fix the VersionGuesser in Composer to handle this case better, probably it'll require us to list and lookup remote branches as well as local ones to try to find a matching one.

So my recommendation @nicolas-grekas is still to revert your version field thing back to how it was before.. keep COMPOSER_ROOT_VERSION to keep travis working (as there is no full clone there we can't guess correctly as we don't have all branches/commits), and the contributor issue should be fixed once the bug is fixed in Composer.

**Comment by nicolas-grekas** [comment]
I'm not sure the dev-master branch alias ever worked actually. It's always been an issue locally (most of the time, composer didn't care having an accurate version number, but sometimes it did).

I really think we should be able to commit a `-dev` version in the file and that composer should pick that for populating the root-version. That's the most accurate way of making the info available.

**Comment by naderman** [comment]
The branch alias definitely always works locally and still does, as long as the version guesser determines the version to be master, which it may not.

We very intentional try to get people away from commiting version numbers. Branch aliases were a compromise and I'd prefer we didn't have to add more of these. Fixing the version guesser to work correctly seems like a better solution to me and I created a corresponding PR.

**Comment by stof** [comment]
My proposal above is to add a new (optional) `root_version` field which would be used when guessing the root version

**Comment by nicolas-grekas** [comment]
Thanks @naderman!

There is another use case where using the current `version` would help: when using `"path"` repositories.

In https://github.com/symfony/symfony/blob/5.1/composer.json, you'll see:
```
    "repositories": [
        {
            "type": "path",
            "url": "src/Symfony/Contracts"
        }
    ],
```

composer doesn't know which are the versions of the packages in this folder. By default, composer takes the same version as the root-version. But this is wrong here (contracts are at v2.*)

This makes resolving deps fail with composer 2 (but it works with composer 1 btw).
Here is the error:
```
- Root composer.json requires symfony/contracts ^2.1, it is satisfiable by symfony/contracts[dev-master, v2.1.0, ..., 2.3.x-dev (alias of dev-master)] from composer repo (https://repo.packagist.org) but symfony/contracts[dev-cb03860eee66b6dbac9522e275cbb3f312f2be37] from path repo (src/Symfony/Contracts) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
To work around the issue with composer 2, I have to add `"version": "2.3-dev"` in `src/Symfony/Contracts/composer.json`.
```

**Comment by stof** [comment]
As PathRepository uses the VersionGuesser, my idea of allowing a `root_version` field impacting the guessing of the root version might solve this issue too.

**Comment by naderman** [comment]
Then his issue should also be solved by my improvements to the version guesser?

**Comment by stof** [comment]
@naderman no. The composer.json in the subpath can have different config than the main composer.json. but the git repo is the same and so would still guess it as 5.x

**Comment by stof** [comment]
that's a case where guessing from git does not produce the result we want for the path repository.

**Comment by naderman** [comment]
Wait so they are in the same git repository, get tagged with the same version number but somehow the version number isn't supposed to apply to some directory? That really just doesn't make any sense? If you don't want the tags to apply to all of it, why are they in one repository?

**Comment by nicolas-grekas** [comment]
>If you don't want the tags to apply to all of it, why are they in one repository? 

because that helps contributing A LOT, like allowing one to make one PR that span several packages, have green CI, etc. Basically the many benefits from a monorepo.

**Comment by stof** [comment]
@naderman the package for this particular sub-path is *not* in the `replace` and `autoload` lists of the `symfony/symfony` package. so the subtree package (tagged separately) will always be used to install the package, never the monorepo

**Comment by stof** [comment]
@naderman do you have any objection to that `root_version` field, which would allow to take control for when the VersionGuesser is not guessing what we need ?

**Comment by naderman** [comment]
@nicolas-grekas Isn't the main point of a monorepo that you version things together to get all those benefits, just seems odd to me to then somehow use separate version numbers for some directory.

@stof I don't have an objection to that field in general. I'd prefer it stayed in extra as that will cause less BC issues, no need to adjust packagist much etc., also curious if it should then always be used or only as a fallback?

**Comment by stof** [comment]
@naderman I would say that if it is specified, it wins over any guessed thing (so the VersionGuesser would check that first, or maybe second after `COMPOSER_ROOT_VERSION`, to be defined).

> no need to adjust packagist much

even if we make that a top-level field, Packagist does not need adjustment (except updating its `composer/composer` dependency to a version including the field in the schema). That's a root-only field so Packagist does not care about storing it as there is no need to have it in the downloaded metadata.

> Isn't the main point of a monorepo that you version things together to get all those benefits, just seems odd to me to then somehow use separate version numbers for some directory.

whether releases are synchronized or no is not mandated by monorepos. both cases exist and correspond to different use cases.  That's not the main benefit of the monorepo. For instance, https://github.com/async-aws/aws develops packages in a monorepo, but releases are all separate (that monorepo is not available as a package on its own on packagist)

**Comment by nicolas-grekas** [comment]
`extra.dev-version: 3.4` <=> version = 3.4.x-dev?

I'm not sure about the name `root_version` @stof: the path repos are not root ones, yet composer would need to read that field to populate their version.

**Comment by stof** [comment]
Well, the path repository goes reading a bunch of packages and applies the same logic than for the root package for their version guessing. So I would not find it weird that it respects their own `root_version` field. AFAICT, PathRepository is also taking `COMPOSER_ROOT_VERSION` into account in some cases

**Comment by nicolas-grekas** [comment]
See https://github.com/composer/composer/pull/9273

**Comment by Seldaek** [comment]
The fix for version guesser is now merged and present in snapshot builds FYI. I guess this still doesn't resolve the issue with path repos though.
