### ISSUE TITLE
Some of my packages are not auto-updating despite following the exact same steps as my other packages

### ISSUE THREAD

**Issue by redbastie** [composer/packagist#1128]
I just added this package: https://packagist.org/packages/redbastie/swift

It says it is not auto-updating. Yet, I am logged in with my Github account, and followed the exact same steps to submit it as another package which IS being auto updated: https://packagist.org/packages/redbastie/crudify

What am I missing?

**Comment by stof** [comment]
For reference, a package is marked as auto-updated once the webhook is received. So when adding a new package, Packagist will consider it auto-updated only after the next push.

**Comment by redbastie** [comment]
Yes I noticed that which is why I closed the issue :)

**Comment by stof** [comment]
> Yes I noticed that which is why I closed the issue :)

I guessed that. But having the solution written will help if someone else faces that and searches for existing issues.
