### ISSUE TITLE
Bugged package chrsm/prayerletters masquerading as laravel/laravel on packagist.org 

### ISSUE THREAD

**Issue by hopeseekr** [composer/packagist#1129]
OK, I literally have no idea where to put this, so I’m going to put it here.

https://packagist.org/packages/chrsm/prayerletters

Due to either chicanery on the `laravel/laravel` project or a bug in packagist.org, packagist is confused and thinks that this project is laravel/laravel, awarding it all the GitHub stars, and claiming its URL is the same as laravel's.

This is obviously a bug.

----

**UPDATE:** I have analyzed every single packagist package with >= 1,500 github stars (704 projects) and this is the only project that is masquerading as another one, at least as per github stars.

The SQL I used (via my Bettergist Collective project):

    SELECT package, sub.* 
    FROM packagist_stats ps 
        JOIN (
            SELECT github_stars, COUNT(*) count
            FROM packagist_stats 
            WHERE github_stars > 1500 
            GROUP BY github_stars 
            HAVING COUNT(*) > 1
        ) sub ON sub.github_stars=ps.github_stars
    ORDER BY count DESC, github_stars DESC;

                     package                 | github_stars | count 
    -----------------------------------------+--------------+-------
     laravel/laravel                         |        61550 |     2
     chrsm/prayerletters                     |        61550 |     2

**Comment by Seldaek** [comment]
No bug nor masquerading, the author simply changed the package URL to laravel's so packagist started syncing from that, but using the original name. It's not that bad really.. Anyway I deleted it as it was clearly not needed there.
