### ISSUE TITLE
Allow the submission of packages without necessitating ownership

### ISSUE THREAD

**Issue by daved** [composer/packagist#114]
Hi, Guys.
Great job so far.
The site is looking very impressive, and my test runs with composer/packagist have been wonderful.
However, when I submitted a package, thinking that I was simply adding it to the database, I realized that I was also listed as the maintainer.  It would be great if the site had the ability to declare a maintainer, or, at least, declare oneself as not the actual maintainer.
My packagist account is linked to my github account, so please, if it is not too much trouble, clear my account of ownership of the package that I submitted.
Thanks!

**Comment by PommeVerte** [comment]
I don't mean to spam but does anyone know what the process is to get maintenance of your own project on packagist? 

I went to submit my project today and realized someone had already done so.. I would like to be able to manage it but am unsure of how to do this. 

https://packagist.org/packages/brightzone/gremlin-php

Thanks for your help

**Comment by stof** [comment]
@PommeVerte contact the current maintainer and ask them to add you. If it does not work, ask @Seldaek

**Comment by PommeVerte** [comment]
Well they submitted a fork so I'm afraid it will be more complicated than just adding me. I'll ask @Seldaek . Poor fellow surely has better stuff to do than to chase after this kind of stuff.

**Comment by Seldaek** [comment]
@PommeVerte do you have the same username  on github? I can fix that up for you.

**Comment by PommeVerte** [comment]
@Seldaek Awesome thanks a lot.

The github account is this one I'm posting with. I registered to Packagist via github so I have the same username (PommeVerte). 
The repo that was submitted and keeping me from registering is this fork : `https://github.com/chekun/gremlin-php.git`
But the repo (mine) I'd like to register is : `https://github.com/PommeVerte/gremlin-php.git`

Thanks a tonne.

**Comment by Seldaek** [comment]
@PommeVerte I can do the URL change and give you access, but it'd be great if you can take a look at the changes in https://github.com/chekun/gremlin-php/compare/36e0ed2...master which is what they did to the fork. It seems like good changes to me..

**Comment by Seldaek** [comment]
Done, also please check don't forget to tag a version and set up the github hook for auto-updates.

**Comment by stof** [comment]
changing the namespace case is a BC break though, because composer autoloading is case-sensitive (and their change is incomplete and broken for people on case-sensitive filesystems though). So only part of the change is good, not all of it.

**Comment by PommeVerte** [comment]
Yeah I had noticed those changes. I'm in the process of applying some of those changes. like @stof mentions, other changes might come down the road but I would rather avoid BC breaking or anything that will be a pain with our CI at this point.

Again, Thanks a lot!!
