### ISSUE TITLE
Hide stars and other GitHub-centric stats when not using GitHub

### ISSUE THREAD

**Issue by ancarda** [composer/packagist#1141]
I moved [my package](https://packagist.org/packages/ancarda/psr7-string-stream) from GitHub to SourceHut, and I noticed Packagist continues displaying "stars", "watchers", and "forks". They seem to work by just appending `/stargazers` to the end of the repo URL (for instance, in the case of stars). That URL doesn't exist.

Can these 3 stats be removed/hidden if the repo is not hosted on GitHub?

**Comment by stof** [comment]
When changing the source of a package from github to a non-github location, the fields storing github-only metadata probably need to be reset (as they won't be updated to new values for the new source)
