### ISSUE TITLE
Representation of No Packages For A Component

### ISSUE THREAD

**Issue by criminosis** [composer/packagist#1146]
Hi Packagist!

While working against your API I came across something that surprised me so just wanted to see if I'm interpreting it correctly.

You have an endpoint that lets you see the releases of a component. For example for 

https://repo.packagist.org/packages/gurrabergh/weather

it's located at: https://repo.packagist.org/p/gurrabergh/weather.json

In particular I want to call attention to {"packages": {"gurrabergh/weather": {...}}}

Which is to say that packages's value is another json object of which the first is called "gurrabergh/weather" and so forth for its nesting.

What I'm confused of though is in cases when the component is delisted, for example for this one:

https://repo.packagist.org/packages/clinpath/ping

and the corresponding json file:

https://repo.packagist.org/p/clinpath/ping.json
```
{"packages":[]}
```

It is now suddenly an empty array.

I understand that an empty may be just how Packagist has chosen to represent the lack of being able to parse the referenced repository (maybe they deleted it, maybe it's made private, etc).

But what I'm wondering about is shouldn't it be `{"packages":{}}`? That is to say that the "packages" field is now an empty object instead of suddenly being an empty array?

**Comment by stof** [comment]
I would say that's because of how PHP's json_encode behaves by default (it cannot know whether an empty array was meant to be a list or a map)

**Comment by Seldaek** [comment]
Yeah that's just how it is I am afraid. I don't think it's worth fixing the composer v1 metadata anymore for this.

**Comment by criminosis** [comment]
@Seldaek is there a newer means to obtain this via a composer v2 API? It didn't seem to be mentioned in https://packagist.org/apidoc#get-package-data

**Comment by stof** [comment]
the v2 metadata is documented on https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#for-composer-repository-implementors and packagist.org exposes under `/p2/` (instead of the `/p/` of the v1 metadata).
In the v2 metadata, the absence of a package is represented by a 404

**Comment by criminosis** [comment]
I'll check it out. Thank you @stof!

**Comment by stof** [comment]
@Seldaek this packagist doc page should probably be updated to mention the v2 metadata too (and mark the v2 format preferred over v1)

**Comment by Seldaek** [comment]
Yup that's my plan, but was a bit busy today with the sf4.4 migration.
