### ISSUE TITLE
Packagist vector icon

### ISSUE THREAD

**Issue by mondeja** [composer/packagist#1147]
Hi. First of all, thanks for your work! :clap: 

I'm a maintainer of [simple-icons](https://github.com/simple-icons/simple-icons) and I would like to add the [Packagist icon](https://github.com/composer/packagist/blob/master/web/apple-touch-icon.png) to our project so it could be easily included in a badge using [shields.io](https://shields.io/). We could vectorize the PNG image that you share in this repository, but their quality would be lower than if we could use a vectorized version that you can provide. Could this be possible?

**Comment by Seldaek** [comment]
No vector version, but here is the largest I have:

![packagist-logo](https://user-images.githubusercontent.com/183678/102594041-fd04c900-4115-11eb-9a94-2d1ac30bd912.png)
