### ISSUE TITLE
Package Deletion

### ISSUE THREAD

**Issue by michaelcullum** [composer/packagist#115]
Allowing the maintainer to delete/remove his/her own packages from packagist. Or maybe just have a soft package deletion where they just get hidden?

**Comment by emmetog** [comment]
> It is possible to delete a package when it has only a few downloads (I don't remember the threshold)

@stof does this still apply? Do you know where to find the threshold (or what it is set as)? I've had a quick look at the [packagist source](https://github.com/composer/packagist) code but I couldn't find it.

We're trying to decide if it's worth it to protect ourselves against a package that has 4824 installs from suddenly disappearing.

**Comment by Seldaek** [comment]
The limit is pretty low, 50 or 100 I don't remember exactly.

**Comment by RomainSanchez** [comment]
Hi is there a way to "request" a package deletion?
I have a package that's abandoned and republished under a new vendor name.
I'd like the old one to disappear, it has 130 downloads and all come from our team.
The package name is libre-informatique/core-bundle

**Comment by Seldaek** [comment]
Done. That said for anyone else finding this via google, please rather ask by email at contact@packagist.org to avoid spamming everyone here :)

**Comment by RomainSanchez** [comment]
Thanks a lot
