### ISSUE TITLE
Package fixtures?

### ISSUE THREAD

**Issue by BenMorel** [composer/packagist#1159]
Hi, I'm trying to familiarize myself with the codebase to submit a PR for a new feature. I ran the instructions in the README, so far so good.

But now I'm left with an empty database, and can't seem to find any fixtures. **What's the recommended way to get package / author / ... sample data for a reasonable number of packages?**

The feature I'll be working on is a daily export of all packages, together with their download stats, as proposed in an earlier email.

Thanks!

**Comment by Seldaek** [comment]
We don't really have that sorry, you can create an account and submit a bunch of packages yourself, make sure to run the `bin/console pack:run` command so that their metadata syncs up.

**Comment by BenMorel** [comment]
Thanks, I was afraid that was the case. **Would you be interested in extracting a subset of the database for development purposes?** Like the top 1000 packages, together with their relationships.

I have a tool that can export referentially intact subsets: https://github.com/BenMorel/smartdump
I can provide you with the right command to run to extract just what's needed.

That would be much faster than attempting to create 1000 packages by hand! Committing the SQL output, and updating it from time to time, could help contributions. Password hashes would need to be filtered out in some way, though.

**Comment by stof** [comment]
@BenMorel the source of truth of package metadata is not on packagist but in the VCS repositories being registered. If you register them and run the command fetching metadata from github, you will have them.

**Comment by BenMorel** [comment]
@stof Do you mean?

- create a user account locally
- register existing packages
- run `bin/console pack:run`

**Comment by stof** [comment]
@BenMorel running `bin/console packagist:update` as third step to fetch the metadata from github, before dumping them.

@Seldaek isn't it `packagist:dump` rather than `pack:run` ? I don't find any `pack:run` command in the Packagist codebase (maybe that's a Private Packagist thing ?)

**Comment by stof** [comment]
ah, found it. that's `packagist:run-workers`

**Comment by BenMorel** [comment]
Thank you, I'll look into this! I'll first have to figure out why console commands output a whole load of `[cache] Failed to save key "%5B%5BC%5DApp%5CEntity%5CJob%24packageId%5D%5B1%5D" of type integer.` even though I have Redis running (and can see some keys successfully set in the CLI, like `sess:*`).

**Comment by Seldaek** [comment]
The cache warnings i see as well, i suspect it's a doctrine cache misconfiguration since the 4.4 upgrade but haven't had a chance to dig further. If you find a solution feel free to PR that separately but you can also ignore it otherwise, things run fine anyway.

**Comment by BenMorel** [comment]
I opened a draft PR #1159 with some fixtures. Comments welcome!
