### ISSUE TITLE
Question: is there a way to request https://packagist.org/explore/popular via API?

### ISSUE THREAD

**Issue by wbars** [composer/packagist#1165]
Or request only top N items from https://packagist.org/packages/list.json sorted by popularity/downloads?

**Comment by stof** [comment]
https://packagist.org/explore/popular.json gives you the same list in JSON format

**Comment by stof** [comment]
@Seldaek this issue should be closed

**Comment by wbars** [comment]
@stof Is there a way to fetch more than 15 elements via this API?

**Comment by Seldaek** [comment]
You can get max 100 with https://packagist.org/explore/popular.json?per_page=100

**Comment by Seldaek** [comment]
Then there's a `next` key at the end with the link to follow for more
