### ISSUE TITLE
Packagist site and repo unreachable

### ISSUE THREAD

**Issue by ChadSikorra** [composer/packagist#1174]
I wasn't sure whether to open this here or not, but the packagist site and the main repo is currently un-reachable by me. It seems like my connection times out trying to reach anything hosted at OVH. The weird part is that the site, and OVH, seems reachable to me from my phone's data connection.

The only other report I see of issues people are having was this one:

https://github.com/composer/composer/issues/9795

If I set composer to some different mirrors I can get it to work. But are there any issues going on with the main one that would be impacting some subset of connections?

**Comment by Seldaek** [comment]
Not that I am aware of. Broader internet routing issues do happen every now and then though. What IP does repo.packagist.org resolve to for you? Can you try by setting the repository URL to `repo-us-west-1.packagist.org` or `repo-ca-bhs-3.packagist.org` explicitly see if either fixes it (please beware as those names are not stable and may disappear at any time)?

**Comment by ChadSikorra** [comment]
The name `repo.packagist.org` resolves to `142.44.164.249` for me. And when I attempt to tracepath to it this it dies at something in the OVH network it seems (`six.sea.wa.us.ovh.net`):

```sh
 1?: [LOCALHOST]                      pmtu 1500
 1:  _gateway                                              3.231ms 
 1:  _gateway                                              2.004ms 
 2:  10.2.25.1                                            14.869ms 
 3:  ???                                                   6.740ms 
 4:  ???                                                   3.763ms 
 5:  win-restech-services-002-01.direct.airstreamcomm.net   7.148ms 
 6:  air-eucl-asr-to-mdsn.airstreamcomm.net.194.33.64.in-addr.arpa  11.847ms 
 7:  ???                                                  13.102ms 
 8:  six.sea.wa.us.ovh.net                                78.465ms 
 9:  no reply
10:  no reply
11:  no reply
```

Neither of those repo addresses work for me either. They get stuck in the same spot as the above trace. Guess I have no idea how the hosting works for packagist and its infrastructure. Assuming the above hop is unrelated and just some messed up route I happen to be stuck on :/

**Comment by Seldaek** [comment]
I assume that's the SIX/OVH interchange all the way up left on http://weathermap.ovh.net/#usa 
![image](https://user-images.githubusercontent.com/183678/112733251-12706700-8f3f-11eb-8f23-c814b70daf2e.png)

Not sure what this tells us tbh, except that indeed it seems to be a network issue not really under our control.

**Comment by ChadSikorra** [comment]
Sounds good. Thanks for taking the time to check. I'll just have to keep an eye on when the network / routing issue resolves so I can switch off the mirror I'm on. Finding a mirror from the list that worked was actually a bit of a pain.
