### ISSUE TITLE
Not all versions are listed in JSON file

### ISSUE THREAD

**Issue by zim32** [composer/packagist#1175]
I have strange issue. I have pushed tag, to github. New version appears in packagist site, but not in json file

Here is json file https://repo.packagist.org/p2/zim32/symfony-rest-helper-bundle.json
I expect to see version 1.3.3 which is is listed here https://packagist.org/packages/zim32/symfony-rest-helper-bundle#v1.3.3

Beause of this issue composer did not see latest version

**Comment by ngmy** [comment]
I have the same issue.

https://repo.packagist.org/p2/ngmy/typed-array.json
https://packagist.org/packages/ngmy/typed-array#0.10.0

**Comment by ngmy** [comment]
It seems to have been reflected in the json just now.

**Comment by Seldaek** [comment]
Does anyone still see any issues?

**Comment by zim32** [comment]
Now it's ok

**Comment by Seldaek** [comment]
Ok then closing..
