### ISSUE TITLE
releases.rss not updating?

### ISSUE THREAD

**Issue by giggsey** [composer/packagist#1176]
https://packagist.org/feeds/releases.rss doesn't seem to have updated since last September.

    <pubDate>Fri, 11 Sep 2020 12:48:53 +0000</pubDate>

The atom feed is fine, and the other feeds are fine.

**Comment by giggsey** [comment]
Looks like you've fixed it after I created this.

If so, thanks!

Closing

**Comment by giggsey** [comment]
Spoke too soon - it's back to September.

I'll leave this open until you confirm.

**Comment by Seldaek** [comment]
It seems there was a cache corruption of some kind, I wiped all nginx caches clear and fixed our cache setup in https://github.com/composer/packagist/commit/edb80531d2784fd3bad165e980e1b7049f7b3f22, let's hope this prevents it from occurring again.
