### ISSUE TITLE
Packagist v2 endpoint returns version list instead of version map, confusing API documentation

### ISSUE THREAD

**Issue by steve-thousand** [composer/packagist#1177]
[The documentation for the v2 package endpoint](https://packagist.org/apidoc#get-package-data) lists this as an example response:

```
GET https://repo.packagist.org/p2/[vendor]/[package].json

{
  "packages": {
    "[vendor]/[package]": {
      "[version1]": {
        "name": "[vendor]/[package],
        "description": [description],
        // ...
      },
      "[version2]": {
        // ...
      }
      // ...
    }
  },
  "minified": "composer/2.0"
}
```

But it looks like when I hit [an example endpoint](https://repo.packagist.org/p2/monolog/monolog.json), the true format of the response contains a list of versions rather than a map of `version string -> version` like so:

```
{
  "packages": {
    "[vendor]/[package]": [
      {
        "name": "[vendor]/[package],
        "description": [description],
        // version1 ...
      },
      {
        // version2 ...
      }
      // ...
    ]
  },
  "minified": "composer/2.0"
}
```

Is this an error in the documentation or does the expansion of the minified JSON produce a map from the list, or is there something else I am misunderstanding here?

**Comment by stof** [comment]
this is a mistake in the doc (the v1 format was putting versions as keys in an object, so probably a bad copy-paste).
The minified format relies on the order of versions, and JSON does not guarantee the order of object keys.
