### ISSUE TITLE
New published version of the package not fetched by composer

### ISSUE THREAD

**Issue by soullivaneuh** [composer/packagist#1184]
I recently published `nexylan/nexycrypt:v0.8.1`, visible on packagist: https://packagist.org/packages/nexylan/nexycrypt#v0.8.1

However, composer still fetchs the `0.8.0` release (tested from a new blank project):

```
❯ composer req --ignore-platform-reqs nexylan/nexycrypt
Using version ^0.8.0 for nexylan/nexycrypt
```

Maybe a cache issue or something else? :thinking:

**Comment by Seldaek** [comment]
Are you using composer v2? 

I believe we are having issues with the v1 metadata at the moment, I'm investigating. v2 should work AFAIK.

**Comment by soullivaneuh** [comment]
I am :

```
❯ composer -v     
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 2.0.11 2021-02-24 14:57:23
```

**Comment by soullivaneuh** [comment]
FYI, I just tried again and now I have the correct release.

It seems the bug produces a delay but not a static bug.

**Comment by Seldaek** [comment]
Everything should be back on track now.
