### ISSUE TITLE
Values set as `"__unset"` in the p2 API

### ISSUE THREAD

**Issue by damz** [composer/packagist#1185]
In the JSON rendering of the p2 API, there are values that are set as the string `"__unset"`:

```
% curl -s https://repo.packagist.org/p2/composer/composer.json | jq | grep '__unset'
        "funding": "__unset"
        "conflict": "__unset"
        "require-dev": "__unset"
        "suggest": "__unset"
        "extra": "__unset"
```

**Comment by glaubinix** [comment]
This is part of the new Composer 2 metadata format. Only the first version in the list will be complete. All subsequent versions  only contain the diff compared to the previous version where `__unset` means that the field does not exist.

If you want to convert the data back to it's original format you can use the MetadataMinifier https://github.com/composer/metadata-minifier/blob/main/src/MetadataMinifier.php#L22-L46

**Comment by damz** [comment]
Sounds good, just wanted to report it in case this was an issue. There are no public reference to values set as `"__unset"` anywhere.
