### ISSUE TITLE
Reserve `local` vendor name for non-packagist packages

### ISSUE THREAD

**Issue by SerafimArts** [composer/packagist#1192]
## Problem

In the case of registering own package using a custom repository, you needs to specify the name of this package. The name of this package must be in the format `vendor/name`. For example:

```json
{
    "repositories": [
        {"type": "path", "url": "path/to/package"}
    ],
    "require": {
        "vendor/name": "*"
    }
}
```

The problem is that a situation may arise where a similar vendor or package name may appear on the package. Or some third party package might depend on this name. Like:

```json
{
    "name": "symfony/example-component",
    "require": {
        "vendor/name": "^1.0"
    }
}
```

In this case, an attempt to install this dependency will result in an error:

```json
{
    "repositories": [
        {"type": "path", "url": "path/to/package"}
    ],
    "require": {
        "vendor/name": "*",
        "symfony/example-component": "*"
    }
}
````

## Suggest

Reserve some system vendor name for local packages. Packages with such vendor-name should not be available to creating/reserving on pakagist.org. This way we can ensure that no conflicts will arise when using the reserved prefix.

I suggest the following acceptable names as options:
  - `local` - (https://packagist.org/packages/local/) I just registered this namespace for local packages and I want to transfer it to the community.
  - `app` - (https://packagist.org/packages/app/) This namespace is already registered by a third party user.
  - `vendor` - (https://packagist.org/packages/vendor/) This namespace is already registered by a third party user.
  - `system` - (https://packagist.org/packages/system/) This namespace is already registered by a third party user.
  
Some other option is also possible. We can discuss it.

In any case, I consider the option with the reservation of the `local` name is acceptable. Therefore, I propose to reserve this namespace for user needs and remove my `local/local` package when (if) the functionality is going to be implemented.

**Comment by Seldaek** [comment]
I am not strictly opposed to reserving a couple vendor names on packagist.org, but you have to keep in mind that this is only solving the potential for conflict on packagist.org, if you use other package repositories like drupal's or magento's they may not have the same reserved names.

I guess we could mention these reserved names here https://getcomposer.org/doc/02-libraries.md#every-project-is-a-package and also reserve acme/ for good measure.

However, I don't necessarily think it's a great idea for internal packages to just be called local/* or app/*, using your org's name as  a vendor name probably makes more sense and the risk of conflicts is extremely low.

**Comment by SerafimArts** [comment]
@Seldaek hmmm.... As an alternative idea: Is it possible then to allow the use of names without prefixes in the same way as it is done in the case of `ext-some`, for example `my-package`?

**Comment by stof** [comment]
@SerafimArts that would not solve things: `my-package` would still have issues with all `my-package/*` packages due to the structure of the vendor folder.

**Comment by SerafimArts** [comment]
@stof you misunderstood me. 

It is forbidden to name packages in the `[NAME]` format, only `[VENDOR]/[NAME]` is a valid option. And the following names are allowed as an exception to this rule:
- `php`
- `ext-xxx`

These are the existing "system reserved" names.

Thus, as an idea, I propose to add the ability to name packages for custom needs in a format like `acme-xxxx`, `vendor-xxx`, `local-xxx`, etc (The name of a valid prefix can be chosen later if everyone is satisfied with this proposal/idea).

**Comment by stof** [comment]
@SerafimArts if you name your package `acme-hello` and someones publishes a package named `acme-hello/world` on Packagist, you have a conflict: your own package would be installed in `vendor/acme-hello` and the open-source package would need to be installed in `vendor/acme-hello/world`. Nesting packages inside each other does not work.

The `ext-xxx` names don't cause such conflicts, because they are for platform packages, not for packages installed in the `vendor` folder.

**Comment by SerafimArts** [comment]
> @SerafimArts if you name your package acme-hello and someones publishes a package named acme-hello/world on Packagist, you have a conflict: your own package would be installed in vendor/acme-hello and the open-source package would need to be installed in vendor/acme-hello/world. Nesting packages inside each other does not work.

@stof it depends on the implementation. If this is implemented so that these packages will be installed along the `vendor/composer/acme` path, then there will be no conflicts.

**Comment by Seldaek** [comment]
We are definitely not going to do that. Frankly I think this whole issue is rather a solution looking for a problem. I haven't seen naming conflicts being a huge problem in practice in 10years of Composer.. so I think we can leave it as is.
