### ISSUE TITLE
"The last update failed in an unexpected way."

### ISSUE THREAD

**Issue by asgrim** [composer/packagist#1197]
Not even sure where to start looking at this...? 

https://packagist.org/packages/browscap/browscap isn't grabbing the latest release ([6.0.46](https://github.com/browscap/browscap/releases/tag/6.0.46)):

![Screenshot from 2021-05-29 23-06-09](https://user-images.githubusercontent.com/496145/120085738-84e1fc80-c0d2-11eb-8ffb-863156b1bd6e.png)

I click the "View last update log" link, it gives me a white box with `An unexpected failure occurred`.

If I click `Update` to manually update, nothing really seems to happen. Any advice would be appreciated please! Thank you folks.

**Comment by Seldaek** [comment]
Ah that was a type error due to your releases that don't contain any dots e.g. `6028` that got turned to an int when used in an array key and then obviously failed to be used as a string somewhere else because strict types.. Oops :D

Anyway fixed now.

**Comment by asgrim** [comment]
Thank you so much @Seldaek :+1: yes we switched to a less silly versioning scheme some time ago, but a tag is a tag forever :tm:  :disappointed:
