### ISSUE TITLE
Search not working due to content-security policy

### ISSUE THREAD

**Issue by HeyRatFans** [composer/packagist#1198]
Google Chrome 91.0.4472.77 on macOS Catalina 10.15.7 the search on Packagist.org for me. The errors shown in Chrome's developer tools are as follows:

`Refused to load the script 'https://cdn.jsdelivr.net.x.2e10a6a50cb5704edc092a1029b5813b2e70.9270fa5c.id.opendns.com/s/cdn.jsdelivr.net/npm/instantsearch.js@2.7.4/dist/instantsearch.min.js?X-OpenDNS-Session=_2e10a6a50cb5704edc092a1029b5813b2e709270fa5c_ZJzXgLeI_' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net/ https://www.google-analytics.com/ https://www.google.com/recaptcha/api.js https://www.gstatic.com/recaptcha/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

`search.js?v=1622725740:14 Uncaught ReferenceError: instantsearch is not defined`

Image of the errors and issues tab in Google Chrome:

<img width="1551" alt="Screen Shot 2021-06-04 at 11 46 21 AM" src="https://user-images.githubusercontent.com/1496909/120829030-1ca87600-c52b-11eb-8ed0-511e850dbaa8.png">

**Comment by stof** [comment]
it looks like something rewrite the script source here. The packagist sourcecode does not use `cdn.jsdelivr.net.x.2e10a6a50cb5704edc092a1029b5813b2e70.9270fa5c.id.opendns.com` as domain. The script source is https://cdn.jsdelivr.net/npm/instantsearch.js@2.7.4/dist/instantsearch.min.js which is allowed in CSP

You should check whether you have a browser extension (or a proxy) replacing the URL

**Comment by HeyRatFans** [comment]
It's probably by employer's VPN / security policy - I will check with them.

**Comment by Seldaek** [comment]
Yeah I have had one previous report of this same thing, but never got to the bottom of it. Not sure why opendns.com would insert itself there.

**Comment by HeyRatFans** [comment]
This was my being caused by employer's security policy - they made some changes to allow the search to function correctly.
