### ISSUE TITLE
Iterating through https://packagist.org/search.json may skip some packages

### ISSUE THREAD

**Issue by rob006** [composer/packagist#1204]
I had this problem before, but only for abandoned packages. Now this happens for this package: https://packagist.org/packages/akr/chevereto

Script to reproduce:

```php
$response = [
	'next' => 'https://packagist.org/search.json?page=1&type=flarum-extension&per_page=100',
];

$results = [];
do {
	$response = json_decode(file_get_contents($response['next']), true);
	foreach ($response['results'] as $item) {
		if ($item['name'] === 'akr/chevereto') {
			echo "Found\n";
			return;
		}
	}
} while (isset($response['next']));

echo "Not found\n";
```

I get "Not found" as a result, even if package clearly exist on Packagist. It can be also found when I use `https://packagist.org/search.json?page=1&type=flarum-extension&per_page=100&q=akr/chevereto` as URL, so it can be found using this API, but it looks like it is lost "between pages".

**Comment by rob006** [comment]
On second though it could be something with pagination - API reports 1118 results, but only 10 pages are available. Is there any hidden limit which will show only first 1k results in this enpoint?

**Comment by Seldaek** [comment]
It may be a restrictions of the search provider (algolia), not sure if the result count is a rough estimate or accurate, but most likely it is an estimate.

If you want all packages of a given type, you're way better off using our API endpoints, see https://packagist.org/apidoc e.g. https://packagist.org/packages/list.json?type=flarum-extension returns `akr/chevereto` in a single and simple request.

**Comment by stof** [comment]
@Seldaek there is indeed a limit: https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/

**Comment by rob006** [comment]
> If you want all packages of a given type, you're way better off using our API endpoints, see https://packagist.org/apidoc e.g. https://packagist.org/packages/list.json?type=flarum-extension returns `akr/chevereto` in a single and simple request.

Yes, but package name is not the only thing I need. For example I want to know if package is abandoned and what is its repository URL. With search I would need 12 requests. If all I have is list of packages names, I need almost 1200 requests. For now I'm using search to fetch first 1k packages and API to fetch individually remaining 200 records. With caching it works reasonably well, but it will get worse and worse as number of packages will grow. It would be great to at least have an endpoint to fetch package info in batches, like `https://packagist.org/search.json?page=1&package[]=akr/chevereto&package[]=rob006/example-package`.

**Comment by Seldaek** [comment]
OK, you can fetch repository using https://packagist.org/packages/list.json?type=flarum-extension&fields[]=repository - for abandoned there is no support yet, but it could be added.

**Comment by Seldaek** [comment]
OK now you get hopefully all you need at https://packagist.org/packages/list.json?type=flarum-extension&fields[]=repository&fields[]=abandoned
