### ISSUE TITLE
Latest package versions not visible for Composer

### ISSUE THREAD

**Issue by bobvandevijver** [composer/packagist#1205]
So, it seems there might be an issue with the API updates on Packagist. My latest two tags are propagated the [webinterface](https://packagist.org/packages/bobv/latex-bundle) and [vendor RSS feed](https://packagist.org/feeds/vendor.bobv.rss), but not fully to the [package RSS feed](https://packagist.org/feeds/package.bobv/latex-bundle.rss) and not at all to the composer [v1](https://repo.packagist.org/p/bobv/latex-bundle.json) or [v2](https://repo.packagist.org/p2/bobv/latex-bundle.json) endpoint.

Is anything broken, or is there something I did wrong? If it is the latter, I wouldn't know where to find the relevant error.

**Comment by Seldaek** [comment]
It's back now, sorry we had some major failure on the metadata dumping which I didn't pick up quickly enough due to bad combination of vacation and missing monitoring on something.

**Comment by bobvandevijver** [comment]
No worries, thank you for fixing it and keep up the good work! I just hope I didn't mess too much with your vacation 😅
