### ISSUE TITLE
I can't receive a message reset password.

### ISSUE THREAD

**Issue by hmingv** [composer/packagist#1207]
After submitting the password reset page, prompt:
An email has been sent that contains a link that you can click to reset your password. This link will expire in 24 hours.
If you don't receive an email please check your spam folder or try again.

But in fact, I didn't receive the email (Test other account binding "@qq.com" can be received)
My mailbox suffix is "@******.software", please help check

**Comment by Seldaek** [comment]
For which username is it?

**Comment by hmingv** [comment]
> For which username is it?

eternal-software

**Comment by Seldaek** [comment]
I see, there was a typo in the email, it was `.softwre` (missing `a`). I fixed that now so you can try a password reset again, I assume it will work now.

**Comment by hmingv** [comment]
Yes, I can log in normally. Thank you.
