### ISSUE TITLE
can not submit the register  form

### ISSUE THREAD

**Issue by marunrun** [composer/packagist#1220]
I set the env `APP_RECAPTCHA_ENABLED=false`
but i found the  [code](https://github.com/composer/packagist/blob/f57912d64181e4de2c405c0b63186e78d4c2e4f6/templates/registration/register.html.twig?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L3)
`{% set requiresRecaptcha = true %}` 

so I can not submit the register  form.

**Comment by Seldaek** [comment]
We do not support running packagist as a project sorry, if you do that you're on your own.
