### ISSUE TITLE
[bug] about information doesn't update on packagist

### ISSUE THREAD

**Issue by joubertredrat** [composer/packagist#1222]
Hi guys, 
When I created https://github.com/joubertredrat/deeper I put "Soon" in about during the development. When I added the project to packagist, I forgot to update this about, then packagist parsed the information, as image below.

![screenshot-packagist org-2021 11 29-11_36_18](https://user-images.githubusercontent.com/1520407/143887071-1d9e7d73-cfdd-4567-a590-8671dc816c39.png)

But I updated the about and tried to update about in packagist using update option, but doesn't update.

**Comment by Seldaek** [comment]
It's here :) https://github.com/joubertredrat/Deeper/blob/master/composer.json#L3

**Comment by joubertredrat** [comment]
Oh @Seldaek sorry, was my fault, I will provide fix for this
