### ISSUE TITLE
Images in README.md of GitLab repositories not loaded

### ISSUE THREAD

**Issue by pixelbrackets** [composer/packagist#1223]
**What I did**

- Package hosted on GitLab.com
- Add README.md with screenshots / images
- Add to package to Packagist

**What I expected**

- Images are rendered in the package detail view on packagist.com (just like any package hosted on GitHub.com)

**What happend instead?**

- The image is not rendered
- The relative link is not transformed to an absolute link pointing to GitLab.com, and therefore will fail to load

**Additional information**

I searched for [existing tickets](https://github.com/composer/packagist/search?q=gitlab+images&type=issues) and this seems to be an ongoing issue, with the images from GitLab being allowed, then removed again.

The current app does look for *GitHub* Readmes and replaces image links inside of them, see https://github.com/composer/packagist/blob/787bd997f96fcb812efa2b3683acb1770269d5df/src/Package/Updater.php#L682-L693

[Example package](https://packagist.org/packages/pixelbrackets/markdown-mini-page) hosted on GitLab and shown on Packagist with missing image on top (*Screenshot*).

**Comment by pixelbrackets** [comment]
Questions: 
* Is this a missing feature or an active decision (as in "we only modify GitHub READMEs")?
  * If missing feature: would it be okay if I try to pick this up in a PR and convert relative to absolute images for the three big git hosters GitHub.com, GitLab.com and BitBucket.com?

**Comment by stof** [comment]
At the time this was implemented initially, 95% of packages registered on packagist.org were hosted on GitHub.

Adding support for gitlab.com probably makes sense now.

**Comment by Seldaek** [comment]
We're still at 95% github.. so I am not going to bother, but sure feel free to send a PR I have nothing against supporting it.
