### ISSUE TITLE
Bug: Firefox could not download the search plugin

### ISSUE THREAD

**Issue by abolabo** [composer/packagist#1224]
Hi. 
Tried to add packagist info search engine list in the firefox and got error
Firefox could not download the search plugin from: https://packagist.org/search.osd?v=1638885118

To replicate 
1. open [packagist.org](https://packagist.org/)
2. click lens with green plus icon and choose "add packagist"
3. got alert

**Comment by Seldaek** [comment]
Ah it was missing the correct mimetype in the response, fixed now 👍🏻
