### ISSUE TITLE
<Please help> I can't install laravel. It's maybe composer setting problem.

### ISSUE THREAD

**Issue by shogaita01** [composer/packagist#1227]
Hi. This is Sho.

I am trying to install laravel with following command on terminal.
But I can't install.
I think some settings or files have problem.
Please kindly help.

Running "$composer global require laravel/installer"
Terminal gives me some error messages.
1-----------------------------------------------------------------------------------------------------------------------
https://repo.packagist.org could not be fully loaded (curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate), package information was loaded from the local cache and may be out of date
--------------------------------------------------------------------------------------------------------------------------
2------------------------------------------------------------------------------------------------------------------------
 [RuntimeException]                                                                                          
  No composer.json present in the current directory (./composer.json), this may be the cause of the followin  
  g exception.    
------------------------------------------------------------------------------------------------------------------------
3----------------------------------------------------------------------------------------------------------------------
[Composer\Downloader\TransportException]                                                                    
  curl error 60 while downloading https://repo.packagist.org/p2/laravel/installer.json: SSL certificate prob  
  lem: unable to get local issuer certificate   
------------------------------------------------------------------------------------------------------------------------

And the result of running "$ composer diagnose" is follow.
-----------------------------------------------------------------------------------------------------------------------
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://getcomposer.org/versions: SSL certificate problem: unable to get local issuer certificate
Composer version: 2.2.3
PHP version: 7.4.21
PHP binary path: /Applications/MAMP/bin/php/php7.4.21/bin/php
OpenSSL version: OpenSSL 1.0.2u  20 Dec 2019
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.0.2u
zip: extension present, unzip present, 7-Zip not available
-----------------------------------------------------------------------------------------------------------------------

And the result of running "$ composer diagnose -vvv" is follow.
-----------------------------------------------------------------------------------------------------------------------
Running 2.2.3 (2021-12-31 12:18:53) with PHP 7.4.21 on Darwin / 17.7.0
Reading ./composer.json (/usr/local/bin/composer.json)
Loading config file ./composer.json (/usr/local/bin/composer.json)
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt does not exist or it is not a file.
Checked directory /etc/ssl/certs/ca-certificates.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/ca-bundle.pem does not exist or it is not a file.
Checked directory /etc/ssl/ca-bundle.pem does not exist or it is not a directory.
Checked CA file /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a file.
Checked directory /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a directory.
Checked CA file /usr/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/usr/local/bin): git branch -a --no-color --no-abbrev -v
Executing command (/usr/local/bin): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/usr/local/bin): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/usr/local/bin): hg branch
Executing command (/usr/local/bin): fossil branch list
Executing command (/usr/local/bin): fossil tag list
Executing command (/usr/local/bin): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /Users/user/.composer/composer.json

Reading /usr/local/bin/vendor/composer/installed.json
Checking composer.json: Reading ./composer.json (/usr/local/bin/composer.json)
WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
[200] http://repo.packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate
Checking github.com rate limit: Downloading https://api.github.com/rate_limit
[200] https://api.github.com/rate_limit
OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
FAIL
[Composer\Downloader\TransportException] curl error 60 while downloading https://getcomposer.org/versions: SSL certificate problem: unable to get local issuer certificate
Composer version: 2.2.3
PHP version: 7.4.21
PHP binary path: /Applications/MAMP/bin/php/php7.4.21/bin/php
OpenSSL version: OpenSSL 1.0.2u  20 Dec 2019
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.0.2u
zip: extension present, unzip present, 7-Zip not available
-----------------------------------------------------------------------------------------------------------------------

**Comment by herndlm** [comment]
This pretty much looks like the same symptoms and setup as #1218 had. Please check that.

I assume your SSL bundle is outdated, your openssl version is also pretty old. I'm not sure how to update that on MacOS, but if you use brew installing `ca-certificates` should fix it. In #1218 the reporter seemed to update the file manually

**Comment by shogaita01** [comment]
Hi Thank you for your advise.
[Run]
brew install ca-certificates
[Result]
Warning: ca-certificates 2021-10-26 is already installed and up-to-date.
To reinstall 2021-10-26, run:
  brew reinstall ca-certificates

Still have error message with running "composer diagnose".

**Comment by herndlm** [comment]
Oh strange, I'm on Mac too on my work machine and Composer is using that file then. Well, you could still replace the other file as suggested in https://github.com/composer/packagist/issues/1218#issuecomment-963226201

**Comment by shogaita01** [comment]
Excuse me but which file?

**Comment by herndlm** [comment]
The one that composer identified as being your CA bundle
> Checked CA file /private/etc/ssl/cert.pem: valid
that one then, same procedure as was recommended in https://github.com/composer/packagist/issues/1218#issuecomment-963226201 should fix it then

**Comment by herndlm** [comment]
That's something you have to do in a console with root rights. You should have that file, maybe try `ls -al /private/etc/ssl/cert.pem` to verify?

**Comment by shogaita01** [comment]
Yes. I found it!!
Thank you.

[Run]
ls -al /private/etc/ssl/cert.pem
[Result]
-rw-r--r--  1 root  wheel  227344 12  5  2017 /private/etc/ssl/cert.pem

[Show in finder]
![スクリーンショット 2022-01-05 17 13 18](https://user-images.githubusercontent.com/94301795/148200598-65449ae9-3c57-44e5-800e-a8e84580dec4.png)

I will try to replace it.
And I will report the result later.

**Comment by shogaita01** [comment]
Hi.
Excuse me but I would like you to advise me how to replace ? update ? cert.pem.

**Comment by herndlm** [comment]
Something like the following should work, be careful with root
```sh
sudo cp /private/etc/ssl/cert.pem /private/etc/ssl/cert.pem.bak
sudo curl -L https://curl.se/ca/cacert.pem -o /private/etc/ssl/cert.pem
```

**Comment by shogaita01** [comment]
Thank you!!
I will try it.

**Comment by shogaita01** [comment]
Hi. Thank you for your advise.
I tried the commands that you gave me.
cert.pem has replaced, I think.

But "composer diagnose -vvv" result shows fail.
Please see bold text.

Running "composer global require laravel/installer" also shows simmilar error message.

Could you advise to solve it?

(Remark:Before I issue #1227, I manually put composer.json since terminal said "can't find composer.json")

**[Run]**
sudo cp /private/etc/ssl/cert.pem /private/etc/ssl/cert.pem.bak
then
sudo curl -L https://curl.se/ca/cacert.pem -o /private/etc/ssl/cert.pem

**[Result]**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

**[Run]**
composer diagnose -vvv

**[Result]**
Failed to initialize global composer: Composer could not find the config file: /Users/user/.composer/composer.json
To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage
Checked CA file /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /etc/pki/tls/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/certs/ca-certificates.crt does not exist or it is not a file.
Checked directory /etc/ssl/certs/ca-certificates.crt does not exist or it is not a directory.
Checked CA file /etc/ssl/ca-bundle.pem does not exist or it is not a file.
Checked directory /etc/ssl/ca-bundle.pem does not exist or it is not a directory.
Checked CA file /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a file.
Checked directory /usr/local/share/certs/ca-root-nss.crt does not exist or it is not a directory.
Checked CA file /usr/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /opt/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/local/share/curl/curl-ca-bundle.crt does not exist or it is not a directory.
Checked CA file /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a file.
Checked directory /usr/share/ssl/certs/ca-bundle.crt does not exist or it is not a directory.
Checked CA file /private/etc/ssl/cert.pem: valid
Checking platform settings: OK
Checking git settings: Executing command (CWD): git config color.ui
OK
Checking http connectivity to packagist: Downloading http://repo.packagist.org/packages.json
[200] http://repo.packagist.org/packages.json
OK
Checking https connectivity to packagist: Downloading https://repo.packagist.org/packages.json
**FAIL**
**[Composer\Downloader\TransportException] curl error 60 while downloading https://repo.packagist.org/packages.json: SSL certificate problem: unable to get local issuer certificate**
Checking github.com rate limit: Downloading https://api.github.com/rate_limit
[200] https://api.github.com/rate_limit
OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: Downloading https://getcomposer.org/versions
**FAIL**
**[Composer\Downloader\TransportException] curl error 60 while downloading https://getcomposer.org/versions: SSL certificate problem: unable to get local issuer certificate**
Composer version: 2.2.3
PHP version: 7.4.21
PHP binary path: /Applications/MAMP/bin/php/php7.4.21/bin/php
OpenSSL version: OpenSSL 1.0.2u  20 Dec 2019
cURL version: 7.68.0 libz 1.2.11 ssl OpenSSL/1.0.2u
zip: extension present, unzip present, 7-Zip not available

**Comment by herndlm** [comment]
The curl download command did not work. Because of the same outdated SSL certificate. This is a chicken egg kind of problem.
So either download the file with your browser and move it manually. Or run the curl command, that I pasted, with -k (as the error also suggests)

**Comment by shogaita01** [comment]
You mean 

`sudo cp /private/etc/ssl/cert.pem /private/etc/ssl/cert.pem.bak-k
sudo curl -L https://curl.se/ca/cacert.pem -o /private/etc/ssl/cert.pem-k`

right?

**Comment by herndlm** [comment]
Try only the following please
```sh
sudo curl -k -L https://curl.se/ca/cacert.pem -o /private/etc/ssl/cert.pem
```

**Comment by shogaita01** [comment]
I got you.
I will try it.

**Comment by shogaita01** [comment]
Thank you!!
Now it doesn't show any error!!
thank you very much!!
