### ISSUE TITLE
Releasing a package fails

### ISSUE THREAD

**Issue by recursivetree** [composer/packagist#1228]
I wanted to release a new package on packagist, but it failed when I tried to submit it:
```
Uncaught Exception: [RuntimeException] Failed to execute git clone --mirror -- 'https://e729c1134ea7bc221b771dc419a5b25d822780e2:x-oauth-basic@github.com/recursivetree/seat-inventory.git' '/home/composer/.cache/composer/vcs/git-github.com-recursivetree-seat-inventory.git/' Cloning into bare repository '/home/composer/.cache/composer/vcs/git-github.com-recursivetree-seat-inventory.git'... remote: Repository not found. fatal: repository 'https://github.com/recursivetree/seat-inventory.git/' not found
```

![Bildschirmfoto 2022-01-15 um 20 04 52](https://user-images.githubusercontent.com/60423027/149634651-332a94c8-8388-474b-a3f7-d001e74d7a59.png)

I did rename my repository an hour before, so it might be related to it

**Comment by recursivetree** [comment]
forgot to make it public, that fixed it. Maybe consider to add a better error message

**Comment by stof** [comment]
@Seldaek those error messages being displayed should probably sanitize the git credentials.

**Comment by Seldaek** [comment]
Yes that's fixed already
