### ISSUE TITLE
curl error 60 while downloading https://packagist.phpcomposer.com/packages.json: SSL certificate problem: self sign ed certificate in certificate chain

### ISSUE THREAD

**Issue by jengka80** [composer/packagist#1230]
Hi i have an issue "curl error 60 while downloading https://packagist.phpcomposer.com/packages.json: SSL certificate problem: self signed certificate in certificate chain" when i create Laravel through Laragon. I've downloaded the latest cacert.pem and already changed my php.ini "curl.cainfo = "C:\laragon\etc\ssl\cacert.pem""... But it still doesn't work.

Please help me.. thanks

**Comment by Seldaek** [comment]
packagist.phpcomposer.com is not packagist.org - it's a mirror which ew do not support. Remove it from your composer config to use the default packagist.org servers which should not have this issue.
