### ISSUE TITLE
Cleaning up the search feature

### ISSUE THREAD

**Issue by chr-hertel** [composer/packagist#1239]
When I was working on cleaning up the search feature in #1238, I realized that there are more use cases in it than I initially thought.

So there a basically two options:
* cleaning up while keeping feature parity
* consolidate use cases and introduce breaking changes

Before you decide on the options, let's have a look at what we have:

## Status Quo
This is a short summary of what I understood of the current implementation.

### Main Search Functionality (Algolia)
* Javascript implementation
* Part of base layout (using even `render(controller(...))`)

### Query Promotion
* Multiple get params for query
  * The short one: q, e.g. [packagist.org/?q=twig](https://packagist.org/?q=twig)
  * The forms one: search_query[query], e.g. [packagist.org/?search_query[query]=twig](https://packagist.org/?search_query[query]=twig)
  * The normal one: query, e.g. [packagist.org/?query=twig](https://packagist.org/?query=twig)

All of them are promoted to the forms one by [WebController::computeSearchQuery](https://github.com/composer/packagist/blob/main/src/Controller/WebController.php#L427-L448)

**Known issues:**
* unused `orderBys`
* unnecessary usage of form component

### Package Redirection
* Only based on query
* Implemented on `homepage` and `search`

### Search Action
* /search/ and search.html
  * supports Package Redirection
  * Empty content
  * Search provided via Javascript
* /search.json
  * supports Package Redirection (valuable)
  * Part of promoted API

**Known issues:**
* Broken query string handling, see [packagist.org/search.json?search_query=](https://packagist.org/search.json?search_query=)
* Redirection useless in API search, see [packagist.org/search.json?query=twig/twig](https://packagist.org/search.json?query=twig/twig)

## Proposal
* Wrap functional tests around functionality we want to keep
* Introduce search service as interface to algolia
* Kill search actions with HTML Output and focus on JS variant and API
* Kill form component usage and `search_query[query]` variant

So, WDYT?

**Comment by stof** [comment]
The search endpoint is also exposed in the composer repository, using `/search.json?q=...&type=...` right now

**Comment by Seldaek** [comment]
I think the proposal sounds good, cleaning this up would definitely be great as this huge mess of varied args and all is terrifying to modify right now :) 

HTML output search probably not needed, but `https://packagist.org/search/?q=...`  should keep working at least IMO, if it works by loading search params in JS and query algolia in the frontend this is fine, but it shouldn't break. API of course should also keep working.

Then whatever else we forgot can be fixed when someone complains we broke it I guess 🤷🏻‍♂️

**Comment by chr-hertel** [comment]
I guess we're good here for now since #1238 got merged :)
