### ISSUE TITLE
[Question] Disabeling auto-update for abandoned packages

### ISSUE THREAD

**Issue by mimmi20** [composer/packagist#1246]
I have some abandoned packages. One of them is https://packagist.org/packages/mimmi20/file-loader. This package is also archived on Github. Now I got an email, that the auto-update failed, because the composer.json is invalid.

Is there an option to disable auto-update for all my abandoned packages?

**Comment by Seldaek** [comment]
Auto-updating is disabled for abandoned packages actually so this should be fine. Yesterday I had to update all old packages to trigger some data migration step which is why you got the warning I believe.
