### ISSUE TITLE
Replace google fonts

### ISSUE THREAD

**Issue by mariusbuescher** [composer/packagist#1247]
Due to a recent [court decision](https://rewis.io/urteile/urteil/lhm-20-01-2022-3-o-1749320/) in Germany there might be legal problems regarding GDPR by using google fonts.

The font could be hosted on the packagist servers itself, which circumvents problems regarding GDPR.

**Comment by Seldaek** [comment]
Thanks, saw this as well this morning, a good reason to finally get this done :) 

For reference there are other good reasons to do this https://wicki.io/posts/2020-11-goodbye-google-fonts/
