### ISSUE TITLE
Private Packagist does not look upstream when dev version is "matched"

### ISSUE THREAD

**Issue by Wirone** [composer/packagist#1251]
We use Private Packagist (version 1.9.9, as far as our admins told me) both for our internal packages and for public packages. There is edge case, when we can't update packages because our Private Packagist does not have new releases yet (because of 1200 minutes update interval) but it does not look upstream on official Packagist because dev version was matched. 

Imagine scenario:
* I have `phpstan/phpstan` 1.4.4 installed, with `^1.4` constraint
* PHPStan 1.4.5 is released and it's available on `packagist.org` but NOT on our private Packagist (awaiting update)
* I change constraint to `^1.4.5` to enforce newer version
* I do `composer update phpstan/phpstan -w` and instead of getting 1.4.5 I get `Root composer.json requires phpstan/phpstan ^1.4.5, found phpstan/phpstan[dev-master, 1.4.x-dev (alias of dev-master)] but it does not match your minimum-stability.`

This does not make sense for me. [`1.4.x-dev` does not satisfy `^1.4.5`](https://jubianchi.github.io/semver-check/#/^1.4.5/1.4.x-dev) so why is it listed? Why our Private Packagist does not look upstream and update package's information?

Without changing constraint, as far as I remember (can't verify it right now, will do it after new release), there is info that no new version is available, which is somehow OK (not DX-friendly, but reasonable). But that scenario when I explicitly call for newer version that I know it exists, and I don't get it, looks like bug for me.

**Comment by Seldaek** [comment]
The semver check page is buggy there.. 1.4.x-dev is mapped to 1.4.9999999-dev internally so it definitely matches ^1.4.5

Please trust Composer over some random page on the internet ;) I reported it as https://github.com/jubianchi/semver-check/issues/113

As for the phpstan issue, please note that 1.9.9 is *very old* almost 2 years old, you should really update. I am pretty sure this was not using the modern Composer 2 update mechanism which should make updates from packagist.org available very quickly, so that probably explains why it's taking a while to get the new version.

**Comment by Wirone** [comment]
Thank you very much @Seldaek 🙂 Yeah, we're pushing for the upgrade right now, so I hope we'll use latest version soon. Then I'll verify how it behaves in terms of new releases, so feel free to close this if you want, I'll come back if we'll have problems on newest version.

**Comment by Seldaek** [comment]
Sure, in the meantime I believe you should be able to trigger an update of the mirrored package in the interface, which should allow you to upgrade for now.

Also note that this repo is for packagist.org in theory ;) It's probably best if you use the packagist.com support chat or email for Private Packagist questions.

**Comment by Wirone** [comment]
@Seldaek FYI we were able to upgrade to 1.10.8 and it seems like problem disappeared - new versions are available really fast 🥳

**Comment by Seldaek** [comment]
Good to hear :) Make sure you run Composer 2.x too to get the most speed out of it all :)
