### ISSUE TITLE
The API `/p/vendor/package.json` response JSON invalid when no packages

### ISSUE THREAD

**Issue by JacksonTian** [composer/packagist#1256]
When no packages found, it responses a array:
```json
{
  "packages": [
  ]
}
```
The packages is an empty array. Like: https://packagist.org/p/keycdn/optimus-api$454eea274ef715bed0aef364fec823e04318850d28eb04f1c16a03a5127c071c.json

The expected struct is

```json
{
  "packages": {}
}
```

The normal response case:  https://packagist.org/p/tugmaks/russian-text-uniqifier$6097fb12f9723ce4b0fcf4dc08daf998adc2005af411fdc793aec5bfa7ce449f.json

**Comment by chr-hertel** [comment]
Everything alright here:
https://3v4l.org/Dtu90

At least according to PHP standard behavior. Fail to see the see issue this might introduce for clients. So only a matter of expectations IMO.

**Comment by Seldaek** [comment]
This can cause issues if you are using some more strongly typed language where the json has a very strict struct expectation, so I'm happy to fix. 

But please note that you should use the p2/ URLs (see https://packagist.org/apidoc#get-package-data ) as they are more up to date, more complete, and not deprecated. Or use the list endpoint if you are trying to know which packages exist (https://packagist.org/apidoc#list-packages).
