### ISSUE TITLE
Remove politics from update banner

### ISSUE THREAD

**Issue by InTostor** [composer/packagist#1271]
That was added in this file, on 321 line 
src/Package/SymlinkDumper.php
In commit 86244a3695fcaaac9c5ba4257a4314eae1c6d981

This change can cause escalating the political situation, international conflicts and etc. 

Github is bad place for politics. For it, go to government or anywhere else.

**Comment by naderman** [comment]
There are innocent civilians injured and killed every day in Ukraine right now and it needs to end, do not close your eyes to their suffering.

As Jordi pointed out:

> Quoting someone else who said it well, I won't link tho because I don't want to send the haters his way..
> 
```
  ;; You might be reading this because you think it is not appropriate
  ;; to mix politics with software development.
  ;; Or that I should have added banners like #StandWithPalestine or #StandWithYemen,
  ;; and adding it now makes me a hypocrite. And you are right.
  ;; I understand the reasoning, but I decided to add the banner now, because this
  ;; time people I hold very dear are in Kyiv, fighting for their family, their
  ;; lives and their country. Because I know them well, I am
  ;; personally affected.
  ;; So if you disagree, just deal with it, or stop using this tool.
```
> 
> It's a mix of that, and a feeling that this war could have a much bigger/more global impact than others.
