### ISSUE TITLE
Honestly

### ISSUE THREAD

**Issue by garethnic** [composer/packagist#1272]
Why do we need to see political messaging every time we use composer?

It's okay if devs wanna write blogs about the issue of the day, cater websites to it etc. But why mess with the tools and force this one every single dev around the world that has to use this. 

This adds nothing but a visual distraction.

**Comment by Seldaek** [comment]
Bombs are also distracting, I guess you can be glad you just have to deal with some colorful text.

**Comment by garethnic** [comment]
Ja buddy, virtue signal harder.

**Comment by paxperscientiam** [comment]
“Virtue signaling” is the thoughtless squawk for today’s hip, haughty reactionary on-the-go.

As with the context of this discussion, it’s rhetoric deployed to shield oneself from discomfort through (failed) suppression of free expression of complex social issues.

You don't like it? Fork off.

**Comment by garethnic** [comment]
Yeah @paxperscientiam fuck you too.
