### ISSUE TITLE
What is this? You are was hacked?

### ISSUE THREAD

**Issue by WhiteKinkyclone** [composer/packagist#1273]
Why is this here? You are was hacked?? Am i ok, with this?
![2022-03-18_13-16_1](https://user-images.githubusercontent.com/17406112/158962597-e34251f8-3b7f-42ab-a8c7-d00fc4a97770.jpg)

**Comment by Seldaek** [comment]
It seems you are still using Composer 1 despite Composer 2 having been released a year and a half ago. Make sure you upgrade with `composer self-update --2` 👍🏻 

As for the other warning, you are ok don't worry, we have not been hacked.

**Comment by WhiteKinkyclone** [comment]
@Seldaek I'm talking about #StandWithUkraine and not about my version
