### ISSUE TITLE
Remove #StandWithUkraine 

### ISSUE THREAD

**Issue by thursdaybw** [composer/packagist#1276]
Messages like this have absolute no place in the output of a tool It has no place here any more than it would if you put it in a speaker in my hammer and forced the user to listen to it.

It should be removed as a matter of urgency. Send the message on twitter, not in composer.

https://github.com/composer/composer/discussions/10600

**Comment by wilty39** [comment]
Next up, #GetyourBOOSTER!!!

**Comment by Seldaek** [comment]
Yes, also go get your fucking booster.
