### ISSUE TITLE
The stand with ukraine message makes it feel like malware is being installed.

### ISSUE THREAD

**Issue by Quilava1** [composer/packagist#1279]
When I installed a package and saw the #StandWithUkraine letters, I panicked and quickly closed the terminal, thinking it was installing malware infected dependancies. And it led to a good half hour of searching why it appeared. I was worried my PC at that point had malware installed and was trying to remove it. 
Seeing messages like that on installer is confusing. I think most developers seeing something like that appear on the console will alt+f4 before seeing why the message is there.

**Comment by karol-haltenberger** [comment]
#1280

**Comment by Seldaek** [comment]
Yes.. because if your computer is compromised and running third party code, closing the window is definitely fixing it. Sorry but that sounds like ostrich security practices.

Anyway, we will remove this when we deem it appropriate, thank you.

**Comment by almazdanilov** [comment]
Now composer is malware itself. Please use clear one https://github.com/open-composer/composer

**Comment by kryoz** [comment]
It seems Seldaek has become not only excellent developer but a great political analyst.

**Comment by politsin** [comment]
```sh
git clone https://github.com/composer/composer.git --branch 2.5.4  ~/composer-build && \
    composer install  -o -d ~/composer-build && \
    wget https://raw.githubusercontent.com/politsin/snipets/master/patch/composer.patch -q -O ~/composer-build/composer.patch  && \
    cd ~/composer-build && patch -p1 < composer.patch && \
    php -d phar.readonly=0 bin/compile && \
    rm /usr/local/bin/composer && \
    php composer.phar install && \
    php composer.phar update && \
    mv ~/composer-build/composer.phar /usr/local/bin/composer && \
    rm -rf ~/composer-build  && \
    chmod +x /usr/local/bin/composer
```
