### ISSUE TITLE
Unable to submit package to packagist.org

### ISSUE THREAD

**Issue by dvikan** [composer/packagist#1283]
Error: `The package name was not found in the composer.json, make sure there is a name present.`

The package does indeed have a package name in `composer.json`.

This is on https://packagist.org for https://git.sr.ht/~thirdplace/http

I suspect there's an item in the cache because I may have submitted a prior package with the same name, and then deleted it.

Maybe it's related to branch names. My new package uses `main` while the prior one possibly used `master`.

@Seldaek

**Comment by Seldaek** [comment]
Yup that does look like there was a cache issue here. Not sure.. but anyway you can try to submit again now.
