### ISSUE TITLE
Is there a way to get the package hash(md5,sha1,sha512...) by an API call? 

### ISSUE THREAD

**Issue by p-brito** [composer/packagist#1296]
Hi

Is there a way of getting the original package hash by an API call? 

Ty

**Comment by Seldaek** [comment]
I'm not sure what hash you are referring to, but I'm afraid the answer is no.

**Comment by simialbi** [comment]
@p-brito you see the hashes here:
https://repo.packagist.org/packages.json
And so on in the corresponding files. E.g.:
https://repo.packagist.org/p/provider-2013$28c7556bfcc60a0c1fd17c3c80d4e3b0a97813acba7a2ac3f4ee10fa63b1e6af.json
