### ISSUE TITLE
https://asset-packagist.org/packages.json is down

### ISSUE THREAD

**Issue by jlariza** [composer/packagist#1297]
https://asset-packagist.org/packages.json is down so `composer update` command does not work.

I tried running a wget and this was the answer

```
wget https://asset-packagist.org/packages.json
--2022-04-18 19:40:32--  https://asset-packagist.org/packages.json
Resolving asset-packagist.org (asset-packagist.org)... 75.2.81.221
Connecting to asset-packagist.org (asset-packagist.org)|75.2.81.221|:443...
```

it never resolved

Thank you,

**Comment by RundleSG** [comment]
The asset-packagist devs are based in Ukraine. It looks like the domains expired, theres a issue over https://github.com/hiqdev/asset-packagist/issues/146

**Comment by stof** [comment]
This repo is not about asset-packagist.org which is a separate project.

**Comment by SilverFire** [comment]
Asset-packagist is up, sorry for the troubles. You can find an explanation in the original issue: https://github.com/hiqdev/asset-packagist/issues/146#issuecomment-1106742011
