### ISSUE TITLE
Composer require returns a very old version of the package

### ISSUE THREAD

**Issue by lucraraujo** [composer/packagist#1306]
When I require the package `laravel/framework` I get the version ^4.2 as the most recent but the most recent should be ^9.14.
I have experienced the same issue trying to install other package some time ago.
PHP Version: 8.1.5
Composer version: 2.3.5
Command executed: `composer require laravel/framework`

**Comment by chr-hertel** [comment]
cannot reproduce on empty folder
![Bildschirmfoto von 2022-05-26 14-54-19](https://user-images.githubusercontent.com/2852185/170491676-349c9e0d-c9d4-4756-97ae-3d62e3c7f411.png)

What does the output of `composer why-not laravel/framework 9.14` say? if it's not the php version maybe another pre-existing dependency hinders the latest version to be installed

**Comment by lucraraujo** [comment]
I ran the command and I was  missing the mbstring module.
