### ISSUE TITLE
Security Advisories API requires "packages" even if "updatedSince" is included in request

### ISSUE THREAD

**Issue by GuySartorelli** [composer/packagist#1310]
## Description
[The documentation](https://packagist.org/apidoc#list-security-advisories) for the security advisories API suggests that `packages` can be omitted if `updatedSince` is passed in - but this isn't the case.
> Either a list of packages as query or request parameter or a timestamp as updatedSince query parameter need to be passed.

But if I send a request that includes `updatedSince` but omits `packages` I get an error as below. I suspect it is the documentation rather than the implementation that is incorrect - I can't think of a use case where getting _all_ updates since a given time would be useful.

## Reproduce
`curl -X POST -F 'updatedSince=1653893419' https://packagist.org/api/security-advisories/`
> {"status":"error","message":"Missing array of package names as the \u0022packages\u0022 parameter"}

**Comment by stof** [comment]
Can you send a PR updating the doc ?

**Comment by GuySartorelli** [comment]
@stof #1311

**Comment by GuySartorelli** [comment]
As pointed out in the PR:
> Sending one of them is enough however, updatedSince is currently expected to be set as query parameter. See https://github.com/composer/packagist/blob/main/src/Controller/ApiController.php#L322

> Query parameters are not limited to GET requests. You can also use them with POST requests e.g. curl -X POST https://packagist.org/api/security-advisories/?updatedSince=TIMESTAMP
