### ISSUE TITLE
Feature Request: Jump to search with `/`

### ISSUE THREAD

**Issue by LiamKearn** [composer/packagist#1313]
Google now almost universally adopted this UX principal. Would be really nice for something with heavy searching like packagist.

If anyone else is interested would be appreciated happy to make a PR.

**Comment by Seldaek** [comment]
Not against it if you want to PR it. But tab should work already FYI

**Comment by LiamKearn** [comment]
Yeah its the first element on the page that is focusable. That should make it easy but for some reason for me I always find myself: `mod+f -> search "sign in" because it is visually before the searchbar -> tab` and it never works 😄. In reality the mental pattern I should have is `mod+r -> tab` but I feel spoilt by the recent influx of websites that support `/` to search (even github right now).

**Comment by stof** [comment]
@Seldaek this should be closed as it has been implemented
