### ISSUE TITLE
Wrong forks URL destination!

### ISSUE THREAD

**Issue by ngekoding** [composer/packagist#1319]
I don't know is this a bug or not, but I see it is a bug.

So, when we try to see (click) the package/repository forks, it will open `https://github.com/{username}/{package}/network` URL, but the actual URL is `https://github.com/{username}/{package}/network/members`. So, it just missed `/members` part.

Here I attach the screenshot for better.

![Forks Link Bug](https://user-images.githubusercontent.com/11625690/176122509-0467a42b-27d6-49a6-b5f9-6298b8a003b8.png)

Thanks in advance

**Comment by Seldaek** [comment]
IMO this is the better page to see forks because it shows recently active forks. The members list is just a flat list of all forks but it does not tell you any information about which are dead or alive.

**Comment by ngekoding** [comment]
@Seldaek Thanks for the clarification.
