### ISSUE TITLE
[RFC] displaying latest version in search engine view result

### ISSUE THREAD

**Issue by 94noni** [composer/packagist#1320]
Hi

I would like to know if it can be useful to display such info on http://packagist.org/ website

here is an example:
<img width="882" alt="Capture d’écran 2022-07-28 à 14 08 27" src="https://user-images.githubusercontent.com/1358361/181501501-35ccd14a-a2dd-4d1d-8869-2e7e5495d8e1.png">

---

We can imagine storing such data in the package when a new version is added to it
And index such data when indexing all data for the search engine

**Comment by Seldaek** [comment]
What's the value of knowing the last version in a listing though?

**Comment by IonBazan** [comment]
I think npm provides similar feature:
![image](https://user-images.githubusercontent.com/1985514/188569159-84e11a19-f6ca-4de7-ad2b-00eb9df3164f.png)
![image](https://user-images.githubusercontent.com/1985514/188569204-17f9b934-aae7-4130-839d-0f11aaf5a154.png)

Not sure if it provides much value here but I think the last publish date would be helpful here to decide which package is still actively maintained without going to the details page.

**Comment by 94noni** [comment]
@Seldaek @IonBazan thx for stopping here

> What's the value of knowing the last version in a listing though?

mostly yes to know how a package evolve, some projects has little deps tho knowing a packages have new versions is good
also yes with the date, both could be good (mimic the npm page)

it was just an idea I got this summer tho wanted to write it down, if you think it is not that relevant, could be closed for now, thanks

**Comment by chr-hertel** [comment]
I would argue that the search results should give info that helps a developer to choose if a package is worth investigating or not - the detail view will be used anyways btw.
I can see how stars and downloads help with that, but i don't think the version number is really relevant.
the only thing i can see is that it would be worth providing an info about stability of a package, like is there a stable version or not for example

**Comment by Seldaek** [comment]
I can see some value in the last release date to see if something's been "dead" for years, although in some cases I'd argue stuff is just stable and working and doesn't need work and thus it's fine. For example https://packagist.org/packages/seld/cli-prompt is almost 2y stale and before that it was almost 3y.. yet it "just works".

So even the date needs to be taken with a grain of salt, and newer isn't necessarily better.

The version is even less "comparable" between packages IMO, so why show it in a list? 

Overall not so convinced that more info is more value.

**Comment by 94noni** [comment]
@Seldaek @chr-hertel fair enough, thx for taking time to comment

then we can consider closing? if it does not add much value for majority ppl

or you want to keep open to discus what can be added (not the latest version) but others data

**Comment by Seldaek** [comment]
Yeah I think I'd rather close then. We can always revisit later if there are more compelling arguments

**Comment by 94noni** [comment]
PR as discussion draft opened here https://github.com/composer/packagist/pull/1410
Feel free to comment :)
