### ISSUE TITLE
HTML-Link in error message is escaped

### ISSUE THREAD

**Issue by JanSlabon** [composer/packagist#1341]
I just tried to add a new package and received a "Gateway error". After reloading (F5) the package was added but an error message appears which seems to have the link unwanted escaped:

![grafik](https://user-images.githubusercontent.com/12390057/201699019-bcd2bb0e-9250-4b9b-a137-1d3c49f53b0a.png)

**Comment by Seldaek** [comment]
Do you have JS disabled? Because normally it shows up like this with JS:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/183678/213159174-8e210dea-6979-4940-9121-f73c6b9efab6.png">

**Comment by Seldaek** [comment]
Yeah can repro by disabling javascript.. but I have to say I don't really care to fix that edge case.

**Comment by JanSlabon** [comment]
Okay, but I had JS enabled 🤷🏻‍♂️

**Comment by Seldaek** [comment]
Ah well.. might have been a glitch in JS loading if something was temporarily offline? I'm not sure.. can you still reproduce if you try to submit an already existing package URL?
