### ISSUE TITLE
Abandoned packages in google

### ISSUE THREAD

**Issue by ro0NL** [composer/packagist#1347]
Abandoned packages seem to be indexed by google

![image](https://user-images.githubusercontent.com/1047696/209995343-9399e088-1377-4412-a2ba-e427d5d1259e.png)

shall we not? :D

**Comment by Seldaek** [comment]
Not so sure about this.. Abandoned doesn't really mean it should be wiped from the earth IMO :)

**Comment by ro0NL** [comment]
yes i removed the git repo :) (after migration comes removal)

generally im not sure abandoned packages should be advertised in whatever way

however, there is defintively a state issue currently, causing a "Broken package" (let it be abandoned or not), because the repo url got broken over time.

**Comment by Seldaek** [comment]
I deleted thoes two dead packages you had there. So they'll be gone from google too in time. IMO if the content is still there even if abandoned it should remain discoverable.
