### ISSUE TITLE
The PHP version usage statistics is not include 8.2 version

### ISSUE THREAD

**Issue by vtsykun** [composer/packagist#1349]
https://packagist.org/php-statistics
![Selection_1135](https://user-images.githubusercontent.com/21358010/210360796-870d644d-5a18-4b79-bb82-932569f9dac9.png)
PHP 8.2 was released a month ago, but on the PHP version graph it not showing (stopped showing between 2022-08 and 2022-09).

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/packagist/commit/736ea0268ce1eadf4af522ec5649ae0f168cc547
