### ISSUE TITLE
Is there any end of life date for https://repo.packagist.org/p/[vendor]/[package].json

### ISSUE THREAD

**Issue by PrajwalJeethan** [composer/packagist#1352]
Is there any end of life date for https://repo.packagist.org/p/[vendor]/[package].json

**Comment by Seldaek** [comment]
Nope, we are still updating them for now. I think at worst we may stop updating at some point and keep a readonly copy but I don't think we can "ever" delete it. That said, it doesn't contain new packages and is not updating as frequently so you should definitely use the p2 (v2) endpoints, see https://packagist.org/apidoc#get-package-data
