### ISSUE TITLE
Why do I get this error message when I try to submit my repository?

### ISSUE THREAD

**Issue by 91ahmed** [composer/packagist#1358]
**Warning: The package name is blocked, if you think this is a mistake please get in touch with us.**

I get this error message every time I am trying to submit the Github repository.
I've changed the package name several times, and I'm still getting the same error.

Note: this is my first time to use Packagist, can someone help please.

**Comment by vtsykun** [comment]
Hi @91ahmed 
The Packagist uses this [regex](https://github.com/composer/packagist/blob/36fc31c61c4310981046ec924de5b37b6bf07ff7/src/Validator/ValidPackageRepositoryValidator.php#L100) to check for a valid package name

```
(free.*watch|watch.*free|(stream|online).*anschauver.*pelicula|ver.*completa|pelicula.*complet|season.*episode.*online|film.*(complet|entier)|(voir|regarder|guarda|assistir).*(film|complet)|full.*movie|online.*(free|tv|full.*hd)|(free|full|gratuit).*stream|movie.*free|free.*(movie|hack)|watch.*movie|watch.*full|generate.*resource|generate.*unlimited|hack.*coin|coin.*(hack|generat)|vbucks|hack.*cheat|hack.*generat|generat.*hack|hack.*unlimited|cheat.*(unlimited|generat)|(mod(?!ule)|cheat|apk).*(hack|cheat|mod(?!ule))|hack.*(apk|mod(?!ule)|free|gold|gems|diamonds|coin)|putlocker|generat.*free|coins.*generat|(download|telecharg).*album|album.*(download|telecharg)|album.*(free|gratuit)|generat.*coins|unlimited.*coins|(fortnite|pubg|apex.*legend|t[1i]k.*t[o0]k).*(free|gratuit|generat|unlimited|coins|mobile|hack|follow))
```

I see that your package name `jsonphpmodifier/json-modifier`  matches to pattern 
```
(mod(?!ule)|cheat|apk).*(hack|cheat|mod(?!ule))
```
Live regex validator checker https://www.phpliveregex.com/
![Selection_1242](https://user-images.githubusercontent.com/21358010/215238822-e8e42676-e098-4e91-95df-fc2eb761c598.png)



You can try choosing a different vendor name to not include `mod` substring in two parts of the package name and vendor together. For example `<youorgname>/json-modifier`

**Comment by 91ahmed** [comment]
@vtsykun 

Thank you so much

**Comment by Seldaek** [comment]
@91ahmed sorry about this, this is to block some spam we got in the past, but I can add an exclusion for your vendor if you like to submit with a name that is reasonable, let me know.

**Comment by 91ahmed** [comment]
@Seldaek 

Ok, the original vendor name would be better. 
Thanks for help

**Comment by Seldaek** [comment]
OK @91ahmed you can now delete the new package and resubmit with the other name.
