### ISSUE TITLE
Unexpected files in packages (should be removed by `archive.exclude`)

### ISSUE THREAD

**Issue by cedric-anne** [composer/packagist#1364]
I am not sure where I should open this issue, as I do not know who is responsible of crafting dist archives that are downloaded by composer.

I figured out the, at least on 2 packages, `dist` package fetched when running the `composer install --prefer-dist --no-cache` contains files and directories that should not be there due to `archive.exclude` rules.

Packages are `bacon/bacon-qr-code:2.0.8` and `robthree/twofactorauth:2.0.0`.

My composer version is `Composer version 2.5.4 2023-02-15 13:10:06`.

**Comment by Seldaek** [comment]
This setting is only used when running composer archive explicitly. Most packages are zipped up by github using git export tho for which ignore rules should be added to .gitattributes instead e.g. https://github.com/composer/composer/blob/main/.gitattributes#L13

**Comment by cedric-anne** [comment]
I used to add ignore rules in `.gitattributes`, but at least 2 people that are building RPM packages for CentOS/Fedora says that they are requiring tests to be present in Github archives to be able to run them in their packaging build process.

Would a routine that do the clean after archive extraction could be accepted?

**Comment by stof** [comment]
Packagist does not do any archive extraction.

**Comment by vtsykun** [comment]
+1

Is it possible to do this at the Composer `ArchiveDownloader` level? This would be useful as it allowed to reduce the size of the vendors and the size of docker image

**Comment by cedric-anne** [comment]
> Packagist does not do any archive extraction.

Indeed, I was not aware of this before @Seldaek comment. Maybe this issue could be moved in `composer/composer` repository.

**Comment by williamdes** [comment]
ping @voku (https://github.com/phpmyadmin/sql-parser/pull/379#issuecomment-1173872883)

**Comment by cedric-anne** [comment]
I close this topic as it is not located on the good repository. Maybe I will open a similar one on `composer/composer` later, but I currently have no time to invest on this subject.
