### ISSUE TITLE
How to share package version information between GitHub and packagist via Webhooks?

### ISSUE THREAD

**Issue by siims-biz** [composer/packagist#1370]
composer show
siims/hello_packagist dev-main 4f68428 Hello World Packagist

My GitHub repository uses Webhooks to notify packagist about changes.
Observation.
Composer displays a commit number, not a tag or release number.
My assumption is that the Webhook configuration requires some fine tuning.
Any recommendations?

**Comment by glaubinix** [comment]
Packagist doesn't use the webhook payload to find version. Instead, with every webhook call, Packagist will search the GitHub repository for valid branches and tags and add them as versions.

Looking at your `siims/hello_packagist` package, all tags of the GitHub repository use the `-dev` suffix, which gets skipped by Packagist/Composer as the dev stability is only used by branches. You can learn more about versions and what stabilities are available in the docs [here](https://getcomposer.org/doc/articles/versions.md).

**Comment by siims-biz** [comment]
Thanks, Confirmed.
Reading composer.json of siims/hello_packagist (v0.0.6-dev)
Skipped tag v0.0.6-dev, invalid tag name, tags can not use dev prefixes or suffixes
composer show
-->
siims/hello_packagist 0.0.2           Hello World Packagist
I close the ticket
