### ISSUE TITLE
PR branches are included in package version

### ISSUE THREAD

**Issue by asispts** [composer/packagist#1373]
I have noticed that when I create a new branch to open a pull request, the branch is included in the package version on Packagist's website.

![000](https://user-images.githubusercontent.com/79239132/233506095-4274cef7-b65f-4672-bbe2-0af26a3caa9f.png)

**Comment by asispts** [comment]
The problem is that the branches were removed automatically after the PRs were merged. There might be an issue with the webhook for branch removals.

![000](https://user-images.githubusercontent.com/79239132/233609888-89e840f6-be42-4db7-8d58-55a9e1abb438.png)

**Comment by glaubinix** [comment]
Deleted versions (branches/tags) get removed with a delay of one or more days from packagist.org.

**Comment by asispts** [comment]
> Deleted versions (branches/tags) get removed with a delay of one or more days from packagist.org.

I didn't know about that. We can close this issue. Thank you.
