### ISSUE TITLE
How can I remove old versions of my package ? 

### ISSUE THREAD

**Issue by SeymaAkdoganRepalogic** [composer/packagist#1377]
I can't remove old versions of my package. e.g. I uninstall v1.0 but it comes back when I refresh the page.

**Comment by stof** [comment]
You need to remove the tag from Github if you don't want it to re-appear.

**Comment by SeymaAkdoganRepalogic** [comment]
But before i could only remove from packagist. When the user ran the "composer require packageName" command, the last version was being installed. It doesn't work like that now.

**Comment by stof** [comment]
Well, if you only remove it from Packagist, it will be re-added automatically the next time Packagist updates your package from GitHub. This has always been the case. What might be different now is whether an update is triggered or no for your package.

**Comment by SeymaAkdoganRepalogic** [comment]
I just refresh the page without updating my package. And the deleted versions are coming back.

**Comment by stof** [comment]
Well, package updates can be triggered automatically, not just manually. Maybe packagist now automatically triggers an update after deleting versions (and for sure, if you have the github hook enabled, any push to your repo will trigger an update).

**Comment by SeymaAkdoganRepalogic** [comment]
Got it. Thank you for the information

**Comment by Seldaek** [comment]
There was a permission bug it should work again now
