### ISSUE TITLE
Update failed, invalid composer.json metadata [Composer\Repository\InvalidRepositoryException]

### ISSUE THREAD

**Issue by remarkablemark** [composer/packagist#1389]
I submitted a [package](https://packagist.org/packages/remarkablemark/php-composer-test) and it failed with the error:

<img width="879" alt="Screen Shot 2023-08-05 at 9 14 44 PM" src="https://github.com/composer/packagist/assets/10594555/06275074-b9c8-401d-bfbf-d683e1d6f988">

Here's the copied error:

```
Update of remarkablemark/php-composer-test failed, invalid composer.json metadata [Composer\Repository\InvalidRepositoryException] Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches
```

```
Reading composer.json of remarkablemark/php-composer-test (v1.0.0)
Importing tag v1.0.0 (1.0.0.0)
Reading composer.json of remarkablemark/php-composer-test (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
funding.7.url : invalid value (['link1), must be an http/https URL
funding.8.url : invalid value (link2), must be an http/https URL
```

I believe this is caused by a parsing error from [.github/FUNDING.yml](https://github.com/remarkablemark/.github/blob/master/FUNDING.yml).

I ran `composer validate` and didn't get any errors:

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
# General warnings
- The version field is present, it is recommended to leave it out if the package is published on Packagist.
```

Related to #1097

**Comment by stof** [comment]
Try removing the comments in that file. This will avoid confusing the extractor.

**Comment by remarkablemark** [comment]
Makes sense! Is that a bug with the extractor?

**Comment by stof** [comment]
Yeah. The logic is at https://github.com/composer/composer/blob/95dca79fc2e18c3a4e33f207c1fcaa7d5b559400/src/Composer/Repository/Vcs/GitHubDriver.php#L204

It does not use an actual Yaml parser to avoid introducing that as a dependency of composer.

**Comment by remarkablemark** [comment]
Gotcha, thanks for the context!

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/composer/commit/e02f7ba58b3f6428d146f0d6eec51468d22da9b7
