### ISSUE TITLE
The github hook does not delete versions when a branch is deleted

### ISSUE THREAD

**Issue by stof** [composer/packagist#139]
Github has an [event](http://developer.github.com/v3/events/types/#deleteevent) triggered when deleting a branch, but the github hook does not use it.

**Comment by sagikazarmark** [comment]
:+1:

**Comment by stof** [comment]
This should be fixed thanks to https://github.com/composer/packagist/commit/197d4466dbdb5c85e0beab58c3d749adf37d8c4b
