### ISSUE TITLE
curl: (60) SSL: no alternative certificate subject name matches target host name 'codeload.github.com'

### ISSUE THREAD

**Issue by rimadjamaa** [composer/packagist#1390]
am trying to launch an laravel project when do this comande `composer create-project laravel/laravel example-app` composer faile to upload or clone some packages from this url [codeload.github.com'](url) and when i tried to access the URL i get the insecure error : 
<img width="917" alt="image" src="https://github.com/composer/packagist/assets/88832599/46fe3d63-8f98-43f4-b436-4fd2a448db23">
can someone tell me if the erreur is due to the SSL certification ? and how to fixe this error

**Comment by Seldaek** [comment]
codeload.github.com is just meant to download zip archives, so no browser access.. Maybe if you showed the initial error you got someone might help.
