### ISSUE TITLE
no ext-grpc package found

### ISSUE THREAD

**Issue by venkata-ramana** [composer/packagist#1396]
Hi Folks,

I am trying to install open telemetry and needed to install https://packagist.org/packages/open-telemetry/transport-grpc package.

transport-grpc have dependency on https://packagist.org/providers/ext-grpc but I am not able to find it on packagist.

Could you please help with solution. thanks :)

**Comment by stof** [comment]
`ext-*` packages are PHP extensions. You find them on PECL, not on Packagist (which is a registry for userland packages installable through composer).

The grpc extension is at https://pecl.php.net/package/grpc

**Comment by venkata-ramana** [comment]
thanks :)
