### ISSUE TITLE
How can i update the version of my library correctly and remove the tag ignored warning message ?

### ISSUE THREAD

**Issue by richardsonoge** [composer/packagist#1404]
Hello to the Packagist.org team!

I don't know what's going on but I uploaded my "https://packagist.org/packages/richardsonoge/pdf-translator" package, fixed some bugs and added a new version in my Github code. And when I got to my "https://packagist.org/packages/richardsonoge/pdf-translator" package and clicked on "Update", there was no update of my "https://packagist.org/packages/richardsonoge/pdf-translator" package. No code has been updated see my version will change. I don't know what to do... The old version is "1.0.0" and it should be in this new version "1.0.1" Can you help me in this case? And show me how can i too remove [packagist.org](http://packagist.org/) Tag Ignored Warning Message? Tell me what to do step by step so that I can better understand this problem.
![Capture+_2023-11-23-21-57-31](https://github.com/composer/packagist/assets/37945903/fd60961f-a8fc-44d4-907a-d4888e53eb5e)

**Here the link of my library on Github:** [github.com/richardsonoge/pdf-translator](https://github.com/richardsonoge/pdf-translator)

**Comment by stof** [comment]
have you tried clicking on the "read more" link ?

for a package that is in a VCS repo, you should not specify the `version` in your composer.json. Composer will *always* guess the version based on the git metadata and the explicit version can never help (as it will mark versions as invalid in case of mismatch and provide no benefit when it matches)

**Comment by richardsonoge** [comment]
Ok now the problem was been resolved.
