### ISSUE TITLE
composer won't update latest project tag

### ISSUE THREAD

**Issue by d47081** [composer/packagist#1405]
I can install latest version witch `composer create-project kevachat/webapp`
https://packagist.org/packages/kevachat/webapp#1.0.3

But can't update it on release new tag.

Also I found that `composer.json` installed by `composer install` contain deprecated description than on Github, for example it license is "proprietary" even package have "MIT" license (it was proprietary by symfony installation and I've fixed it later)

![288855324-dbbf1753-3daf-4701-827a-801d2be28666](https://github.com/composer/packagist/assets/108541346/8758e3bc-3343-4148-b12c-2db0944e9c2c)

Maybe it's cache - I don't know how to update the app from latest tag on GitHub - `composer.lock` is available in repo.

The packagist project updated with hooks, manually, - nothing help.

I have tried also to delete project from packagist and add it again - no result. Composer just grab latest tag with different `composer.json` and won't do `composer update` later on GitHub release.

```
Ubuntu 22.04.3 LTS
Composer 2.2.6
```

**Comment by stof** [comment]
`composer create-project` is about creating a new project based on a package used as template. It is not meant to install a project and keep it updated.
