### ISSUE TITLE
[FEATURE] Geographical installation chart

### ISSUE THREAD

**Issue by Geolim4** [composer/packagist#1415]
Hello,

As a package maintainer, I have a package that is getting popular and I was curious about something:
Where is it popular around the world ?

I'd really like to have a data-map visualization such as Highcharts [map series](https://www.highcharts.com/docs/maps/map-series). 

This way developer would like to be able to know where their package are popular around the globe.

In my case I have serious doubts about a very high popularity of my package on India, but nothing helps me to be sure of that today.

Thank you !

**Comment by Seldaek** [comment]
Sorry but I don't think we can do this, it'd require tracking ips and geolocating them for every package. That just sounds like a huge effort and infra costs. Plus with all servers and CI doing installs you would have a fairly biased/incorrect map IMO.
