### ISSUE TITLE
Not receiving email when resetting password

### ISSUE THREAD

**Issue by afraazali** [composer/packagist#1418]
After submitting the password reset page, prompt:
An email has been sent that contains a link that you can click to reset your password. This link will expire in 24 hours.
If you don't receive an email please check your spam folder or try again.

I didn't receive the email. I can log in fine using my GitHub account, but one of my organizations needs me to enable 2FA, and I can’t submit the 2FA code without my password.

**Comment by Seldaek** [comment]
What's your username and email? Please rather email contact@packagist.org so we can deal with this privately.
