### ISSUE TITLE
Can get the user details

### ISSUE THREAD

**Issue by naveen-murali-av** [composer/packagist#1421]
After login when I got in to the redirect URL, I am calling `Socialite::driver('okta')->user()`. But its giving `InvalidStateException` from `Laravel\Socialite\Two\InvalidStateException`.

I am using laravel 9 and `"socialiteproviders/okta": "^4.4"`.

Please let me know if you want any other informations.

**Comment by stof** [comment]
This issue tracker is about the packagist.org website itself. It is not a support forum for all packages referenced in it. You need to ask your question to the package you use.
