### ISSUE TITLE
Dropdown menu no longer works

### ISSUE THREAD

**Issue by mindplay-dk** [composer/packagist#1446]
The dropdown menu on the desktop version of the website no longer works.

![packagist-menu](https://github.com/composer/packagist/assets/103348/6279a574-240c-4ffc-bd43-ef935b174360)

(Latest version of Chrome on Windows.)

**Comment by chr-hertel** [comment]
Hmm, unfortunately I can't reproduce that with Chromium 123.0.6312.86 on Ubuntu.

![packagist-menu](https://github.com/composer/packagist/assets/2852185/0cb76e64-a6fe-4578-8378-f635b3ca97e9)

**Comment by mindplay-dk** [comment]
Yeah, sorry about that - it was a Chrome extension breaking the menu.

**Comment by chr-hertel** [comment]
Good news for this project tho 👍
