### ISSUE TITLE
Allow prefixes when parsing SemVer

### ISSUE THREAD

**Issue by AlexSkrypnyk** [composer/packagist#1451]
Sometimes packages are based on the major version of the upstream project.

In our use case, we want to have a version like `10.x-1.2.3`, where `10.x` is a major version of the upstream project. 

The reason why we cannot simply do `10.2.3` is because it may confuse our project's users: they may think that `2.3` related to the version `10.2.3` of the upstream package, where, in this case, it is only the major version `10` of the upstream package.

I have 2 questions:
1. How do others solve this?
2. Is there any possibility to implement this in Packagist.org with being able to resolve against that version set in prefix?

**Comment by Seldaek** [comment]
Nope we are not going to support these sorry. There is no need to version things like this when you have a package manager as the dependency resolution takes care of this for you.

So you could just release 1.2.3 and maybe it supports/requires drupal 10.x, or maybe it requires drupal 11.x, or maybe it allows both if that's possible. And if not you can tag 2.0.0 for drupal 11.x, and whenever someone requires your package Composer will pick whatever fits per the currently installed drupal version.
