### ISSUE TITLE
not detecting subfolder in github repo

### ISSUE THREAD

**Issue by BeycanDeveloper** [composer/packagist#1454]
Hello, I started to develop the PHP side of our open source project, the JS side is finished. However, when I use the following URL in packageist, it does not detect it.

https://github.com/MultipleChain/php/tree/master/packages/utils

**Comment by chr-hertel** [comment]
You need a composer.json file in the root dir of your repository for registering a package on packagist, see "Publishing Packages" at packagist.org

**Comment by BeycanDeveloper** [comment]
Yes, I understand. Every package have to be different repository.

**Comment by Seldaek** [comment]
Right, this is not something we're likely to change so closing.
