### ISSUE TITLE
Narrow API token permission to common safe actions

### ISSUE THREAD

**Issue by Krinkle** [composer/packagist#1458]
The API token allows access to:
* read-only APIs,
* safe APIs that delegate pre-existing authority (e.g. trigger pull from VCS, idempotent, and might happen on its own),
* sensitive API (`creating-package`)
* other APIs not listed at https://packagist.org/apidoc.

I'm looking at publishing Wikimedia packages ([@wikimedia](https://packagist.org/packages/wikimedia/?query=wikimedia), <https://doc.wikimedia.org/>) from our Gerrit repositories directly to Packagist instead of via GitHub mirrors. I would have more confidence and less reservations about risk in setting this up, if I could run this in an environment where we don't have to worry a lot about the security implications of this token leaking. We don't want to make it public, but exposing it as a secret to a CI pipeline that does get mixed with containers running untrusted code would be much less of a concern if we know the token is of limited power. The fact that `create-package` is gated by the same token, would justify a more elaborate setup, which would cost more, or get delayed/post-poned.

**Comment by Seldaek** [comment]
Ok it's now available at https://packagist.org/profile/ - the safe one should only grant access to update right now. /cc @bshaffer as you had some token woes as well :)

**Comment by Krinkle** [comment]
Thank you @Seldaek, this is great! I've put forward a [proposal](https://phabricator.wikimedia.org/T373933) on our end to adopt this, so that we can publish our software independent of GitHub.com mirroring.

**Comment by Seldaek** [comment]
@Krinkle ok after reading that I think there's one misunderstanding which IMO makes this a bad change in terms of UX: We do not create zip archives, they're just plain git exports from github/gitlab/bitbucket APIs. As such if you plug packagist.org directly into Gerrit you'll have packages installable solely from source, meaning a full git clone. That's way slower than archives.

We have discussed hosting archives ourselves but that would probably mean ~80TB/month of additional bandwidth IIRC, so it's been kicked down the road for a while.. If Gerrit offers zip archives tho (sorry I'm not very familiar with it) there might be a way we can support that at least.

**Comment by Krinkle** [comment]
@Seldaek Thank for reading the downstream task, I appreciate it.

Gerrit provides direct HTTP downloads of tar archives from git-export, similar to how GitHub does. I hadn't yet considered that Packagist needs to know for each code hosting platform how/where to get these archives. That makes sense. I suppose we'll need to add/select a VCS subclass and/or provide a URL template somewhere in composer.json to make this possible?

Example:
* Package: https://packagist.org/packages/wikimedia/cdb
* Source repo browser: https://gerrit.wikimedia.org/g/cdb/ -> https://gerrit.wikimedia.org/g/cdb/+/3.0.0 -> tgz
* Git URL: `https://gerrit.wikimedia.org/r/cdb`
* Export URL: `https://gerrit.wikimedia.org/r/plugins/gitiles/cdb/+archive/3d7622f39319ea2149cac92415222d1fb39c46d0.tar.gz`

Another example:
* Package: https://packagist.org/packages/wikimedia/less.php
* Source repo: https://gerrit.wikimedia.org/g/mediawiki/libs/less.php/ -> https://gerrit.wikimedia.org/g/mediawiki/libs/less.php/+/v5.1.1
* Git URL: `https://gerrit.wikimedia.org/r/mediawiki/libs/less.php/`
* Export URL: `https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/libs/less.php/+archive/29e14517d40b321bdbf8823eae1c327fc6b227f5.tar.gz`

**Comment by Seldaek** [comment]
Yes, if there is some kind of API to retrieve these URLs, it might be doable to add a gerrit driver in the style of https://github.com/composer/composer/blob/main/src/Composer/Repository/Vcs/GitHubDriver.php - the main problem with those is identifying that your domain uses gerrit at all, which is usually not so trivial without doing http requests which I'd rather avoid at the point where we just try to determine which driver to use.

Anyway another option is that we would start generating/hosting archives at least for packages that do not use a dist-compatible driver. As I mentioned above it's kinda on our roadmap but I really cannot say when we get there.

**Comment by stof** [comment]
@Seldaek for composer itself, this might rely on a `gerrit-domains` config setting, as done for Gitlab or GitHub Enterprise Server.
And for packagist.org, maybe submitting a package should provide a setting to define that it is hosted on Gitlab/GHES/Gerrit, so that packagist.org can dynamically provide the appropriate `*-domains` config when handling updates for that package instead of supporting things only for domains configured globally on the packagist.org infrastructure.

**Comment by Krinkle** [comment]
@Seldaek I see. I'd rather not require configuration on consuming side in composer.json for packages, since these are public, not private packages. However, inside each Wikimedia package's composer.json, right next where we set the Git url, setting `type: gerrit` seems easy enough? I am making the assumption that the Composer CLI will have received from Packagist the package metadata before it tries to download the archive.

But... I notice that we don't currently set any Git url in composer.json at all. I'm guessing this is automatically added by Packagist based on when where it discovered/pulled the git tags. That's nice, but that also means there isn't a natural place for publishers to declare the type of the source repo. Except maybe in the UI on packagist.org. There could a be dropdown menu there perhaps of VCS types/drivers, but afaik there isn't something like that today.

I don't see mention of `type: gitlab` or `gitlab-domains` at https://getcomposer.org/doc/04-schema.md for example. Is this declared somewhere else, or am I misunderstanding that self-hosted GitLab is supported today for public packages on Packagist.org? (in a way that works transparently to consumers).

**Comment by Seldaek** [comment]
Yeah the VCS driver is auto-selected by packagist the same way that Composer does it if you declare a `"repositories":[{"type":"vcs","url":"..."}]`. 

GitLab.com is detected, but self hosted ones are not right now. I have done it recently for some Drupal repos though, manually configuring their domain to be marked as a gitlab one.

**Comment by Krinkle** [comment]
I see.  So if I understand correctly:

1. Today, there is not currently a way to, inside the `composer.json` of a library, to indicate where the library's own source control is, or what type that is? This is defined on packagist.org instead, where the vcs type isn't controllable by package owners currently.
2. If a "gerrit" vcs type were added to composer, you're open to setting a Wikimedia's domain within packagist.org's configuration? Similar to drupal for https://github.com/composer/packagist/issues/1464, right? This is a short-term workaround, but until there's another way, that'd be great.

I'm aware that individual consumers can set `repositories`, but that means they'd bypass packagist.org entirely for those packages, right? This would be more boilerplate than typical consumers expect to deal with (i.e. they expect `"require": { "vendor/name": version }` to work if the package is on packagist.org, and for that to perform dist-based installation).

And if I were to set `repositories` inside the composer.json of a library, this a no-op right? This is not taken into consideration by packagist.org currently as a way to partially merge or override the source of the package (e.g. to take "dist" from it). This too seems reasonable since that mechanism is, I believe, mainly a way to install packages _not_ on packagist.org (or to use an alternative version of the package, e.g. a fork). So using it in conjuction with packagist.org could be confusing. Plus, it'd still leave us with a somewhat ambigious outcome where we have to hope that the URL that packagist.org pulls from matches what the library puts into `repositories`. So if they're different in some minor way (e.g. points to a mirror or alternative protocol or alternative path), it'd suddenly be ignored, with no clear way to warn authors about this, since it's not required/expected for `repositories` to match this.

Anyway I'll stop rambling. I imagine you already have an idea of how to crack this nut. Thanks for everything!

**Comment by stof** [comment]
@Krinkle the repository has to know the driver *before* being able to read the composer.json file (as the driver is the one responsible for reading it).
This is why I suggested adding a setting in the packagist package submission form, not in the composer.json.


> And if I were to set `repositories` inside the composer.json of a library, this a no-op right?

It is indeed. However, packagist.org itself relies on the composer repository system to read the data (this is why the packagist source code uses `composer/composer` as a dependency).
Once composer supports reading metadata using a gerrit driver, it will become possible to configure packagist to use it (either by registering the wikimedia domain as being a gerrit domain as done for git.drupalcode.org, or by using my proposal to allow wikimedia to declare that the submitted repository should use the gerrit driver). But packagist cannot support gerrit if composer does not support it.
