### ISSUE TITLE
dist properties for packages from git.drupalcode.org

### ISSUE THREAD

**Issue by drumm** [composer/packagist#1464]
This is part of https://www.drupal.org/project/project_composer/issues/3464712

On Drupal.org, we have “general projects.” When one of these has a `composer.json` file, we send it to Packagist.org for processing. https://packagist.org/packages/drupal/general_example is one of these.

For historical reasons, we had blocked requests to `https://git.drupalcode.org/api/v4/projects/…/repository/archive.zip` We no longer do that blocking.

I'd like Packagist.org to pick this up so https://packagist.org/p2/drupal/general_example.json has data instead of `"dist":null`

I'm guessing either may be the case:
* Packagist.org may not be aware of self-hosted GitLab instances
* git.drupalcode.org was put on a list for not allowing the archive API

**Comment by stof** [comment]
packagist.org is indeed not aware of self-hosted gitlab instances, as supporting them requires configuring the `gitlab-domains` setting in the composer config

**Comment by drumm** [comment]
Is this something which might be supported in the future? Are there tasks to supporting this which would be useful to contribute?

(I personally do not expect to be able to spend time on this. There's some possibility the Drupal.org issue reporters may be able to. So don't need to go into full implementation detail right away.)

**Comment by Seldaek** [comment]
Ok I've enabled it, and force-updated all packages using this GitLab instance. So you should have dists everywhere now. Please check everything works as expected.. One possible improvement would be getting me a readonly auth token I can set up on our end so as to ensure we don't get rate-limited, but given the small amount of packages maybe it's fine as is too.
