### ISSUE TITLE
src of images in README incorrect if URL is private-user-images.githubusercontent.com

### ISSUE THREAD

**Issue by lukasbableck** [composer/packagist#1467]
If a package has an image with the URL private-user-images.githubusercontent.com in the README.md, the URL is changed to user-images.githubusercontent.com for the img src attribute. 
As a result, the image is not displayed as it is not available under this URL. However, the a tag around the image still has the correct, unchanged URL, so you are still able to open the image by clicking on the link.

Packagist:
<img width="1008" alt="Bildschirmfoto 2024-10-02 um 07 33 54" src="https://github.com/user-attachments/assets/7fbffac1-df2b-401b-86bc-6b8abf58b72a">

GitHub:
<img width="617" alt="Bildschirmfoto 2024-10-02 um 07 36 54" src="https://github.com/user-attachments/assets/7f1a8777-b079-490c-9b56-257d7af41698">

I wasn't able to find any information on why that is, but it seems incorrect to me. 
The URL seems to get modified here: https://github.com/composer/packagist/blob/main/src/HtmlSanitizer/ReadmeImageSanitizer.php#L36.

Here are some packages that show this behavior: 
https://packagist.org/packages/lukasbableck/contao-better-elementgroups-bundle
https://packagist.org/packages/lukasbableck/contao-recurring-element-bundle

**Comment by Seldaek** [comment]
Yeah I added this in here https://github.com/composer/packagist/commit/de47fc8224c6d9ad4bffb90865945f77d341e63a#diff-8f50dbbcac4adac76d2b2b4fe2c36cb461ad5d227ca1f4a8834c5738ad397e50R36 but I am not sure why anymore now. Pretty sure there was a good reason but 🤷🏻‍♂️ will have to investigate.

**Comment by Seldaek** [comment]
I see.. so probably not much we can do except re-fetching the README from GitHub on demand/when JWT links expired?

**Comment by glaubinix** [comment]
The JWT token expires after 5min. I don't think that is an option.

**Comment by Seldaek** [comment]
And yes using raw URL would be better indeed, but that'll require some possibly error-prone matching.

**Comment by Seldaek** [comment]
I reached out to GH support just in case they have more of a clue, otherwise I'll try to find options.. I guess another one would be to use the raw file and convert to html ourselves, but that might require us to do the code syntax highlighting manually which I'd rather avoid dealing with. Need to see what's available there in markdown libs.

**Comment by lukasbableck** [comment]
I just noticed the "raw URL" could possibly be derived fron the private-user-images.githubusercontent.com URL returned by the GH API. Maybe this helps.

private-user-images.githubusercontent.com/42083846/370308489-<ins>1bf9b427-0daf-4b69-9b45-a9a8fc09467f</ins>.png?jwt=...

github.com/user-attachments/assets/<ins>1bf9b427-0daf-4b69-9b45-a9a8fc09467f</ins>

**Comment by Seldaek** [comment]
Thanks good catch. Added support for that at least for now.. We'll have to see if it covers everything or not.

**Comment by Seldaek** [comment]
I updated your two packages just as test and it does work there.
