### ISSUE TITLE
list.json cannot take multiple filters

### ISSUE THREAD

**Issue by tacman** [composer/packagist#1487]
listing by vendor or type works as expected:

* https://packagist.org/packages/list.json?vendor=zenstruck
* https://packagist.org/packages/list.json?type=symfony-bundle

But combining the filters doesn't:

* https://packagist.org/packages/list.json?vendor=zenstruck&type=symfony-bundle

I might be able to submit a PR if someone can point me to the file where this happens.

**Comment by stof** [comment]
this is implemented in https://github.com/composer/packagist/blob/aeb9a88cffaf6cedeb6620c5dcdd307e9cb8c982/src/Controller/PackageController.php#L100

**Comment by tacman** [comment]
My thought is to refactor that to use a QueryBuilder.  Or do you have another suggestion?

**Comment by tacman** [comment]
Since this is running on Symfony 7, is there any reason not to take advantage of the cool features later Symfony versions offer, e.g.

```php
    public function listAction(Request $req,
        #[MapQueryParameter] ?string $type=null,
        #[MapQueryParameter] ?string $vendor=null
    ): JsonResponse
```

**Comment by stof** [comment]
@tacman I don't see how this is relevant to this issue about supporting to combine filters instead of applying them separately.

**Comment by tacman** [comment]
What do you think about combining this into a single method getPackageNamesByVendorAndType()?

```php
        if ($req->query->get('type')) {
            $names = $repo->getPackageNamesByType($req->query->get('type'));
        } elseif ($req->query->get('vendor')) {
            $names = $repo->getPackageNamesByVendor($req->query->get('vendor'));
```
