### ISSUE TITLE
property tax payment 

### ISSUE THREAD

**Issue by Arif6666-h** [composer/packagist#1498]
hie I enter all details and it also completed I also received a message saying result of your transaction your payment has been approved please wait while we redirect back to merchant .... and then suddenly payment already deducted and show its showing payment pending and ask me to check with internal server error contact serve administrator with this ID

**Comment by stof** [comment]
There is no payment at all on packagist.org, so this is probably reported in the wrong issue tracker.

**Comment by Arif6666-h** [comment]
but my payment was deducted 
![WhatsApp Image 2024-12-18 at 5 48 06 PM](https://github.com/user-attachments/assets/0c0f607b-740b-4d3a-a92e-5c58ed07cbdf)
![WhatsApp Image 2024-12-18 at 5 48 52 PM](https://github.com/user-attachments/assets/b780c075-12ca-4375-89cd-e1ca0747c205)
please check this

**Comment by stof** [comment]
@Arif6666-h this screenshot has nothing to do with https://packagist.org/. this github repository is hosted the source code powering https://packagist.org/. Its issue tracker is not a generic issue tracker covering every sites on the Internet.

**Comment by Arif6666-h** [comment]
but they only directed me to you as there is some error contact here and payment also deducted

**Comment by Seldaek** [comment]
Sorry but no clue what this is about, please contact the website where you made the payment.
