### ISSUE TITLE
Mark packages as Deprecated /  "this is not maintained anymore"

### ISSUE THREAD

**Issue by simensen** [composer/packagist#192]
Packages stop being maintained. Sometimes new projects spring up and replace aging ones. It would be great to be able to mark a package as deprecated and optionally be able to forward to one or more alternatives.

Real world examples:

[dflydev/twig-github-gist-sculpin-bundle](http://packagist.org/packages/dflydev/twig-github-gist-sculpin-bundle) is a package I intended to keep working on but have since replaced it with a more portable [dflydev/github-gist-twig-bundle](http://packagist.org/packages/dflydev/github-gist-twig-bundle). I realize it is not appropriate to delete the older package, but it would be nice to somehow indicate that it really isn't meant to be used anymore.

> @simensen: is there a way to mark packages at deprecated?
> @Seldaek:  yeah that'd be great, feel free to report on packagist :)
> @Seldaek: a "this is not maintained anymore" flag on packagist would be good at least

**Comment by Krozark** [comment]
+1
