### ISSUE TITLE
Rename packages

### ISSUE THREAD

**Issue by Vrtak-CZ** [composer/packagist#225]
Hi i need rename this packages:

<table>
    <tr>
        <th>From</th>
        <th>To</th>
    </tr>
    <tr>
        <td>http://packagist.org/packages/nella/nette-addon-diagnostics</td>
        <td>nella/diagnostics</td>
    </tr>
    <tr>
        <td>http://packagist.org/packages/nella/nette-addon-forms</td>
        <td>nella/forms</td>
    </tr>
    <tr>
        <td>http://packagist.org/packages/nella/nette-addon-media</td>
        <td>nella/media</td>
    </tr>
    <tr>
        <td>http://packagist.org/packages/nella/nette-addon-diagnostics</td>
        <td>nella/diagnostics</td>
    </tr>
</table>

**Comment by TomasVotruba** [comment]
I didn't find any clear solution, just replacement workaround.
So, how to approach renaming nowadays?
