### ISSUE TITLE
Unable to add SVN repositories over HTTPS

### ISSUE THREAD

**Issue by simonwelsh** [composer/packagist#255]
Trying to add a SVN repository with a HTTPS URL results in "No valid/supported repository was found at the given URL"

Using the standard http URL of the same repository works fine.

**Comment by quinncomendant** [comment]
I'm experiencing this now with Composer version 1.0-dev (f1aa655e6113e0efa979b8b09d7951a762eaa04c) 2015-08-20 11:59:54, and svn version 1.6.11:

    {q@localhost} composer install
    Loading composer repositories with package information
    Installing dependencies (including require-dev) from lock file
      - Installing strangecode/codebase (dev-trunk)
        Checking out /trunk/@537
                                                                                    
      [RuntimeException]                                                                              
      Package could not be downloaded,                                                                
      svn: OPTIONS of 'https://svn.strangecode.com/codebase/trunk': Server certificate verification   
      failed: issuer is not trusted (https://svn.strangecode.com)                                     

I'm using a self-signed certificate on that repo. Is there any way to pass the `--trust-server-cert` to svn via composer?

**Comment by quinncomendant** [comment]
I solved the problem my connecting to the SVN repo once, and when SVN prompted me to accept the cert, I accepted it permanently, then running via composer worked:

    {q@localhost} svn co https://svn.strangecode.com/codebase/trunk codebase
    Error validating server certificate for 'https://svn.strangecode.com:443':
     - The certificate is not issued by a trusted authority. Use the
       fingerprint to validate the certificate manually!
    Certificate information:
     - Hostname: svn.strangecode.com
     - Valid: from Mon, 11 Dec 2006 23:15:25 GMT until Thu, 08 Dec 2016 23:15:25 GMT
     - Issuer: Strangecode Internet Consultancy, Chico, California, US
     - Fingerprint: 10:ab:14:c8:5f:4f:97:48:6e:e6:bb:36:cc:7f:b9:dd:d2:64:42:5b
    (R)eject, accept (t)emporarily or accept (p)ermanently? p
    A    codebase/composer.json
    A    codebase/tests
    …

It would be good if composer could catch this, and display a more useful error message.
