### ISSUE TITLE
Provide support for advanced tracking and statistics of package installations

### ISSUE THREAD

**Issue by tedivm** [composer/packagist#264]
Packagist lists some basic statistics about how many times a package has been installed, but these could be expanded greatly. 

The first way to improve this would be to over more granularity over the range you're looking at. Right now you can see how many times an installation happened today, this month, or all time- but seeing how many had last month and the month before that is vital to tracking growth.

Another way, which is arguable more important, is to list which packages are triggering the installation. In other words, it would be really cool to see what libraries or programs have my libraries as dependancies and how many times my projects are downloaded because of that. This can help someone who is developing a library figure out who is using it and potentially work with them on improving both projects.

**Comment by Seldaek** [comment]
https://twitter.com/seldaek/status/612473905886961664
