### ISSUE TITLE
Change priority of versions so -dev is not preferred if stable versions are available

### ISSUE THREAD

**Issue by simensen** [composer/packagist#276]
The problem:

> This is more of a packagist idea/suggestion than a composer issue. In the last couple of days I had +10 people in #phpunit, by mail and stuff ask me why their phpunit 3.8.x-dev doesn't work properly.
> After pointing out that 3.8.x-dev is a dev version and why the heck they use that their general reponse was "copy pasted the first line from packagist versions"
> So I was wondering if it would make sense to maybe put a "unstable" or something into the website.
> Just a basic idea.. nothing wrong with the way things are displayed and yes: I would have expected folks to not install dev / stuff without releases but well. Aparently nether reading the phpunit docs or packagist pointing out "DEV" is enough. Not sure you can fix people though ;)
> — @edorian

The solution:

> probably we should show the stable releases first yeah
> or just make the "open" version the last stable one instead
> — @Seldaek

**Comment by Seldaek** [comment]
Resolved
