### ISSUE TITLE
Add ability to delete one's own user account

### ISSUE THREAD

**Issue by Seldaek** [composer/packagist#277]

**Comment by chalasr** [comment]
+1

I changed the vendor name of my packages and I need to remove those with the old vendor name, same for the whole corresponding account.

@Seldaek For now, is there a way to delete an account ? Maybe manually ?

Thank's

**Comment by Seldaek** [comment]
@chalasr no, I can delete packages if they look reasonably unused. Let me know which.

**Comment by chalasr** [comment]
@Seldaek I would like to remove the [chalasdev](https://packagist.org/packages/chalasdev/) packages, at least the [csvparserbundle](https://packagist.org/packages/chalasdev/csvparserbundle). 
Most of installs are tests. The packages have been recreated the new [rch](https://packagist.org/packages/rch/) vendor.

Thank you!

**Comment by piotzkhider** [comment]
@Seldaek please delete [piotzkhider2](https://packagist.org/piotzkhider2/)

Thank you!

**Comment by mseshachalam** [comment]
@Seldaek please delete [mseshachalam](https://packagist.org/users/mseshachalam/)

Thank you!

**Comment by Seldaek** [comment]
@mseshachalam all your packages *and* the user account?

**Comment by mseshachalam** [comment]
yes please

**Comment by samueldervis** [comment]
How do i delete my accounts, 
How do i unlink a github account that i had deleted

**Comment by mark-adigital** [comment]
Hi, @Seldaek please delete [a-digital_uk](https://packagist.org/users/a-digital_uk/)

Many thanks!

**Comment by Seldaek** [comment]
@mark-adigital done.

**Anyone else wanting an account deleted**, please reach out to contact@packagist.org to avoid spamming people in this issue.

**Comment by Seldaek** [comment]
This has been added some time ago
