### ISSUE TITLE
Add possibility to rate and review packages

### ISSUE THREAD

**Issue by bonndan** [composer/packagist#298]
Packagist might gain from a rating system which allows users to review packages they have  downloaded. At the moment is quite difficult to tell apart which packages are reliable and well crafted and which are unstable, buggy or poorly designed (unless you download them and inspect them for a while).

A review system might be inspired by the one from amazon, namely allowing users to give 1-5 stars and optionally add a review text. Such ratings should be related to a certain version of the package.

**Comment by eddiejaoude** [comment]
> I am currently thinking about creating a separate site that reviews composer packages

@bonndan did anything get built regarding this, here or else where?

I think there is some value in crowdsourcing feedback.

For example:
* Activity
* Documentation
* Community
etc...

**Comment by bonndan** [comment]
@eddiejaoude see here: https://github.com/Wuzzitor/metagist-server

The project is not actively developed anymore, and I've shut down the server.

**Comment by eddiejaoude** [comment]
@bonndan Thanks for the link. 

Any reason why it is not actively developed anymore & the server has been shut down? Lack of time or lack of interest from the community?

**Comment by bonndan** [comment]
There hasn't been too much interest and I could not afford to invest my free time and money. Closing this issue now. 

@eddiejaoude Good luck if you want to start something in that direction.

**Comment by bonndan** [comment]
There hasn't been too much interest and I could not afford to invest my free time and money. Closing this issue now. 

@eddiejaoude Good luck if you want to start something in that direction.

**Comment by bonndan** [comment]
There hasn't been too much interest and I could not afford to invest my free time and money. Closing this issue now. 

@eddiejaoude Good luck if you want to start something in that direction.

**Comment by eddiejaoude** [comment]
thanks :+1:
