### ISSUE TITLE
Duplicated dependencies

### ISSUE THREAD

**Issue by evert** [composer/packagist#325]
On this page:

https://packagist.org/packages/sabre/dav

The vobject dependency appears 4 times:

* sabre/vobject: >=3.0,<3.1
* sabre/vobject: >=3.0,<3.1
* sabre/vobject: >=3.0,<3.1
* sabre/vobject: >=3.0,<3.1

Link to composer.json:
https://github.com/fruux/sabre-dav/blob/master/composer.json

**Comment by stof** [comment]
@Seldaek this should probably be closed. IT does not seem to appear anymore (it may have been fixed by the fix for https://github.com/composer/packagist/issues/328 too)
