### ISSUE TITLE
Setting up permissions – RuntimeException when adding a package

### ISSUE THREAD

**Issue by ronnylt** [composer/packagist#332]
Hi, 

We are installing packagist in our private organisation. 

When trying to add a new package, we are getting an error like this:

```
Uncaught Exception: [RuntimeException] /.composer/cache/vcs does not exist and could not be created.
```

It should be due the web server user not having permissions to create composer cache.

Do you have any tips on how to setup permissions to make this work. 

Thanks

**Comment by arc92** [comment]
i have use composer on local windows and still this error,any idea?
