### ISSUE TITLE
Allow a package owner to claim ownership / maintainer status

### ISSUE THREAD

**Issue by burzum** [composer/packagist#346]
Right now other people can add repos under their name and set themself as maintainer.

If somebody adds a package but is not the person who owns the repository the owner should be allowed to take it back.

This could be done by a simple check against the repository. If you're a member of that repo or organization you can claim it and Packagist sets this user as maintainer.

**Comment by zborboa-google** [comment]
:+1:

**Comment by stof** [comment]
This seems related to https://github.com/composer/packagist/issues/163

**Comment by zachborboa** [comment]
:+1:

**Comment by respinoza** [comment]
:+1:

**Comment by rmoreas** [comment]
:+1:

**Comment by Seldaek** [comment]
This is fairly easily handled by talking to people and raising the issue up with contact@packagist.org if no agreement can be found between the involved parties. I don't think we need a more official process, and it seems nobody is willing to write the code for it either.

**Comment by dereuromark** [comment]
See https://packagist.org/packages/cakephp/abnlookup for abusing a namespace and no resolvement by talking to people :)
I still think it would be worth pursuing what is mentioned in this ticket.

**Comment by Seldaek** [comment]
@dereuromark it seems kinda unused anyway so I removed it. Now that the user is kicked out of the vendor namespace he can't re-add it so it's all good in the future nobody else can add things. That's why I think we don't need a more elaborate "report" system. Email works :)

**Comment by dereuromark** [comment]
:+1: 
You should probably kick out https://packagist.org/packages/cakephp/monolog too.

**Comment by Seldaek** [comment]
That one is still installed quite a bit and already marked deprecated so 
I think it's fine, the owner got the message..

**Comment by mxr576** [comment]
I might came later for the party... but is still https://github.com/composer/packagist/issues/346#issuecomment-107162142 the only way to change maintainer of a package displayed on Packagist?

**Comment by Seldaek** [comment]
Yes

**Comment by andrewnicols** [comment]
Is this still the only way to get a package assigned to the correct owners? I contacted the e-mail address 9 days ago without response and just want to make sure that I'm following the correct approach.

**Comment by Seldaek** [comment]
@andrewnicols please email again or cc j.boggiano@seld.be directly because I cannot find your email sorry.
