### ISSUE TITLE
Version is updated on packagist.org website, but not in the API

### ISSUE THREAD

**Issue by hkdobrev** [composer/packagist#352]
After creating a new tag in a repo it appears as a new version on packagist.org.

`0.3.4` on https://packagist.org/packages/openbuildings/purchases

However this version is not present on https://packagist.org/packages/openbuildings/purchases.json

This prevents me from updating to this new version.

`composer show openbuildings/purchases` show that `0.3.3` is the latest version and clearing the composer cache is not helping.

**Comment by stof** [comment]
@Seldaek this should probably be closed now that the cron runs more often

**Comment by mmucklo** [comment]
This is occurring right now again:

package: mmucklo/queue-bundle
Versions showing on website: through 2.7.12
Version missing on API: 2.7.12

https://packagist.org/p/mmucklo/queue-bundle.json
https://packagist.org/packages/mmucklo/queue-bundle

**Comment by Seldaek** [comment]
@mmucklo working now? I think it was an issue in the sync to our north american mirror, it needed a bit of a kick :)

**Comment by timbroder** [comment]
I'm seeing this happen on this package

https://packagist.org/packages/kidfund/monkey-patcher
https://packagist.org/packages/kidfund/monkey-patcher.json

The json is only showing the `dev-master` version, not the `0.9.0` or `0.9.1` I published this AM

![image](https://user-images.githubusercontent.com/121503/49592633-a158b000-f93f-11e8-9748-f30d47d0cc9f.png)

![image](https://user-images.githubusercontent.com/121503/49592647-acabdb80-f93f-11e8-8e41-25bbfc2b750e.png)

Is there anything I can try?

**Comment by Seldaek** [comment]
As per https://packagist.org/apidoc#get-package-data 

> The JSON API for packages gives you all the infos we have including downloads, dependents count, github info, etc. However it is generated dynamically so **for performance reason we cache the responses for twelve hours**.
