### ISSUE TITLE
Sorting of search results

### ISSUE THREAD

**Issue by nfx** [composer/packagist#365]
In order to get better package selection, it would be good to sort results based on downloads, number of stars, forks, any other things that promote package maturity.

**Comment by marceloandrader** [comment]
+1 if you need some hands to help also

**Comment by MTon** [comment]
+1

**Comment by Grynn** [comment]
+1

**Comment by forsethc** [comment]
+1

**Comment by Arsey** [comment]
+1

**Comment by Kampfbereit** [comment]
+1

**Comment by jakubpas** [comment]
+1

**Comment by stopsopa** [comment]
+1

**Comment by stopsopa** [comment]
i have my brutal solution for this.
- go to page http://httpd.pl/bookmarklets#toc_11
- drag button "packagistsort" to bookmarks toolbar in browser
- search eg. "curl" in packagist.org
- press just created button in bookmarks "packagistsort"

Please don't use this when phrase is not precise and packagist return 100 pages of results

**Comment by laland** [comment]
+1

**Comment by vimishor** [comment]
I created a [gist](https://gist.github.com/vimishor/e770294b39f4e83a3136) with a (_temporary_) solution for CLI, which I'm using. Maybe someone could find it useful.

**Comment by nickdietel** [comment]
+1

**Comment by Seldaek** [comment]
You can now sort by Stars and Downloads

**Comment by justinkwanlee** [comment]
@Seldaek OMG THIS IS THE GREATEST WOOOOOOO

**Comment by jakubpas** [comment]
Cool ;-)

**Comment by saurini** [comment]
THANK YOU SO MUCH!

**Comment by stopsopa** [comment]
Great :)

**Comment by BlakeGardner** [comment]
So much yes

**Comment by stopsopa** [comment]
great, and thanks to remove my solution ;) indeed it's not useful anymore.

**Comment by zonky2** [comment]
hmm ...??
I can't find anything to sort on the site https://packagist.org/

I would like to sort by 
* last added
* by date of release

**Comment by stonetwig** [comment]
How do you sort by downloads / stars? It's not very obvious

**Comment by alexkuc** [comment]
I think the feature used to be there (sorting) but it is gone now https://github.com/composer/packagist/issues/818 ?
