### ISSUE TITLE
Show package type

### ISSUE THREAD

**Issue by schmunk42** [composer/packagist#382]
It should be at least visible on the detail page of a package which type it is, eg. `library`, `yii2-extension`, ...

Maybe next to the tags in a different color.

**Comment by sebastiansommer** [comment]
Would be awesome to search for an specific type!

**Comment by stof** [comment]
searching for a specific type is actually already supported, except that the search form does not expose it. Add ``&type=symfony-bundle`` at the end of the search result page URL and you will get the filtered results.
See https://packagist.org/search/?q=test&type=symfony-bundle for an example
