### ISSUE TITLE
composer_home environment variable not set

### ISSUE THREAD

**Issue by etcook** [composer/packagist#393]
I tried the installation on another server just to make sure it wasn't an environment issue, and now I'm running into this:

```
Uncaught Exception: [RuntimeException] The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
```

Which is triggered by submitting a package. Any ideas?

**Comment by zqhong** [comment]
I just edit **/etc/profile**，and append **export HOME=~**, then I exec `$ source /etc/profile`.

**Comment by samlikins** [comment]
If the system which Packagist is set-up on, runs the webserver with a user without a home directory, the simplest (and most effective) way to correct the missing environment variable issue is to add it to the server configuration.

# Apache
If the webserver is Apache, you can add the environment variable directly in the vHost/configuration file or (if `AllowOverride` is set to allow it) in the Access file (ex: `.htaccess`).

## vHost / configuration
```apache
<VirtualHost addr:*>
    ...
    SetEnv COMPOSER_HOME "/path/to/use/for/composer/home"
    ...
</VirtualHost>
```

## Access file (ex: `.htaccess`)
```apache
SetEnv COMPOSER_HOME "/path/to/use/for/composer/home"
```

# NGINX
If the webserver is NGINX, you'll need to add it to the server configuration.
```nginx
server {
    ...
    location ~ \.php$ {
        ...
        fastcgi_param COMPOSER_HOME "/path/to/use/for/composer/home";
        include fastcgi_params;
    }
}
```

Make sure to restart the webserver after making modifications to the configurations (not required if changing the Access file).


Best of luck!

**Comment by SmellyFish** [comment]
I ran into this issue while working on some really old Puppet code. The manifest file was installing Composer like this:
```
exec {
  'composer install':
    command => 'curl -sS https://getcomposer.org/installer | php',
    path    => '/usr/bin:/usr/local/bin:/usr/sbin:/sbin',
    creates => '/usr/local/bin/composer.phar',
    cwd     => '/usr/local/bin',
    require => [ Package[ 'curl' ], Class [ 'php::mod_php5' ] ],
  }
```

To fix it, I brought in a composer package from puppetforge (https://forge.puppet.com/willdurand/composer is the one I used) and installed it via:
```
class { '::composer':
  command_name => 'composer',
  target_dir   => '/usr/local/bin',
  require => [ Package[ 'curl' ], Class [ 'php::mod_php5' ] ],
}
```

**Comment by crismablanco** [comment]
@samlikins  and what is "/path/to/use/for/composer/home"  ???
Is it the web folder? example: "/var/www/html/myweb"  ??
Thanks

**Comment by samlikins** [comment]
@crismablanco 

It's been some time since I posted, and can't recall my thought process at the time.  I however have reviewed the issue again, and from what I can tell the ``COMPOSER_HOME`` environment variable should be pointing to the directory which has the composer configuration files in it (ex: ``.composer``).  Make sure you aren't pointing to a file, but that the path is to the directory.
