### ISSUE TITLE
Gitlab Hook

### ISSUE THREAD

**Issue by etcook** [composer/packagist#394]
I would love to see a Gitlab auto-update hook.

**Comment by jelen07** [comment]
@Seldaek OK, but how to send request body `{"repository":{"url":"PACKAGIST_PACKAGE_URL"}}`?
<img width="588" alt="Hook setup" src="https://cloud.githubusercontent.com/assets/2346295/20972998/2790ba56-bc97-11e6-9855-2196a54718e5.png">

**Comment by stof** [comment]
@jelen07 this is part of the payload sent by gitlab to webhooks.

**Comment by marcoocram** [comment]
have you get this works, @jelen07?

**Comment by joshbruce** [comment]
If you scroll down in settings -> integrations on the repo you get a list of integrations. 

Find Packagist, click link, and you get the proper form. 

Add username and API Key from your Packagist account to the form; profile -> show API Token -> copy to clipboard. 

Test and save changes -> look at Packagist to see if the auto-update notice is still there.
