### ISSUE TITLE
Description not updated on packagist.org

### ISSUE THREAD

**Issue by jdeniau** [composer/packagist#407]
Hi, 

I updated the description on [a project](https://github.com/mapado/MysqlDoctrineFunctions) a long time ago now but the description does not update [on packagist.org](https://packagist.org/packages/mapado/mysql-doctrine-functions).

The package adds some new functions, so updating the packagist description would be great !

Thanks

**Comment by AuditeMarlow** [comment]
This should've been obvious to me, but it wasn't. You helped me out here, bud. Thanks for that.
