### ISSUE TITLE
Information on website not in sync with API

### ISSUE THREAD

**Issue by mikehaertl** [composer/packagist#408]
It's quite annoying, that when you push an update for one of your packages, the commit on the packagist website is updated quite fast. But then when you try to install the package with composer it takes a couple of minutes until the new commit is used. I've also tried to flush my composer cache in my home directory to no avail.

So I assume this is an issue with the packagist API which is not in sync with the data on the website.

**Comment by stof** [comment]
@Seldaek isn't it back to a faster schedule now ?

**Comment by Seldaek** [comment]
Oh yes thanks
