### ISSUE TITLE
Please Tag A Working Release

### ISSUE THREAD

**Issue by winmillwill** [composer/packagist#416]
Please tag a release where following the directions is known to yield a web application that renders html.

Following the directions with current HEAD (36e75c356f04adfddb75a51dd880561fcd19c66f) just gives me an application that throws exceptions having to do with inactive scope and twig being unable to find the templates in the Packagist WebBundle. 

----------------------------------------

Symfony\Component\DependencyInjection\Exception\InactiveScopeException: You cannot create a service ("request") of an inactive scope ("request"). in /Users/will/projects/packagist/app/cache/prod/appProdProjectContainer.php on line 869

Twig_Error_Loader: Unable to find template "PackagistWebBundle:Web:index.html.twig" (looked into: /Users/will/projects/packagist/app/Resources/views, /Users/will/projects/packagist/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form). in /Users/will/projects/packagist/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 202

----------------------------------------

I am able to run console commands without issue.

By all means, tag HEAD if this is something I'm doing wrong.

**Comment by stof** [comment]
@Seldaek I suggest closing this, given there is no feedback from the reporter
