### ISSUE TITLE
Searching by package name does not match exact name (without vendor)

### ISSUE THREAD

**Issue by Wirone** [composer/packagist#454]
Few days ago I searched google/github/packagist for Doctrine Migrations provider for Silex and did not found existing package. So I spent few hours and wrote one and after submitting to GitHub and then to Packagist, the latter one showed me that there is similar package. I thought: wtf?

My package: `codito/doctrine-migrations-service-provider`
other package: `rmasters/doctrine-migrations-service-provider`

This is really weird that when you enter `doctrine-migrations-service-provider` in search box, none of those 2 packages appear. Earlier I searched "Doctrine migrations provider" and as I said it did not found that package from rmasters. It does find however when full package name (with vendor) is entered.

I don't know search engine of Packagist, but it doesn't do what it supposed to do. It is easy to find that if someone wrote Doctrine Migrations provider it would be named `doctrine-migrations-service-provider`.. vendor name isn't as easy as that :-)

PS. So I published my package anyway this time, sorry ;-)

**Comment by Seldaek** [comment]
Not sure what was up but all the searches you mention now find the codito package so closing..

**Comment by Wirone** [comment]
I think a lot has changed in Packagist since November 2014 ;-) Yes, searching works ok now.

PS. I didn't worry about Codito package, I just would have used `rmasters`' one instead of writing my own :-)
