### ISSUE TITLE
Using a CDN like CloudFlare in front of Packagist

### ISSUE THREAD

**Issue by lavoiesl** [composer/packagist#467]
Over at Wpackagist, we are considering putting CloudFlare in front of the server and I am wondering what Packagist is using, if you considered it and if you foresee any problem with it.

https://github.com/outlandishideas/wpackagist/issues/50 

Right now, it seems like Packagist is not providing any caching header except Last-Modified, not even on files with shasum in their names, any reason for that as well ?

**Comment by Zoddo** [comment]
@soundasleep : It may be disable on some URLs.

**Comment by stof** [comment]
@Zoddo except that the case where the Packagist performance is the most critical is precisely for the API

**Comment by hirak** [comment]
@stof I think this is the most critical in Asia. Any news about this issue ?

I benchmarked.
[performance of "composer update" download meta.json phase](https://gist.github.com/hirak/ee7eab122a7cbdcf4d9d)

```
packagist.org 103.39s -> cloudflare 17.99s
```

**Comment by alcohol** [comment]
The problem is that a lot of files change too rapidly to benefit from caching.
