### ISSUE TITLE
Support renaming packages

### ISSUE THREAD

**Issue by Seldaek** [composer/packagist#47]
~The procedure for renaming packages should be as such:~
~- Update your composer.json with `"name": "new/name"` and `"replace": {"old/name": "self.version"}`~
~- Press a button on Packagist if you're maintainer, and it will rename if those two preconditions are met.~

# EDIT: Current solution/procedure:

## If you just want to update the github/repo URL

- Do the rename on github or wherever
- Edit the package URL on packagist, no need to change the package name for this

## If you really really want to rename a package

- Update the name in composer.json on the master branch or whatever the default branch is
- Resubmit the package to packagist using the new name
- Mark the old package as "Abandoned" on packagist, and use the new name in the form so that people get pointed to it when they install with the old name
- And no you can't keep your download stats

**Comment by TomBZombie** [comment]
I'm also interested in doing this. I want to rename [user]\[package] to [organisation]\[package]. Could this be as simple as:

1) Transfer the repo on github
2) Create a repo with the old name
3) Add a composer.json to the old repo name that just has `"require": { "newPackageName": "*"}`

Obviously you'd lose the download count and technically have two packages, but presumably this would mean anyone who tried to run `composer install` where the old package was being referenced would not even be aware it's been renamed?

**Comment by Seldaek** [comment]
If all you want is move repos around on github, do it and then edit the repo URLs on packagist and all is well. You don't have to *rename* the packages in composer.json to do this.

If you really want to rename them, then do the above, but then on top of that rename in composer.json, and re-submit the URL on packagist, and mark the old name one as "Abandoned" on packagist, and point to the new one. That's the smoothest transition possible for everyone.

**Comment by TomBZombie** [comment]
Thanks for the speedy response, makes sense :)

**Comment by barryvdh** [comment]
So to be clear, renaming a package can only be done by resubmitting a github repo with a different name, and deprecating the old one? Only downside is losing stats and double listing?

And for moving github repos, you can manually change the location?

**Comment by Seldaek** [comment]
That is all correct yes. Moving repos just edit the package url on
packagist and you're done.

**Comment by nadar** [comment]
In case of resubmitting the package, the GitHub Service for packagist must be removed and readded, otherwise auto-update will not work for the newly submitted package.

**Comment by gsouf** [comment]
No way to delete abandoned package? 
In my case, had a WIP, and before publishing it with a stable I released the name was not good, it creates an useless abandoned package in the vendor name.

**Comment by aik099** [comment]
@gsouf , you can delete abandoned package if it has small download count. Not sure about exact number maybe it's 40 downloads or less.

**Comment by gsouf** [comment]
It looks like having more than 1000  makes it not eligible to deletion!

**Comment by tuupola** [comment]
The OCD in me does not feel good about having double listing and abandoned package under vendor name. Allowing to rename a package and aliasing old name to new name in the same way as GitHub does with repositories would keep vendor namespaces clean.

**Comment by TomasVotruba** [comment]
How to rename package nowadays? Is there some solution apart deleting and uploading a new one?

**Comment by Seldaek** [comment]
@barryvdh's comment is still up to date, quoting it here:

> So to be clear, renaming a package can only be done by resubmitting a github repo with a different name, and deprecating the old one? Only downside is losing stats and double listing?
> And for moving github repos, you can manually change the location?
