### ISSUE TITLE
packagist.org causes "SlowTimer" and fails with Composer\Downloader\TransportException 

### ISSUE THREAD

**Issue by mwjames** [composer/packagist#470]
Restarted the Travis queue but it repeatedly failed with:
```
Loading composer repositories with package information
Installing dependencies (including require-dev)
SlowTimer [5002ms] at curl: https://packagist.org/p/provider-archived$50a273efcf9e5da6d7b253952ac1dbd91cafe52426d630599c943efaddbf40c8.json
SlowTimer [5000ms] at curl: https://packagist.org/p/provider-archived$50a273efcf9e5da6d7b253952ac1dbd91cafe52426d630599c943efaddbf40c8.json
                                                                               
  [Composer\Downloader\TransportException]                                     
  The "https://packagist.org/p/provider-archived$50a273efcf9e5da6d7b253952ac1  
  dbd91cafe52426d630599c943efaddbf40c8.json" file could not be downloaded: Fa  
  iled to open https://packagist.org/p/provider-archived$50a273efcf9e5da6d7b2  
  53952ac1dbd91cafe52426d630599c943efaddbf40c8.json (Operation timed out afte  
  r 5000 milliseconds with 1064716 out of 1169937 bytes received)  
```

https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/49452991

**Comment by mwjames** [comment]
This is annoying now:

```
SlowTimer [5000ms] at curl: https://packagist.org/p/provider-2012$bdbda67a6596c5f05c78c3336e2140f5fa9ba8d803dcab6049919fe16cb9ab9a.json
SlowTimer [5000ms] at curl: https://packagist.org/p/provider-2012$bdbda67a6596c5f05c78c3336e2140f5fa9ba8d803dcab6049919fe16cb9ab9a.json
SlowTimer [5000ms] at curl: https://packagist.org/p/provider-2013$acaa72090d61507d2d3ffbe05caa6d986242312685fbb749ac51b336c693b931.json
SlowTimer [5000ms] at curl: https://packagist.org/p/provider-2013$acaa72090d61507d2d3ffbe05caa6d986242312685fbb749ac51b336c693b931.json
SlowTimer [5001ms] at curl: https://packagist.org/p/provider-2013$acaa72090d61507d2d3ffbe05caa6d986242312685fbb749ac51b336c693b931.json
``` 
https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/49608054

**Comment by JeroenDeDauw** [comment]
+1 to getting this resolved

**Comment by stof** [comment]
Looks like HHVM is considering that the network between Travis and Packagist is too slow

**Comment by mwjames** [comment]
We just hit another one today:

```
SlowTimer [42835ms] at curl: https://packagist.org/p/provider-2013$da4cac940612024a2f5a0e571c3b9a5f94e4f06e0278fac44aa0b9c13582b3b8.json
SlowTimer [30585ms] at curl: https://packagist.org/p/provider-2014$256c4f1c2ac5e2c666751ee1697d2b4e814b672a543af4d5e40b07023ef9eeab.json
SlowTimer [28610ms] at curl: https://packagist.org/p/provider-2014-04$1f71ecf6f13656f88666f4bc7762ebd6d7877d0e9a2d7dad7d75104de4bca3e8.json
SlowTimer [57167ms] at curl: https://packagist.org/p/provider-2014-07$118e542df7aaf9bbf12154b7d33a77edb35a44331452f0ab09c1b1936322db6d.json
SlowTimer [48615ms] at curl: https://packagist.org/p/provider-2014-10$a2fc424eaa161a05f9fd948fead22a7aadbacf26df8d96911c725292e7efd0cc.json
SlowTimer [60000ms] at curl: https://packagist.org/p/provider-2015-01$38ee07322aeac2ed6978fe51d0dc87d5b1eb229eafd4649692ec6fea33197e73.json
SlowTimer [60000ms] at curl: https://packagist.org/p/provider-2015-01$38ee07322aeac2ed6978fe51d0dc87d5b1eb229eafd4649692ec6fea33197e73.json
SlowTimer [59999ms] at curl: https://packagist.org/p/provider-2015-01$38ee07322aeac2ed6978fe51d0dc87d5b1eb229eafd4649692ec6fea33197e73.json
```

https://s3.amazonaws.com/archive.travis-ci.org/jobs/55648968/log.txt

**Comment by JanTvrdik** [comment]
Me too https://travis-ci.org/nextras/migrations/jobs/55665621

**Comment by schmunk42** [comment]
I have this issue during docker builds.

**Comment by mwjames** [comment]
Closing the issue doesn't make it go away, just see Travis fight against SlowTimer on HHVM and being absolute stale (+5 min) on any PHP version:

```
SlowTimer [30351ms] at curl: https://packagist.org/p/provider-2014-07$9b2d66a77e2f17ca1c18602419a2b53b00d42e0010d0a64fbbdcc1a01bbe092b.json
SlowTimer [30191ms] at curl: http://packagist.org/p/onoi/message-reporter$6b69eeb8c39d1271958a45bec1658ecd99498e1b3793686cd897ee2d547e81b4.json
SlowTimer [30198ms] at curl: http://packagist.org/p/doctrine/cache$d569be3f78cd7976d45f2b92cbeb692de9ab29b12d24094519f1804f4e30540a.json
SlowTimer [60011ms] at curl: http://packagist.org/p/sebastian/comparator$ae9517b709925b1757162ae83ad02ef0d5349fafae5b7e86dcd00ddb56974de8.json
```

**Comment by JeroenDeDauw** [comment]
Is this perhaps supposedly fixed in a version not yet used by Travis? Reason for closing would indeed be nice

**Comment by Seldaek** [comment]
@mwjames do you always experience this? The reason I closed it was that we used to have bandwidth issues, and yesterday evening there were some instabilities as well so maybe that's why you got the errors. But in general now it should be faster so not causing any such problems.

**Comment by mwjames** [comment]
> @mwjames do you always experience this?

It just reappeared with [0].

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/66673568

**Comment by andrerom** [comment]
Have been experiencing it consistently since around Friday, on normal php builds.

Either on composer install
```
Loading composer repositories with package information
Installing dependencies (including require-dev)

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

Also sometimes failing on composer self-update during the last few days, either with same output as above, or with Exception.

**Comment by mwjames** [comment]
@Seldaek This issue beomes real no real pain point now (I waited 4 days for the issue to disappear just to encounter it again [0]). This makes CI runs that rely on getting the correct dependencies via Composer unreliable.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/67260288

**Comment by schmunk42** [comment]
Same here with my travis-ci builds: https://travis-ci.org/phundament/app/jobs/67135036

But not happening every time, usually I need to restart the build and then it works...

**Comment by Seldaek** [comment]
Might be related to https://github.com/composer/composer/issues/4142#issuecomment-113174436 - is there a way to disable ipv6 on travis to confirm?

**Comment by mwjames** [comment]
@Seldaek I ask the Travis support whether this issue is caused on their side or not, I have copied the response from Sven Fuchs (support@travis-ci.com) / Thu, Jun 18, 2015 at 6:53 PM.

>Thanks for getting in touch, and sorry to hear about the trouble.

>We have seen a few similar incidents where composer would suddenly take forever before it actually starts to install packages. We have, so far, failed to actually get to the bottom of the issue, but in many cases things have suddenly resolved, even though it does not seem that the download from packagist.org is the actual problem. (E.g. we've been pointed to https://github.com/composer/composer/commit/ac676f47f7bbc619678a29deae097b6b0710b799 by some PHP experts in our circles).

>Instead, from what we have seen, it rather seems as if the dependency resolution itself takes forever, for unknown reasons. We have been hinted that GC settings might be off for some PHP versions, but we haven't been able to track this down further.
>That said, our own knowledge about both PHP internals, such as GC, and Composer is quite limited, so it's not very easy for us to track this down.

>I see your build is running on our "standard" (i.e. full VM based) infrastructure, so it is possible to boot up a debug VM for this. Do you think it would help you to ssh into a VM and debug this interactively? E.g. we have, so far, failed to figure out the exact HTTP request that Composer makes to packagist.org, so we could actually pin-point whether it's this request, or rather the dependency resolution happening afterwards.

**Comment by Seldaek** [comment]
Alright.. well yes I guess having access to one of their VM might help 
to try and debug things. At least running composer with -vvv might 
provide more hints as to what goes wrong.

Another thing that I find surprising is that the SlowTimer notice 
mentions curl, which composer does not use internally.. where is that 
coming from?

**Comment by mwjames** [comment]
> SlowTimer notice mentions curl, which composer does not use internally.

SlowTimer is a message that comes from HHVM (https://github.com/facebook/hhvm/blob/4498e2b25bc17ace502b4c86c551dbab25f284bf/hphp/runtime/base/http-client.cpp#L121).

**Comment by Seldaek** [comment]
Oh ok I didn't realize sorry, interesting that they implement the http stream with curl internally.. Anyway how do we get access to this debug VM then?

**Comment by mwjames** [comment]
> Anyway how do we get access to this debug VM then?

@Seldaek Travis support just sent me the details for access, please let me know where I can forward the email (since the settings are private for a debug VM).

**Comment by Seldaek** [comment]
j.boggiano@seld.be thanks

**Comment by Seldaek** [comment]
@mwjames I ran a composer update without cache in a while loop for a bit and didn't find anything conclusive.. it ran fairly smoothly, sometimes locks up on a given request for a couple seconds but then it keeps moving along. I ran mtr as well for quite some time and it seems there is no packet loss. Worst latency is around 80ms, nothing extreme. Not sure what else to do :/

**Comment by mwjames** [comment]
> Not sure what else to do :/

Thanks for effort.

**Comment by Seldaek** [comment]
How often do you get these lately?

**Comment by mwjames** [comment]
> How often do you get these lately?

Today I haven't seen it once (and I did a couple of Travis runs) but the day before that at least once per job  run.

**Comment by mwjames** [comment]
I should have kept my mouth because it just [0] reappeared.

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/67606044

**Comment by Seldaek** [comment]
Yeah I am trying to figure out what's wrong with the packagist dependencies.. causing high i/o which might create some failures, sorry about that.

**Comment by forddyce** [comment]
How come each packagist needs to download so many json files?
![screenshot from 2015-08-24 18 22 04](https://cloud.githubusercontent.com/assets/6212875/9438996/1d853be0-4a8d-11e5-96f8-e4c5250e1b04.png)

**Comment by alcohol** [comment]
Because it needs to retrieve all available information of the packages you have in your composer.json when you run `update`. This is not the case when you run `install`.

**Comment by tgr** [comment]
We see this a lot on Wikimedia CI (not the SlowTimer part, I think, but we have recently switched to Zend so I can't verify). Ideally when `packages.json` changes the old files should be left alive for a while to avoid race conditions like these.

(Dowstream task is [T182266](https://phabricator.wikimedia.org/T182266).)

**Comment by alcohol** [comment]
@Seldaek do you immediately purge old provider files? Or do we keep them around for several minutes/hours/days?

**Comment by Seldaek** [comment]
We clean up files older than 10minutes once an hour. If your install takes a long long time though it's possible you hit a file that's gone already.

**Comment by Krinkle** [comment]
@Seldaek This still happens on a regular basis. Is there a way in which we can prevent this issue in a more general way, that hopefully also avoids too much load or storage pressure on your side?

See https://phabricator.wikimedia.org/P7484$1052 for a recent transcript of a build in which this error occurred.

For that build, it seems like the failure was printed only 3 minutes after the `composer require` command.
