### ISSUE TITLE
Split Components into Seperate Repositories

### ISSUE THREAD

**Issue by davidbarratt** [composer/packagist#483]
I'd like to propose to the [Drupal.org](https://www.drupal.org/) team to integrate packagist-like features into the [massive](https://www.drupal.org/project/project_module) contrib hosting/directory. Since all the projects are hosted on [drupal.org](https://www.drupal.org/), and Drupal has it's own [Composer](https://github.com/drupal/drupal/blob/8.0.x/composer.json) file that is ready  to ingest third-party libraries, modules, themes, etc. A user should be able to specify a composer repository on [drupal.org](https://www.drupal.org/) (which we'd probably write into the default [composer.json](https://github.com/drupal/drupal/blob/8.0.x/composer.json) file) and then be able to install modules, themes, etc. with Composer. :)

This is similar to the work that is happening here:
https://github.com/drupal-composer/drupal-packagist

However, for this to work on [drupal.org](https://www.drupal.org/), the team would need the components used on Packagist (parsing repositories, creating packages.json files, etc.) to be split from the site. This could be done with Read-Only subtree splits much in the same way Symfony splits their components from their framework:
https://github.com/symfony

Would this be possible to do? I think it would be huge for the Drupal community and the Composer project.

**Comment by stof** [comment]
Parsing repositories is actually done in Composer itself.

**Comment by ryanaslett** [comment]
I think you can close this issue. The Drupal.org team implemented packages.drupal.org and solved the requesters needs.
