### ISSUE TITLE
Allow deleting packages gracefully

### ISSUE THREAD

**Issue by Addvilz** [composer/packagist#484]
There seems to be plenty of issues about this already, but what if we would allow to delete packages gracefully?

Example workflow:
1. Owner decided to delete a package for whatever reasons;
2. Owner goes to the packagist and deletes package;
3. Cool-down period is started, for example, 1 month;
3.1 During this period, when doing composer update or install against the package, a notice, similar to one about package abandoned is displayed;
4. After cool-down period, package is removed from index completely.

For example, I have a package I used to develop under and did install myself plenty of times as a dependency, for testing. However, because the installs is now above threshold, I can not remove it. Probably not that big of an issue for me, as I will reuse the name, but it sure might be for someone else.

For example, NPM allows to un-publish a whole thing even without grace, and gives 404 for potential users. This is probably not something we want, but a cool-down period would be something of a middle ground between allowing owners, well, ownership over their own packages and users certain assurances the package will not just disappear.

**Comment by stof** [comment]
Given that Packagist only stores the metadata and not the code, the grace period would not work unless the owner waits 1 month before deleting the github repo

**Comment by Addvilz** [comment]
@stof that is true, however, advance warning is advance warning. This feature would be useful either way.
