### ISSUE TITLE
Edit tags/labels

### ISSUE THREAD

**Issue by ThaDafinser** [composer/packagist#485]
When submitting a new package, its possible to define tags/labels for the package.

But where is it possible to edit them?

**Comment by GRMule** [comment]
Seconded. I realized that I neglected a few fairly obvious tags. The edit screen only provides a mechanism to change the repository URL. There is no way to edit the description or tags.

**Comment by Seldaek** [comment]
You can simply update the `keywords` and `description` keys inside your composer.json in master branch and packagist should follow suit :)
