### ISSUE TITLE
Problem with this package is not auto-updated

### ISSUE THREAD

**Issue by petehouston** [composer/packagist#488]
I've tried with my repo: https://github.com/petehouston/bladie 
The webhooks & services is already Active and Test Service okay.

However, in Packagist, it doesn't seem to update.

Any idea?

**Comment by mpoiriert** [comment]
Same problem with my package:

https://packagist.org/packages/draw/swagger

**Comment by ksdev-pl** [comment]
Try to add `https://packagist.org` as a domain in packagist service configuration. GitHub default is `http://packagist.org` (http instead of https) - and this created problems for me.

**Comment by jonnywilliamson** [comment]
@ksdev-pl THANK YOU. That was exactly the issue, as soon as https was used everything worked perfectly.

**Comment by Seldaek** [comment]
I sent a PR to github to make the hook use https always https://github.com/github/github-services/pull/1049 - and in the meantime I fixed packagist to support http hooks again

**Comment by petehouston** [comment]
yay, it's working now.

**Comment by mpoiriert** [comment]
It's not working for me maybe it's related to something else ?

When I do a force update it does work but not the web hook...

**Comment by Seldaek** [comment]
@mpoiriert it likely is a misconfiguration of your github hook, please check that you have your PACKAGIST username and api token in there, not the github one, and that your username is a maintainer of the given package on packagist.

**Comment by mpoiriert** [comment]
Yeah sorry, I put my email instead of my username... everything seem ok now. Sorry

**Comment by Seldaek** [comment]
No worries. Maybe we need to accept both, I don't think you're the first to make that mistake.

**Comment by mpoiriert** [comment]
keep it simple and don't accept both less code to maintain ;)

**Comment by Seldaek** [comment]
Yup, I did send https://github.com/github/github-services/pull/1054 a while back but it's still not merged.

**Comment by kanekesofficial** [comment]
yeay all its works. thanks

**Comment by ahmedali5530** [comment]
@Seldaek [https://github.com/composer/packagist/issues/488#issuecomment-108509029](url) this worked for me

**Comment by ahmedali5530** [comment]
@Seldaek thanks this [https://github.com/composer/packagist/issues/488#issuecomment-108509029](https://github.com/composer/packagist/issues/488#issuecomment-108509029) worked for me
