### ISSUE TITLE
Private Packagist

### ISSUE THREAD

**Issue by davidbarratt** [composer/packagist#489]
My apologize if this is a duplicate.

It would be amazing if Packagist supported private packages like npm:
https://www.npmjs.com/private-modules

I think people would even be fine paying a fee for private packages (like GitHub) and that money could help support Packagist and Composer development.

**Comment by Seldaek** [comment]
There is already https://toranproxy.com/ which serves this purpose for self-hosted/enterprise customers. Hosted solution is on the roadmap :)

**Comment by andreaspenz** [comment]
Is there still a plan to create a hosted-solution for that?

**Comment by prisis** [comment]
is it this one http://packagist.com/ ?

**Comment by Seldaek** [comment]
Yup, we just launched that last night, it's fully hosted and still in beta but we're very happy to get feedback so try it out if you get a chance and let us know if you hit any blockers or missing features :)

**Comment by ElectricMaxxx** [comment]
@Seldaek @naderman got some nice stickers yesterday but got no url where to find the beta, can you give some hint?

**Comment by stof** [comment]
@ElectricMaxxx the link is just above in @prisis's comment

**Comment by ElectricMaxxx** [comment]
Thank, Sorry it was late yesterday ...
