### ISSUE TITLE
Wrong release dates 

### ISSUE THREAD

**Issue by reiz** [composer/packagist#490]
The release dates for [ronanguilloux/isocodes](https://packagist.org/packages/ronanguilloux/isocodes) are wrong on Packagist. It shows for alle versions `2012-10-10`, but that is wrong. Here are the correct release dates: https://github.com/ronanguilloux/IsoCodes/tags. One of the VersionEye users found this issue and opened originally a ticket here: https://bitbucket.org/versioneye/versioneye/issue/55/datum-der-versionen-stimmen-nicht.

**Comment by Seldaek** [comment]
The issue is https://github.com/ronanguilloux/IsoCodes/blob/master/composer.json#L7 - composer is just doing what it's told..
