### ISSUE TITLE
Allow users to disconnect themselves from their GitHub account

### ISSUE THREAD

**Issue by kherge** [composer/packagist#494]
I need to be able to dissociate my Packagist account from my GitHub account so I can link it to another GitHub account. @Seldaek was nice enough to do this manually for me once before, but I think that it would be better if Packagist supported users doing this for themselves.

**Comment by theq86** [comment]
3.5 years later ... still not possible to delete my own github connection.
I accidentally deleted the OAuth Token from github. But I cannot re-establish or delete my github connection ...

**Comment by ThibaudDauce** [comment]
@Seldaek Any update on this problem? I revoked Packagist's permission on Github (misunderstood the problem with https://twitter.com/packagist/status/1037035587453235201) and my Github account is still marked as linked in my Packagist profile.

**Comment by Seldaek** [comment]
If you login again it should log you in your account based on the GitHub
I'd?

**Comment by ThibaudDauce** [comment]
Ok. I needed to connect with Github and not with my email / password. I don't really understand how the link works (between email / password login, and Github auth) but it works. Thanks!

**Comment by stof** [comment]
@ThibaudDauce the new system requires more scopes for the github token (to get access to the management of webhooks). If you login by email/password, it won't grant additional scopes from Github (while logging in again with Github will ask github for the new list of scopes).

**Comment by Seldaek** [comment]
This is possible at https://packagist.org/profile/edit "Disconnect your GitHub account"
