### ISSUE TITLE
Integrity Constraint Violation

### ISSUE THREAD

**Issue by GaryJones** [composer/packagist#495]
I [updated](https://github.com/TGMPA/TGM-Plugin-Activation/commit/f535d456ce05cc16ed9be446107a9027a242e9c7) the composer.json file in the GitHub develop branch for the [tgm/plugin-activation](https://packagist.org/packages/tgm/plugin-activation) package, and did a Force Refresh. All fine.

I then found that the best way to rename a package was to submit a new package and Abandon the old package with a recommendation of the new one. I registered [tgmpa/tgm-plugin-activation](https://packagist.org/packages/tgmpa/tgm-plugin-activation) and upon Force Refreshing that, got the following error:

![screenshot 2015-05-06 19 13 05](https://cloud.githubusercontent.com/assets/88371/7502903/466f75cc-f437-11e4-8bb2-58bd819b0c83.png)

Everything seems to have worked though in terms of registering the new package - the notice for not having auto-updates has successfully disappeared, and all the branches look to be present, despite the violation. I can `composer create-project tgmpa/tgm-plugin-activation --no-dev` just fine too.

**Comment by Seldaek** [comment]
This btw is due to the fact that you have both a 2.4.0 and v2.4.0 tags. Since they resolve to the same composer normalized version it conflicts in the DB. Just saying so you can fix it on your end, but we definitely should display this nicer ;)

**Comment by GaryJones** [comment]
Thanks for the explanation. Nothing to do with my change of package name procedure at all then. I've removed the `v2.4.0` tag since we're a few releases further on anyway.

**Comment by Seldaek** [comment]
Just for the record, catching the exception and reporting a more human-readable error would be nice.

**Comment by mhujer** [comment]
This was fixed in https://github.com/composer/packagist/commit/f30c10eb50a0942cd4cc4e7c7633e1e9ca1e67e9

I've created a testing repo and tried id locally and when running update from CLI, it skips the duplicate versions propery:

```bash
λ php app\console packagist:update mhujer/test-repo-with-messed-up-versions -v
Importing https://github.com/mhujer/test-repo-with-messed-up-versions
Skipping version 1.0.0.0 (duplicate of v1.0.0)
Skipping version 1.0.0 (duplicate of v1.0.0)
```
