### ISSUE TITLE
Composer issue with moved branches

### ISSUE THREAD

**Issue by dereuromark** [composer/packagist#497]
I now get
```
  Problem 1
    - Installation request for dereuromark/cakephp-tools dev-cake3 -> satisfiabl
e by dereuromark/cakephp-tools[dev-cake3].
    - dereuromark/cakephp-tools dev-cake3 requires dereuromark/cakephp-shim dev-
master -> no matching package found.
```
But the branches and the constraints all look good.

All I did was moving the new major version branch to the "master" branch and making an old version branch for the former master branch a while back. But that shouldnt matter.

All the packagist dependencies seem fine, I also deleted and force refreshed them.

Issue can also be seen in travis, so caching or local issues cannot be it: https://travis-ci.org/dereuromark/cakephp-ajax/jobs/59999027

It works with other plugins/packages, so that's why I initially thought some typo might be it, but I cannot find any.

**Comment by dereuromark** [comment]
One solution seems to be `minimum-stability: dev`, but thats "usually a really bad idea, because it applies to all constraints and as a result you will get unstable versions of all packages".
In this case it should just get the dev branch as stated in `require-dev` and its `require` dependencies.

**Comment by Seldaek** [comment]
If you require dev stuff people using your package will need to also allow those dev things themselves, that's just the way it is, so everyone remians in control of their own package stability policy.

**Comment by Seldaek** [comment]
So yes in other words you need minimum-stability dev, or to require `dereuromark/cakephp-shim: dev-master` in the package requiring `dereuromark/cakephp-tools`

**Comment by dereuromark** [comment]
I understand that this works, but why is this necessary? If I deploy without dev, then I have a dependency in there I wouldnt need as it only is needed for the dev package here (for local dev).
Additionally, the app shouldnt need to know about the require dependencies of that lib package.

If I require-dev "package-a" and this has 2 require dependencies, then I would expect to only include those for dev. All require-dev dependencies are ignored, of course, either way.

**Comment by Seldaek** [comment]
the stability notion of `dev` has nothin to do with require-dev vs require. That might be what has you confused here.

Above I meant requiring dev packages in the sense that you require packages which have a stability of dev, like dev-master, or dev-cake3. It doesn't matter if you put them in require or require-dev. 

The install or install --no-dev for prod just means require-dev (and their dependencies) will be skipped, but this again has no relation with dev stabilities, it includes all require-dev packages and all their dependencies.
