### ISSUE TITLE
Can search API include dependencies?

### ISSUE THREAD

**Issue by anvaka** [composer/packagist#498]
Hello,

I want to construct dependencies graph of the packagist.

Looking at the source code it seems like I will need to first index all available packages via search API, and then make one request for each found package to get its dependencies.

What do you think about adding `fields` query string argument, which would let consumers specify required search response fields?

**Comment by Seldaek** [comment]
You can hit https://packagist.org/packages/list.json to get all the names, and then fetching `https://packagist.org/p/foo/bar.json` is the most efficient as this is just a static json file. Make sure you fetch them with gzip enabled to minimize the bandwidth and it shouldn't take too long :)

**Comment by anvaka** [comment]
Thanks so much @Seldaek . This is perfect.
