### ISSUE TITLE
Pushing a tag doesn't update in Packagist

### ISSUE THREAD

**Issue by jaitaiwan** [composer/packagist#500]
**Environment:**
 - Bitbucket
 - Bitbucket Packagist POST Hook

**Replication steps:**
 1. Create a new commit.
 2. Push commit to repo.
 3. Realise one forgot to tag the release.
 4. Tag release and push it to the repo.

**Symptoms:**
 - Package does not auto-update to latest release likely due to [#200 (Specific Comment)](https://github.com/composer/packagist/issues/200#issuecomment-103464979)
 - Force update does not result in latest release appearing

**Comment by stof** [comment]
@jaitaiwan can you link to the package being affected ?

**Comment by jaitaiwan** [comment]
No worries: centricwebestate/provender is the main one. It seems to happen
sporadically, sometimes the force update works, other times it's totally
useless.

**Comment by stof** [comment]
AFAICT, all tags appear on Packagist for this repo

**Comment by jaitaiwan** [comment]
Yes that's because I've since done a push of changes AND tags in the one go
for a new release.

**Comment by stof** [comment]
Does it also affect force updates, or only the update from the hook ?

If it only affects the hook, the question is whether Bitbucket triggers the hook when pushing only a tag.

**Comment by jaitaiwan** [comment]
Yes it effects force updates. 

Did you read the full post? I mentioned that under the "Symptoms" heading. I also referenced a comment in which I confirm that bitbucket fails to push adequate data on non-commit pushes...

**Comment by Seldaek** [comment]
I don't think it's due to that bitbucket issue, as the only information we need from the hook data is the repository URL. If it affects force updates, then it might just be a delay in the bitbucket API propagating new tags, or network failure of some sort.

**Comment by jaitaiwan** [comment]
I can't say for certain, but my hooks into SemaphoreCI seem nearly instant.
There is the random occasion where the hook isn't run, but when it is, its
nearly instant.
