### ISSUE TITLE
Add maintainers of namespaces

### ISSUE THREAD

**Issue by Swader** [composer/packagist#503]
In organizations with many repos, it's tedious to add maintainers one by one into one by one project. It'd be awesome if we could add a maintainer to a whole namespace, making them the maintainer of all projects under it. 

It would be even better if there was a way to have Packagist grab the maintainers of projects from Github and automatically apply them to newly added projects (maybe a checkbox on project addition: "Try to add maintainers from Github?")

**Comment by alcohol** [comment]
How would it add maintainers from GitHub? What qualifies as a maintainer?

**Comment by Swader** [comment]
Read from `composer.json` maybe

**Comment by alcohol** [comment]
It already reads `authors` from `composer.json`. Is that not sufficient?

**Comment by Swader** [comment]
It reads it, but those entries are in no way linked to Github, or are they? So Packagist can't turn them into maintainers automatically.

**Comment by alcohol** [comment]
I'm not sure if it would be wise to do that even. An author might not have a packagist account or the author definition might not match any credentials of their packagist account. So imho there is no safe way to automatically add maintainers. Doing so manually is the best course of action.

**Comment by Swader** [comment]
Agreed
