### ISSUE TITLE
packagist.org front-end issue

### ISSUE THREAD

**Issue by krzysztofp** [composer/packagist#509]
Chrome Version 43.0.2357.124 (64-bit)
OS X Yosemite version 10.10.2
MacBook Pro (13-inch, Mid 2009)

When you go to the main packagist site:
https://packagist.org/

You see this broken front-end:

![image](https://cloud.githubusercontent.com/assets/1634660/8141132/fed48bfa-1162-11e5-84a1-32170fa678e0.png)

**Comment by stof** [comment]
I can see exactly the same kind of output... when I start scrolling the page.

**Comment by krzysztofp** [comment]
Maybe this problem is related to the browser and/or OS and/or screen resolution, on my screen this is on page load, before the scrolling.

**Comment by Seldaek** [comment]
Do you still experience this? I wonder if it might have to do with the autofocus of the search bar (which I now removed).

**Comment by driesvints** [comment]
I can confirm that this is still happening. I'm on Chrome Version 43.0.2357.81 (64-bit)

Ps. Great update @Seldaek! Packagist is looking mighty fine :smile:

**Comment by Seldaek** [comment]
@driesvints with chrome 44 beta on windows it's not happening, and with 43.0.2357.124 on OSX it's not happening. I don't know what to say :)

**Comment by driesvints** [comment]
I'm now on `Version 43.0.2357.124 (64-bit)` on OSX Yosemite 10.10.3 and I'm experiencing the bug. @Seldaek have you tried clearing all the browser caches etc?

**Comment by SoboLAN** [comment]
I too confirm this is still happening on Firefox 37.0.2 + Windows 7. Clearing the cache doesn't solve it and no error/warning is written to the console.

Works fine on Chrome 43 though.

**Comment by Seldaek** [comment]
I did a few tweaks that might help although I doubt it.. I still can't reproduce this without scrolling down, are you 100% sure you're scrolled to the top of the page when you see this? Firefox 38 on win8 I can't reproduce. I don't have a mac at hand to test that right now.

**Comment by SoboLAN** [comment]
@Seldaek Absolutely sure.

If I add the `margin-top: 50px;` property to the `.wrapper-search` CSS class, it kind of works. Did it with Firebug.

**Comment by Seldaek** [comment]
Damn this is really strange. If I add that I get a huge gap obviously..

**Comment by fabiancz** [comment]
You have to add padding-top for body. See reed note in Bootstrap documentation: http://getbootstrap.com/components/#navbar-fixed-top

**Comment by Seldaek** [comment]
So that does the same problem (huge gap for me), but I dug a bit more and found something else..

This is what makes it work for me:

`body > section:first-child {   padding-top: 58px; }`

Can any of you with the bug check if the first `<section class="wrap">` has that style applied to it and if not why not? Is there something injected in the body before the section that makes it not the first child anymore for you?

**Comment by Seldaek** [comment]
I guess if I deploy the fix I have it'll work but I'd like someone to check so I can possibly understand what the hell is happening before I deploy the fix :)

**Comment by Seldaek** [comment]
Ah well @fabiancz's screenshot https://www.dropbox.com/s/x3lk0qtrzlej99x/Screenshot%202015-06-19%2018.09.49.png?dl=0 actually shows exactly what I was asking about.. there is a StayFocusd-infobar div that's been injected in there. Interesting. Do all the others experiencing the issue also have some weird extension injecting things?

**Comment by fabiancz** [comment]
Hmm you'r right. In anonymous Chrome window everything is ok.

**Comment by Seldaek** [comment]
Yeah if it was a widespread issue I believe more people would have complained, because it looks really borked. Anyway the fix is deployed now.

**Comment by SoboLAN** [comment]
I confirm that it's working now :) .

You can probably put back the autofocus of the search bar :D .

**Comment by Seldaek** [comment]
So thank you StayFocusd for wasting all of our time by keeping everyone from wasting time on silly websites. That was a fun one..

@SoboLAN I removed it for mobile users because it popped up the keyboard, but you can focus it by pressing `s` or tab.

**Comment by fabiancz** [comment]
I think it's not StayFocusd problem. I developed many sites with Bootstrap and everything was ok, because I added padding-top as they write in doc.

**Comment by Seldaek** [comment]
It's not about bootstrap or not bootstrap IMO, it's just bad luck that we targetted something with first-child, if we had done that with something non-bootstrap related it would still have messed it up. Extensions modifying the markup don't sound like a very good idea unless they target specific sites. Anyway no big deal..

**Comment by driesvints** [comment]
It's fixed for me now. I also have StayFocused installed btw. That's indeed a stupid problem :-/

**Comment by ThaDafinser** [comment]
@Seldaek i miss the focus really badly...can we add it back?

**Comment by Seldaek** [comment]
@ThaDafinser we could add it back for desktop only, or you can learn to hit `s` or `tab` when you need to search :)
