### ISSUE TITLE
The profile page has a broken display when the API token is hidden

### ISSUE THREAD

**Issue by stof** [composer/packagist#511]
![packagist_api_token](https://cloud.githubusercontent.com/assets/439401/8142238/de6c3462-1176-11e5-9153-18e9e45384ee.png)

In case it is browser specific, I'm using Firefox

**Comment by Seldaek** [comment]
I can't even reproduce this in Firefox here unfortunately. Do you mind taking a closer look in the inspector at least?

**Comment by stof** [comment]
This is not happening anymore, so closing
