### ISSUE TITLE
Login shows a 403 error

### ISSUE THREAD

**Issue by heiglandreas** [composer/packagist#512]
After login in (password is shown in cleartext as already mentioned) I am redirected to ```https://packagist.org/connect/registration/1434178891``` which shows 
![bildschirmfoto 2015-06-13 um 09 05 39](https://cloud.githubusercontent.com/assets/91998/8143414/77cadfe4-11ab-11e5-8966-3e34a1be3412.png)

**Comment by Seldaek** [comment]
Did you try to do a login with github first?

**Comment by heiglandreas** [comment]
i think I did. I will check that out later today
