### ISSUE TITLE
Some packages return a 500 server error

### ISSUE THREAD

**Issue by oscarotero** [composer/packagist#514]
Two examples:
* https://packagist.org/packages/psr7-middlewares/psr7-middlewares
* https://packagist.org/packages/fol/app-installer

**Comment by stevleibelt** [comment]
Same for:
* [https://packagist.org/packages/jacwright/restserver](https://packagist.org/packages/jacwright/restserver)

**Comment by Seldaek** [comment]
This is fixed, but BTW @oscarotero please consider deleting that psr7-middlewares package and re-adding it with a more sensible vendor name. I don't think having psr anything in the vendor is a great idea if you are not representing the php fig/psr.

**Comment by oscarotero** [comment]
Ok, no problem.
thanks
