### ISSUE TITLE
Front-end performance improvement

### ISSUE THREAD

**Issue by kix** [composer/packagist#516]
I ran a Chrome Audit on the Packagist website, and got this:
```
bootstrap-theme.min.css: 79% is not used by the current page.
bootstrap.min.css: 90% is not used by the current page
jackedup.css: 92% is not used by the current page.
```
Looks like if we could serve a CSS with only the needed rules, we could severely improve page load time.

Also, looks like it could be worth it to concatenate and minify/uglify CSS and JS code.

I could totally implement this. However, all of these steps would require some updates in Assetic configuration.

If it will be possible to use JavaScript on the server during build time (so that we could use [`csso`](https://github.com/css/csso) or likes), this would be even more awesome.

And last but not the least, I would suggest to add a version scheme for the CSS and JS code once its concatenation and minification is implemented, and then make sure we leverage browser caching. Caching is important here, as I think most of the Packagist web visitors return way more than just once (I personally visit Packagist 3-5 times a week).

**Comment by Seldaek** [comment]
I don't really think serving CSS with only needed rules would bring much benefit, the amount of CSS is already fairly small.

Concatenating might bring minimal improvements but down the line we can hopefully switch to HTTP2 and forget about this altogether soon enough.

Browser caching is the main thing that should be done IMO, and biggest win for time spent. I'll try and do that when I'm done looking at other css fixes people sent.

**Comment by Seldaek** [comment]
Ok there is now proper expire/cache-control on the css/js assets.
