### ISSUE TITLE
Text color contrast ratio is unsufficient

### ISSUE THREAD

**Issue by dg** [composer/packagist#517]
Currect color contrast ratio is unsufficient for small text:

![2015-06-14_14-36-57](https://cloud.githubusercontent.com/assets/194960/8148562/e8974f08-12a2-11e5-8353-873009a9c106.png)

I have good eyes and it is unpleasant to read this text, for people with visual impairments it will be even worse. According to http://juicystudio.com/services/luminositycontrastratio.php color #F25B1A can be used only for large texts (at least 18 point or 14 point bold) but now it is used for (cca) 9pt text.

**Comment by dg** [comment]
Thank you!

**Comment by Seldaek** [comment]
No worries, hope it's better.
