### ISSUE TITLE
Allow non-maintainers to force-update

### ISSUE THREAD

**Issue by thiemowmde** [composer/packagist#521]
Please make the "force refresh" button public to have a workaround for the reoccurring issue of not auto-updating, see #200, #422, #500 and so on.

The only reason I can think of why this button is not accessible to non-maintainers is that it can be used as a DoS vector. This should be very easy to avoid.

**Comment by Seldaek** [comment]
There is very rarely a need for this at least when people set up the hook properly (which is the case for most popular packages really). I don't really see this as a good thing to have random people hammer this button whenever they think something might be off. If there are bugs we need to fix them, and if not well then there is no need for that button.
