### ISSUE TITLE
Obfuscate email addresses

### ISSUE THREAD

**Issue by martinbean** [composer/packagist#535]
I noticed that author and contributor email addresses on the Packagist website aren’t obfuscated.

It would be good if email addresses could be obfuscated to avoid bots crawling the Packagist website and harvesting developers’ email addresses.

**Comment by Seldaek** [comment]
They're also available in clear on github in the composer.json, so I doubt there is much benefit to any obfuscation. It's not like we force anyone to publish that :)

**Comment by stof** [comment]
Well, on github, such files do not produce a mailto link. So crawling bots would need to have a special knowledge to extract emails from there. On packagist on the other hand, any crawling bot looking for mailto links will find these emails

**Comment by martinbean** [comment]
@stof Indeed. This was my concern, @Seldaek.

**Comment by Seldaek** [comment]
Ah well I can remove the mailto I doubt that'll be a huge issue.

**Comment by martinbean** [comment]
@Seldaek I don’t think the removal of the mailto: link is necessary, just to obfuscate the email address. One approach is to replace alpha-numeric characters to their hexadecimal equivalent: https://github.com/LaravelCollective/html/blob/5.1/src/HtmlBuilder.php#L388

**Comment by Seldaek** [comment]
Well I tend to agree with http://www.theguardian.com/technology/2010/dec/21/keeping-email-address-secret-spambots but anyway I implemented the display:none trick from http://superuser.com/a/235965/37460 as the others might hinder copy pasting or don't seem extremely effective.
