### ISSUE TITLE
Packages are not auto updated

### ISSUE THREAD

**Issue by rebendajirijr** [composer/packagist#536]
Hi, I've been struggling with two of my packages which are not being auto updated:
[jr/framework](https://github.com/rebendajirijr/framework) and [jr/cms](https://github.com/rebendajirijr/cms). My other recently added repos are working ok, but those two don't. Maybe it is somehow related to the fact I had deleted these repos and then after some time I've created them again? Only manual update at packagist.org is working for them. I'm using same API key and credentials for my other packages, what should I try next?

**Comment by stof** [comment]
Have you enabled the packagist service hook on the github repos ?

**Comment by rebendajirijr** [comment]
@stof Of course I've enabled the hook, even when I hit the test button, nothing happens. Packagist gives me no warning about packages not being auto updated even when they are not obviously.

**Comment by rebendajirijr** [comment]
Somehow, problem is gone and it's working already. Strange...
