### ISSUE TITLE
package name leads to 404

### ISSUE THREAD

**Issue by serbanghita** [composer/packagist#538]
Ok, you got me, bad project name https://packagist.org/packages/serbanghita/form-to-object.js

All I did is adding the package with the following configuration https://github.com/serbanghita/formToObject.js/blob/master/composer.json

**Comment by stof** [comment]
The weird thing is that we are getting a 404 from Nginx here, not from Symfony.

@Seldaek do you have anything special in your Nginx config for URLs ending in ``.js`` ?

**Comment by Seldaek** [comment]
Eh yeah sorry I had a location block matching on `.js$` to set expire headers, I made it more specific now so it doesn't conflict with the php 404 handler :)
