### ISSUE TITLE
Release tag with identical SHA as master does not appear

### ISSUE THREAD

**Issue by ahoffmann-wi** [composer/packagist#541]
Repository: [uwmadison_doit/caos-php-client](https://packagist.org/packages/uwmadison_doit/caos-php-client)

1. Created and pushed `1.5.0-RC1` tag from `master` branch
2. Clicked *Update* on the package's Packagist page 
3. Release `1.5.0-RC1` does not appear
4. Created and pushed a new commit on `master`
5. Release `1.5.0-RC1` now appears after clicking *Update*
6. Created and pushed `1.5.0-RC2` tag from `master` branch
7. `1.5.0-RC2` release does not appear after clicking *Update*

It appears that if a tag has an identical SHA as the master branch, the duplicates will be resolved to just show `dev-master`.

There will be long periods of time where master is identical to the latest release, since this will not be updated often. How do we get around this duplication issue? 

The only workaround I can think of is immediately committing an arbitrary change to master after tagging to cause the SHAs to differ. However, after inspecting the commit history of a couple well-known packages, I do not see this sort of procedure being used.

Is there something fundamentally wrong with our release process? Should master never be identical to the most recent release?

**Comment by Seldaek** [comment]
I just hit Update again and now it worked although the references are still the same, so I am wondering if it isn't a bitbucket API cache issue. Maybe they bust their cache when you push a new commit?

One solution I could imagine is to use `git push origin/master --tags` to push the last commits together with the new tag, which probably helps. Or migrate to github for public code as everyone is a lot more familiar with it I think it's a good thing anyway.

**Comment by ahoffmann-wi** [comment]
Thanks for the reply! We will move the project to GitHub, which sounds like will resolve most of these issues.

I also wanted to mention that packagist.org is returning a 406 response code whenever our webhook is called. The webhook I entered is: https://packagist.org/api/bitbucket?username=ahoffmann-wi&apiToken=[redacted]

**Comment by ahoffmann-wi** [comment]
Moving from BitBucket to GitHub has resolved the issues we were seeing.
