### ISSUE TITLE
Unknown license

### ISSUE THREAD

**Issue by rougin** [composer/packagist#542]
Hello! I did submit my [library](https://packagist.org/packages/rougin/transcribe) into Packagist but it seems that it cannot detect the license for it (which is MIT). Is there something I did wrong or I'll just wait to detect it?

**Comment by hkdobrev** [comment]
You need to specify the license in the `composer.json` file. Take a look at the documentation: https://getcomposer.org/doc/04-schema.md#license

**Comment by rougin** [comment]
Oh. I forgot it. Thanks!
