### ISSUE TITLE
JSON files seem aggressively cached - new stable releases are not installable

### ISSUE THREAD

**Issue by fredemmott** [composer/packagist#543]
I published hhvm/xhp-lib v0.0.2 and v1.0.0 25 minutes ago; these immediately showed up on https://packagist.org/packages/hhvm/xhp-js , but do not appear in https://packagist.org/packages/hhvm/xhp-js.json , and are not installable via composer.

RE composer: I have tried removing composer.lock, vendor/, and running composer clear-cache.

Additionally, installing dev-master installs an old revision.

**Comment by Seldaek** [comment]
There is a delay of up to 1min in normal circumstances for this stuff to propagate to the static files composer uses (which is at https://packagist.org/p/hhvm/xhp-js.json btw, note the /p/). The URL you used to check is the API URL which contains a bit more infos and is indeed cached for 1h as third party services don't usually need last-minute info.

It's all fixed now so I guess it was just bad luck.. In some cases the dumper messes up and locks up for a bit longer that's a known issue that I gotta work on :)
