### ISSUE TITLE
Impossible to change e-mail when login in with github.

### ISSUE THREAD

**Issue by vpakg** [composer/packagist#544]
Upon signing up with github, user is prompted to pick a username and e-mail. I've accidental added one extra letter to my e-mail and saved.  Because I've logged in with github, I was never asked to chose a password, however to change anything in the settings I need the password (for example, to change the e-mail). And the only way I found to request a password is to have it sent to my e-mail, which has one extra letter so will never be delivered.

![packagist](https://cloud.githubusercontent.com/assets/4654583/8629066/ff756cfe-2725-11e5-9680-67ec5d342380.png)

**Comment by Seldaek** [comment]
That's indeed an issue, but there is no perfect way around it if you typo your email. Please email contact@packagist.org with the username and correct email so we can fix it.
