### ISSUE TITLE
Bitbucket: support to webhooks.

### ISSUE THREAD

**Issue by rentalhost** [composer/packagist#546]
Currently you need create a **Service > POST** on Bitbucket to support auto update. But it'll be unsupported in some moment on future:

> In the future, you will not be able to create POST or Pull Request POST services from this screen, as Bitbucket's new and improved webhooks will replace these services. Existing POST services will continue to function as expected for now. To create a new webhook, refer to [the documentation for Bitbucket's updated webhooks](https://confluence.atlassian.com/x/VAjZKw).

**Comment by stof** [comment]
Well, there is a single change to do in Packagist, and then you will be able to use the same URL to create a webhook registered on the ``Push`` event of your repo. It will do exactly the same than the Post service, as far as Packagist is concerned.
The change is just a matter of updating https://github.com/composer/packagist/blob/327fdcf8d213881f0bbfbe21fc6c9b8f21606686/src/Packagist/WebBundle/Controller/ApiController.php#L80 to support the new way to get the repo URL (it will be in ``$payload['repository']['links']['html']['href']``)

**Comment by fulopattila122** [comment]
Is there any plan on when is this going to be released?

**Comment by alcohol** [comment]
@fulopattila122 once the merged changes are deployed, please be so kind as to test if this works as expected. I don't have any bitbucket repositories myself, so I based this purely on their documentation. Expectations might not match reality :p

**Comment by alcohol** [comment]
@Seldaek is there any way to see when packagist was last deployed/updated? Maybe you could include in the UI on which revision it is running somewhere?

**Comment by Seldaek** [comment]
Maybe I could, but I doubt many people care :) Anyway it's been 
deployed, it usually is once I merged.

**Comment by alcohol** [comment]
Fair enough. Thanks :-)
