### ISSUE TITLE
Problem submiting a repository after renaming it to lowercase

### ISSUE THREAD

**Issue by antonienko** [composer/packagist#547]
I was trying to submit a repository (https://github.com/antonienko/MoneyFormatter) and packagist complained about the use of uppercase characters.

So I proceeded to rename it (https://github.com/antonienko/money-formatter) but I still get the same old error message:

    The package name antonienko/MoneyFormatter is invalid, it should not contain uppercase characters. We suggest using antonienko/money-formatter instead.

But I'm using the suggested name!

So I guess there's something that wasn't cleared from the first error.

**Comment by hkdobrev** [comment]
@antonienko You could use uppercase letters in your GitHub repository name. What's needed to be lowercase is the package name in [your `composer.json`](https://github.com/antonienko/money-formatter/blob/86180e80db4c7cbdc9cba79ab141961d4c583f51/composer.json#L2).

**Comment by antonienko** [comment]
Nice! Maybe the error should be a little more descriptive :)

Thanks!
