### ISSUE TITLE
Dependency issues with Snc/RedisBundle

### ISSUE THREAD

**Issue by bymdev** [composer/packagist#548]
Hey guys,

It seems at the current state of the dependency chain, some classnames are broken.

When trying to update (and run many commands via app/console) the system throws:

```PHP Fatal error:  Class 'Predis\Profile\Factory' not found in .../vendor/snc/redis-bundle/Snc/RedisBundle/DependencyInjection/SncRedisExtension.php on line 158```

After upgrading 

Predis to latest, the console starts working, but the frontend gets fatals for class not found:

```Failed opening required '.../vendor/predis/predis/lib/Predis/Client.php```

(... is replacing actual server path.).

Thanks

**Comment by bymdev** [comment]
Downgrading to snc/redis-bundle 1.1.8 seems to solve the issue

**Comment by Seldaek** [comment]
Fixed the composer.json now
