### ISSUE TITLE
README integration with Gitlab

### ISSUE THREAD

**Issue by ragboyjr** [composer/packagist#556]
I've submitted several packages to `packagist` and none of them show the README at the bottom of the package. Here is an [example package](https://packagist.org/packages/krak/array) that doesn't have the README. In fact, all of them from the [Krak](https://packagist.org/packages/krak) package aren't showing a README. I've compared my `composer.json` to many other projects, and I don't see anything wrong with them. The only thing different is that my projects are from gitlab where as the others are from github. 

I don't know if this is a bug or just a missing feature, but I wanted to report it here in case I was missing something.

Thanks!

**Comment by alcohol** [comment]
As you can see here, this functionality seems currently implemented for GitHub only:
https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Package/Updater.php#L393

If Gitlab has a similar API, then you could write a method similar to the above and call it after this block:
https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Package/Updater.php#L170-L172

We are open to pull requests ;-)

**Comment by ragboyjr** [comment]
Thanks! It looks like Gitlab doesn't support this feature as of yet. I added a feature request [here](http://feedback.gitlab.com/forums/176466-general/suggestions/9177020-add-repo-contents-api-like-github), but it's unknown if it will get implemented any time soon. So I don't know exactly what you guys want to do with this

**Comment by stof** [comment]
Well, nothing will be done with this until an API is available.

**Comment by Garbee** [comment]
Would the [repository file](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/repository_files.md#get-file-from-repository) API handle this case?

**Comment by alcohol** [comment]
@Garbee technically, yes I reckon it would. But it isn't as straight forward as the Github API.

**Comment by stof** [comment]
@Garbee  no it would not, as this would not return a rendered readme, forcing Packagist to implement rendering of all text formats supported by gitlab for their readmes (and would require guessing the name of the readme file, requiring several API calls to gitlab).

Vote on https://gitlab.com/gitlab-org/gitlab-ce/issues/24124 to support the feature request on gitlab

**Comment by tflori** [comment]
hm why not add a key `readme` in composer.json which is a relative path to the readme? packagist can then update the readme from this file...

**Comment by alcohol** [comment]
Because adding yet another composer.json config option for something as insignificant as a readme is really not a viable solution.

**Comment by stof** [comment]
@tflori and even then, unless you write your readme in HTML (which nobody does AFAIK), it would still require implementing readme rendering in PAckagist and hoping that rules are the same than on the original site (hint: Github and Gitlab don't have exactly the same supported features in the markdown syntax)

**Comment by tflori** [comment]
@alcohol if it is insignificant why to show it on packagist? for me it does not seem to be insignificant.

@stof there are plenty of implementations. maybe there are differences but at least we can see something. it's not only about gitlab. currently no readme works except github.

I think it is viable and even not a big deal. It makes sense also because there are a lot of different implementations of git over http.

**Comment by stof** [comment]
@tflori yes, today it has been implemented only for github, because they are the one providing an API to get the rendered readme (and it covers 80% of the Packagist database). And this is why I created the feature request on gitlab to provide a similar API, which would make supporting readmes coming from gitlab an easy task (currently, it would require a big work for a small amount of packages).

**Comment by tflori** [comment]
@stof without sarcasm. it will be great when it works on gitlab.com. but that does not solve the problem that it is still not working for custom gitlab installations - or how do you know that git.example.com is a gitlab installation?

**Comment by stof** [comment]
well, if you have a custom packagist deployment, you can make it work, as you can configure the gitlab domains in the composer config in your setup.
For packagist.org, they would indeed not be detected as gitlab repos automatically (gitlab.com is detected by default). So there is 3 ways to manage it:
- implement a way to submit additional gitlab domains to packagist.org to make it update the composer config
- make @Seldaek add additional gitlab domains in the composer config of the server manually on demand
- add a way to detect gitlab automatically in composer when the domain is not a registered gitlab domain

IMO, the first option is overkill, as the extra complexity added for it is probably not worth it compared to the number of packages registered in packagist.org and coming from custom gitlab instances (custom gitlab instances are used for in-house hosting, so is it really the place where you host your open-source packages ?)

The third option is hard. This would require performing an HTTP request, meaning it should be done only for deep detection of the driver, but the URL is very likely to have matched the GitDriver regex already

**Comment by stof** [comment]
but anyway, this discussion is needed only once we can have support on gitlab side first, so we can delay the discussion about how to make packagist.org detect custom gitlab instances as being gitlab

**Comment by tflori** [comment]
I have a own gitlab instance - why? I wanted to know :)

it sounds like rocket sience for a solution that is not solving all problems. but we can have an easier solution that solves all problems (with readme).

**Comment by stof** [comment]
@tflori your "solution" would imply several things:

- adding a new field in the composer schema to give a path to the readme, which creates bloat in the schema
- implementing a way for Packagist to retrieve the content of this file, for any supported source (hint: this might not be as easy as you think, given the number of VCS drivers supported by Composer)
- implementing the conversion of the readme source to HTML:
    - not all readmes are markdown
    - not all markdown readme are using the same Syntax (Bitbucket, Gitlab and and Github all have their own specific flavor with different features, and people will expect that the rendering works fine)
    - code snippets in the readme needs to get syntax-highlighted in the HTML (and we rely on the github highlighting now rather than highlighting in JS now, because the JS code may not have the info about the language defined in the markdown source, and the language detection may not work well)

I don't think this is easier.
If you know Ruby, it might be easier to contribute the gitlab endpoint instead (they already have the logic to perform the readme rendering on their side, and the logic to build an API, but they need to be combined)

> I have a own gitlab instance - why? I wanted to know :)

But do you use it to host your open-source packages ? It might not be the easiest way to get contributions if they need to create an account on your own instance first.

**Comment by tflori** [comment]
@stof Yes, I do - because I want to have everything on one place. And Yes thats a problem for other contributors. But my packages are not that popular :(

- for me description is more bloat than a refrence to the readme
- I don't know how it is working but when I'm correct packagist downloads all of the package (including the README.md)
- conversion:
  - support only text and markdown if it is anything else just write the file name
  - use a simple implementation taken from 3rd party package - it will do at least something with the code (every developer will be happy because at least there is something - and 99% it works)
  - gitlab does not have a highlighting in html - it is using javascript. and again: gitlab is not the only implementation of git over http (git-http-backend for example)

**Comment by alcohol** [comment]
The inclusion readme is a novelty feature. It is there because Github offers it, and it was rather trivial to implement. Once (if ever) Gitlab's API offers it too, we will implement that as well. That is what this issue is for. Can you drop this discussion now please? You are taking it off-topic.

**Comment by tflori** [comment]
@alcohol This topic is from @ragboyjr and the solution you suggest (add the rendered readme feature in gitlab.com) and implement it in packagist only works for gitlab.com projects. Maybe you didn't noticed that @ragboyjr example is a custom gitlab instance. Your solution is not a solution for his problem it is a solution to get away work from packagist developer.

**Comment by alcohol** [comment]
You are wrong. On premise Gitlab instances offer the same API, just like on premise Github instances offer the same API.

**Comment by ragboyjr** [comment]
@tflori thanks for pointing that out. @alcohol is correct. If the feature is developed in Gitlab CE, then we'd be able to make use of it in our system.

**Comment by tflori** [comment]
@alcohol And you rather want to maintain a list of gitlab instances than developing a solution that works also for fossil, git-http-backend, svn, hg, bitbucket?

@ragboyjr I have it already working for my old gitlab instance on my local packagist installation... It's really not that big deal.

**Comment by alcohol** [comment]
> And you rather want to maintain a list of gitlab instances

I do not know why we would want to do that, or what that has to do with this topic. But no, we are not going to maintain a list.

You seem to be under the impression that open source software developers should be there to implement whatever you may desire. Unfortunately (for you), that is not how open source software development works. Anyway, I am unsubscribing from this thread.

**Comment by tflori** [comment]
@alcohol I don't think that open source means that the maintainer of a package should develop what any user requests. You provide the main php package resource and should not be stick to github. Also you should not handle feature requests as blame. It is great to have a package repository for open source php projects. But it will be greater if we can help @ragboyjr (and me too) to have the readme shown on packagist.

If you check what driver is used for his gitlab instance you will see that it is GitDriver and not GitlabDriver. To add the readme api to gitlab does not help if you don't find out it is gitlab - this will be greater deal than adding the support of a readme property in composer.json. Or if you don't want to touch this specification: try the "README.md" file - it will help 90% of the 20%.

It's up to you: I'm already making the required changes - that is open source software: everyone can contribute.

**Comment by Garbee** [comment]
I think there is a different way to look at this over a simple "support one other provider" request. It comes down to monoculture. To not have the ability to support any git host and only saying "Providers that do X for us get the best experience." means saying that for developers to get the best representation of their packages they must use one of those providers (currently only *one*.) This means encouraging a monoculture among developers which we know is bad for communities and progression at large.

By doing markdown parsing internally (which there are packages available for) it means you aren't tied to a vendor needing to do it for you. Meaning if one does, that's great it saves some processing power locally, however it doesn't discourage developers from using other platforms.

If someone from the community would submit a patch adding functionality for this in would it have a chance at getting accepted? Or must parsing be done by the git host for some reason?

Yes, it will use some extra cycles on packagist's end. However it fights monoculture which is an important thing as well.

**Comment by Seldaek** [comment]
You can discuss this from an ideological viewpoint all you want, the bottom line is 97% of packages on packagist are hosted on github right now, so doing a github specific fix that is tons easier than a general solution makes sense. If someone wants to implement something generic for non-github repos that doesn't incur a huge mess in the code then I guess we can accept it, but due to the nature of our repo support, you'd have to add support in all the VcsRepository driver classes to cover everything, which will mean a lot of extra work for almost no benefit.

**Comment by tflori** [comment]
@Seldaek That's great. I'm on it and can create PR in the next days.

You are right. I have to implement a function in every driver but it is almost done. So it will be two PRs.

**Comment by tflori** [comment]
Created pull request in composer/composer. Without this feature it will not be possible or at least too much work.

**Comment by Seldaek** [comment]
Fixed by #750

**Comment by tflori** [comment]
yeah! thanks!
https://packagist.org/packages/tflori/secure-token
