### ISSUE TITLE
Search caching issue

### ISSUE THREAD

**Issue by mindplay-dk** [composer/packagist#557]
Search results are being cached (on the client-side?)

I notice this often after submitting a new package, because it doesn't come up when searching - I have to force refresh the page to find a newly added package.

It happens since the redesign of packagist.org only, I think? I don't recall ever having this issue before, but since the redesign, I run into this a lot, and it confuses me every time - thinking my package wasn't properly submitted or was somehow deleted...

**Comment by stof** [comment]
The search index is updated by a cron job, so this is not immediate. The cron runs every 5 minutes AFAIK (unless it changed).

and the list of new packages on https://packagist.org/explore/ is also cached for 900s (i.e. 15 minutes), to avoid redoing the query all the time

**Comment by mindplay-dk** [comment]
Ok, by design then, got it :-)
