### ISSUE TITLE
quick mockup for redesign

### ISSUE THREAD

**Issue by flip111** [composer/packagist#564]
* favor package title over vendor
* stable/dev release indication
* more versions in the same box
* versions go into box with button to copy (just like github link box)
* Readme more visible
* add hourglass to search box

Stuff not in image below:
* The area of requires/requires-dev/suggests/provides/conflicts/replaces (lets call it relates-to-area) moves down below readme
* Dependents goes to relates-to-area

Boxes on the right: (changes not visible in picture)

Box 1: general
Maintainer name (make icon smaller in front)
License
Github URL

Box 2: statistics
Downloads
commits
stars
watchers

Box 3: authors and contributors
list of top 5 with show more

![image](https://cloud.githubusercontent.com/assets/2244480/9255102/6bbdcd12-41e7-11e5-9544-73cdfde92973.png)

**Comment by stof** [comment]
> favor package title over vendor

I'm not sure about it. the package name is ``symfony/console``, not just ``console``. And many different packages are named ``*/console`` for instance.

> The area of requires/requires-dev/suggests/provides/conflicts/replaces (lets call it relates-to-area) moves down below readme

given that the readme can be very look, this may be weird

> Dependents goes to relates-to-area

This looks weird to me, as the way to compute dependants is totally different, and they are not computed for this version but for any version AFAIK.

> Boxes on the right: (changes not visible in picture)

why not making them visible ?

> Box 1: general
> Maintainer name (make icon smaller in front)
> License
> Github URL

The license can actually be different per version.

and we can have more links depending of what is configured in the composer.json

**Comment by flip111** [comment]
@stof 
you mean the readme could be very long? maybe a button to expand?
some things are not visible in the picture because i stopped editing at that point ... i mean for those boxes to be visible on the website itself

Perhaps as a sort of subtitle of the version some more information could be shown like the license and hash

If there is any more interesting i could try a few more designs, just for brainstorming sake i guess

**Comment by Seldaek** [comment]
Thanks for the suggestions but to be frank I have to say I disagree with most of them. Quite a lot of thought went into the current design and I don't really have time to expand on everything but stof already explained quite a bit anyway.
