### ISSUE TITLE
Solr HTTP error: Not Found (404)

### ISSUE THREAD

**Issue by achristodoulou** [composer/packagist#568]
When I tried to search for a package I received the following error **We're so sorry, something is wrong on our end.** and in the application logs the below critical error message was occurred. 

fyi, I have installed solr and run it without making any additional configuration changes.

```
[2015-08-16 09:20:09] request.INFO: Matched route "search.ajax". {"route_parameters":{"_controller":"Packagist\\WebBundle\\Controller\\WebController::searchAction","_route":"search.ajax"},"request_uri":"http://localhost:8001/app.php/search/?search_query%5Bquery%5D=ac"} []
[2015-08-16 09:20:09] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2015-08-16 09:20:09] security.DEBUG: User was reloaded from a user provider. {"username":"andreas","provider":"Packagist\\WebBundle\\Security\\Provider\\UserProvider"} []
[2015-08-16 09:20:09] request.CRITICAL: Uncaught PHP Exception Solarium_Client_HttpException: "Solr HTTP error: Not Found (404)" at /home/achristodoulou/Projects/test/packagist/vendor/solarium/solarium/library/Solarium/Result.php line 98 {"exception":"[object] (Solarium_Client_HttpException(code: 404): Solr HTTP error: Not Found (404) at /home/achristodoulou/Projects/test/packagist/vendor/solarium/solarium/library/Solarium/Result.php:98)"} []
[2015-08-16 09:20:09] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []

```

**Comment by Seldaek** [comment]
You need to set up the schema.xml for Solr, and then run app/console 
packagist:index to build up the solr index. Then search should work.

**Comment by achristodoulou** [comment]
I took a look at the doc/schema.xml and I did not see anything that needs to be change, so I just run app/console packagist:index while solr was running on default port in the background and I received the below  error. Any suggestions like what needs to be updated in doc/schema.xml?

```
$ php app/console packagist:index                   
  [Solarium_Client_HttpException]   
  Solr HTTP error: Not Found (404)                                      
packagist:index [--force] [--all] [--] [<package>]
```

**Comment by alcohol** [comment]
But did you actually configure solr with said schema?

**Comment by khalid05** [comment]
First copy the schema.xml.
cp doc/schema.xml /opt/solr/example/solr/conf/schema.xml
and add the core in the configuration of solarium:
```
nelmio_solarium:
    clients:
        default:
            dsn: http://solr:8983/solr
            core: collection1 
```

**Comment by achristodoulou** [comment]
fyi, I am using the latest version of solr-5.2.1 and I had to modify the schema.xml by removing some deprecated attributes in order to be able to add a new core through solr interface. I even added the above lines nelmio_solarium in packagist config.yml but still when I run the following command I am getting the same error message.

```
php app/console packagist:index --no-debug --env=prod

[Solarium_Client_HttpException]   
Solr HTTP error: Not Found (404)
```

**Comment by khalid05** [comment]
Hi, 
Can you put your solr configuration.

**Comment by achristodoulou** [comment]
I have uploaded solr 2 config files in github:

I have updated also the schema that it was with packagist as some attributes were not valid in the latest version:
https://github.com/achristodoulou/dump/blob/master/solr/schema.xml

https://github.com/achristodoulou/dump/blob/master/solr/solrconfig.xml

**Comment by musiaht** [comment]
I think I ran into this issue before; solr-5.2.1 could not load the packagist schema.xml and I got a 404. 

I ended up dropping to solr-4.10.4 to get the search to work; even then, I had to add this:

```
   <field name="_version_" type="long" indexed="true" stored="true"/>
```
to the list of fields to make it work.

**Comment by Niiko** [comment]
Same here on Solr 5.3.0

I could make it working with two adjustments : 
- Removing all statements enablePositionIncrements="true" in schema.xml (deprecated from 4.4 and removed in 5.x)
- Add field : <field name="_version_" type="string" indexed="true" stored="true" multiValued="false" /> (removed in 4.0)

I could make a PR if it works with Solr 3.6

**Comment by daemionfox** [comment]
Just ran into this while performing an upgrade on our local packagist.

-bash-4.2$ app/console packagist:index --all
Solarium_Client_HttpException: Solr HTTP error: Not Found (404), occurred while processing packages: 3,4,5,6,7,8,9,10,12,13,14,15,16,17,18

I've followed the steps here, and upgraded our schema.xml (core already existed in the parameters.yml) but I'm still getting this problem.  Not sure where to go from here.

**Comment by vitman** [comment]
To make it work now(in 2017 and solr 6), you need to comment 2 more lines on solrconfig.xml:

**Comment by HadesArchitect** [comment]
I have got the same issue, in my case it was a misconfiguration: in solr config the core was called 'packagist', but in nelmio_solarium it was called 'collection1'

**Comment by HadesArchitect** [comment]
@vitman If you have solr 6 operational with packagist, could you publish your config files?

**Comment by vitman** [comment]
schema.xml:

> <?xml version="1.0" encoding="UTF-8" ?>
<schema name="packagist" version="1.4">
  <types>
    
    <fieldType name="string" class="solr.StrField" sortMissingLast="true" omitNorms="true"/>
    
    <fieldType name="boolean" class="solr.BoolField" sortMissingLast="true" omitNorms="true"/>
    
    <fieldtype name="binary" class="solr.BinaryField"/>

    

    <fieldType name="int" class="solr.TrieIntField" precisionStep="0" omitNorms="true" positionIncrementGap="0"/>
    <fieldType name="float" class="solr.TrieFloatField" precisionStep="0" omitNorms="true" positionIncrementGap="0"/>
    <fieldType name="long" class="solr.TrieLongField" precisionStep="0" omitNorms="true" positionIncrementGap="0"/>
    <fieldType name="double" class="solr.TrieDoubleField" precisionStep="0" omitNorms="true" positionIncrementGap="0"/>

    <fieldType name="date" class="solr.TrieDateField" omitNorms="true" precisionStep="0" positionIncrementGap="0"/>

    
    <fieldType name="tdate" class="solr.TrieDateField" omitNorms="true" precisionStep="6" positionIncrementGap="0"/>

    
    <fieldType name="text_edgengram" class="solr.TextField" positionIncrementGap="100">
        <analyzer type="index">
            <tokenizer class="solr.StandardTokenizerFactory"/>
            <filter class="solr.WordDelimiterFilterFactory" splitOnCaseChange="1" generateWordParts="1" preserveOriginal="1"/>
            <filter class="solr.LowerCaseFilterFactory"/>
            <filter class="solr.EdgeNGramFilterFactory" minGramSize="1" maxGramSize="100" />
        </analyzer>
        <analyzer type="query">
            <tokenizer class="solr.WhitespaceTokenizerFactory"/>
            <filter class="solr.LowerCaseFilterFactory"/>
        </analyzer>
    </fieldType>

    
    <fieldType name="text_general" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>
    </fieldType>

    
    <fieldType name="text_general_rev" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.ReversedWildcardFilterFactory" withOriginal="true"
           maxPosAsterisk="3" maxPosQuestion="2" maxFractionAsterisk="0.33"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>
    </fieldType>

    
    <fieldType name="text_en" class="solr.TextField" positionIncrementGap="100">
      <analyzer type="index">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        
        
        <filter class="solr.StopFilterFactory"
                ignoreCase="true"
                words="lang/stopwords_en.txt"
                />
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.EnglishPossessiveFilterFactory"/>
        <filter class="solr.KeywordMarkerFilterFactory" protected="protwords.txt"/>
        
        <filter class="solr.PorterStemFilterFactory"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.StopFilterFactory"
                ignoreCase="true"
                words="lang/stopwords_en.txt"
                />
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.EnglishPossessiveFilterFactory"/>
        <filter class="solr.KeywordMarkerFilterFactory" protected="protwords.txt"/>
        
        <filter class="solr.PorterStemFilterFactory"/>
      </analyzer>
    </fieldType>

    
    <fieldType name="text_en_splitting" class="solr.TextField" positionIncrementGap="100" autoGeneratePhraseQueries="true">
      <analyzer type="index">
        <tokenizer class="solr.WhitespaceTokenizerFactory"/>
        
        
        <filter class="solr.StopFilterFactory"
                ignoreCase="true"
                words="lang/stopwords_en.txt"
                />
        <filter class="solr.WordDelimiterFilterFactory" generateWordParts="1" generateNumberParts="1" catenateWords="1" catenateNumbers="1" catenateAll="0" splitOnCaseChange="1"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.KeywordMarkerFilterFactory" protected="protwords.txt"/>
        <filter class="solr.PorterStemFilterFactory"/>
      </analyzer>
      <analyzer type="query">
        <tokenizer class="solr.WhitespaceTokenizerFactory"/>
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.StopFilterFactory"
                ignoreCase="true"
                words="lang/stopwords_en.txt"
                />
        <filter class="solr.WordDelimiterFilterFactory" generateWordParts="1" generateNumberParts="1" catenateWords="0" catenateNumbers="0" catenateAll="0" splitOnCaseChange="1"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.KeywordMarkerFilterFactory" protected="protwords.txt"/>
        <filter class="solr.PorterStemFilterFactory"/>
      </analyzer>
    </fieldType>

    
    <fieldType name="text_en_splitting_tight" class="solr.TextField" positionIncrementGap="100" autoGeneratePhraseQueries="true">
      <analyzer>
        <tokenizer class="solr.WhitespaceTokenizerFactory"/>
        <filter class="solr.SynonymFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="false"/>
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="lang/stopwords_en.txt"/>
        <filter class="solr.WordDelimiterFilterFactory" generateWordParts="0" generateNumberParts="0" catenateWords="1" catenateNumbers="1" catenateAll="0"/>
        <filter class="solr.LowerCaseFilterFactory"/>
        <filter class="solr.KeywordMarkerFilterFactory" protected="protwords.txt"/>
        <filter class="solr.EnglishMinimalStemFilterFactory"/>
        
        <filter class="solr.RemoveDuplicatesTokenFilterFactory"/>
      </analyzer>
    </fieldType>

    <fieldtype name="phonetic" stored="false" indexed="true" class="solr.TextField" >
      <analyzer>
        <tokenizer class="solr.StandardTokenizerFactory"/>
        <filter class="solr.DoubleMetaphoneFilterFactory" inject="false"/>
      </analyzer>
    </fieldtype>

    
    <fieldtype name="ignored" stored="false" indexed="false" multiValued="true" class="solr.StrField" />
 </types>

 <fields>
   

   <field name="id" type="string" indexed="true" stored="true" required="true" />
   <field name="name" type="text_general_rev" indexed="true" stored="true"/>
   <field name="description" type="text_general_rev" indexed="true" stored="true"/>
   <field name="tags" type="text_general_rev" indexed="true" stored="true" multiValued="true"/>
   <field name="type" type="text_general_rev" indexed="true" stored="true"/>
   <field name="trendiness" type="float" indexed="true" stored="true" />
   <field name="downloads" type="int" indexed="true" stored="true" />
   <field name="favers" type="int" indexed="true" stored="true" />
   <field name="language" type="string" indexed="true" stored="true" />
   <field name="repository" type="string" indexed="false" stored="true" />
   <field name="abandoned" type="int" indexed="false" stored="true" />
   <field name="replacementPackage" type="string" indexed="false" stored="true" />
   <field name="_version_" type="string" indexed="true" stored="true" multiValued="false" />

   
   <field name="text" type="text_en" indexed="true" stored="false" multiValued="true"/>

   
   <field name="name_split" type="text_en_splitting_tight" indexed="true" stored="false" />
   
   <field name="package_name" type="text_en_splitting_tight" indexed="true" stored="false" />

   
   <field name="text_ngram" type="text_edgengram" indexed="true" stored="false" multiValued="true" />
 </fields>

 
 <uniqueKey>id</uniqueKey>

 
 <defaultSearchField>text</defaultSearchField>

 
 <solrQueryParser defaultOperator="OR"/>
  

   <copyField source="name" dest="text"/>
   <copyField source="description" dest="text"/>
   <copyField source="tags" dest="text"/>

   <copyField source="name" dest="name_split"/>

   <copyField source="name" dest="text_ngram"/>
   <copyField source="tags" dest="text_ngram"/>
</schema>

=====================================

solrconfig.xml

**Comment by vitman** [comment]
solrconfig.xml
> <?xml version="1.0" encoding="UTF-8" ?>



<config>
  <luceneMatchVersion>LUCENE_36</luceneMatchVersion>
  
  <directoryFactory name="DirectoryFactory" class="${solr.directoryFactory:solr.StandardDirectoryFactory}"/>


  <updateHandler class="solr.DirectUpdateHandler2" />

  <requestDispatcher handleSelect="true" >
    <requestParsers enableRemoteStreaming="false" multipartUploadLimitInKB="2048" />
  </requestDispatcher>

  <requestHandler name="standard" class="solr.StandardRequestHandler" default="true" />
  
  

  
  <admin>
    <defaultQuery>solr</defaultQuery>
  </admin>

</config>


schema.xml
> <?xml version="1.0" encoding="UTF-8" ?>



<config>
  <luceneMatchVersion>LUCENE_36</luceneMatchVersion>
  
  <directoryFactory name="DirectoryFactory" class="${solr.directoryFactory:solr.StandardDirectoryFactory}"/>


  <updateHandler class="solr.DirectUpdateHandler2" />

  <requestDispatcher handleSelect="true" >
    <requestParsers enableRemoteStreaming="false" multipartUploadLimitInKB="2048" />
  </requestDispatcher>

  <requestHandler name="standard" class="solr.StandardRequestHandler" default="true" />
  
  

  
  <admin>
    <defaultQuery>solr</defaultQuery>
  </admin>

</config>

**Comment by vitman** [comment]
@HadesArchitect 
here is the gist:

https://gist.github.com/vitman/ff693986ca294f3a39183a1d396e9393

also please note that you will need to copy few more files into your data/{collectionName} folder:
stopwords_en.txt  synonyms.txt  protwords.txt  solrconfig.xml  stopwords.txt

I've took them from collection example bundled with solr ( /opt/solr-6.4.1/example/files/conf/ in my case)

**Comment by hackzilla** [comment]
We decided to use docker to install Solr 3.6 on our Ubuntu 16.04 server.

Pretty straight forward, and saves worrying about compatibility with a Solr version that isn't supported.
https://github.com/UKWebMedia/packagist-solr
