### ISSUE TITLE
rST README rendering: definition lists not rendered

### ISSUE THREAD

**Issue by cweiske** [composer/packagist#569]
rST definition lists are not rendered as definition lists, see the "Links" section in https://packagist.org/packages/pear/services_yadis

**Comment by alcohol** [comment]
Correct, this doesn't seem to be a part of the allowed attribute list. Should be an easy fix.

https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Package/Updater.php#L417

**Comment by Seldaek** [comment]
Deployed and force-updated pear/services_yadis to confirm it works. Other packages will need an update before the new elements render correctly as we do the html filtering only once on update.
