### ISSUE TITLE
The warning about license being unknown should be displayed in a prominent place

### ISSUE THREAD

**Issue by stof** [composer/packagist#577]
Currently, the message about license being unknown is low in the page (even off-screen when you have lots of dependencies).
And even if it is displayed in red, this is not very visible in the orange UI
![unknown_license](https://cloud.githubusercontent.com/assets/439401/9639781/0748f36c-51ae-11e5-9732-3be105ea1e04.png)

It would be great to make it more visible. I see 2 solutions:

- move the licensing info higher in the page for everyone
- add a warning at the top of the package page for maintainers in case it has no license, similar to what we do when the package does not have the github hook to auto-update it.

**Comment by Seldaek** [comment]
I wouldn't move the license, but adding a warning to maintainers (or even everyone) sounds good yes.

**Comment by stof** [comment]
yeah, I also think the warning is a better solution.
