### ISSUE TITLE
Feature request: order 'providers' page by popularity

### ISSUE THREAD

**Issue by fredemmott** [composer/packagist#578]
eg https://packagist.org/providers/psr/log-implementation would be more useful if monolog and graylog2/gelf-php were near the top

**Comment by alcohol** [comment]
I looked at this but it doesn't seem to be a simply copy-pasta portable solution. It's kind of tied into the search form/functionality. Providers is not a search action. It's a listing. I also wouldn't know where to put the order by icons in the template. Next to the search box seems ambiguous.

@Seldaek any suggestions/feedback?

**Comment by Seldaek** [comment]
Well we could just order them by popularity always that removes the UI concerns.

**Comment by alcohol** [comment]
That was what I concluded my comment with. So I assume this means you agree that is the quickest win and an acceptable solution :p

**Comment by Seldaek** [comment]
Yeah pretty much :)

**Comment by alcohol** [comment]
As I understand it the popularity comes from solr? So need to rank packages using values from another array?

**Comment by Seldaek** [comment]
Well it can also be fetched from redis for every package, and then sort 
them..  `$redis->zscore('downloads:trending', $package->getId()));`

It's that or moving the provides to solr and then do the whole query via 
solr.

**Comment by alcohol** [comment]
I'll take a peek tomorrow afternoon.
