### ISSUE TITLE
Evaluate support for markdown tables in READMEs

### ISSUE THREAD

**Issue by Seldaek** [composer/packagist#580]
Not sure if feasible or how easy it would be but it has been requested so it'd be good to take a look. Not really a major requirement though.

**Comment by stof** [comment]
This is just a matter of updating the HtmlPurifier whitelist actually. The markdown rendering is done by github which supports tables. But we probably drop them when sanitizing the HTML to avoid XSS: https://github.com/composer/packagist/blob/a30abcb27f7a4c346fd4075ce4711a9c47835608/src/Packagist/WebBundle/Package/Updater.php#L416

**Comment by alcohol** [comment]
Probably, I'm trying to find a repository that has a table to check how the API returns it.

**Comment by stof** [comment]
@alcohol you can also create a temporary repo on your account with such a readme to test it rather than searching for such a repo :smile:

**Comment by alcohol** [comment]
I just did!

**Comment by Seldaek** [comment]
Eh yes probably just allowing table/tr/td would be enough.

**Comment by stof** [comment]
probably also thead, tbody, tfoot (in case they are used by the table renderer) and th (table headings are possible in MD).

**Comment by alcohol** [comment]
I didn't see tfoot. Not sure also how to produce this in markdown. Let me check.

**Comment by alcohol** [comment]
Officially tables are not even supported by markdown. I don't think GFM supports footers though.

**Comment by stof** [comment]
Indeed, tfoot does not seem to be supported in GFM. And they don't exist in rST either. I don't know about other prose markup formats supported by github.

Regarding the fact that standard markdown does not support tables, we don't care: we are not rendering markdown here, but github readmes. And these support tables.

**Comment by alcohol** [comment]
I know, was just reporting my findings.
