### ISSUE TITLE
Suggestions and dependents page

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/packagist#582]
Could be nice to count suggested package as a dependency for the dependents section.

Concrete example: https://packagist.org/packages/sllh/iso-codes-validator/dependents

You can see 2 package that depends of this one.

But in this package: https://packagist.org/packages/ronanguilloux/isocodes

You can see that sllh/iso-codes-validator is suggested. It should appear on dependents section IMO.

**Comment by stof** [comment]
Or maybe in a list of suggesters, to distinguish both cases

**Comment by Soullivaneuh** [comment]
@stof Yes we could separate cases, but show both on a single page would be simpler IMO.

Example:

### Dependents

* package01
* package02
* package03

### Suggested

* package42
* package1337

**Comment by Seldaek** [comment]
Sounds good to me.

**Comment by Soullivaneuh** [comment]
> Sounds good to me.

@Seldaek Would you prefer?

1. Two separated pages
2. Two separated section on a single page

I would :+1: for option 1.

In case of option 2, what name should we give to the concerned page?

**Comment by stof** [comment]
We should have 2 separate pages. Having 2 paginated lists on the same page is insane.

**Comment by cisso** [comment]
Any chance this information could be exposed via the JSON API as well?
Use case: I'm currently working on a web app that creates a graphical representation of package dependencies to help users find and explore implementations (among other things).
