### ISSUE TITLE
[Question] Does packagist have an API?

### ISSUE THREAD

**Issue by samayo** [composer/packagist#588]
I would like to know, if there is any way to find out if certain package exists using cURL. An example of request would be 
`http://api.packagist.org/package/samayo/bulletproof`
Which would result in a JSON format of the package's details (exists, date, download count .. ) if, not the JSON would return 404. 

I searched for this and could not find anything except for [KnpLabs/packagist-api](https://github.com/KnpLabs/packagist-api) which unfortunately, is a PHP-only solution.

**Comment by alcohol** [comment]
The API methods it has are located in the following file:

https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Controller/ApiController.php

Unfortunately, it seems "error" responses, such as a package not found, will still return a '200 OK' header actually. The response body will contain a JSON object which has a status propery that will have the value of "error".

@Seldaek is this where you learned your lesson about how **not** to do it? :P

**Comment by alcohol** [comment]
Aside from that, no, Packagist does not seem to offer any methods that match your use-case.

**Comment by stof** [comment]
https://packagist.org/packages/samayo/bulletproof.json does what you want

@alcohol the file you linked contains webhooks, for which a 200 is indeed returned to avoid the webhook call being retried.

**Comment by alcohol** [comment]
Ah ok, fair enough. I still think returning error codes is better though. Any proper service wouldn't retry an API if it received a 400 or 404 for example.

**Comment by stof** [comment]
Well, you should first check how the different webhook systems (github, bitbucket, gitlab, etc...) are behaving regarding retry.

**Comment by samayo** [comment]
@stofChristopheCoevoet Thanks. That is what I was looking for. One last question, is there a rate limit as to how many times per minute we can make a request to the server?

**Comment by alcohol** [comment]
Hopefully they properly support 503 in that regard :-)

**Comment by alcohol** [comment]
@samayo no limits are artificially imposed. But please be considerate.

**Comment by laudeon** [comment]
Hello,

I would like to know if there is any way to call packagist API without server-side language ? 
Actually, JSONP is not allow and CORS too. And I found only PHP client.

Kind regards!

**Comment by alcohol** [comment]
@Seldaek do you have any desire or intent to allow CORS on the API?

**Comment by Seldaek** [comment]
I don't have any desire or intent but I'm not really against it I guess..
We could add the NelmioCorsBundle and set it up for the few read-only api
urls.

**Comment by samayo** [comment]
While you are at it, could you guys make the API a bit readable? If you check the aesthetics between the
[Github API](https://api.github.com/repos/samayo/bulletproof) and the [Composer API](https://packagist.org/packages/samayo/bulletproof.json) you'll see the github API is more user-friendly to read, as it shows the JSON structure clearly.  

It is not important though, just a little bit nice to have if possible.

**Comment by alcohol** [comment]
We don't use pretty print, no. I think there would be little harm to doing that. But then again, you could just as well run your cURL output through any command line json beautifier, or use any of the various websites that a simple [Google search](https://www.google.com/search?q=json+beautifier) returns to  beautify the output.

**Comment by javiereguiluz** [comment]
I'm also interested in accessing the API via JSONP. Can we do something to help you make this possible? Thanks!

**Comment by Seldaek** [comment]
As I said in https://github.com/composer/packagist/issues/588#issuecomment-164134406 I'd be up for allowing CORS. JSONP is unnecessary these days IMO.

**Comment by samayo** [comment]
Can someone assign this to me? I am trying to get my hands on Symfony, and this will be the best incentive to for me. I can create a NelmioCorsBundle

**Comment by Seldaek** [comment]
@samayo I can't assign to people outside the organization sadly but if you say you'll do it go for it. See https://github.com/nelmio/nelmiocorsbundle
