### ISSUE TITLE
Site Search ( or composer search ) does not search

### ISSUE THREAD

**Issue by cedamorim** [composer/packagist#595]
When I try to do any research, it is always returned the same result (all records).

**Comment by rchouinard** [comment]
I'm experiencing the same. Looks like the changes to WebContoller in 46bc2d4 might have broken it.

**Comment by chlabelek** [comment]
Same. When typing, the search query is "q" instead of "tags".

**Comment by alcohol** [comment]
Cannot reproduce. Searching works just fine for me :\

**Comment by chlabelek** [comment]
Fixed indeed.
