### ISSUE TITLE
The package page is very slow

### ISSUE THREAD

**Issue by stof** [composer/packagist#597]
Loading the page of a package seems to take several seconds currently, which is not a good experience

**Comment by alcohol** [comment]
Can confirm. Consistently between 1.5 and 2 seconds for TTFB (time to first byte).

@seldaek anything modified on this page recently?

**Comment by Seldaek** [comment]
Seems to be a problem with the Dependents query cache. I'll investigate in a bit.

**Comment by Seldaek** [comment]
There you go, that was the feeling like an idiot moment of the day..
