### ISSUE TITLE
Getting repo watch and fork count in the API

### ISSUE THREAD

**Issue by samayo** [composer/packagist#602]
I realize that packagist now shows watchers, forks count but I am unable to find this in your API, is it not yet add to the API? 

Also, for example in packagist [samayo/bulletproof](https://packagist.org/packages/samayo/bulletproof) shows that the repo has 1 issue. But there is no issue in github [samayo/bulletproof](https://github.com/samayo/bulletproof) no matter how many times I update the packagist page, the issue remains.

**Comment by alcohol** [comment]
Packagist only fetches those changes from Github when it receives a notification/hook. You might be able to refresh this "1 issue" by using the "test trigger" functionality in Github. Not sure if that will really work though.

This data is indeed not in the API.

**Comment by samayo** [comment]
Hm, I just went to the webhook page for the repo in github, and sent a "test service" with success message "Okay, the test payload is on its way. " but no effect in packagist even after updating. Maybe it takes time. It would've been much better if the issue count was updated when an issue event is triggered in github. But, that it is ok.

**Comment by samayo** [comment]
The issue is still unresolved, could this be a bug?

**Comment by stof** [comment]
@alcohol I found the bug: the code uses ``if (!empty())`` to detect whether the info is returned by the github API. But ``0`` is empty in PHP. So it will never reset it to 0.

**Comment by samayo** [comment]
@stof  could you please share the link to that line here? thanks

**Comment by stof** [comment]
https://github.com/composer/packagist/blob/b6d88043ab900cb4c479800c797bcbde4e312a09/src/Packagist/WebBundle/Package/Updater.php#L479-L493

**Comment by Seldaek** [comment]
The empty bug was fixed in b48272af9a3bfcd0a88d0f1597cb528cd6ced10d, as for having them in the API I'm not sure if that's something we want to do to replicate the github API. You can easily fetch it from them.
