### ISSUE TITLE
Include Code Galaxies Visualization

### ISSUE THREAD

**Issue by theofidry** [composer/packagist#603]
Could we put a link to [anvaka.github.io for Composer](http://anvaka.github.io/pm/#/galaxy/composer?cx=-5048&cy=-11654&cz=-10363&lx=0.0871&ly=0.9062&lz=-0.3869&lw=-0.1466&ml=150&s=1.75&l=1&v=2015-09-21T01-00-00Z) somewhere on Packagist?

**Comment by alcohol** [comment]
The one you linked is not for composer.

**Comment by theofidry** [comment]
My bad, fixed

**Comment by Seldaek** [comment]
I think we could, but probably would need a resources page or something where we can link such third party things that are nice..

**Comment by Soullivaneuh** [comment]
@theofidry I remember of something like that but with code contribution history graph.... could not remember the name. :-/

**Comment by theofidry** [comment]
[Gource](http://gource.io/)?

Would be awesome to have it too, although completely useless :P

**Comment by Soullivaneuh** [comment]
> Gource?

Not sure. The one I was talked had a web interface for that AFAIK.

> Would be awesome to have it too, although completely useless :P

Useless so essential! :wink:
