### ISSUE TITLE
Proposal: Remove README expander and show the whole README by default

### ISSUE THREAD

**Issue by cstuder** [composer/packagist#607]
Currently Packagist.org only shows the first couple of lines of a README file and hides the rest behind an easy to miss expander button (grey-on-grey).

Example: https://packagist.org/packages/monolog/monolog

In my opinion, this unneccessarily hides informations from us users. I would propose to remove this functionality entirely. 

But before I submit a pull request doing so, I wanted to ask if there's a specific reason for the readme-expander feature.

**Comment by Seldaek** [comment]
In early testing of the feature I found that a lot of packages had extremely lengthy readmes and while it isn't very critical I find it a bit confusing to have a 3km long page without info, I like that I can now just jump to end of page and find the readme and then expand if needed.. Obviously usage patterns differ, and I am not quite sure which way is the overall best.

One easy compromise way would be to have a "always expand" link on the expander link that stores that preference in local storage, then it can be shown expanded for those that want it. I don't really like adding such customizations though as if we start I'm not sure where it'll end :)

**Comment by PeeHaa** [comment]
@Seldaek I for one don't use the "go to end of page" solution and I suspect neither do most people.

The auto collapser basically just hides useful information for not much gain. As I stated in the dupe the fact that the page gets long doesn't really matter I think (might have a bigger impact on mobile).

Nor do I care much about introducing an option for this.

**Comment by cstuder** [comment]
Awesome, thanks.

**Comment by PeeHaa** [comment]
\o/ Thanks @Seldaek!
