### ISSUE TITLE
[DriverException] Updating package with utf8_mb4 (emoji) characters

### ISSUE THREAD

**Issue by vitkutny** [composer/packagist#608]
Updating package https://packagist.org/packages/ytnuk/translation, broke by commit https://github.com/ytnuk/translation/commit/47a558e92d79abf72f12925b84fcacb1087b433a with emoji character (`\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8` = `🇺🇸`) in `extra` section of `composer.json`. Could be fixed by changing encoding of `extra` column from `utf8` to `utf8_mb4`

<img width="992" alt="snimek obrazovky 2015-11-29 v 17 34 08" src="https://cloud.githubusercontent.com/assets/4031169/11458445/53f37136-96c0-11e5-9b2a-c03335bb4878.png">

> [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'UPDATE package_version SET extra = ?, source = ?, dist = ?, updatedAt = ?, releasedAt = ? WHERE id = ?' with params ["a:2:{s:10:\"extensions\";a:2:{s:17:\"ytnuk.translation\";s:27:\"Ytnuk\\Translation\\Extension\";s:17:\"kdyby.translation\";s:41:\"Kdyby\\Translation\\DI\\TranslationExtension\";}s:17:\"kdyby.translation\";a:1:{s:7:\"default\";s:8:\"\ud83c\uddfa\ud83c\uddf8\";}}", "{\"type\":\"git\",\"url\":\"https:\\\/\\\/github.com\\\/ytnuk\\\/translation.git\",\"reference\":\"ec0ab04a33efcd65f550d4870a0b160b81d6e597\"}", "{\"type\":\"zip\",\"url\":\"https:\\\/\\\/api.github.com\\\/repos\\\/ytnuk\\\/translation\\\/zipball\\\/ec0ab04a33efcd65f550d4870a0b160b81d6e597\",\"reference\":\"ec0ab04a33efcd65f550d4870a0b160b81d6e597\",\"shasum\":\"\"}", "2015-11-29 16:43:42", "2015-11-29 16:35:51", 410779]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x87\xBA\xF0\x9F...' for column 'extra' at row 1

**Comment by alcohol** [comment]
I'm not even sure if we want to allow such characters. 
I'll leave this decision in the capable hands of @seldaek.

Personally I would recommend using a normal value such as '`en_US`'. Using an emoji is probably going to fail for people using editors such as vim from a command line interface.

**Comment by Seldaek** [comment]
I think we'll fix it to allow it just because well.. we shouldn't break, and json = unicode = allow everything. But no it's not an immensely good idea :p
