### ISSUE TITLE
Packagist doesnt detect my tags

### ISSUE THREAD

**Issue by wallacemaxters** [composer/packagist#609]
My github repository has 4 tags. But none of them are being detected as version in Packagist. Only dev-master is appearing.

He was appearing before ` 1.0.0` and `1.1.0`, but after I removed the, is only appearing `dev-master`. The other tags are being ignored

https://packagist.org/packages/wallacemaxters/timer

**Comment by stof** [comment]
Your 1.0.4 tag contains ``"version" : "1.1.0",`` in its composer.json, making the tag invalid (mismatch between the tag name and the version).
The recommendation is to never set an explicit version when your package lives in a git repo. It can only bring drawbacks

**Comment by wallacemaxters** [comment]
What can I do in this case?

**Comment by stof** [comment]
Remove the ``version`` from your composer.json and create a new release which will not be broken (don't re-tag the same version as this would lead to very weird issues for people who already cloned the repo with current tags, as git tags are not meant to be mutated)

**Comment by wallacemaxters** [comment]
I did it and it worked
