### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by Saurabh0X** [composer/packagist#612]
Hi,

Recently i have faced an issue on redis. Getting "NOAUTH Authentication required" message when trying to access redis server from redis client, the issue resolves itself when the service is restarted but it raises again after 4 to 5 hours. Please note that the requirepass is commented in the configuration file.

Redis Version: 2.8.9

Urgent help is required.

Thanks 
Saurabh

**Comment by alcohol** [comment]
Not sure why you are asking the Packagist developers about Redis issues...
