### ISSUE TITLE
Support Gitter link

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/packagist#615]
Gitter is growing and being used by a lot of open-source PHP projects.

As for irc, it would be nice to have a [Gitter.im](https://gitter.im) link support.

I could work on that if you are interested.

**Comment by alcohol** [comment]
Not sure what exactly you mean? Link from where to where? On what page?

**Comment by Soullivaneuh** [comment]
On the right box of this page, near IRC link: https://packagist.org/packages/phpbb/phpbb

This could be added on the `support` section of `composer.json` file.

Link sample: https://gitter.im/puli/issues

**Comment by Seldaek** [comment]
I don't think we have to automate this.. people can put it in the support.irc or support.forum IMO.. I doubt many projects have all 3. It's kind of an IRC replacement so pick the one you want to support as a project and that's that I think.

**Comment by Soullivaneuh** [comment]
I don't know if it's a good idea to put it on the irc section.

If one day we want to improve rendering with, for example, special links for IRC (`irc://`), this will be broken with Gitter link.

**Comment by Seldaek** [comment]
Well people can/should put irc:// URLs in the IRC thing if they want good linking IMO. It's the best way to represent a server+channel pair to be honest.
