### ISSUE TITLE
Emoji in package description breaks packagist

### ISSUE THREAD

**Issue by evert** [composer/packagist#622]
I added a 📅 in the description of my calendaring-related composer package. Manually hitting update on the packagist website yields:

    [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'UPDATE package SET description = ? WHERE id = ?' with params ["\ud83d\udcc5 The VObject library for PHP allows you to easily parse and manipulate iCalendar and vCard objects", 2671]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x93\x85 T...' for column 'description' at row 1

**Comment by staabm** [comment]
Duplicate of https://github.com/composer/packagist/issues/608 ?

**Comment by evert** [comment]
Ah yea possibly. I've leave it up to them to decide if it's the same bug =)

**Comment by alcohol** [comment]
Yeah it's a duplicate. It requires changing the database schema of Packagist, which is not something we can just do casually. But we are aware of the issue, and it will be fixed :)

**Comment by staabm** [comment]
@evert just to let you know. It seems the underlying issue was fixed

**Comment by evert** [comment]
cool! also released on packagist.org ?

**Comment by Seldaek** [comment]
Yup

**Comment by evert** [comment]
whoo!
