### ISSUE TITLE
Differentiating between Branches and Tags

### ISSUE THREAD

**Issue by colelloa** [composer/packagist#623]
Black Duck Software is interested in adding Packagist projects and versions to our KnowledgeBase to help the open source community (via https://www.openhub.net/) manage vulnerabilities and licenses in PHP packages. To add them, we need a way to distinguish between a branch and a tag for each version item in a package. 

For example, in https://packagist.org/packages/00f100/uuid.json , "4.x-dev”,
"2.8.x-dev”, and "dev-master” represent branches in the actual github account, while “4.0.0” and “2.8.4” represent tags. We would like to be able to tell the difference between a tag and a branch
without parsing the version name string, as that can be unreliable in edge cases.

Is there a way to use the Packagist API to get this metadata?

Best,
Andrew Colello
Software Engineer, KnowledgeBase Team
Black Duck Software

**Comment by Seldaek** [comment]
In the case of packagist, you can rely on the fact that `dev-` prefix or `x-dev` suffix means it's a branch. We don't allow tags with those (`-dev` is allowed but not `.x-dev`), and force those pre-/suffixes on all branches. I believe this covers all cases. You can also look at the version_normalized field which should start with `dev-` or end with `9999999-dev` for branches.

I don't think it's likely that we will provide some specific way to query this as it really doesn't serve any purpose on our end.
