### ISSUE TITLE
Don't hijack standard browser behavior when trying to select a package name

### ISSUE THREAD

**Issue by PeeHaa** [composer/packagist#626]
When going to [a package](https://packagist.org/packages/erusev/parsedown) and clicking on the package name or even worse trying to select just the name (without the require command) the default browser behavior (selecting just the highlighted text) is hijacked.

![select hijack](https://cloud.githubusercontent.com/assets/1330296/12020186/a121479c-ad79-11e5-8ea8-0744bd43a08a.png)

This is really annoying because I more often just need the package name instead of the `require` command. Overriding default browser behavior like that is really annoying.

I realize I could try selecting the text of the title instead, but I am conditioned to not being able to sanely do that, because it may be a link. Which is also the case here. Trying to select the text of the title may result in an accidental click instead.

I am willing to PR this as I assume it should be an easy "fix", but I want to make sure I am not the only one annoyed by this first.

**Comment by alcohol** [comment]
Instead of removing this behaviour all-together, I would prefer to see it replaced with a copy-to-clipboard icon/action :-)

**Comment by PeeHaa** [comment]
If there is demand for something like that I am willing to go that route.

**Comment by MadaraUchiha** [comment]
The problem with this kind of behavior (or even a copy-to-clipboard button) is that it's like a USB's Schrodinger situation. There's never a right way. The button will copy to clipboard *both* the entire command *and also* only the name, until I click on it, and then it'll be the one that I don't need. (similar to a USB connector being wrong on both sides, until observed)

Developers are not unfamiliar with the concept of copy/paste, and the UX benefit of keeping consistent behavior with the rest of the OS outweighs the potential help of a button (which comes with its own set of confusions)

**Comment by TazeTSchnitzel** [comment]
Huh, what? Such buttons are common in many sites and universally do one thing: copy the entire text.

**Comment by alcohol** [comment]
If you just want the name, you would be able to select it yourself. Currently that is not an option. So this solves the current issue while not really making things more inconvenient for everyone else.

**Comment by MadaraUchiha** [comment]
@TazeTSchnitzel For example, in GitHub, the button copies the entire git clone command. In BitBucket and Stash, it only copies the repo name.

**Comment by alcohol** [comment]
@MadaraUchiha we have stash here, when I go to clone, it simply shows a dialog in which it pre-selects the entire string/url to the source. There is no copy-to-clipboard action, nor does it show a full command anywhere. So not sure what you are referring to..

Either way, when done properly, a copy-to-clipboard button always clearly indicates what it will copy.

**Comment by MadaraUchiha** [comment]
@alcohol Personally, I much prefer the default behavior of <kbd>TRIPLE CLICK</kbd>, <kbd>CTRL</kbd>+<kbd>C</kbd>, muscle memory kicks in much easier. I don't really see the point of a copy button when you can just use the default features, as I don't see the UX benefit. 

On the other hand, I don't have a compelling argument or a particularly strong opinion against it either.

**Comment by Seldaek** [comment]
I feel like this is really an endless debate.. the feature was added as an easy way for people to get a full require command they can easily paste to grab that package. If you want the name you can triple click on the name. The vendor is linked/clickable as indicated by bold + pointer cursor, the rest of the name isn't and you can triple click there if you like.

I get that this annoys you but if we remove it it'll also annoy someone.. There is no right answer here so I'd say let's leave it as is.

**Comment by PeeHaa** [comment]
Could you please link me to said endless debate please? I tried to find it, but my search failed.

Also note that imo you could always cater for people who want to have a way to copy the entire string (e.g. the tripple click you mentioned or with a button somewhere). I realize that people may want to copy the entire `require` command, but instead of catering for those people the current solution removes *default and expected* functionality for every other user.

In the old interface that's actually [how it worked](https://github.com/Spea/packagist/commit/871ab0ee2e845d4c83006edf88167ca47a30f8fb) AFAICS (copy with a button).

> I get that this annoys you but if we remove it it'll also annoy someone.. There is no right answer here so I'd say let's leave it as is.

My point it that that just isn't needed. Because there are several solutions which don't override default browser behavior. So when you say there is no right answer here I don't see why there is chosen for the imo worst answer possible.

Maybe I am missing something here because I cannot seem to find the previous discussion about this so I will await your link to it so I can see what it is I am missing here.

**Comment by Seldaek** [comment]
I mean that reading this discussion wasted more of everyone's time here
than it would take you to just click the title instead of that require line
and then move on.. It's a tiny detail in the  grand scale of things and I'm
sorry you disagree with me but sometimes that's just life. Anyway I wish
you all a happy new year.
