### ISSUE TITLE
Two accounts synced with one GitHub account

### ISSUE THREAD

**Issue by stmswitcher** [composer/packagist#628]
Hello.

I've been logging in to Packagist woth my GitHub account, but my profile info was incorrent and I was unable to edit it 'couse there were no old password.
So, I've made a bad decision and registered a new account and synced it with the same GitHub profile and now I can change the profile but my package is not mine anymore.

Any way I can get it back to control it?

**Comment by Seldaek** [comment]
If you let me know which accounts these are I can transfer the package.

**Comment by stmswitcher** [comment]
Hello, Seldaek.
Thank you for your response.

Both accounts synced with my GitHub, but the packagist's profile names are `stm.switcher` and `stmswitcher`.

**Comment by Seldaek** [comment]
OK I transfered the package and deleted the old account so you can probably change your username back now if you like..
