### ISSUE TITLE
Oops! An Error Occurred on packages/submit

### ISSUE THREAD

**Issue by sdebacker** [composer/packagist#629]
Hello !
I got “Oops! An Error Occurred” when I tried to visit https://packagist.org/packages/submit

**Comment by sdebacker** [comment]
Changed title

**Comment by cheprasov** [comment]
Oops! An Error Occurred
    The server returned a "500 Internal Server Error".
    Something is broken. Please let us know what you were doing when this error occurred.
    We will fix it as soon as possible. Sorry for any inconvenience caused.

I see this error on next pages:
https://packagist.org/packages/submit
https://packagist.org/change-password

**Comment by Seldaek** [comment]
Fixed submit. Looking at change pwd.

**Comment by cheprasov** [comment]
Super! Thank you.

**Comment by sdebacker** [comment]
Thank you! Super.
