### ISSUE TITLE
Please tag packagist

### ISSUE THREAD

**Issue by aschleifer** [composer/packagist#631]
Hi everybody,

it would be really great if you could tag packagist and use some sort of release versions.

We run a packagist server in our company and at the moment we run on the master branch which breaks some times when you guys do changes at the config (like moving the solr defintions in the parameters.yml).

Best regards
Andreas Schleifer

**Comment by stof** [comment]
I suggest you to read the notice on https://getcomposer.org/doc/05-repositories.md#packagist

**Comment by Seldaek** [comment]
Yup, sorry but this is not something we have the manpower to support.
