### ISSUE TITLE
Can't submit new package or update existing packages from gitlab.com

### ISSUE THREAD

**Issue by wernerdweight** [composer/packagist#632]
If I go to https://packagist.org/packages/submit and try to submit this package: https://gitlab.com/WernerDweight/Microbe.git (using this URL) I'm only getting "undefined" as a response in a white flash message box at the top of the site.

This repo had been on packagist.org already but auto-update failed and manual update didn't work either (same "undefined" message had been shown), so I tried to delete the repo and submit it again but now I can't even submit it.

All my other submitted (3) repos that are hosted on gitlab.com can't be updated as I noticed later ("undefined" message again) (e.g. https://packagist.org/packages/wernerdweight/image-manager-bundle) but a repo of mine hosted on github.com seems to be updated correctly when I trigger manual update - so the problem is somewhere between packagist.org and gitlab.com but I don't know how to investigate further.

The auto-update last worked for me on 2015-12-30. Next change to the repo was made yesterday (2016-01-05).

**Comment by Seldaek** [comment]
Should be fixed now, I updated composer with gitlab support and things broke because I didn't have a gitlab API token set up for packagist  and it seems their API does not allow *any* non-authenticated access. Anyway that's fixed.
