### ISSUE TITLE
More case sensivity issues

### ISSUE THREAD

**Issue by RangelReale** [composer/packagist#633]
I saw all the previous package-name case sensitivity issues, and I understand it is better to use lowercase names.
But my user name is mixed caps, and I already have some projects that are used a lot (like a Go library, that is also imported by repo name), so I can't change it without breaking other things.

Couldn't it be only a warning, but not entirelly blocking it? Otherwise, I can't publish any of my projects to packagist.

**Comment by alcohol** [comment]
Why would you not be able to use lowercase?

**Comment by alcohol** [comment]
Sorry, didn't mean to close.

**Comment by RangelReale** [comment]
The internal package name can be different from the github url?

**Comment by Seldaek** [comment]
@RangelReale the package name is defined by composer.json's name property and that's all there is to it. Github URLs do not matter at all to packagist or package name in general, so no worries about your github username just update the name in the json file and try to submit the package again :)
