### ISSUE TITLE
Logged in only usage

### ISSUE THREAD

**Issue by Gisleburt** [composer/packagist#634]
For other installs (not packagist.org) it would be nice to prevent browsing / access without being logged in.

Example use case: Companies with propriatary code

Useful with #635

**Comment by stof** [comment]
I suggest you to read https://getcomposer.org/doc/05-repositories.md#packagist

Adding features not meant to be used on packagist.org makes the code much harder to manage (and likely to break things). For instance, there was a contribution in the past to allow having ldap auth on self-hosted deployments of packagist, but this code ended up breaking packagist.org.
