### ISSUE TITLE
Email mask and validation

### ISSUE THREAD

**Issue by Gisleburt** [composer/packagist#635]
For other installs (not packagist.org) it would be nice to allow people to only sign up if their email matches a given mask/masks, and for an email to be sent to that person to validate they are who they claim to be.

Example use case: Companies with propriatary code

Useful with #634

**Comment by Seldaek** [comment]
As said in #634, "other installs" isn't really something we want to actively support due to the time it takes. There are alternatives like https://toranproxy.com for private hosting.
