### ISSUE TITLE
Rename/redirect package

### ISSUE THREAD

**Issue by vanderlee** [composer/packagist#636]
I've got a package `vanderlee/php-stable-sort-functions` that was renamed `vanderlee/php-stable-sort` because it was changed to include a class as well as a set of functions.

Is it possible to rename or redirect the old package to a new package?

**Comment by Seldaek** [comment]
If you really want, you can rename it in composer.json and submit it again to packagist, then mark the current one as abandoned and point people to the new name. There is no way to rename per se.
