### ISSUE TITLE
Packagist not showing pushed tag

### ISSUE THREAD

**Issue by mcafee-secure** [composer/packagist#638]
**Packagist repository**
https://packagist.org/packages/mcafeesecure/module-mcafeesecure

**GitHub repository**
https://github.com/mcafee-secure/mcafee-secure-magento2

I pushed tag 0.0.1 to GitHub but, for some reason, the tag is not showing up in packagst.org. Am I doing something wrong? I tried creating a dummy commit and pushed to origin master but still no go.

**Comment by alcohol** [comment]
You should never put the `"version"` attribute inside your `composer.json`.

**Comment by mcafee-secure** [comment]
Thanks Rob. I have removed the `version` attribute from `composer.json`

**Comment by Seldaek** [comment]
Tag is importing fine now :)

**Comment by mcafee-secure** [comment]
Thanks @Seldaek I am wondering what I did wrong here or what you did to get it working?

I just pushed another tag and it is not showing up again in packagist.

**Comment by Seldaek** [comment]
Do you have the github hook set up properly? Because it seems like it didn't update since yesterday.

**Comment by mcafeesecure** [comment]
Yes I am pretty sure it's hooked properly. I got it working by refreshing the github endpoint in packagist.

**Comment by Seldaek** [comment]
Then I'm not sure why it wouldn't work.. I guess if you press the update button on packagist it'll work, but that's exactly the same as what the github hook does really.

**Comment by mcafeesecure** [comment]
I'll try again next time I release tag and I'll let you guys know if the same problem comes up. Thank you very much for the help though :+1:

**Comment by alcohol** [comment]
When you tag, don't put the version in the composer.json either. Just tag, nothing more is required.

**Comment by Seldaek** [comment]
@alcohol they didn't do that though. I believe what might have happened is that you pushed the tag alone after pushing the commits. That unfortunately doesn't trigger the hook so packagist won't update until next time you push a commit. The best is to `git push origin master --tags` to push both tag and commits at once when you release.

**Comment by mcafeesecure** [comment]
@Seldaek , @alcohol is right. I had the `version` attribute in `composer.json` previously. However, I had removed after being told that it's not necessary.

**Comment by Seldaek** [comment]
Yeah but you removed it before 0.0.2 and it still didn't work so it must 
be something else no?

**Comment by McAfeeSECURE** [comment]
I see. Well, this is how my webhook looks like. Let me know if I am doing anything wrong. I am leaving the domain field blank.

http://prntscr.com/9tgkw9

I sent a test request (as seen in the screenshot) to packagist and I am not seeing the latest commit hash.

**Comment by McAfeeSECURE** [comment]
I just created tag 0.0.3 and it appears to be working properly now.
