### ISSUE TITLE
Auto update sometimes misses a commit

### ISSUE THREAD

**Issue by integratedforpublishers** [composer/packagist#640]
Sometimes, I think about 30% of the time, my repositories at https://packagist.org/packages/integrated/ are not updated when pushing a commit. For the other 70% it works fine.

All repositories have the hook enabled. A part of the repo's is on Bitbucket (POST hook), another part on Github (GitHub service hook). The problem occurs with both Bitbucket and Github.

When I click Update manually it is updated fine.

The strange thing is that no other user reported this problem. I have the problem for many months now. I first thought that when we would move from Bitbucket to Github the problem would disappear, but it didn't.

**Comment by HillLiu** [comment]
I always need do manually update (click update button on packagist).

Is there anything wrong?
