### ISSUE TITLE
Can't submit new gitlab repository

### ISSUE THREAD

**Issue by Garbee** [composer/packagist#643]
I am attempting to submit a new package [hosted on gitlab](https://gitlab.com/garbee/Token-Generator). However, every attempt using either the ssh or https URL yields, "Package name could not be found in composer.json...." error message. Using `composer validate` my composer.json checks out and there is only a `master` branch. So there is nothing clearly awry here.

Did something go wrong with gitlab integration? Or is there an obvious mistake in my repo that I am unable to see?

Thanks,
-Garbee

**Comment by Garbee** [comment]
Taking a look into this more this morning, it seems gitlab's API has a bug somewhere. The content length being returned is wrong which is causing the API calls themselves to fail.

I'll try to find the right place on Gitlab's end to report this.

**Comment by danstreeter** [comment]
Hey, Did you raise this elsewhere? I'm also having the same issue which is bugging me no end!

**Comment by Garbee** [comment]
Yes, I raised it with Gitlab directly however that issue was ignored it seems. The very next deployment they did fixed the issue on their end.

https://gitlab.com/gitlab-org/gitlab-ce/issues/13449

**Comment by danstreeter** [comment]
Agh, that might make sense - do you know what RC version it was fixed in, I might have to uplift our GitLab server to that version (or more recent) to bring the fix in.
Did you get it fixed?

**Comment by Garbee** [comment]
I don't remember the exact one. Check whichever version was released about 4-5 months ago.

**Comment by danstreeter** [comment]
No problem, thanks for your help - updated GitLab today to the latest version available and our private Packagist server now talks to it no problem =)
