### ISSUE TITLE
Abandoned package phine/sami-github

### ISSUE THREAD

**Issue by nochso** [composer/packagist#645]
https://packagist.org/packages/phine/sami-github points to https://github.com/kherge-abandoned/sami-github which is abandoned.

Instead there's one fork with a 3 month old commit at https://packagist.org/packages/devedge/sami-github https://github.com/ppetermann/sami-github

I didn't see anything about how to report this, hoping this is ok.

**Comment by stof** [comment]
Well, you should contact the maintainer of the first package, to ask him yo explicitly mark the package as abandonned on Packagist, with the other package as a replacement.

**Comment by nochso** [comment]
Ok, he's got an email. I feel old.
