### ISSUE TITLE
New release not appearing

### ISSUE THREAD

**Issue by balbuf** [composer/packagist#649]
Hello!

I'm not sure why, but my most recent release is not recognized by packagist: https://packagist.org/packages/balbuf/composer-wp. I have the GH hook set up to report updates and have also tried manually updating. Packagist is actually up-to-date in terms of my recent commits to master, though the latest release remains absent. Is there an issue with this release that might cause it to be ignored?

**Comment by balbuf** [comment]
I tried tagging another release and that doesn't want to show up either. :anguished:

**Comment by Seldaek** [comment]
You have `"version": "1.0.0"` in your composer.json, so as this mis-matches the tag names the tags get ignored. It's recommended to just drop that field entirely as it will avoid accidental inconsistencies.

**Comment by balbuf** [comment]
:facepalm: I did not mean to have that in there... Thank you, @Seldaek!
