### ISSUE TITLE
Some values in the X axis of the download stats overlap

### ISSUE THREAD

**Issue by javiereguiluz** [composer/packagist#651]
This visual glitch is only visible in the last values of the X axis:

![stats_glitch](https://cloud.githubusercontent.com/assets/73419/13805704/1cfc1020-eb57-11e5-938a-a48c6e6e2511.png)

**Comment by Seldaek** [comment]
Yes. :p

Not really worth the time to fix such detail IMO, it's just the stats page nothing extremely critical, but if you wanna do it go for it.

**Comment by javiereguiluz** [comment]
Closing it because I won't be able to fix this in the near term. I'm sorry.
