### ISSUE TITLE
package "cross-solution/bootstrap3-dialog" was deleted by mistake

### ISSUE THREAD

**Issue by cbleek** [composer/packagist#654]
we accidentally removed the "cross-solution/bootstrap3-dialog" package.

is it possible to re-add it?

regards

Carsten

**Comment by Seldaek** [comment]
As far as I can tell it is present.. so I guess you figured it out yourself?

**Comment by cbleek** [comment]
Hi Jordi,

I can see the package on packagist.org. But I cannot install it anymore 
via composer.

I get the exception

[InvalidArgumentException]
Could not find package cross-solution/bootstrap3-dialog at any version 
for your minimum-stability (stable). Check the package spelling or your 
minimum-stability

I'm afraid that's because we accidentally removed the package from our 
"my packages" list on packagist.org.

Regards,

Carsten

Am 26.03.2016 um 09:28 schrieb Jordi Boggiano:
> As far as I can tell it is present.. so I guess you figured it out yourself?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/composer/packagist/issues/654#issuecomment-201734254>
>


-- 
Cross Solution           | Carsten Bleek
Diemelstraße 2-4         | Tel: 069-71910361 
<http://phone-cb.hq.cross/command.htm?number=06971910361&outgoing_uri=>
60486 Frankfurt am Main  | Fax: 069-71910369 
<http://phone-cb.hq.cross/command.htm?number=06971910369&outgoing_uri=>
http://cross-solution.de | bleek@cross-solution.de

**Comment by Seldaek** [comment]
As the error message tells you, it's because the minimum-stability (stable) excludes the package.. as it's only available in a dev-master version. I don't know why it worked before, maybe you had tags that you deleted or something?
