### ISSUE TITLE
Open search results in new tab

### ISSUE THREAD

**Issue by rudiedirkx** [composer/packagist#656]
While searching you can use up/down/enter to navigate search results. Since the selected search result isn't a real link, you can't use normal link properties like focus, enter to open, ctrl+enter to open in new tab etc.

I suggest at least adding ctrl+enter support, because it's very useful (and for me common) to open several packages that look alike.

Shouldn't be too hard to put that in here:

```
if (keymap.enter === event.which && currentSelected.data('url')) {
    window.location = currentSelected.data('url');
    return;
}
```

**Comment by rudiedirkx** [comment]
Location in [search.js](https://github.com/composer/packagist/blob/5f431c77e1f55308f591400abf93f9590ae05c1d/src/Packagist/WebBundle/Resources/public/js/search.js#L132)

**Comment by Seldaek** [comment]
If you want to send a PR for ctrl+enter support that sounds ok to me.

**Comment by rudiedirkx** [comment]
Pull request: #657
