### ISSUE TITLE
Private repo for User and Organizations

### ISSUE THREAD

**Issue by Webysther** [composer/packagist#662]

**Comment by Seldaek** [comment]
Any details here? https://toranproxy.com is available as a self-hosted way to host private repos.

**Comment by Webysther** [comment]
Yes, I know, but I am suggesting to have a paid version to resolve recursively, and can manage more broadly organizations, as github or hut.docker.

**Comment by Webysther** [comment]
Not only recursively, but offer all the infrastructure for a modest value, facilitating enough for small startups, perhaps?

**Comment by Webysther** [comment]
The proxy be paid does not make much sense to me, with all due respect. The biggest problem is sometimes the need to have a comfortable interface to many private projects, solve them by composer (using token?) already solves much of the problem, mainly because the composer does a great job when it comes to cache.

**Comment by alcohol** [comment]
Maybe you should list your actual requirements? Right now I am not certain what you are looking for, but it looks to me like you simply do not understand what Toran proxy can offer you. I am willing to bet it will tick most (if not all) of your requirement boxes.

**Comment by Seldaek** [comment]
I think it's pretty clear that setting up a server and so on is more work than just registering to some online service. I get that, and I have started work on a SaaS version, but I don't like to talk about it too much until it's done because my free time to work on this isn't always huge and so progress is hard to estimate into a clear timeline.

**Comment by Webysther** [comment]
Yes, that's it. I hope not too long, the community will be greatly favored and this can reduce the time to develop more ambitious projects. Good luck and thanks!

**Comment by Webysther** [comment]
PSC @cmsouza

**Comment by Seldaek** [comment]
@Webysther just launched this btw - https://packagist.com/ :)
