### ISSUE TITLE
PHP requirement appears twice

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/packagist#671]
Concerned package: https://packagist.org/packages/sonata-project/core-bundle#3.x-dev

Actual composer.json: https://github.com/sonata-project/SonataCoreBundle/blob/3ca8af7ea38f898e485ce273960830cf0d15b72b/composer.json#L19

Screenshot:

![selection_818](https://cloud.githubusercontent.com/assets/1698357/15074397/0ea6c478-139f-11e6-84c3-7a8fdf32992d.png)

This is very weird... did you already have this issue?

**Comment by alcohol** [comment]
I don't see it. :<

**Comment by curry684** [comment]
Probably a fluke, doesn't happen here either. Don't know how the requirements are processed in the database/redis but you may have just pressed F5 at a terribly bad microsecond  :smile:

**Comment by Soullivaneuh** [comment]
> you may have just pressed F5 at a terribly bad microsecon

It was here even after several F5. :wink: 

But indeed, not here now. :+1:
