### ISSUE TITLE
Link to the existing packages under a vendor during package submission displays the HTML

### ISSUE THREAD

**Issue by nesl247** [composer/packagist#672]
As you can see, the anchor HTML is being displayed instead of rendered.

![image](https://cloud.githubusercontent.com/assets/1037526/15117095/f9eba314-15d3-11e6-8ae8-5eda3edf20d9.png)

**Comment by stof** [comment]
well, previously, it was a working link. @Seldaek this is broken by https://github.com/composer/packagist/commit/bdf750160429b4d32f689ebeed372e117306e91a

**Comment by Seldaek** [comment]
Oh. Yes indeed. I'll see what I can do.

**Comment by stof** [comment]
basically, packagist was relying on being able to XSS itself :smile:

**Comment by Seldaek** [comment]
Yeah the problem was if people entered stuff in the URL it didn't get escaped so they could attack themselves which isn't extremely dangerous but I thought I'd fix it to avoid further "security" reports.
