### ISSUE TITLE
Fake Sonata doctrine-mongodb-admin-bundle package

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/packagist#673]
This package is a fake of `sonata-project/doctrine-mongodb-admin-bundle`: https://packagist.org/packages/sonata/doctrine-mongodb-admin-bundle

The GitHub repository is exactly the same as our.

Should not Packagist have a unique database rule against package repositories?

Could you remove this? AFAIK, there is no "report" section on Packagist. If I'm wrong, sorry for that. :-)

cc @rande

**Comment by stof** [comment]
I don't even understand how this package went there, as Packagist reads the package name from the github repo, and the package name in the repo is not ``sonata/*`` but ``sonata-project/*``

**Comment by Seldaek** [comment]
@stof you can change the package name or the repo URL after submitting.. not that hard.

@dizda can you maybe explain why you did this?

I marked the package abandoned for now.. it doesn't seem to be installed in the last six months though so probably safe to delete.

**Comment by Soullivaneuh** [comment]
> you can change the package name or the repo URL after submitting.. not that hard.

Maybe can we add a check at this point?

**Comment by Seldaek** [comment]
No otherwise that would prevent renaming with a smooth transition.

**Comment by dizda** [comment]
Hello guys,

I forked this bundle long time ago, dunno why I became the maintainer on the official's one?

**Comment by Seldaek** [comment]
it's not the official one.. but anyway ok looks like it was a mistake and it's unused now so I'll just delete it :)

**Comment by dizda** [comment]
Alright, sorry about that 👍
