### ISSUE TITLE
New version of package not showing up

### ISSUE THREAD

**Issue by ddelnano** [composer/packagist#675]
I published a new version of my package yesterday and still have not seen it show up on packagist.  Here is my package [page](https://packagist.org/packages/ddelnano/dredd-hooks-php).  So I am wondering how long do I need to wait before the package becomes available?  I have never had to wait over 24 hours before.

**Comment by ddelnano** [comment]
Just showed up, closing this.

**Comment by Seldaek** [comment]
I force-updated it using the "update" button in the UI and it appeared immediately.. so it might have just been bad luck that it failed the update once. It rarely happens but it's definitely possible and right now we don't handle failures very well.

**Comment by ddelnano** [comment]
Ah I didn't know there was an update button.  Now I will know if this happens in the future, thanks
