### ISSUE TITLE
[InvalidArgumentException] Entity has to be managed or scheduled for removal for single computation 

### ISSUE THREAD

**Issue by JanTvrdik** [composer/packagist#677]
Invoking update of https://packagist.org/packages/nextras/mail-panel results in error

> [InvalidArgumentException] Entity has to be managed or scheduled for removal for single computation 

![image](https://cloud.githubusercontent.com/assets/175109/15334293/dcd8719e-1c6d-11e6-90eb-0e1a8b4693e9.png)

---

I pushed today stable `v2.3.0` tag pointing to the same commit as the last RC tag `v2.3.0-rc1`. Unfortunately packagist did not register the new release, so I tried force removing the `v2.3.0-rc1` tag from GitHub and corresponding release from packagist but that did not help. Invoking the update manually results in the aforementioned error. I since pushed the `v2.3.0-rc1` tag back on GitHub.

**Comment by Seldaek** [comment]
Gonna try and fix this soon, please don't touch anything if you can wait a bit :)

**Comment by Seldaek** [comment]
OK it's back on track.. sorry for the trouble.

**Comment by JanTvrdik** [comment]
:+1: Thank you for the quick solution!
