### ISSUE TITLE
Remove CORS in API (https://packagist.org/packages/vendor/name.json)

### ISSUE THREAD

**Issue by datitisev** [composer/packagist#678]
Because Packagist doesn't have the __Access-Control-Allow-Origin: *__ header, I can **NOT** use the Packagist **API** via JavaScript, and have to use the back end instead.

Is this **desired** behavior, or should it behave **otherwise**?
Thank you.

**Comment by Seldaek** [comment]
Without CORS you can also not use it. Maybe the problem is that this
particular route isn't allowed in the CORS config, I'll check later, but
having no CORS header is not gonna help you.

**Comment by datitisev** [comment]
@Seldaek Sorry, it was my fault. I was passing an "unsecure" header to the request, and that is what didn't let me, although I don't understand why the error was the Access-Control-Allow-Origin header...

Sorry about this.
