### ISSUE TITLE
Auto-update with github doesn't work

### ISSUE THREAD

**Issue by Defcon0** [composer/packagist#679]
Hello folks,

auto updating worked for a time quite well. But for some of our moduls it simply doesn't anymore even if I think I did everything just fine. The module is

https://packagist.org/packages/heimrichhannot/contao-submissions

Are you having a bug here at the moment?

**Comment by stof** [comment]
Well, this module is uptodate compared to the commit in github

**Comment by Defcon0** [comment]
I'm affraid to tell, but the module is only updated because I did it manually. I even deleted the corresponding github repo and recreated it again. That's why 1.0.9 is the first version. But the auto update error message still is visible in the packagist page for the module:

https://packagist.org/packages/heimrichhannot/contao-submissions

Also at the moment I get 502 and even 504 error again :-(

**Comment by Seldaek** [comment]
Yeah we've had some issues with APCu segfaulting, which probably lead to a few package update requests getting lost. Sorry about that.
