### ISSUE TITLE
[ErrorException] Illegal offset type in isset or empty

### ISSUE THREAD

**Issue by k-gun** [composer/packagist#680]
Hi,

I am trying to update [froq/froq](https://github.com/froq/froq) lib. on Packagist but getting this error;

```
[ErrorException] Illegal offset type in isset or empty
Reading composer.json of froq/froq (v1)
Importing tag v1 (1.0.0.0)
Reading composer.json of froq/froq (1.0.17)
Importing tag 1.0.17 (1.0.17.0)
Reading composer.json of froq/froq (1.0.16)
Importing tag 1.0.16 (1.0.16.0)
Reading composer.json of froq/froq (1.0.15)
Importing tag 1.0.15 (1.0.15.0)
Reading composer.json of froq/froq (1.0.14)
Importing tag 1.0.14 (1.0.14.0)
Reading composer.json of froq/froq (1.0.13)
Importing tag 1.0.13 (1.0.13.0)
Reading composer.json of froq/froq (1.0.12)
Importing tag 1.0.12 (1.0.12.0)
Reading composer.json of froq/froq (1.0.11)
Importing tag 1.0.11 (1.0.11.0)
Reading composer.json of froq/froq (1.0.10)
Importing tag 1.0.10 (1.0.10.0)
Reading composer.json of froq/froq (1.0.9)
Importing tag 1.0.9 (1.0.9.0)
Reading composer.json of froq/froq (1.0.8)
Importing tag 1.0.8 (1.0.8.0)
Reading composer.json of froq/froq (1.0.7)
Importing tag 1.0.7 (1.0.7.0)
Reading composer.json of froq/froq (1.0.5)
Importing tag 1.0.5 (1.0.5.0)
Reading composer.json of froq/froq (1.0.4)
Importing tag 1.0.4 (1.0.4.0)
Reading composer.json of froq/froq (1.0.3)
Importing tag 1.0.3 (1.0.3.0)
Reading composer.json of froq/froq (1.0.2)
Importing tag 1.0.2 (1.0.2.0)
Reading composer.json of froq/froq (1.0.1)
Importing tag 1.0.1 (1.0.1.0)
Reading composer.json of froq/froq (1.0.0)
Importing tag 1.0.0 (1.0.0.0)
Reading composer.json of froq/froq (master)
Importing branch master (dev-master)
```

Before this error I was getting an extra info such `Skipped tag 1.0.6, Array to string conversion` and I removed `1.0.6` tag from Github but still seeing this error.

Thank you.

**Comment by Seldaek** [comment]
Huh, strange, but thanks I'll look into it in a bit.

**Comment by k-gun** [comment]
Yes! 
http://i.imgur.com/Ta84SwR.png

**Comment by gomboc** [comment]
I got the same error for g4/log package.

http://www.awesomescreenshot.com/image/1282674/a8d32baa0dd1de1307b6b4c654739e60

**Comment by clue** [comment]
Same problem here for [clue/redis-react](https://packagist.org/packages/clue/redis-react): http://imgur.com/cBCJ8cv

The latest tag (v1.0.0) is listed on Packagist, but somehow doesn't end up in its JSON files, so downloading this version doesn't work with Composer. (disregarding custom repos here)

In my case, all earlier tags work just fine, even the one that's been released only a few minutes before the broken one.

**Comment by k-gun** [comment]
Hello,  is there any progress?

**Comment by Seldaek** [comment]
The update is fixed now, sorry folks for the delay, been quite busy :/

**Comment by clue** [comment]
Thanks for the fix @Seldaek, I can confirm this is now resolved for my project :+1:

**Comment by k-gun** [comment]
Yes! Thank you @Seldaek  +1.
