### ISSUE TITLE
The package name is invalid

### ISSUE THREAD

**Issue by kaduamaral** [composer/packagist#681]
I sent a package KaduAmaral/ConnectionPDO with success, now I'm trying to send the package KaduAmaral/Base and the site is saying:

> The package name KaduAmaral/Base is invalid, it should not contain uppercase characters. We suggest using kadu-amaral/base instead.

![packsubmit](https://cloud.githubusercontent.com/assets/4316607/15710139/047fda80-27df-11e6-9d65-5c457ed2a853.png)

**Comment by Seldaek** [comment]
As you can see, https://packagist.org/packages/kaduamaral/connectionpdo is all lowercase, so adjust the name in the composer.json for the new package and it will be fine, just like the message tells you..

**Comment by kaduamaral** [comment]
Solved with the [answer of issue 547](https://github.com/composer/packagist/issues/547#issuecomment-121286062).
