### ISSUE TITLE
Invalid constraint?

### ISSUE THREAD

**Issue by sagikazarmark** [composer/packagist#682]
For some reasons the following package generates the following error in packagist update hook:

https://github.com/indigophp/sonata-admin-print-bundle

```
Reading composer.json of indigophp/sonata-admin-print-bundle (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
require.sonata-project/admin-bundle : invalid version constraint (Could not parse version constraint  ^3.0: Invalid version string " ^3.0")
```

The constraint: https://github.com/indigophp/sonata-admin-print-bundle/blob/master/composer.json#L16

**Comment by stof** [comment]
This issue should be closed, as it looks like garbage

**Comment by sagikazarmark** [comment]
Sorry, accidentally submitted it without description

**Comment by Seldaek** [comment]
You got a non-breaking space in the require that makes it invalid..

```
$j = json_decode(file_get_contents('https://raw.githubusercontent.com/indigophp/sonata-admin-print-bundle/master/composer.json'), true);

var_dump(ord(utf8_decode(substr($j['require']['sonata-project/admin-bundle'], 7, 2)))); 
// 160 = nbsp
```

Try typing it from scratch :)

**Comment by sagikazarmark** [comment]
LOL, thanks.
