### ISSUE TITLE
Incorrect dependents list

### ISSUE THREAD

**Issue by aik099** [composer/packagist#683]
The https://packagist.org/packages/console-helpers/svn-buddy#dev-master uses https://packagist.org/packages/console-helpers/db-migration#v0.1.0 , but later package isn't showing that it has 1 package depending on it.

Maybe dependent packages are only collected from stable versions of other packages and not `master` branches.

**Comment by Seldaek** [comment]
We cache these listings for a week as the queries are a bit heavy so it should show up within a few days.

**Comment by aik099** [comment]
Will keep that in mind. Thanks.

**Comment by mindplay-dk** [comment]
Do packages that *were* dependencies (but not longer are, e.g. in latest tagged release) get removed from the dependents list or not?

(we're a team trying to deprecate a package with lots of dependents - we're trying to use the `/dependents` listing for that package to assess whether all other packages have moved away from it so we can abandon it...)

**Comment by Seldaek** [comment]
@mindplay-dk they will but they're also subject to this 1week cache. The dependent list only checks development versions, so as soon as a dependency is removed from all branches of a package, it'll stop appearing as a dependent.

**Comment by mindplay-dk** [comment]
> as soon as a dependency is removed from all branches of a package, it'll stop appearing as a dependent

I was hoping that was the case - thanks! :-)
