### ISSUE TITLE
API - Get Vendor List with limit

### ISSUE THREAD

**Issue by mtangoo** [composer/packagist#686]
First I was shocked to find that packagist have official API. Its a nice thing for us who would love to make graphical stuffs instead of commandline when dealing with packages. Its good news, thank you.

I find searching by vendor needs exact name. It would be nice for it to search like it does for packages. It would be great to actually have all searches behaving like search by package name.

Another thing in same issue is putting limit on results. it would be nice to specify the API to fetch 5 results for example something like

`GET https://packagist.org/search.json?q=[query]&l=10` 

TIA

**Comment by Seldaek** [comment]
You can use the per_page parameter to limit, for example https://packagist.org/search.json?q=test&per_page=5

**Comment by mtangoo** [comment]
Wow didn't know that. Does it work for all queries?

**Comment by Seldaek** [comment]
Nope, which other are you interested in?

**Comment by mtangoo** [comment]
We have only four api search as per docs. If it is possible having it in all of them will be nice.  
- List packages by organization
- Search packages by tag
- Search packages by name
- Get a package by name

**Comment by Seldaek** [comment]
Well the two search ones support it, the list's only point is to get the full list IMO, and the package name is a single package so I don't really see where else we need the per_page thing :)

**Comment by mtangoo** [comment]
Oh forgive me about the last one. You're right no paging is needed. As for listing, you're right also but I think we need search also.

You see if you type full vendor name that's is not the problem. But sometimes all you remember is half of the name. So it'll be good to be able to search by vendors too. 

Other than that,  I think only searches need paging. Sorry for inelaborate post. I now understand I didn't clarify well what I was asking here. :)
