### ISSUE TITLE
Search is too... fuzzy!?

### ISSUE THREAD

**Issue by stayallive** [composer/packagist#689]
When looking for (for example) `laravel/framework` (or `doctrine/dbal`) I got some dude's Laravel fork instead of the actual thing on top of the results... this seems unwanted and potentionally dangerous.

It would be nice I think if you do `laravel/` you get results with that "namespace" first. When searching for `facebook/php-sdk-v4` I get correct top result but the facebook results are a bit pushed down because other packages mention `facebook` & `sdk`.

![screen shot 2016-06-17 at 09 26 46](https://cloud.githubusercontent.com/assets/1090754/16143588/f78d72c4-346d-11e6-8db6-192b9ccec8b3.png)

**Comment by alcohol** [comment]
I think it would be nice if by default, downloads and stars affect the score of search results. This would hopefully push more relevant results more to the top.

**Comment by Soullivaneuh** [comment]
> I think it would be nice if by default, downloads and stars affect the score of search results. This would hopefully push more relevant results more to the top.

Maybe, but name matching is not correct in any case IMHO.

If the user search `laravel/framework` and a package has exactly the same name, it should be the first result.

**Comment by Soullivaneuh** [comment]
> It would be nice I think if you do laravel/

Nice idea. Should not be so hard to do, all package names have the same format: `<vendor>/<package>`.

**Comment by stayallive** [comment]
I think it should be namespace first and then star / downloads in scoring each item.

Or if that is not an option stars/downloads should be counted heavy in the score although I think it's more fair to have the name be a little less fuzzy (for authors that have a very new package that might not show up if the search is purely star/download scored).

**Comment by mindplay-dk** [comment]
I think the real problem is the search function combines search terms with `OR` by default - it's the opposite of most other search engines, which combine terms with `AND` by default.

Most users probably expect to narrow down their search when they enter more search terms - instead you get more results when adding more terms, which doesn't really make sense.

Search engines that do resort to `OR` searches, usually do so after attempting an `AND` search first, then display a notice at the top of the search results, like "we found no results matching all of those terms, here are results matching some of those terms instead."

**Comment by curry684** [comment]
> I think it would be nice if by default, downloads and stars affect the score of search results.

Its effects would have to be corrected for recency, ie. last 3 months, or 6 months declining. Packagist is full of abandoned or outdated projects with tons of stars and downloads... in 2014.

Also yeah, the default `OR` is pretty wacky, I've run into those issues as well - adding terms nearly always causes (much) worse results.

**Comment by stof** [comment]
@Seldaek @alcohol Search has been reimplemented fully a few months ago, so I suggest closing this issue related to the old search engine.

**Comment by Seldaek** [comment]
True
