### ISSUE TITLE
Vendor name reserved by account

### ISSUE THREAD

**Issue by TamTamDevTeam** [composer/packagist#690]
Hi,

We made a package with tamtam as vendor name. But the account was a personnal account. So we created another account (TamTamDevTeam) for a new project which will be the only place to store the package from the vendor tamtam which is my company name.

The problem is that as we have a package named tamtam/helpers-bundle in the personnal account, i can't take the vendor name for my new project.

Can you delete tamtam/helpers-bundle so i can reimport it in the new account and create other project with this vendor name.

This will not break anything because i will reimport tamtam/helpers-bundle in the new account as soon as i can.

Or can you move it to the new account directly ?

Thanks in advance

**Comment by stof** [comment]
Add this new account as a maintainer on the existing package, and it will then have access to this vendor name (you need to connect with the personal account to manage maintainers of the existing package)

**Comment by TamTamDevTeam** [comment]
Thank you, it does exactly what we wanted. 

Our package is now in the good account.

Thanks
