### ISSUE TITLE
Details about server errors were reported when I submit a new package

### ISSUE THREAD

**Issue by halaei** [composer/packagist#691]
I was submitting a new package (halaei/html) that I see a pop-up alert showing an error. It was something about doctrine and I guess it has codes in it. It disappeared after a few second, so I can't remember what the content was.
I am wondering if it can be a security issue, because I am not sure what was in that alert. Maybe some password?

**Comment by Seldaek** [comment]
Thanks for the report but this is by design, as the code is open source there isn't much to be hidden.
