### ISSUE TITLE
Stargazers, Watchers, Forks URLs wrong if repo url ends '.git'

### ISSUE THREAD

**Issue by giggsey** [composer/packagist#695]
For example: https://packagist.org/packages/giggsey/libphonenumber-for-php

When I created the package, I used the full git URL: https://github.com/giggsey/libphonenumber-for-php.git

As a result, the GitHub links for Stars, Watchers & Forks go to https://github.com/giggsey/libphonenumber-for-php.git/stargazers

I can easily sort this by removing the .git from the URL, but I feel Packagist should handle this automatically.

**Comment by Seldaek** [comment]
Thanks, I fixed the records in the DB and made sure this doesn't happen in the future https://github.com/composer/packagist/commit/b0ab24bd4df1a467b6cf6fff4bb2dbc3b6c89af6
