### ISSUE TITLE
Download stats graph: Y-axis has incorrect/duplicate labels

### ISSUE THREAD

**Issue by colinodell** [composer/packagist#696]
Something doesn't seem right here:

![image](https://cloud.githubusercontent.com/assets/202034/16401574/996b97e0-3cb3-11e6-865d-28f5d6ac973b.png)

https://packagist.org/packages/league/commonmark/stats

**Comment by Seldaek** [comment]
It's just due to the slightly greedy rounding.. It's 1.2K and 1.4K really. Feel free to PR improvements :)

**Comment by Dumkaaa** [comment]
@Seldaek @colinodell 
Guys, I fix that. check please #703
