### ISSUE TITLE
Packagist Data Dumps?

### ISSUE THREAD

**Issue by bshaffer** [composer/packagist#697]
Is there a way to get a Packagist data dump (a la [rubygems](https://rubygems.org/pages/data))? The use case is running queries on said data without destroying the Packagist API.

**Comment by stof** [comment]
There is no such feature currently

**Comment by Seldaek** [comment]
Indeed. I updated https://packagist.org/apidoc yesterday though to detail the best way to query the package data efficiently. Those are static files so it doesn't hit the server very hard.
