### ISSUE TITLE
Setting up an avatar when registered with github

### ISSUE THREAD

**Issue by Geolim4** [composer/packagist#698]
Hello,

It seems that we can't set up an avatar when you registered with Github.

Regards,
Georges

**Comment by Seldaek** [comment]
We use gravatar.com exclusively for avatars.

**Comment by Geolim4** [comment]
This is nota problem at all, i have a gravatar account and the avatar doesn't match, should i link my gravatar account somewhere ?

**Comment by Seldaek** [comment]
No gravatar is linked via email, just make sure your packagist email address is the right one and it should go fine :)

**Comment by Geolim4** [comment]
Houston i have a problem: I have two emails, and i can't change the Packagist one because i don't know my password (as i registered via Github) :)

**Comment by Seldaek** [comment]
You can either add the second one to your gravatar account, or use the password reset on packagist to "create" a password.

**Comment by Geolim4** [comment]
Ok, a bit tricky but it's working.
Should be mentioned in the user control pannel (IMO)

/solved
