### ISSUE TITLE
Incomplete versions for repository

### ISSUE THREAD

**Issue by klatys** [composer/packagist#701]
https://packagist.org/packages/symfony/http-foundation and https://packagist.org/packages/symfony/dependency-injection are displaying *-dev only versions even though there are proper tags in repositories - https://github.com/symfony/dependency-injection / https://packagist.org/packages/symfony/http-foundation

**Comment by SpacePossum** [comment]
same here, for ref: https://github.com/silexphp/Silex/issues/1400

**Comment by alcohol** [comment]
Might have been a glitch. Everything seems ok now?

**Comment by SpacePossum** [comment]
looks all good now, thanks @alcohol for checking :+1:

**Comment by fabpot** [comment]
I would reopen this one as I fixed the issue by hand. @Seldaek might want to investigate the issue further and try to understand why it happened.

**Comment by fabpot** [comment]
symfony/yaml was also broken.

**Comment by hboomsma** [comment]
https://packagist.org/packages/symfony/framework-bundle too

**Comment by fabpot** [comment]
symfony/framework-bundle fixed manually.

**Comment by Seldaek** [comment]
Should be fixed by c22b770171cedb0f7ac12fbf9d893fb9c266ddc3
