### ISSUE TITLE
Support filter by package type

### ISSUE THREAD

**Issue by Webysther** [composer/packagist#706]
Specially for composer-plugin, best way is search with "composer-plugin" in github or packagist, but not fit all plugins.

![captura de tela de 2016-07-26 11-14-16](https://cloud.githubusercontent.com/assets/750007/17141417/5a58261a-5322-11e6-8980-de3614994339.png)

It would be great to allow a more comprehensive survey of third-party improvements made in composer.

**Comment by stof** [comment]
This is already supported, even though the form does not exposes it. Add ``type=composer-plugin`` in the query string of the search.

**Comment by Webysther** [comment]
Thank you!
