### ISSUE TITLE
Solr 6 support

### ISSUE THREAD

**Issue by cannibal** [composer/packagist#713]
Could someone please update the schema.xml and solrconfig.xml for Solr 6 (and add some more instructions about how to configure a working solr installation for use with packagist)?

I have absolutely no idea where to start with this! 

Alternatively, elastic search support would be much more convenient...

**Comment by Seldaek** [comment]
Nope sorry. We run on 3.6 for now, and as packagist isn't made to be reused by others, I won't spend time on a needless upgrade.

**Comment by Soullivaneuh** [comment]
SolR 3.6 seems to be very outdated.

Indeed, this project is not made to be reused by others, but it's quite hard to find a old version of SolR compatible with our OS, or if we want to work with a more recent system like docker: https://hub.docker.com/_/solr/ (Only 5.x and 6.x are available).

If we submit you a PR for a SolR 6 configuration, would you consider an upgrade?

Regards.

**Comment by Seldaek** [comment]
I have no interest in this at the moment, but you can do a PR though 
which you can then at least use in your deployment.. and maybe we'll use 
it at some point, but no promises.

**Comment by Soullivaneuh** [comment]
Ok I'll think about it when I'll get some time. :wink:

**Comment by hackzilla** [comment]
We decided to use docker to install Solr 3.6 on our Ubuntu 16.04 server.

Pretty straight forward, and saves worrying about compatibility with a Solr version that isn't supported.
https://github.com/UKWebMedia/packagist-solr
