### ISSUE TITLE
Open issue count mismatches for custom issue channels

### ISSUE THREAD

**Issue by Rarst** [composer/packagist#715]
Packagist seems to pull and display "Open Issues" count from GitHub repo of the package, but the _link_ might be taken from `composer.json` if provided there. That can result in mismatch between the two.

Example at https://packagist.org/packages/johnpbloch/wordpress

**Comment by Seldaek** [comment]
That is a correct analysis, but there isn't much we can do to improve this I am afraid? If there is a custom issues link I think it's best to show that, but then maybe we should not show the count? I don't know what's best.

**Comment by Rarst** [comment]
I suggest just don't show the GitHub count and link to a custom tracker.

**Comment by Seldaek** [comment]
OK.. might be better yes
