### ISSUE TITLE
Packagist account linked to deleted Github account

### ISSUE THREAD

**Issue by raymondschouten** [composer/packagist#719]
Is there a way to unlink my old and deleted Github account from my Packagist account, maybe manually? I had re-created my Github account with the same name, but I'm unable to link my new Github account to my Packagist account.

This also causes a "403 Forbidden" after logging in. Changing the url to the dashboard displays my account correctly afterwards.

Both my old and new Github account and my Packagist account are named "raymondschouten".

**Comment by Seldaek** [comment]
I disconnected your account, so if you login on packagist then go to your profile you should be able to connect it with github, then can use the github login functionality.

**Comment by raymondschouten** [comment]
Thank you very much, it worked as described.

**Comment by coolcodemy** [comment]
i have the same problem too.. my old username is ahmadfikrizaman and the new one is coolcodemy

**Comment by Seldaek** [comment]
@coolcodemy your packagist user coolcodemy uses ahmadfikrizaman at gmail as the email, so if you still own that email address you can access it by login/password, use the password reset form to create a password if you don't have one.
