### ISSUE TITLE
Questions about bus factor of packagist.org

### ISSUE THREAD

**Issue by Halleck45** [composer/packagist#721]
Hi,

> Sorry for my bad english. I hope that nothing is lost in translation. If I'm not enough clear, do not hesitate to ask me for details.

Composer is an excellent tool. But I have serious questions about the "bus factor" of packagist.org. Maybe these questions have been already asked, but I don't find discussion on this subject (except [this issue](https://github.com/composer/packagist/issues/574))

Today, packagist.org is:
- a website
- a database of repositories (today, I think that a large majority of PHP projects depend of packagist.org to be installed)
## License

packagist.org is a database. What is the licence of this database ? ([this licence file ](https://github.com/composer/packagist/blob/master/LICENSE) does not concern database)
## Bus factor

If packagist.org is down, there are few unofficial repositories ([example](https://packagist.jp/)). I there are some unofficial tools to create mirrors ([example](https://github.com/hirak/packagist-crawler). **But these tools are not official and not maintained**. (Satis/Toran are not concerned according to me : yes we can mirroring packages with Toran/Satis, but it requires a specific work, and if someone create mirror it still unofficial).
- I think that it could be interesting to **ask for communities** (The PHP Group, AFUP, PHP-FIG, The free software foundation...) in order to see if they would accept **to host mirrors** of packagist. What do you think about this idea ?
- is there a discussion in order to **integrate the database of packagist.org to php.net ([this subject is evocated here](http://externals.io/thread/276)) ?
- what is the workflow if you decide to close packagist.org ?
- do you need more money to host packagist.org ?
- what do you think about making this website more transparent (providing informations about hosting, open sourcing recipes of deployment, of backup processes...) ?

I really appreciate Composer, and I hope that this discussion can help to improve it :)

**Comment by Seldaek** [comment]
> I think that it could be interesting to **ask for communities** (The PHP Group, AFUP, PHP-FIG, The free software foundation...) in order to see if they would accept **to host mirrors** of packagist. What do you think about this idea ?

Mirroring isn't very hard, but mirroring at high speed and atomically is a bit more difficult. Hardly impossible to write though, but it's not really one of my priorities, I rather focus on running the service as it is. We don't really have a mirroring support in Composer either, so these mirrors would essentially be opt-in or present only in case of disaster scenario, which isn't useless of course but in my experience it's maybe not useful enough to motivate many people to work on this :)

> is there a discussion in order to **integrate the database of packagist.org to php.net ([this subject is evocated here](http://externals.io/thread/276)) ?

Nope. I don't really see a point to doing this. Everyone is too busy and that's just adding a lot of "paperwork" problems that nobody will be interested in.

> what is the workflow if you decide to close packagist.org ?

I can't foresee that eventuality, but right now we are two people with the keys and a couple others could be given access if needed.

> do you need more money to host packagist.org ?

Not really, https://toranproxy.com provides enough for server costs.

> what do you think about making this website more transparent (providing informations about hosting, open sourcing recipes of deployment, of backup processes...) ?

I am a bit ambivalent about this, open sourcing server configs and such has a few minor benefits as far as I can see but also a lot of problems and wasted time as people will want to contribute things to it that we might not be interested in, or argue about details that don't matter, etc.
