### ISSUE TITLE
This package is not auto-updated! [ERROR]

### ISSUE THREAD

**Issue by subversivo58** [composer/packagist#722]
Package don't aut-uploaded results strange error. Package don't downloadable by cmd using command (composer require "myvendor/mypack": "1.0.*") this command returns error "The requested package exists but these are rejected by your constraint". Package only downloadable by (composer require "myvendor/mypack": "dev-master" ?

**Comment by Seldaek** [comment]
If you have a problem with the update of a package, please at least provide the package name otherwise we can't possibly help.

**Comment by subversivo58** [comment]
My composer is update my package is: https://packagist.org/packages/mdbsh/mdbsh

**Comment by Seldaek** [comment]
The package seems fine to me. Not sure what to do here.
