### ISSUE TITLE
Package releases from the feature in RSS feed.

### ISSUE THREAD

**Issue by Fahrradflucht** [composer/packagist#723]
Viewing the [RSS](https://packagist.org/feeds/releases.rss) or Atom feed of new releases I see packages like `vespakatalog/app (1.0.16)` which according to the provided will be released on `Fri, 24 Mar 2017 00:00:00 +0000`.

Is this a bug?

At the time of this writing there are 3 of these `vespakatalog/app`versions from the same day in the future in the feed. But in addition to that there are 6 different packages from the vendor `rougin` which are date to different dates in the next couple of days.

How is this possible?

It's kind of annoying to filter this data out every time you parse through the updates.

**Comment by Seldaek** [comment]
It's possible because you can do whatever you want with git commits, which is where we get the date from. Anyway I filter these out now :)
