### ISSUE TITLE
Do search on load

### ISSUE THREAD

**Issue by theofidry** [composer/packagist#726]
If you go to https://packagist.org/?q=phar&type=composer-plugin, you will have the following page:

<img width="1280" alt="screen shot 2016-09-22 at 12 51 02" src="https://cloud.githubusercontent.com/assets/5175937/18747123/4de8cfbe-80c3-11e6-802b-26b8895469c0.png">

Where I would have expected:

<img width="1280" alt="screen shot 2016-09-22 at 12 52 07" src="https://cloud.githubusercontent.com/assets/5175937/18747142/64e848f2-80c3-11e6-8c20-3bb66790c3c5.png">

To achieve the desired result, I have to first type "phar" in the search and *then* add the `&type=composer-plugin` and press `Enter` again to get the correct search.

It is also worth nothing that changing the searched word will remove extra parameters like the type. For example if I have https://packagist.org/?q=pha&type=composer-plugin and in the search bar I'm adding the missing `r`, the search will become https://packagist.org/?q=phar.

**Comment by Seldaek** [comment]
That's because the search endpoint is on /search/ and not on the homepage.. https://packagist.org/search/?q=phar&type=composer-plugin works fine :)
