### ISSUE TITLE
Allow sorting of dependent packages

### ISSUE THREAD

**Issue by mhujer** [composer/packagist#728]
When considering a package, it may be useful to see if any high-profile packages depend on it. The dependent packages are currently ordered by name which prevents this case.

For example, when choosing a HTTP client library and one of the candidates is Guzzle, it may be useful to know that AWS SDK depends on it ("If they trust it, I can use it as well"). It is not possible now, because there are [287 pages of dependents packages](https://packagist.org/packages/guzzlehttp/guzzle/dependents) for Guzzle and they can't be sorted by _Downloads_ of _Stars_.

**I suggest that it should be possible to sort _Dependents_ by _Downloads_ and _Stars_**. (probably same thing applies to _Suggesters_)

If you think that it is a good idea, I'd be happy to work on it.

**Comment by Seldaek** [comment]
Sounds good yeah

**Comment by mhujer** [comment]
Fine, I'll work on it

**Comment by mhujer** [comment]
I've just found the issue you had for it year ago: #534

**Comment by javiereguiluz** [comment]
On symfony.com we recently redesigned the pages of Symfony Components and now we link to the dependents page on Packagist.org (see for example https://symfony.com/components/Console) We'd love to have this option so we can link to the URL that sorts dependents by downloads or stars. Thank you!

**Comment by arcticlinux** [comment]
I agree, I was looking at https://packagist.org/packages/webmozart/assert and was wondering how it had almost 80 million installs, it took me until page 10 of dependents results to find PHP
phpdocumentor/reflection-docblock which has almost 100 million installs.

**Comment by stof** [comment]
The hard part about that is that downloads are not stored in MySQL. So sorting by downloads would require loading *all* dependent packages from MySQL and then sorting it based on downloads. Loading such unpaginated list is probably not a good idea.

**Comment by Seldaek** [comment]
@stof they are in MySQL now for a while, so it's more possible to do such things, but the dependent queries are still slow as it needs a lot of JOINs on a lot of data, so not sure I want to do add to it..

**Comment by javiereguiluz** [comment]
Maybe I'm saying something stupid ... but given that Packagist.org search now uses Algolia ... and Algolia fully supports faceting and a million other features ... couldn't all this be implemented "for free" using Algolia features and not with custom search queries on Packagist.org server?

Maybe Nuno (@nunomaduro) who works as an engineer at Algolia and loves PHP could help us here. Thanks.

**Comment by stof** [comment]
Well, that would require storing links between packages in Algolia (and not requirements, but dependents, so updating a package in Packagist would require reindexing all its dependencies). That's probably not easy to integrate in the system.

**Comment by Seldaek** [comment]
The finding of dependents could be fairly easily implemented that way I think (@stof I think we could store the requires as if it was a tag for example, and then find anything which requires x, no need to store dependents on a given package IMO?), but the sorting IIRC needs  a new algolia index per sort type which would increase our data size there quite a bit..

**Comment by Seldaek** [comment]
Fixed by https://github.com/composer/packagist/commit/6c1127b2e3e0c636ecb9878a0faaba0f696059e2 

See e.g. https://packagist.org/packages/monolog/monolog/dependents?order_by=downloads 
I also added a JSON version for API consumption https://packagist.org/packages/monolog/monolog/dependents.json?order_by=downloads
