### ISSUE TITLE
Allow colspan and rowspan in README.

### ISSUE THREAD

**Issue by donquixote** [composer/packagist#733]
If you compare these two pages:
- https://github.com/donquixote/cellbrush
- https://packagist.org/packages/donquixote/cellbrush

The one on packagist looks broken. Look for the 3rd table with "Full rowspan and colspan".
This is a pity, because the rowspan / colspan is kind of the selling point of cellbrush :)

Could we allow those in packagist README display? I imagine this is just a html filter that is a bit more strict than necessary.

**Comment by stof** [comment]
I opened a PR to allow them in the HTML filtering. Once my change is merged and deployed, things will get fixed at the next update of your package

**Comment by donquixote** [comment]
Thanks!
