### ISSUE TITLE
[suggestion] Rely on github syntax highlighting in readme

### ISSUE THREAD

**Issue by stof** [composer/packagist#735]
Currently, we perform the highlighting client-side in JS, relying on auto-detection of the language.

Github has a much better way to detect the language (as most readmes are declaring it in markdown). And the github API actually performs the syntax highlighting when rendering the markdown. We don't have it on Packagist because the HTML_Purifier config drops it (it drops all spans and divs, and all classes).

What do you think about relying on the github-provided highlighting instead (which would support any language supported by github btw) ?

FYI, the CSS used by the github markdown rendering is available at https://github.com/sindresorhus/github-markdown-css, which include the highlighting styles (the `pl-*` classes)

**Comment by alcohol** [comment]
I think that would be a good idea. Would also be better for our end users. No need to run highlightjs then. Can the CSS be used without any issues though? Do we need additional markup to make sure it does not affect other aspects of our own layout?

**Comment by stof** [comment]
This CSS is scoped with a class on a parent element, so there would be no issue (we just need to add the ``markdown-body`` class on the div around the readme content)

**Comment by Seldaek** [comment]
c.f. https://packagist.org/packages/monolog/monolog - this has now gh styling, other packages will get in line as they update (for the syntax highlighting).
