### ISSUE TITLE
README doesn't match selected version

### ISSUE THREAD

**Issue by schnittstabil** [composer/packagist#738]
The README section doesn't match the selected version on the right side.
Even worse, the displayed README is always the one of the `master` branch, typically the development branch of github projects, which leads to many annoying issues.

**Comment by stof** [comment]
Packagist only stores 1 README for the package. It does not store the readme for each version currently.

**Comment by schnittstabil** [comment]
That is very bad indeed.

**Comment by alcohol** [comment]
Well we could also **not** display any readme. But then people would cry over that. So, this is the middle ground.

**Comment by schnittstabil** [comment]
> Well we could **also** not display any readme.

Sure, not *any* readme, but the *latest readme*? Most users want to install the *latest stable* and packagist already preselects the *latest stable*, hence displaying the *latest stable readme* seems to be the most reasonable choice to me.

Additionally, just because packagist does not store the readme for each version currently, does not mean it can not be changed.

**Comment by alcohol** [comment]
Since you're the only one so far who sees added value here, you're welcome to implement it and submit a PR. But do not count on others to do the work for you.

We currently store the README on package level, not version level. Hence why it always retrieves the README from the main branch on Github (which defaults to master for most repositories). Changing this will require quite some effort, on both the backend and frontend.

**Comment by Seldaek** [comment]
The thing as well is not only about technically doing it, but it'll increase the amount of github API  requests quite a bit, for little added value IMO. We provide the HEAD readme as a bonus, if you want more source just go to the repo, it doesn't make sense for us to mirror it all.

**Comment by schnittstabil** [comment]
> Since you're the only one so far who sees added value here, you're welcome to implement it and submit a PR. But do not count on others to do the work for you.

@alcohol It was not my intention to annoy you. I've created this issue to find out if the current behavior is intended, and whether a PR has a chance to get accepted. Telling me it's not possible is obviously just a lie. I want to help packagist to become even more awesome – lying to project stakeholders is not helpful, but that is just a personal opinion.

--

> The thing as well is not only about technically doing it, but it'll increase the amount of github API requests quite a bit, for little added value IMO. We provide the HEAD readme as a bonus, …

Thanks @Seldaek, that sounds reasonable. However, providing the latest stable readme instead seems to be an acceptable compromise, doesn't it?

**Comment by alcohol** [comment]
I am not annoyed and I did not say it is not possible. :-/

**Comment by Seldaek** [comment]
@schnittstabil we provide the README from the default branch AFAIK, which is what github shows you as the default README as well, which sounds perfectly acceptable to me. Especially for some libs that haven't been tagged in a while the last stable can be well out of date.

**Comment by schnittstabil** [comment]
> Well we could also **not** display any readme.

> I am not annoyed and I did not say it is not possible. :-/

Sorry, if I get you wrong, I'm not a native speaker.

**Comment by alcohol** [comment]
I meant that, instead of showing a readme, we could decide to not show any readme. Then the "*README section doesn't match the selected version on the right side.*" issue goes away too. In short, I proposed that removing the functionality would also solve this issue. But then I proceeded to mention that some users would prefer to see any readme, rather than none. Hence the current approach. It's a compromise between having to store many readme's, and having no readme.

**Comment by schnittstabil** [comment]
@alcohol I'm really sorry, I've totally misunderstood you.

--

Many thanks for all the insights. If you think it's not worth, then I won't bother anymore and enjoy the autumn instead – hoping you can do as well.

**Comment by alcohol** [comment]
It is quite alright. No feelings were hurt (at least I think so). I hope you can understand why we feel that this compromise is satisfying.

**Comment by schnittstabil** [comment]
:grin: Seems I'm not the only one who struggle with this: https://github.com/lcobucci/jwt/issues/134#issue-186322940 – okay, to be fair, I don't know how @nanokid found the jwt package: by searching on packagist, github or whatever.

– Don't get me wrong, I don't want to restart this discussion – It's just because @nanokid created that issue a few minutes ago…
