### ISSUE TITLE
Adding repo with HTTPS URL fails with SSH URL error

### ISSUE THREAD

**Issue by gohanman** [composer/packagist#741]
I'm running a copy and having intermittent problems with runtime exceptions when trying to add a package. None of the repos are private and the behavior is entirely intermittent leading me to believe it has something to do with rate-limiting on github's API. I do have proper client_id and client_secret in parameters.yml and the problem only seems to impact the web UI; the console commands all behave fine.

Example: if I add a package with this URL: 
`https://github.com/CORE-POS/LanePlugin-MemberCard.git`
I get back this exception:
`Uncaught Exception: [RuntimeException] Failed to execute git clone --mirror 'git@github.com:CORE-POS/LanePlugin-MemberCard.git' '/var/www/.composer/cache/vcs/git-github.com-CORE-POS-LanePlugin-MemberCard.git/'`

After a bit of hunting I determined the actual exception is coming from Composer in [GitHubDriver](https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitHubDriver.php#L305-L327). 
- First it tries to get content from `https://api.github.com/repos/CORE-POS/LanePlugin-MemberCard`
- That fails with HTTP 401
- It then looks for an oauth token in `github.accesstoken` in the current working directory's git configuration
- Then finally it switches to the SSH URL - failing I image because www-data has no keys, among other problems

Do I have to generate an OAuth token manually and add it to the packagist repo's git configuration? If not, I'd appreciate any hints what the [fetch-info](https://github.com/composer/packagist/blob/master/src/Packagist/WebBundle/Controller/PackageController.php#L136-L189) controller is doing that ultimately fires off a call to download the repository URL.

**Comment by alcohol** [comment]
You can set `no-api: true` for that repository definition. See if that solves it.

**Comment by Seldaek** [comment]
Sorry but we do not support packagist installs, it's not advertised as being usable by third parties and as it's not made for private packages at all for that matter.

**Comment by gohanman** [comment]
Fair enough. Should anyone stumble across this on google generating oath tokens manually does help quite a bit (I have no idea if this would work with anything actually private).
