### ISSUE TITLE
How can I edit my account if I am logging in via GitHub?

### ISSUE THREAD

**Issue by ama3ing** [composer/packagist#742]
Hola, 
I've been logging in to packagist using my github account, now I want to edit my profile and I can't do this since it requires password. However I do not have any password set and can't change anything in my packagist account.
Thanks in advance!

**Comment by mhujer** [comment]
See #359

**Comment by ama3ing** [comment]
@mhujer Thanks, but I doubt if it will help me, because I lost access to email used in packagist. Basically I want to change my email that's the reason of asking this question. CircularReferenceException 😆

**Comment by alcohol** [comment]
@Seldaek can you help this guy out? He is stuck in a circular issue indeed.

**Comment by Seldaek** [comment]
Yeah this happens once in a while and usually people email contact@packagist.org and we get it sorted. That's the best way really as we need to authenticate your account ownership and stuff, please email account details (old and new email, and packagist api token as proof of ownership) and I can get it sorted.

**Comment by ama3ing** [comment]
@Seldaek Thanks for your response. I've sent an email.
