### ISSUE TITLE
Wrong "repository" attribute on packagist for sebastian/git

### ISSUE THREAD

**Issue by andygrunwald** [composer/packagist#749]
We have added this repository in our medusa app to mirror it locally.
Medusa is requesting packagist.

If you have a look at the package.json file on packagist for this repository: https://packagist.org/packages/sebastian/git.json

You will see something like
```
"repository":"https:\/\/github.com\/sebastianbergmann"
```

If you compare this to e.g. X (https://packagist.org/packages/nelmio/cors-bundle.json), you see it like
```
"repository":"https:\/\/github.com\/nelmio\/NelmioCorsBundle"
```

Means: It seems to be point to an invalid repository.

Medusa will clone your repository and throw an exception:
```
 [Exception]
 Cloning into bare repository '/appdata/www/trivago/git-mirror/sebastian/git.git'...
 fatal: repository 'https://github.com/sebastianbergmann/' not found


add [--with-deps] [--] <package> [<config>]
```

My assumption: Someone is doing a str_replace of the string "git" somewhere. E.g. packagist?

**Comment by andygrunwald** [comment]
I posted this in https://github.com/sebastianbergmann/git/issues/31 as well.
Not sure where the issue is.

**Comment by stof** [comment]
@Seldaek have you performed a DB cleanup to remove all ``.git`` at the end of github repository URLs, which might have broken it for this package ?

**Comment by stof** [comment]
@andygrunwald can you close this as the issue has been fixed now ?

**Comment by andygrunwald** [comment]
Fixed. Thx.

**Comment by Seldaek** [comment]
I did this once but that was ages ago.. Anyway good if it's solved.
