### ISSUE TITLE
add maintainer avatar at package data API

### ISSUE THREAD

**Issue by IndraGunawan** [composer/packagist#754]
when get package data using API the `maintainer` object only provide name. i think it would be good if API of package data can provide gravatar url as maintainer avatar

https://packagist.org/packages/monolog/monolog.json

```
{
    "package": {
        "name": "monolog/monolog",
        "maintainers": [
            {
                "name": "Seldaek",
                "avatar": "//www.gravatar.com/avatar/48b79d17cd8a911327cbd88c122b1efb",
            }
        ],
        ...
    }
}
```

**Comment by Seldaek** [comment]
Sounds fine to me, if you wanna send a PR..
