### ISSUE TITLE
HTMLPurifier - problem with permissions

### ISSUE THREAD

**Issue by f3l1x** [composer/packagist#758]
I am trying to run own packagist in docker container. I have found little tiny edge problem with HTMLPurifier.

```
Directory /srv/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777
```

Is there any way how to change purifier cache directory? I don't known reason why would it store cache to vendor directory.

Thank you guys.

**Comment by stof** [comment]
We should configure HTMLPurifier cache directory instead of letting it use its own folder, so that we can use the Symfony cache. This would solve this

**Comment by f3l1x** [comment]
I solved it in my Docker image. So it doe not really bother my anymore. :-)
