### ISSUE TITLE
Transfer of ownership of packages

### ISSUE THREAD

**Issue by Pegasuz** [composer/packagist#760]
I've added some packages in the past from my company namespace on github onto my personal packagist account. We have now created a company account on packagist and would like to transfer our company packages to this company account. Also because the company namespace is currentlu reserved for my personal account and no other packages can be added on the company account.

my packagist and github account: Pegasuz
Company packagist account: studioemma

Packages on personal account to be transfered to company account:

* studioemma/migrations
* studioemma/multilingual
* studioemma/plugin-installation-step

Thanks in advance!

**Comment by stof** [comment]
you can add new maintainers on a package where you are maintainer, so you can do this yourselves. Connect with your personal account, and add the company account as another maintainer of the package

**Comment by Pegasuz** [comment]
Thank you. But I believe this doesn't fix the problem of being able to add new packages to the company account when the namespace is already registered with my personal account?

**Comment by stof** [comment]
A namespace can be used by anyone being maintainer on at least one of the existing packages. This is how reserving works. So it would also solve it.

**Comment by Pegasuz** [comment]
Thank you very much. I've added the company account as a maintainer and I am now allowed to add packages on the company namespace on the company account.

Thank you @stof !
