### ISSUE TITLE
create account error

### ISSUE THREAD

**Issue by jeje-50** [composer/packagist#761]
on register page i have an error :

Block "fos_user_header" on template "PackagistWebBundle::layout.html.twig" does not exist.

so i remove "{{ block('fos_user_header') }}" form /app/Resources/FOSUserBundle/views/layout.html.twig
and all seems good

**Comment by stof** [comment]
This does not make sense, as Packagist uses Twig 1.x, which does not throw errors for unknown blocks.
Have you run ``composer update`` instead of using ``composer install`` to install the locked dependencies ? this is not a supported usage of Packagist.

**Comment by stof** [comment]
Btw, fixing compatibility with Twig 2.x is a good idea for the future of Packagist of course, but this is a different discussion than a bug report.

**Comment by jeje-50** [comment]
Yeah i make an `composer update` instead of `composer install` sorry.
I clean up my install and make `composer install` and all it's good :)

Otherwise update to Twig 2.x is a goal ?
