### ISSUE TITLE
RC1 release considered as stable release

### ISSUE THREAD

**Issue by Geolim4** [composer/packagist#763]
Hello,

It seem that RC* version are considered as a stable release, is this a expected behavior ?
[Here you can see](https://packagist.org/packages/phpfastcache/phpfastcache) the context.

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello, any news about this ?

Cheers,
Georges

**Comment by stof** [comment]
What do you mean by "are considered as a stable release" ?

**Comment by Geolim4** [comment]
Hello,

The latest version displayed is the 6.0.0-rc1.
As you can see here:
https://packagist.org/packages/symfony/symfony

For symfony, the currently display version is 3.2.3 despite the 3.2.x-dev

Cheers,
Georges

**Comment by Seldaek** [comment]
We just display the latest tag by default, and ignore dev versions (i.e. branches).
