### ISSUE TITLE
getting strange error

### ISSUE THREAD

**Issue by flik** [composer/packagist#765]
$ composer require xorm/xorm

  [InvalidArgumentException]
  Could not find package xorm/xorm at any version for your minimum-stability
  (stable). Check the package spelling or your minimum-stability

Please check attached pic for detail. 
![xorm error](https://cloud.githubusercontent.com/assets/900323/22477665/bfb2ebc8-e808-11e6-90a9-465b54e59466.png)

**Comment by Seldaek** [comment]
Most likely the problem is that your minimum-stability is set to the default (stable), so it doesn't find it. You can `composer require xorm/xorm:dev-master` to specifically require the master version, which will bypass the minimum-stability.
