### ISSUE TITLE
Added stat about all php package version requirements

### ISSUE THREAD

**Issue by andreybolonin** [composer/packagist#767]
What do you think about adding to https://packagist.org/statistics graph with the version of all php packages registered into packagist.org?

@Seldaek @naderman 

It would be very interesting info. 
We understanding, how php world migrating from php 5.x to php 7.x.

**Comment by Seldaek** [comment]
Might be nice to see that graph, but it'd probably have to be computed in the background because grouping the php versions with LIKE queries + doing that for every single version results in pretty heavy queries, especially if you want to do it over time.
