### ISSUE TITLE
Change jquery-form ownership

### ISSUE THREAD

**Issue by kevindb** [composer/packagist#768]
https://packagist.org/packages/malsup/form

The [jquery-form](https://github.com/jquery-form/form) project has changed ownership. It looks like the package was published to Packagist by someone other than the original project owner. How can I take ownership on packagist.org? My username is [kevinmorris](https://packagist.org/users/kevinmorris/).

I'm not sure what the best practice is to update the package in Packagist. The canonical URL should probably change to `https://packagist.org/packages/jquery-form/form`, but I don't want to break dependencies or installations that are pointing to `malsup/form`.

Also, the repo URL has changed. Is there anything I need to do to update the URL other than update it in composer.json?
OLD:  
`https://github.com/malsup/form.git`  
NEW:
`https://github.com/jquery-form/form.git`

Thank you

**Comment by stof** [comment]
The repo URL can be edited on Packagist by the maintainer.

Regarding the package name, renaming package can be done by renaming it in the composer.json, then submit the package on Packagist again (which will detect the new name) and then mark the old package as abandoned on Packagist (with the new package name as replacement)

**Comment by kevindb** [comment]
I have submitted the package and the new URL is live:  
https://packagist.org/packages/jquery-form/form

The owner (maintainer?) of https://packagist.org/packages/malsup/form is listed as RobLoach. He is not a contributor to the project, so I don't have any contact information for him. I think he just uploaded it to Packagist so he could use it. There isn't any contact information on his profile page. How can I ask him to mark his version as abandoned?

**Comment by stof** [comment]
@RobLoach can you give your mind on this ?

**Comment by stof** [comment]
@RobLoach why have you added me as a maintainer ?

**Comment by RobLoach** [comment]
@kevindb Thanks so much for taking action on this. Looks like you've done a great job in bringing 4 up to date.

I've added you two as maintainers, and marked the package as abandoned.

> why have you added me as a maintainer ?

For fun? In case anything else goes wrong?

**Comment by kevindb** [comment]
Thank you @RobLoach and @stof!
