### ISSUE TITLE
Wasn't able to 'submit' the package

### ISSUE THREAD

**Issue by heykarthikwithu** [composer/packagist#769]
While i was trying to submit the package (https://packagist.org/packages/submit), it was throwing an error "The package name heykarthikwithu/Phantoman is invalid, it should not contain uppercase characters. We suggest using heykarthikwithu/phantoman instead."
but package url is resolved to https://github.com/heykarthikwithu/phantoman

**Comment by stof** [comment]
the package name has nothing todo with the URL. It has to do with the content of the ``name`` field in the composer.json

**Comment by heykarthikwithu** [comment]
yup, i missed it.. got fixed... thanks @stof
