### ISSUE TITLE
Case Sensitivity Problem with Package names and directories

### ISSUE THREAD

**Issue by felipemarques** [composer/packagist#771]
This is related from https://github.com/composer/packagist/issues/186.

Hi guys,

I have one real public problem.

When I use the joshrps/laravel-shopify-API-wrapper via composer, all files are downloaded successfully. But one specific file does not have download with the same name in this repository. 

The file is: ./vendor/rocket-code/shopify/src/RocketCode/Shopify/api.php

This file must will be ./vendor/rocket-code/shopify/src/RocketCode/Shopify/API.php, such as in github repository in uppercase: API.php . 

Please see the file: https://github.com/joshrps/laravel-shopify-API-wrapper/tree/master/src/RocketCode/Shopify

I use this package: https://github.com/joshrps/laravel-shopify-API-wrapper
In my composer json:

{ ...
"rocket-code/shopify": "~2.0",
...} 

Or using this command:
`$ composer require rocket-code/shopify`

Thanks for your attention.

**Comment by stof** [comment]
The commits from the PR https://github.com/joshrps/laravel-shopify-API-wrapper/pull/10 renaming the file to uppercase is not part of any release yet. The 2.0.2 tag has it in lowercase: https://github.com/joshrps/laravel-shopify-API-wrapper/tree/2.0.2/src/RocketCode/Shopify

so there is no issue in composer or in packagist. Composer uses stable versions by default (unless you tell it that dev versions are OK), and the maintainer does not have a stable version including the fix.

**Comment by stof** [comment]
And your issue has nothing to do with package names. It is about the name of a file inside a package.

**Comment by felipemarques** [comment]
Hi @stof , thanks for your attention...

Yes, you are totally correct! The problem is in name of a file inside a package.
But, I can resolve this without creating a fork or make changes directly in a package:

...
"files": [
      "vendor/rocket-code/shopify/src/RocketCode/Shopify/api.php"
    ]
...

Thank you so much!!
