### ISSUE TITLE
Please remove package https://github.com/staempfli/symlinker-pro

### ISSUE THREAD

**Issue by jalogut** [composer/packagist#774]
Hello,

Could you please remove the package with following url:

- https://github.com/staempfli/symlinker-pro

If seems that I created a mess renaming it:

- from `staempfli/simlinker-pro` to staempfli/symlinker-pro`

Now composer gets stuck if I require this package on`Resolving dependencies through SAT`:

`
Writing /Users/alojua/.composer/cache/repo/https---packagist.org/provider-trentrichardson$jquery-timepicker-addon.json into cache
Downloading http://packagist.org/p/twbs/bootstrap%24ed661dc7551246d83a1d683080cb5bebaa3a2638fd4fcef611ee02fb884ac715.json
Writing /Users/alojua/.composer/cache/repo/https---packagist.org/provider-twbs$bootstrap.json into cache
Resolving dependencies through SAT
`

I tried the following without success:

- Remove package from Packagist
- squashed all my commits into one, so there is no sign of the wrong package name anywhere on the repository. 
- Submit again
- clear composer cache

I removed the package again from packagist but I do not get any message like `package could not be found in any version`. Composer just get stuck. Which means that the corrupted package is still somewhere.

Thanks in advance

**Comment by Seldaek** [comment]
Could you just resubmit it to packagist and leave it there and then tell me exactly what you are trying to do that fails?

**Comment by jalogut** [comment]
Hi @Seldaek 

I just resubmitted the package. What I am trying now is:

`composer require "staempfli/symlinker-pro":"dev-master"`

**Comment by jalogut** [comment]
Sorry I pressed the close issue button by mistake

**Comment by Seldaek** [comment]
So in an empty folder if I run that command the package installs fine.. If it doesn't for you I need more details.

**Comment by Seldaek** [comment]
```
Package operations: 5 installs, 0 updates, 0 removals
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.4) Downloading: 100%
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.4) Downloading: 100%
  - Installing staempfli/symlinker-pro (dev-master cf792f5) Cloning cf792f5aec from cache
```

**Comment by jalogut** [comment]
Yes, it works now after submitting it again. Not sure what was happening before. 
Thanks for your help and sorry for the inconvenience.

**Comment by Seldaek** [comment]
No worries, glad it works.
