### ISSUE TITLE
My readme is readable in bitbucket but not in packagist

### ISSUE THREAD

**Issue by ColonelMoutarde** [composer/packagist#776]
My readme.md is readable on my BitBucket repo but not in my packagist "page". I tried to let only a few basic lines in case it was a syntax error but it didn't work. Is there a known (or unknown) conflict between packagist and BitBucket (all packages I saw was only on GitHub)?

**Comment by Seldaek** [comment]
It would help if you linked to the repo/package, but from what you say I'm thinking maybe the problem is you called the file `readme.md` instead of `README.md`?

**Comment by stof** [comment]
Support for readme files on non-Github repos is only available on Packagist since the beginning of January. So you should also make sure that your package got updated after January. If it is an older package not receiving updates, you should force an update to ensure that the readme gets updated

**Comment by ColonelMoutarde** [comment]
After update, it work! thank you.
And long life for packagist and composer 👍
