### ISSUE TITLE
Github signup

### ISSUE THREAD

**Issue by lakshmaji** [composer/packagist#780]
Hi There,

I have signed up to packagist using github authorization. I just wanted to change my user name but it was asking me the current password. How can i get the password as I have done signup through Github authorization ??

**Comment by stof** [comment]
duplicate of https://github.com/composer/packagist/issues/359

**Comment by lakshmaji** [comment]
Hi @stof ,
That works fine, but the github authenticated users requires this ???

**Comment by stof** [comment]
well, the fact that it should not be requried for them is precisely what #359 is about (except that nobody contributed a fix for it yet, and this is a not high-priority task for maintainers as there is a workaround so they spent their time on more important tasks related to Composer and Packagist)

**Comment by lakshmaji** [comment]
@stof Thanks
