### ISSUE TITLE
Interesting behaviour regarding download count

### ISSUE THREAD

**Issue by rathalos64** [composer/packagist#781]
I have published a package on packagist and noticed that after several installs of this package, packagist increased the download count no matter how often I downloaded it.

I wondered whether this stat can be manipulated.
Therefore, I have created a script which downloads (and removes) the package n times. Intersting enough, packagist apparently increases the download count only ten times. Afterwards, you can download the package as often you want; the download count won't increase longer.

Is this IP related? On other PCs it worked also only ten times.
This is not necessarily an issue, but an intersting behaviour which I think can be reported.

**Comment by Seldaek** [comment]
This is nothing extraordinary, it's all in the code, but we don't advertise this too much to avoid giving ideas to people about abusing stats.. Some have been caught in the past and punished (i.e. stats reset to 0..). 

It works to give a rough indication of usage as long as people play nice, if people don't play nice then everyone loses. That's what open source is all about.
