### ISSUE TITLE
reduce polling time for packages

### ISSUE THREAD

**Issue by satboy78** [composer/packagist#785]
Hi here, is there a way for lowering the polling time of packages? Is there a configuration parameter that I can set for adjusting it?

Please let me know if you need any more informations.

Thanks a lot.

Matteo

**Comment by stof** [comment]
You mean the polling for updating metadata on Packagist when you push in the VCS ?

There is a way: notify Packagist of pushes thanks to the webhook instead of relying on the cron.
The way to do it depends on whether you use Github, Bitbucket, Gitlab or a different git hosting

**Comment by satboy78** [comment]
Hi stof, yes, right.

I already have webhooks enabled, and they are working fine; however, sometimes it happens that my Packagist goes out of memory, so it happened that I missed some tags.

Where can I find the cron?

Thanks a lot.

**Comment by stof** [comment]
@satboy78 if you use your own Packagist instance, have you read the [Day-to-Day operation section](https://github.com/composer/packagist#day-to-day-operation) of the readme ?

**Comment by satboy78** [comment]
Hi stof,
here we have a separated team that works on mantaining Packagist, so I'll pass this suggestion to them.

Basically I'm investigating on the possibility to fix these problems with missing tags (that happens when packagist goes out of memory).

Thanks a lot for your suggestion!!

**Comment by stof** [comment]
Well, forcing an update might not help, as it would probably get an OOM error again. If your update needs lots of memory, you might need to increase the memory limit instead.

**Comment by satboy78** [comment]
yes, sure!

but at least, after restoring the system, the cron job will get latest updates.
