### ISSUE TITLE
Support info are missing from the dumped metadata

### ISSUE THREAD

**Issue by stof** [composer/packagist#787]
Packagist stores the support metadata (and uses them in the UI). but it does not include them in the dumped files loaded by composer.
This means that composer does not have access to these when using a package from Packagist (which is the common case). This is too bad, because `composer show` displays the support info when it is available too.
Can it be included in the dumped metadata ?

**Comment by alcohol** [comment]
@Seldaek Any idea how this would impact data volumes transferred? Insignificant, or?

**Comment by Seldaek** [comment]
Yeah adding anything there at this point is probably not a great idea as it means more data.. I think we'll have to take this into consideration for the v2 data format which we need to figure out still, but rather not add it right now. /ref composer/composer#6415

**Comment by X-Coder** [comment]
Please add this support property, I require it too, because it is missing in the generated composer.lock file, which I want to parse for a GUI in my project.

I think it makes not much sense to include every property of [property composer.json schema](https://getcomposer.org/doc/04-schema.md#properties), except the support one. It should be more consistent.

**Comment by stof** [comment]
@Seldaek now that the v2 format supports compression of similar properties, could this be re-evaluated ? I guess most versions will have the same support info, so this should not increase the payload too much. And this would mean that these support info can now be available to client-side tools (`composer show` for instance).

**Comment by Seldaek** [comment]
Yes we could I guess.. we do exclude authors/keywords from v2 format though but I guess I should undo that as well as it also should not change that much.
