### ISSUE TITLE
CORS response headers are being cached during calls to the packagist API

### ISSUE THREAD

**Issue by MetalArend** [composer/packagist#791]
As I was looking to ways to add repository stars and watchers to a new html/javascript github page, I stumbled upon the Packagist API. It works really fast and reliably, until I started noticing some XHR requests throwing errors due to `No 'Access-Control-Allow-Origin' header is present on the requested resource.`. They faded away after a few hours, one by one, so it seemed to be cache related, and it looked like it would be resolving itself.

However, when moving from development (http://0.0.0.0:4000) to github production (https://phpqa.github.io), I received either these errors as well as `The 'Access-Control-Allow-Origin' header has a value 'http://0.0.0.0:4000' that is not equal to the supplied origin.` on every package I tried to look up. It looks like the cache is responding with the domain in it's response that was used during the last request to recreate the cached page, so it responded with both the originally seen errors on development from not-yet-cached-as-CORS responses and the CORS responses created by using the development version of the website.

This surely seems to defeat the whole purpose of CORS, but it also makes the API virtually unusable to any CORS secured website - not to mention it bleeding information from potentially other users. I'm not sure if it is something you want to support ([#588 (comment)](https://github.com/composer/packagist/issues/588#issuecomment-164134406)), but I'm hoping there might be a simple solution to this, without too big of an impact on the packagist service and its performance.

I'm not completely sure about it, but I think it might be as easy as adding an `Access-Control-Allow-Origin` header with an asterisk, as mentioned [here](https://developer.mozilla.org/en/docs/Web/HTTP/Access_control_CORS).
>  In this case, the server responds with a Access-Control-Allow-Origin: * which means that the resource can be accessed by any domain in a cross-site manner.

Thanks for looking into this.

**Comment by alcohol** [comment]
AFAIK the `nelmio/cors-bundle` is being used and said headers should be properly set already?

https://github.com/composer/packagist/blob/master/app/config/config.yml#L119-L130

Do you have any more debugging details or information that could help?

**Comment by MetalArend** [comment]
The [page]( https://phpqa.io) where I'm trying this is live [now]( https://phpqa.io).

The most common error is:
`XMLHttpRequest cannot load XXX. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://phpqa.io' is therefore not allowed access.`

Could it be that most commonly the header is stripped away?

You can see these errors in the Chrome debugging tools, and trigger it yourself by pasting this into the debugging console and hitting enter:
```
$.ajax({
    url: 'https://packagist.org/packages/phpunit/phpunit.json',
    dataType: 'json',
    xhrFields: { withCredentials: false }
});
```
If I inspect the request, I see the following properties in the request headers:
```
Host:packagist.org
Origin:https://phpqa.io
```
But the response has no `Access-Control-Allow-Origin` header.

**Comment by MetalArend** [comment]
From https://www.html5rocks.com/en/tutorials/cors/ I read:

> Access-Control-Allow-Origin (required) - This header must be included in all valid CORS responses; omitting the header will cause the CORS request to fail. The value of the header can either echo the Origin request header (as in the example above), or be a '*' to allow requests from any origin.

Somehow the header is not there in the response. As it might be the plugin's fault, I just stumbled upon https://github.com/nelmio/NelmioCorsBundle/issues/68.

**Comment by MetalArend** [comment]
Hooray, all calls are coming back nicely!

Big thanks for fixing this. And for providing this simple yet effective service - it is a big help.

Just to make sure: as you are caching these requests, and probably are getting many requests per second, is it okay to use the API like this on our page? It is on the roadmap to add some local caching nonetheless, but I want to make sure to not be a bad user of your service ;)

**Comment by Seldaek** [comment]
It's fine but it does weird requests like https://packagist.org/packages/.json and then that results in a redirect to https://packagist.org/search?q=.json&reason=vendor_not_found so it requests that too. Probably wanna look at the requests you're doing there :)

**Comment by Seldaek** [comment]
And yeah generally speaking caching wouldn't hurt I guess.

**Comment by MetalArend** [comment]
Ah, yeah, those `.json` requests must be of the packages that don't have packagist, have to fix that. Thanks for letting me know.

**Comment by MetalArend** [comment]
Fixed the empty requests.
