### ISSUE TITLE
Enquiry: Process for repo owner to assign packagist maintainer (in absentia of existing maintainer)

### ISSUE THREAD

**Issue by tractorcow** [composer/packagist#793]
In the situation where a repository admin, whether an individual or an organisation, has control over the github repository of a package, but is not currently one of (or able to communicate with) the assigned maintainers on the packagist registration, what is the process for regaining control of maintainer status?

This situation normally arises when a colleague registers a package for an organisation, and then either goes on temporary leave, or moves positions, leaving the package running but out of direct control by the organisation.

My best digging led me to https://github.com/composer/packagist/issues/503, which suggested that it could be achieved in a haphazard way via a composer.json authors registration. I concur with the suggestion that this is not a robust way to deal with this situation (due to the lack of explicit mapping between composer authors and a packagist username). However, this still leaves a lack of a remedy.

Before I make any suggestions as to what kind of process would be nice, can someone please tell me what system is in place already? Does it require someone to directly contact packagist support and confirm their identity, or some other human process? If so, could this process be documented in an accessible place?

In the absence of any existing process, I would suggest something self-administered, that might provide an API for any admin of a repository to self-assign them to the packagist maintainers list. Of course, that may be complicated, and others are probably better aware of the security concerns than myself. :)

**Comment by Seldaek** [comment]
The current system is contact@packagist.org - where I deal with such requests on a case by case basis. Usually it's reasonable requests. It's not really worth it for me to develop a more complex automated system as doing it by hand really doesn't take all that long. If someone wants to solve it somehow that'd be cool as I don't particularly enjoy dealing with this though ;)

**Comment by tractorcow** [comment]
Thanks @Seldaek, that's a good an answer as I was hoping for. :) I appreciate the prompt response!
