### ISSUE TITLE
Cannot get the last version of a package from the API

### ISSUE THREAD

**Issue by ciaoben** [composer/packagist#795]
I am writing an automation tool, but having problem finding the last version of a package through the API, eg.:

`https://packagist.org/packages/aws/aws-sdk-php-laravel.json`

In the array versions the entries are in a random order:
```
"versions": {
            "dev-master": {},
            "1.0.x-dev": {},
           "dev-revert-105-1.0": {},
            "dev-sdk3": {},
            "2.0.x-dev": {},
            "dev-fix-remove-config_path": {},
            "3.1.0": {},
            "3.0.3": {},
            .....}
```
and this makes it really hard if not impossible to understand what is the last version of a package through the api.

Am I missing something? I really hope so because all my idea would crash if this is the case :(

**Comment by stof** [comment]
Well, returning sorted versions is not a guarantee we can make, as versions are not all comparable (for instance, `dev-revert-105-1.0` cannot be sorted, as it is not a branch version matching to a version number).
Thus, `last version` can have different meaning (if I release 3.0.3 after 3.1.0, which one is the last version ?).

Btw, depending on the endpoint being used (the JSON endpoint you used above, or the dumped files from the Composer repository, which are better for performance as they are static files), the order will be different (I'm not even sure the JSON endpoint guarantees an order).

to find the highest version, I suggest you to rely on the `version_normalized` field of each version, and using `version_compare` as a sorting function (removing first versions where the normalized version starts with `dev-` as these are not sortable).
Btw, if you want only releases (regardless of being an alpha release or a stable one) and not branches, you can use the `dev` field of the version to identify the branch.
If you want to find the latest version, you can use the `time` field of each version to perform the sorting.

**Comment by ciaoben** [comment]
@stof thanks for the explicative answer. 

So I could theoretically get the version with the last timestamp on the branch master, and I would be sure that is the one that a user download if he's doing the same moment (without dep restrictions obviously). Right?

**Comment by stof** [comment]
Composer's selection is about selecting the highest version, not the latest released version.

> edit: I cannot see any dev field in the output..

sorry, there is no `dev` field in this endpoint (I don't remember if only the other endpoint has it, or whether the field was removed at some point). If you need it, you can comput it like this: `$dev = false !== strpos($version_normalized, 'dev')`

**Comment by BlazeIsClone** [comment]
Just as @stof mentioned earlier here is what I came up with.

```php
namespace App\Services;

use Composer\InstalledVersions;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Http;

class PulseService
{
	/**
	 * Get installed packages and their dependencies.
	 */
	public function getPackagesAndDependencies(): array
	{
		$requiredPackages = $this->getComposerArray()['require'];

		$latestVersions = $this->getLatestVersions($requiredPackages);

		$packages = [];

		foreach ($requiredPackages as $name => $version) {
			if ($name !== 'php') {
				$packages[] = [
					'name' => $name,
					'current_version' => InstalledVersions::getVersion($name),
					'latest_version' => $latestVersions[$name] ?? InstalledVersions::getVersion($name),
				];
			}
		}

		return $packages;
	}

	/**
	 * Get the composer file contents.
	 */
	private function getComposerArray(): array
	{
		$json = file_get_contents(base_path('composer.json'));

		return json_decode($json, true);
	}

	/**
	 * Get latest versions of packages from Packagist.
	 */
	private function getLatestVersions(array $requiredPackages): array
	{
		$latestPackages = [];

		foreach ($requiredPackages as $package => $version) {
			if ($package !== 'php') {
				$response = Http::get("https://repo.packagist.org/p/{$package}.json");
				$packageData = $response->json();

				if (isset($packageData['packages'][$package])) {
					$packageRepository = $packageData['packages'][$package];

					$stableVersions = array_filter($packageRepository, function ($key) {
						return strpos($key, 'dev') === false && strpos($key, 'beta') === false;
					}, ARRAY_FILTER_USE_KEY);

					uasort($stableVersions, function ($a, $b) {
						return $a['time'] <=> $b['time'];
					});

					if (!empty($stableVersions)) {
						$latestPackages[$package] = Arr::last($stableVersions)['version_normalized'];
					}
				}
			}
		}

		return $latestPackages;
	}
}

```

**Comment by stof** [comment]
@BlazeIsClone please open a new issue instead of commenting on an issue from 2017. Things have changed since then.
