### ISSUE TITLE
adding a section explaining who can submit a package

### ISSUE THREAD

**Issue by Grummfy** [composer/packagist#800]
Hello,
in open source most of the time we work as team. On github you can specify several teams inside a same organisation (https://github.com/orgs/XXX/teams).

When a new project came up, most of the time is inside the same organisation (github.com/XXX/new-project). But sometimes it's not the same that are in charge of this new project than the other main project.

So my point is, could you make a bit more explicit, through some documentation, who can submit new package in this case?

thanks

**Comment by Seldaek** [comment]
Well when you try to submit a package it does explain you to contact one of the maintainers of any of the packages in the vendor if there is a conflict.. If you or someone else would like to provide more docs somehow I'm not against it but not sure where to best explain this.
