### ISSUE TITLE
Your configuration does not allow connections

### ISSUE THREAD

**Issue by jefry86** [composer/packagist#802]
Uncaught Exception: [Composer\Downloader\TransportException] Your configuration does not allow connections to http://gitlab.xxxx/xxxx/xxxxx.git. See https://getcomposer.org/doc/06-config.md#secure-http for details.

>composer config -gl
[secure-http] false

**Comment by stof** [comment]
I don't see how this relate to Packagist itself.

And `-g` in your command line means you looked only at the global config, ignoring any project-level config, so this is not the value being used.
