### ISSUE TITLE
Packagist doesn't sync profile picture with GitHub

### ISSUE THREAD

**Issue by elsieholmes** [composer/packagist#803]
Hello!
I changed my GitHub profile picture recently, but my Packagist account didn't fetch it, so one can still see my old profile pic on the package's page and the worst thing about it all is that there seems to be no option to manually change it. Is there an existing way to do it or I've found a real bug?
Thanks in advance!

**Comment by Seldaek** [comment]
Packagist only fetches avatars from gravatar.com based on your email address. GitHub does too btw unless you update it on GitHub itself, so do many other services, so I'd recommend using gravatar as it simplifies changing one's avatar greatly.
