### ISSUE TITLE
To make it work with index.php 

### ISSUE THREAD

**Issue by com2** [composer/packagist#807]
Renaming app.php to index.php does not work. I also renamed app.php in .htaccess but that does not help. Any suggestion how to make it work without the ugly php file in the URL?

**Comment by stof** [comment]
Why are you trying to rename files ?

**Comment by com2** [comment]
It is working like
>  https://packagist.test/app.php/register/

 but I want it work like
>  https://packagist.test/register/

I tried [this suggestion](https://stackoverflow.com/questions/11149526/symfony2-rewrite-rules-htaccess-app-php?answertab=active#tab-top) but it keeps saying "The requested URL /login/ was not found on this server."

**Comment by stof** [comment]
well, if you use Apache, the `.htaccess` should already make this work (assuming you have mod_rewrite in your Apache setup, but I think it is ON by default in most distributions).
If you use Nginx, look at the Symfony documentation for the proper configuration for a Symfony project.

**Comment by com2** [comment]
Yes it's fixed. The default apache2.conf has AllowOverride none
