### ISSUE TITLE
CI build is not running all tests

### ISSUE THREAD

**Issue by Jean85** [composer/packagist#808]
I was trying to contribute to this project, and I started to build my local dev env. During this process I discovered that:

 * the Travis build is not running all tests ([only 5!](https://travis-ci.org/composer/packagist/builds/265946063#L455))
 * the Travis build uses PHPUnit 6.3, the project requires 5 (it invokes `phpunit` instead of `vendor/bin/phpunit`)
 * a lot of tests are broken due to the fact that by default in MySQL we have `ONLY_FULL_GROUP_BY` enabled, that triggers some errors when filtering results in queries
 * I'm unable to set up Solr correctly

If it could be helpful, I can open a WIP PR with a basic docker-compose setup that I'm currently using, to help diagnose the issue.

**Comment by Jean85** [comment]
Ok, I've updated the PR but unfortunately the build is behaving in a strange way: when building in this repo it goes well, but it runs in the described way; when it runs [on my fork](https://travis-ci.org/Jean85/packagist/builds), it uses PHPUnit 5 and runs more tests, with failures. Is there any specific setting on Travis for this repo that's causing this strange behavior?

**Comment by stof** [comment]
For tests not running, I think this is related to the usage of PHPUnit 6 (with some classes still extending the `PHPUnit_Framework_TestCase` and so not considered test cases in PHPUnit 6).

Updating Travis to `vendor/bin/phpunit` would be the first step (and this can be done in a PR easily without working on a docker-compose environment)

**Comment by Jean85** [comment]
I can work on that on a separate PR, maybe tomorrow.

**Comment by Seldaek** [comment]
https://travis-ci.org/composer/packagist now builds as I did the vendor/bin/phpunit tweak, so that's good, thanks for spotting that, I completely missed the fact that travis was skipping a lot of tests. As for solr, no need to worry as it's gone now (#805).

**Comment by Jean85** [comment]
Good to know that Solr is gone/going away... I'll try to help on that!

But... I think that Travis is till skipping some tests. In my PR (#810) [I see 56 executed tests](https://travis-ci.org/composer/packagist/builds/274959563#L665), in your build [I see 50](https://travis-ci.org/composer/packagist#L634)..

**Comment by Seldaek** [comment]
Yup, I deleted some Solr tests so that's normal. I'll get your PR merged in a bit.
