### ISSUE TITLE
No result after hitting enter on search

### ISSUE THREAD

**Issue by theofidry** [composer/packagist#811]
Issue: after hitting enter once typing a search keyword, the result page goes blank.

Steps to reproduce:

Go on the website:

<img width="1440" alt="screen shot 2017-09-13 at 13 59 19" src="https://user-images.githubusercontent.com/5175937/30378710-f6413e04-988b-11e7-83e3-39efac752f1d.png">

Type something:

<img width="1440" alt="screen shot 2017-09-13 at 13 59 46" src="https://user-images.githubusercontent.com/5175937/30378714-feac7c98-988b-11e7-9632-8fd046e098df.png">

Sometimes the search is quick enough and you see results appearing. So everything works fine. However if you type a bit too fast and is impatient and/or used to type enter to trigger the search, when you hit enter, you get:

<img width="1440" alt="screen shot 2017-09-13 at 13 59 41" src="https://user-images.githubusercontent.com/5175937/30378755-2aa988c2-988c-11e7-8290-91bd8d835844.png">

Also note the URL changing when doing so.

**Comment by jordikroon** [comment]
It does work when you replace the search_query[query] to `q` or `query`, but I don't think renaming the name in the form is _the_ solution given the references in the controller.

**Comment by stof** [comment]
Well, we should ensure that the form and the JS code are using the same name for the query when doing the search, so that we don't have 2 different URLs
