### ISSUE TITLE
typo in line 59 and 173 @ ./src/Packagist/WebBundle/Controller/WebController.php

### ISSUE THREAD

**Issue by browseman** [composer/packagist#816]
There are two typos in Lines 59 and 173 I guess. Probably the symbols '??' should be '&&' or '||'. The error is clearly reproducible while executing the following command:
app/console cache:warmup --env=prod

I've tried to replace with '&&' (without looking deeply in to the code, just for test) and it's working fine. 
Hope this information is enough and will help in somehow. 

Have a great day :)

**Comment by stof** [comment]
`??` is a valid PHP operator since PHP 7

**Comment by stof** [comment]
and changing it to a boolean operator would break the code entirely (this is PHP code, not JS code, so `||` cannot be used to set a default value. It always produces a boolean)

**Comment by browseman** [comment]
My mistake then, I didn't realize that the packagist is requiring PHP7. You can close the issue.

**Comment by stof** [comment]
well, the composer.json says `>= 5.6` but I just opened a PR to fix that.

Anyway, this is the source code for the packagist.org site, and any other usage of this codebase is not officially supported. So the only PHP version needing to be supported is the one running on the Packagist server.

**Comment by browseman** [comment]
Currently I'm running PHP 5.6.30, but with '??' operator I've get errors like:
PHP Parse error:  syntax error, unexpected '?' in /var/www/packagist.test.fb/src/Packagist/WebBundle/Controller/WebController.php on line 59
+
PHP Parse error:  syntax error, unexpected '?' in /var/www/packagist.test.fb/src/Packagist/WebBundle/Controller/WebController.php on line 173

If I understand you correctly it should work with 5.6.30, correct me if I'm wrong.

BTW - Just spot one more issue (please excuse me if this is not the correct place to report it):
./app/console packagist:index --no-debug --env=prod

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "packagist:index" is not defined.                       
  Did you mean one of these?                                      
      **packcagist:index**                                            
      packagist:dump                                              
      packagist:update                                            
      packagist:tokens:generate                                   
      packagist:stats:compile                                     
      packagist:clear:versions                                    
                                                                  
I guess that, this time the issue is a real typo...

**Comment by alcohol** [comment]
That definitely looks like a typo. Please submit a PR :-)

**Comment by alcohol** [comment]
> If I understand you correctly it should work with 5.6.30, correct me if I'm wrong.

No, it should work with `>= 7.0`.

**Comment by browseman** [comment]
> That definitely looks like a typo. Please submit a PR :-)

I've submitted a PR. It's the first one I'm submitting so there is a big possibility to make things incorrectly. Let me know if I made some mistake.

Thanks in advance.
