### ISSUE TITLE
Search results doesn't show current page.

### ISSUE THREAD

**Issue by emil-nasso** [composer/packagist#819]
If I search for swagger on packagist, move to page two and then clicks anywhere on the page, there is nothing that indicates what page I'm currently on. This makes browsing and looking through the results a bit troublesome.

This is what being on the seconds page result looks like:

![https://dl.dropboxusercontent.com/s/tyrrszr54anfimz/2017-09-20%20at%2012.20.png](https://dl.dropboxusercontent.com/s/tyrrszr54anfimz/2017-09-20%20at%2012.20.png)

**Comment by julienbourdeau** [comment]
You're right, I'll look into this.
