### ISSUE TITLE
Transfer origin package from bitbucket to github

### ISSUE THREAD

**Issue by reginaldojunior** [composer/packagist#821]
Hello,

Before, this respository was in bitbucket, but I changed to github, and now the packagist get it from bitbucket. So, how can I change this source to github respository? 

Package: https://packagist.org/packages/pluggto/pluggto-php

Old Origin: bitbucket.org/pluggto/pluggto-php.git
New Origin: https://github.com/plugg-to/pluggto-php

**Comment by Seldaek** [comment]
I updated the URL, but next time you could do it yourself using the "edit" button on the package page as you are the maintainer.
