### ISSUE TITLE
Package name constraints differ from composer's

### ISSUE THREAD

**Issue by svenluijten** [composer/packagist#822]
In [composer's documentation](https://getcomposer.org/doc/04-schema.md#name), it's mentioned that a package name can contain whitespace. It only says it needs a vendor name and the project's name:

![desc](https://i.imgur.com/VGurB9W.png)

This would mean the regex should be quite simple to check if the package name is valid: `(.+)\/(.+)`.

However, while trying to submit [this repository](https://github.com/svenluijten/packagist-test/tree/147cdb2aa022979a105421fe00abc42543887309) to Packagist's website, I get the following error: 

```
The package name my vendor/some package is invalid, it should have a vendor name,
a forward slash, and a package name. The vendor and package name can be words
separated by -, . or _. The complete name should match 
"[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*".
```

Is this an error in Composer's documentation, or should the validation rules on https://packagist.org be loosened?

**Comment by Seldaek** [comment]
Composer is a tool, and it's flexible. On Packagist, which is just one repository amongst others, we set stricter restrictions on naming because we need to be able to serve things via URLs, etc. I don't see a problem with those two things not matching. According to Composer you can call your packages whatever you want, but not on Packagist :)

**Comment by svenluijten** [comment]
Huh, alright, that makes sense. I've always seen the two as closely coupled, but I suppose that isn't the case (anymore). Thanks for the clarification!

**Comment by stof** [comment]
`composer validate` should also be displaying you a warning when the package name you used does not match the regex supported by Packagist btw.

**Comment by stof** [comment]
@Seldaek we might want to add a note in the doc to mention that Packagist has additional requirements on the name though
