### ISSUE TITLE
Package page updated fine, JSON version not

### ISSUE THREAD

**Issue by amosmos** [composer/packagist#824]
Hi!

In this package page: https://packagist.org/packages/boaideas/laravel-shopify the version number is 1.0.0 and the downloads count is 1,

while on the JSON version: https://packagist.org/packages/boaideas/laravel-shopify.json the only version is dev-master, and the number of downloads is 0.

There are other differences, but you get the point.

Is this because of me doing something wrong?

Thanks,
Amos

**Comment by Seldaek** [comment]
The json API is cached for up to a day as we have a lot of people scanning all packages, so it takes a while to update. Nothing to worry about.
