### ISSUE TITLE
Packagist structure

### ISSUE THREAD

**Issue by Webysther** [composer/packagist#825]
I see packagist.org have two copies of same file:

Whitout hash: https://packagist.org/p/0s1r1s/dev-shortcuts-bundle.json
With hash: https://packagist.org/p/0s1r1s/dev-shortcuts-bundle$6c7710a1ca26d3c0f9dfc4c34bc3d6e71ed88d8783847ed82079601401e29b18.json

They are the same, composer use the version without hash in any situation?

**Comment by stof** [comment]
No, composer always use the version with the hash, which is a static file dumped by a cron.

The dynamic version without the hash is the API meant for low-volume usage, which is simpler to use (as you don't have to explore the composer repository to know which hash to use to load the file). Composer has all the code necessary to make this exploration (thus, it does not hardcode any specific URL pattern about packagist.org and so must explore the repo) and reading the static files is much better for performance (Composer is not a low-volume usage of Packagist).

**Comment by Webysther** [comment]
Great explanation. Thanks.

**Comment by Seldaek** [comment]
Just a small clarification here. What stof described as the dynamic version without hash is under `/packages/$name.json`. What you listed `/p/$name.json` is the static file API, just without hash. We dump both with and without hash to make it easier to retrieve the files, but Composer atm only uses the ones with hash. See more at https://packagist.org/apidoc#get-package-data
