### ISSUE TITLE
[ErrorException]   file_exists(): open_basedir restriction in effect. HALP PLS!

### ISSUE THREAD

**Issue by Schoggiei** [composer/packagist#827]
So i'm trying to install the composer and i get this error : "[ErrorException]
  file_exists(): open_basedir restriction in effect." I have searched online and found nothing that works.
I'm new to this so thanks in advance...

**Comment by Seldaek** [comment]
This sounds like a PHP setup issue and nothing to do with Composer. Check your php.ini for open_basedir and remove it if possible.
