### ISSUE TITLE
Packagist and Apache Alias

### ISSUE THREAD

**Issue by com2** [composer/packagist#829]
My packagist shares domain with another app and I used Apache's Alias this way:

    Alias /packagist /var/www/packagist/web

When I do an composer require it does not include the the /packagist in the URL:

```
 [Composer\Downloader\TransportException]
  The "https://mydomain.com/p/vendor/package%241ec551a85cab7cc2063c7a43b78761af5799ac9bd86cd243fa30da6a744e6d57.json" file could not be downloaded (HTTP/1.1 404 Not Found)

```
The path should have been: 

```
https://mydomain.com/packagist/p/vendor/package%241ec551a85cab7cc2063c7a43b78761af5799ac9bd86cd243fa30da6a744e6d57.json
```
I tried including Rewritebase /packagist in .htaccess but it did not fix it the issue. 

```
# ----------------------------------------------------------------------
# Symfony front controller
# ----------------------------------------------------------------------

<IfModule mod_rewrite.c>
  RewriteBase /packagist
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ app.php [QSA,L]
</IfModule>

```
 
Is there a configuration option to set the correct path?

**Comment by stof** [comment]
Custom deployments of the packagist.org codebase are not supported.

For your issue, I don't think there is any configuration setting to fix this (precisely because packagist.org does not need this)

**Comment by com2** [comment]
I will simply not use alias then. Thanks anyhow.
