### ISSUE TITLE
Help with packagist replace behavior

### ISSUE THREAD

**Issue by ryanaslett** [composer/packagist#830]
This issue is thus: on a vanilla drupal installation, with an empty cache, composer require on a new module takes about 17 seconds. The SAT solver is only .934 seconds of that time and the *vast* majority of the rest of the time is consumed downloading metadata files from packagist.org. (17 seconds is on my 1Gigabit connection in the US. I shudder to think how bad it is for somebody with terrible bandwidth)
 
Theres a couple of issues here, and either we're doing something wrong, or theres something that could be improved with the packagist codebase, and I'd like to figure out what we could do.

`drupal/core` contains many modules that are shipped with drupal in the same git repo. the composer.json for drupal/core contains a 'replace' key for each module it ships with. (see https://github.com/drupal/core/blob/8.5.x/composer.json#L52)

There are, currently, 103 modules and core packages. None of the modules have a subtree split, nor do they have a composer.json. However, because core says it 'replaces' them, packagist creates a provider file for them, and fills it with the same metadata that exists in drupal/core.
Which is big, because there are 86(?) releases so far of drupal8.  The 'core packages' were designed to be subtree splits off of core, and released as composer packages, which we have done.

And, it is *also* exacerbated by the fact that if somebody forks drupal/core on github, and submits it to packagist.org, then *their* metadata gets attached to drupal/core, and also copied to all 103 other modules. (which essentially multiplies the amount of metadata needed to download by the number of forks).

This leads to downloading about 88 mb of extra metadata spread across 103 files.

So, Im trying to find the right workaround to avoid having to download all of the metadata for drupal/core, which ends up being a whole lot of unnecessary network/bandwidth.

Some problems:
1. caching doesn't help, because each commit to drupal core, which happens daily, will eject *all* of these files from everybodie's caches due to the git commit hash of the dev branch changing, thus changing the sha256's of all the files.
2. Cleaning up bad/invalid forks doesnt help, the metadata still sticks around even if the package is deleted from packagist (related to #299 ?)

Any ideas on how we can mitigate this issue? Everybody in the drupal community believes composer to be tremendously slow, and I'd like to reduce that perception, since its not really composer, its all the metadata downloads.

**Comment by Seldaek** [comment]
This will be solved by the Composer v2 metadata format, so closing as there isn't much that can be done specifically here.

**Comment by ryanaslett** [comment]
Thats good news. Is there any docs/issues that I can follow regarding the v2 metadata format? Im also the maintainer of packages.drupal.org, so Id love to keep up with the changes (or at least have a good awareness around what they are)

**Comment by Seldaek** [comment]
Composer v2 will support the v1 format so things should work and you can then migrate at your pace to the v2 format (which we should document better at some point..). 

The core bits tho are to add a new metadata-url to packages.json (e.g. https://repo.packagist.org/packages.json) and then the files served by that should include only the package of that name, no more replacer/providers (e.g. https://repo.packagist.org/p2/drupal/drupal.json) and on top of that there is a minification format available which we really should open source some component to allow replicating it.

**Comment by Seldaek** [comment]
You can track https://github.com/composer/composer/issues/8248
