### ISSUE TITLE
Adding maintainers to projects without confirmation is an avenue for targeted harassment

### ISSUE THREAD

**Issue by klausi** [composer/packagist#837]
Problem: if you are the maintainer of a project then you can add arbitrary other people as maintainers to your project. That allows harassers to create empty projects with harassing names and pull in victims as maintainers so that it would appear as if they support the project:

Example:
* Alice the attacker creates the project "alice/nadja-penis-pics"
* Alice adds Nadja (the victim) as maintainer
* Nadja is associated with maintaining penis pics.

Solution: Github for example and other project management software only allow adding maintainers if they consent. Nadja would have to click a confirmation dialog.

**Comment by Seldaek** [comment]
We do notify when you get added, so you can't really be associated without your knowledge. Without consent sure perhaps, but hopefully this doesn't become an issue.. I don't really want to complicate the process unnecessarily, so far this hasn't been a problem so fingers crossed.
