### ISSUE TITLE
Packagist metadata tripping IDS

### ISSUE THREAD

**Issue by respinoza** [composer/packagist#838]
A few hours ago our composer stopped working as our company IDS tripped on possible known PHP variables used for web shell injection.

Has anyone reported this?

Sadly I have no more specific data but the offending URL

http://packagist.org/p/provider-latest%24657263bf8c3a4bda5018ce3b550fc2060affd14516e9ebd52b05de0d69ef615f.json

**Comment by respinoza** [comment]
URL is probably not relevant anymore because of the nature of packagist, but anyway, still, I wonder if anyone has experienced this.

**Comment by Seldaek** [comment]
could you share more details on what exactly triggered it? You can do this privately via contact@packagist.org if it's anything sensitive.

**Comment by stof** [comment]
I think this might be related to the `$` in the URL (which is URL-encoded as `%24` in the URL above)

**Comment by respinoza** [comment]
I tried to get more details, at least the specific match but no luck.
@stof you might be right, I just wonder why this just started happening. Anyway I'll do more research on my side. Thanks.
