### ISSUE TITLE
Package not updating - it always has in the past

### ISSUE THREAD

**Issue by judgej** [composer/packagist#840]
This is the source, on version 2.5.1:

https://github.com/thephpleague/omnipay-sagepay/releases

This is on packagist, stuck at 2.4.1

https://packagist.org/packages/omnipay/sagepay

I don't have access to the "omnipay" packagist account, so there may be errors I can't see there.

The githib hook is still in place with the user "adrianmacneil", and nothing has changed there so far as I know.

The composer.json validates okay. Is this likely a problem with my repository, the hook, the packagist account, the way I've made a release, or some wider issue?

Thanks :-)

**Comment by judgej** [comment]
After version `2.4.1`, I took the next release to `v2.5.0`. I'm not sure if the "v" has messed things up somehow? I took the "v" out, and then bumped a new release to `2.5.1` without a "v", but that hasn't kicked anything into action.

**Comment by Seldaek** [comment]
You have a broken branch which is blocing updates.

```
Skipped branch 30alpha1, Invalid package information: 
extra.branch-alias.dev-master : the target branch (~3.0) must end in -dev
```

**Comment by judgej** [comment]
Thanks.

**Comment by judgej** [comment]
I've renamed branch `30alpha1` to `30alpha1-dev` and all appears well.

@Seldaek the error that you pasted, is that anywhere that I, as a non-owner of this vendor or package on packagist, would be able to see, for next time I encounter a problem like this?

**Comment by Seldaek** [comment]
@judgej The only way to see this if you don't own the package is to add the package as a vcs repository to your composer.json and run `composer update -v` to see what it's doing when scanning the repo.

**Comment by judgej** [comment]
Ah, so it's composer doing the heavy lifting behind packagist updates. That makes perfect sense. Thanks.
