### ISSUE TITLE
Feature wish: hotlinkable download count svg badge

### ISSUE THREAD

**Issue by xiaohuilam** [composer/packagist#841]
RT

**Comment by pixelbrackets** [comment]
This is already possible with the service shields.io.

Example for monolog: `https://img.shields.io/packagist/dt/monolog/monolog.svg` → ![Packagist download count](https://img.shields.io/packagist/dt/monolog/monolog.svg)

**Comment by Seldaek** [comment]
Yeah I think we can close this..
