### ISSUE TITLE
Delete my outdated packages, please

### ISSUE THREAD

**Issue by tarampampam** [composer/packagist#842]
Links to the packages below:

* https://packagist.org/packages/avtoraport/b2b-api-php
* https://packagist.org/packages/avtoraport/b2b-api-php-laravel

> Reason: I cant find "Delete" button.

Yes, I know about consequences. Thanks for your time.

**Comment by SerafimArts** [comment]
Same

**Comment by neroux** [comment]
@tarampampam Sorry for hijacking this issue, but there is no other way of contacting you and you seem to have disabled notifications for https://github.com/tarampampam/random-user-agent

Could you clarify if you have stopped work on random-user-agent?

Thanks a lot.

**Comment by tarampampam** [comment]
@neroux - oh s**t, notifications, sorry.

I have a lot of work in offline, so I will check all issues in this weekend, ok? Sorry for this, dude

**Comment by neroux** [comment]
No worries, thats why the "nudge" :) Just wanted to check whether you let the project go.

Take your time.

**Comment by tarampampam** [comment]
@stof check this ussue, please

**Comment by stof** [comment]
I'm not a Packagist maintainer. I don't have any access to the prod server to remove it. I'm not even part of the composer team. So I cannot do anything for you here.

**Comment by Seldaek** [comment]
Done

**Comment by tarampampam** [comment]
@Seldaek great thx 2 u!

**Comment by tarampampam** [comment]
@Seldaek please, delete this packages too:

- https://packagist.org/packages/tarampampam/laravel-dusk-tester
- https://packagist.org/packages/tarampampam/laravel-ide-helper
- https://packagist.org/packages/tarampampam/mikrotik-hosts-parser

**Comment by Seldaek** [comment]
@tarampampam done

**Comment by tarampampam** [comment]
@Seldaek great thanks!

**Comment by tarampampam** [comment]
@Seldaek Could you please remove the package https://packagist.org/packages/tarampampam/wrappers-php also, please

**Comment by Seldaek** [comment]
Done

**Comment by tarampampam** [comment]
@Seldaek And this one, please - https://packagist.org/packages/tarampampam/guzzle-url-mock
