### ISSUE TITLE
Version is updated on packagist.org website, but not in the API (revisited)

### ISSUE THREAD

**Issue by mmucklo** [composer/packagist#845]
(same as #352)

Updated a tag hours ago.  Website is correct, however packagist API is not showing the latest version.

Missing Version Number is: 2.7.12

Missing here:
https://packagist.org/p/mmucklo/queue-bundle.json

But Shows here:
https://packagist.org/packages/mmucklo/queue-bundle

**Comment by cweagans** [comment]
We're seeing the same thing with `drupal/core`. New tag is 8.4.3 (which is showing up in the UI), but https://packagist.org/p/drupal/core.json only has up to 8.4.2.

**Comment by froboy** [comment]
Looks like `drupal/core` 8.4.3 is showing up now in the json linked above. 🎊

**Comment by mmucklo** [comment]
Confirmed that 2.7.12 for mmucklo/queue-bundle is now showing as well.
