### ISSUE TITLE
Don't focus search bar on detail pages

### ISSUE THREAD

**Issue by lornajane** [composer/packagist#849]
I have difficulty using the packagist website because it focuses the search bar on every page.  I need accessibility tools to navigate a page or click on anything, and they are keyboard-based.  As soon as I find the page I need and try to do anything, ooops I've typed into a search box in the header and navigated to another set of search results and now need to start again.

Some interesting references and discussion on the issue of autofocussing fields for accessibility here https://stackoverflow.com/questions/2180645/is-automatically-assigning-focus-bad-for-accessibility/2180679#2180679

I'm happy to try to fix it if this seems like something that might be accepted.

**Comment by Seldaek** [comment]
Yes I can see that on the detail pages it probably doesn't make lots of sense. This is done in search.js the algolia init contains `autofocus: true`. I guess this needs to be made dependent on a global variable defined in the main layout page or something. I can look at that but not for a couple weeks I guess, but feel free to have a go at it if you have time :)
