### ISSUE TITLE
Packagist does not update releases

### ISSUE THREAD

**Issue by mirko-pagliai** [composer/packagist#861]
Hello, I have [this repository](https://github.com/mirko-pagliai/js-cookie
) that is a fork of [this other repository](https://github.com/js-cookie/js-cookie). Basically, compared to the original repository, I only added the `composer.json` file.

And this is [my package](https://packagist.org/packages/js-cookie/js-cookie) on Packagist.org.

As you can see, the latest available version is `v2.1.3`. Instead, there are `v2.1.4` and `v.2.2.0` versions on the repository, as tags and as releases.

Why?

**Comment by Seldaek** [comment]
```
Reading composer.json of js-cookie/js-cookie (v2.2.0)
Skipped tag v2.2.0, no composer file
Reading composer.json of js-cookie/js-cookie (v2.1.4)
Skipped tag v2.1.4, no composer file
Reading composer.json of js-cookie/js-cookie (v2.1.3)
Importing tag v2.1.3 (2.1.3.0)
Reading composer.json of js-cookie/js-cookie (v2.1.2)
Skipped tag v2.1.2, no composer file
```

You need a composer.json file in every tag for it to be picked up.
