### ISSUE TITLE
Oath 'Error while sending HTTP request'

### ISSUE THREAD

**Issue by tomthetommy** [composer/packagist#862]
So we've followed the guide: /docs/enterprise/gitlab-integration-setup

... and we're getting this error: 

![image](https://user-images.githubusercontent.com/16326542/35345193-e87f05d6-0126-11e8-83dc-050242e9f615.png)

We've configured it with an on-premise gitlab server. 

I initially thought it could be an SSL error on the git server as it was missing our internal PKI root / intermediate bundle. I've verified it's working at the OS level with a curl. 

It could even be that the gitserver isn't picking up our bundle. I'm not sure.

Any ideas?

**Comment by stof** [comment]
This repository is about the public packagist. I'm not sure it is the appropriate place to report issues about private packagist (which is a different codebase AFAIK)

**Comment by Seldaek** [comment]
Indeed please reach out to contact@packagist.com for support about Private Packagist.

**Comment by tomthetommy** [comment]
Sorry yes this was the wrong place entirly.

The issue turned out to be specifically because our internal root / intermediate bundle was not a part of the docker container, so the SSL was failing.
