### ISSUE TITLE
How to limit branches or tags from being imported

### ISSUE THREAD

**Issue by jurgenhaas** [composer/packagist#865]
We do have a package like e.g. https://gitlab.lakedrops.com/composer/library/docker-traefik and packagist is updating the master branch and all tagged versions just fine. We can trigger that by either clicking the green "Update" button in the web ui or by posting a request to the packagist API.

Now, in our GitLab repository we also have branches that are used for development purposes only and they should not be listed on the packagist project page.

Is there a way to tell packagist to only import tags and the master branch but to ignore other branches?

**Comment by fulopattila122** [comment]
The only way (at the moment) to hide a branch from packagist is to [remove the composer.json](https://stackoverflow.com/questions/24372839/is-there-a-way-for-composer-to-ignore-a-branch) file from the branch.
