### ISSUE TITLE
Packagist does not take tags/releases that i push on github

### ISSUE THREAD

**Issue by batmahir** [composer/packagist#869]
This is my releases/tags on github :
![image](https://user-images.githubusercontent.com/20837786/35792312-737dca64-0a87-11e8-9a18-981f73b5c49a.png)

This is my packagist :
![image](https://user-images.githubusercontent.com/20837786/35792375-c58d1a12-0a87-11e8-84f6-d91f2c107542.png)

This is my composer.json 
![image](https://user-images.githubusercontent.com/20837786/35792423-0aaf1000-0a88-11e8-8b23-990f17724d34.png)

Someone please help me :(

**Comment by Seldaek** [comment]
Tags can not contain "-dev" but I guess you figured it out as you stopped using that.
