### ISSUE TITLE
Can't update message is unreadable

### ISSUE THREAD

**Issue by Shelob9** [composer/packagist#871]
When trying to update a package with an invalid composer.json the message I see on the screen is unreadable:

![screen shot 2018-02-05 at 1 11 54 pm](https://user-images.githubusercontent.com/1994311/35821240-52b9dc0c-0a76-11e8-94b0-11f87a964924.png)

I am seeing this with Chrome for OSX - Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by Seldaek** [comment]
Can't reproduce this here..
