### ISSUE TITLE
How to delete my outdated packages from packagist.org?

### ISSUE THREAD

**Issue by edoger** [composer/packagist#875]
![image](https://user-images.githubusercontent.com/13347928/36082014-a2ac21f6-0fe0-11e8-8774-6c3e5ac1ab8e.png)
I can not find any delete button!

**Comment by stof** [comment]
Packagist does not allow to delete packages with too many installs (without contacting maintainers), because people might rely on them.

The first step would be to mark it as abandoned, so that people using it get a warning.

**Comment by edoger** [comment]
@stof This is my package for testing, used to test the cluster can be updated normally, but after the test is complete, I found it can not be deleted.

**Comment by mlantz** [comment]
Is there a way to make an exception, I have a couple old packages in this context as well, even an 'archive' option which will take it out of views for me a person who maintains multiple packages?

**Comment by alphex** [comment]
I'd like to figure this out as well.    drupal/ldap isn't working for DRUPAL 8 at the moment because of a Packagist conflict : https://github.com/liip-forks/drupal-ldap/issues/1#issuecomment-378219925

Thoughts?  best way to handle this?   Thank you!

**Comment by Seldaek** [comment]
Please reach out to contact@packagist.org for deletion enquiries.
