### ISSUE TITLE
Transparent renaming of packages

### ISSUE THREAD

**Issue by javiereguiluz** [composer/packagist#876]
First, thanks to all the Composer community and its leaders for the amazing work you do!

-----

There's been a lot of questions about renaming packages: #47, #225, #496, etc. The [current best practice](https://github.com/composer/packagist/issues/47) is to:

1. Update the name in `composer.json` on the master branch
2. Resubmit the package to Packagist using the new name
3. Mark the old package as `Abandoned` on Packagist, and point people to the new package
4. Lose all the download stats and history of the original package

We recently renamed `symfony/symfony-demo` to `symfony/demo` on GitHub. Everything kept working thanks to the internal GitHub redirections ... but you still have to create the project with `composer create symfony/symfony-demo` instead of `composer create symfony/demo`

In [this comment](https://github.com/composer/packagist/issues/496#issuecomment-143700502) you said that losing the stats/history is not such a big deal ... but I think it's devastating for the reputation of the project:

* Existing users will see that the (old) package is abandoned --> not trustworthy!
* New users will see that the (new) package has no downloads --> not trustworthy!

**My question**: are you open to the idea of transparent renamings as performed by GitHub and others? Thank you!

**Comment by javiereguiluz** [comment]
I'm closing this because I already renamed my package following the recommended best practices, so I won't need this feature. Cheers!

**Comment by hopeseekr** [comment]
What are the "recommended best practices?" The only thing I've seen is "Abandon the old name and fuck your existing install base right in the ass" or "Fork the repo and keep them identical except the composer.json."
