### ISSUE TITLE
resources not loaded due to content-security policy

### ISSUE THREAD

**Issue by Lewiscowles1986** [composer/packagist#879]
It's not a big issue, but images linked in GitHub readme files don't load giving a console error 

```
rfc1867:1 Refused to load the image 'https://raw.github.com/Lewiscowles1986/rfc1867/HEAD/diagram/class-relationship.png?raw=true' because it violates the following Content Security Policy directive: "img-src 'self' https://www.gravatar.com/ https://camo.githubusercontent.com/ https://ssl.google-analytics.com/ http://www.google-analytics.com/".
```

**Comment by spmsupun** [comment]
Any updates on that ?

**Comment by Lewiscowles1986** [comment]
still the case for me I'm afraid.

**Comment by spmsupun** [comment]
Use imgur.com

**Comment by Lewiscowles1986** [comment]
If that's honestly your only input you don't understand the problem...

![image](https://user-images.githubusercontent.com/2605791/36733065-5de92616-1bc7-11e8-85bb-8aa3bacd6b90.png)

**Comment by spmsupun** [comment]
😄  I uploaded my image image imgur.com and used its as `<img src="https://i.imgur.com/hGzLkvc.png">`
then github automatically convert it into anonymized image URLs (https://help.github.com/articles/about-anonymized-image-urls/) then your image look like that: `<img src="https://camo.githubusercontent.com/6f3973f2f4430adeb221a142f0977a1f5e90f25d/68747470733a2f2f692e696d6775722e636f6d2f68477a4c6b76632e706e67" data-canonical-src="https://i.imgur.com/hGzLkvc.png" style="max-width:100%;">`

When you use github raw data, github doesn't convert your image to camo.
About fonts, I don't think you can use in packagist

**Comment by Lewiscowles1986** [comment]
I'm not using fonts. And the images are linked to the repo for a reason. If you know of a script to POST to imgur API and rewrite using `sed` before commit, I'm all ears, but the problem as I understand it is that the CSP is too strict. (What's wrong with raw git urls?)

**Comment by spmsupun** [comment]
look at the error messages, you can only use few providers for image.

**Comment by stof** [comment]
Regarding the font loaded as a data URL (and blocked because of that), this is weird as I cannot reproduce the issue. Can you give more details about which page is triggering this and details about your environment (browser, version of the browser, OS, ...) ?

**Comment by Lewiscowles1986** [comment]
Sure, Chrome on Linux 64-bit

![image](https://user-images.githubusercontent.com/2605791/36784680-341de61c-1c78-11e8-96b6-e8596a076c8b.png)
![image](https://user-images.githubusercontent.com/2605791/36784691-3e89cfc6-1c78-11e8-8590-191f89919760.png)

I'm also not getting for fonts in Firefox. weird...

**Comment by stof** [comment]
Using Chromium on Ubuntu, I'm not getting these issues either for the font

**Comment by Lewiscowles1986** [comment]
I've searched `~/.config/google-chrome/Default` using `grep -rl $data-uri`. Looks like it's Grammarly extension making the font errors :blush: The image problem should be fixed when #885 gets merged.

**Comment by arcanck** [comment]
Hi,

I'm having the same problem with README.md from a repository in GitLab. The links of the images are from my site and also the badges of Shields.io.
Any ideas or suggestions?

**Comment by stof** [comment]
@arcanck can you give the link to you package ?

**Comment by arcanck** [comment]
@stof, the link to my package is [https://packagist.org/packages/kimera/lux](this).

**Comment by Lewiscowles1986** [comment]
:laughing: :rofl: still doesn't load my package images and I'm the one that raised the issue...

**Comment by Lewiscowles1986** [comment]
Doesn't load @arcanck linked above either

**Comment by Seldaek** [comment]
The fix at https://github.com/composer/packagist/pull/891 was missnig a `/` in the URL, so it failed. Just deployed another fix now.
