### ISSUE TITLE
Show date of latest version in package list

### ISSUE THREAD

**Issue by robsch** [composer/packagist#880]
It would be nice to get a quick impression whether a package/project is old or still alive. For me it is just as significant as the download and the star number. I probably don't want to require a package that is already some years old, though it has many downloads or stars. On the other side, there might be packages which are new (and stable) but which are not very well-known yet. I think it would helpful if users can see this information immediately, without goint into the package overview page.

Would that be possible? Or would it be more reasonable to show the date of the last activity? I'm not sure how to deal with just-dev-master packages that have no tags. Maybe different kind of dates (hinting the branches) could be shown. Or showing only dates of the latest stable release could encourage maintainers to create tags

Alternatively the passed time could be shown. 

Sorting to the latest release date would be a nice option too, but afaik there is no sorting yet.

**Comment by Seldaek** [comment]
We already show the last tag date by default or last commit date if you check a branch. I am not sure what else to show really. Making such decisions is a mix of last change date, open issues, etc. And the scope of the project too. Some things are very stable and do not change often, it doesn't mean they are bad. I don't think we can really automate this decision process.

**Comment by robsch** [comment]
I was talking about the list. One cannot get a quick impression on this page about the current activity state. You're right, sometimes a project may not be updated anymore since it is feature complete. But often it is interesting to see that is (still) in development. And it would intersting to sort by date somehow. Just my opinion...

<img width="1165" alt="bildschirmfoto 2018-05-15 um 09 45 37" src="https://user-images.githubusercontent.com/2900992/40043481-daa90dc6-5824-11e8-9afe-01d61dfa34bd.png">

**Comment by robsch** [comment]
Something similar is in the project list at GitHub. I guess project are already sorted by activity. I thought about _something_ like that.

<img width="838" alt="bildschirmfoto 2018-05-15 um 10 03 11" src="https://user-images.githubusercontent.com/2900992/40044638-414366f0-5828-11e8-8539-42fd6ad74300.png">
