### ISSUE TITLE
Packagist is email spamming because of invalid SPDX licence identifiers

### ISSUE THREAD

**Issue by pounard** [composer/packagist#883]
It seems that, on (at least one) project of mine, on which I did fix the SPDX licence identifier in the composer.json file, on almost every branch, each time I do create a new tag and push, packagist spams me with 5 emails to tell me there are branches with invalid SPDX licence.

This has to stop, project is fixed, packagist spamming with emails is definitely a faulty behavior.

**Comment by pounard** [comment]
Some more information, for example on this project: https://packagist.org/packages/makinacorpus/drupal-filechunk there's actually 3 branches, master and 1.x have both now a valid SPDX licence identifier. Each new tag + push I create goes throught the github integration, each time, I receive 2 different mails with the warning, which is deeply inconsistent because 2 out of 3 branches have a valid SPDX expression.

**Comment by Seldaek** [comment]
Pushed https://github.com/composer/composer/commit/72476b62d4c0dc816ba459b40ef1ad2daa23dff5 which now only validates licenses for branches updated recently.

**Comment by pounard** [comment]
Thank you very much!
