### ISSUE TITLE
Warning about broken package state advertises for a "Force Update" button instead of the "Update" button

### ISSUE THREAD

**Issue by pounard** [composer/packagist#887]
Recently, and I think this is a followup of #883 and  #866 some of my packages don't even update at all, not even the valid branches with a valid composer.json file.

I can see this message:

> This package is in a broken state and will not update anymore. Some branches contain invalid data and until you fix them the entire package is frozen. Click "Force Update" above to see details.

But where is the "Force update" button it advertises ?

**Comment by stof** [comment]
the text of the button is actually just `Update`, not `Force Update`

**Comment by pounard** [comment]
I see, updating the issue title. Thanks.
