### ISSUE TITLE
Packagist does not detect versions of my package

### ISSUE THREAD

**Issue by Jax-p** [composer/packagist#901]
Hello,
I need some help with understanding versions in Github vs. Packagist.

I have package: https://github.com/Jax-p/entity-grid
Also registred on Packagist: https://packagist.org/packages/jax-p/entity-grid

I have version 0.1.3 (created a tag too for it, pushed too, visible on Github) but Packagist could not recognize it. I had version 0.1.2 and in my project, i have after composer update still old version (even if the old tag does not exist anymore!).

Questions:
1) Should I write current version of my package in composer.json (of the package) or should I just create tag for it?
2) How to tell Packagist I have new version of package (pressed "update" nothing happend)?
3) When I'll do some "fix" in my package, should I make new version or I can update the old one?

Current state: I can't download updates (even trying to put all versions -> it says my version doesn't exist or it say's already up to date, but the source codes which I have downloaded via composer, doesn't exist on Github anymore -.-)

Edit: now it see only the old tag "0.1.1"

**Comment by stof** [comment]
Well, your github repository does not contain any tags

**Comment by Seldaek** [comment]
Indeed, you gotta push tags if you want them to appear on our end..
