### ISSUE TITLE
Packagist doesn’t seem to update after updating git tag 

### ISSUE THREAD

**Issue by mikeerickson** [composer/packagist#902]
For some reason, my package has stopped updating at version 0.15.0.  I have since pushed two updates 0.15.1 and 0.15.2 using git tags but they don’t appear?

I am not doing anything different than I have for the previous versions, this I am not sure what to do.

**Comment by mikeerickson** [comment]
codedungeon/phpunit-result-printer

**Comment by mikeerickson** [comment]
Pilot error, forgot to update the `composer.json` version, was only doing git tag. 

My apologies for the noise

**Comment by stof** [comment]
I suggest you to remove the version entirely from the composer.json. When using git tags, it only has drawbacks.
