### ISSUE TITLE
Reject new packages with non-SSL URLs, warn existing package authors

### ISSUE THREAD

**Issue by naderman** [composer/packagist#904]
We should really not support non-SSL http URLs at all anymore. New packages with non-SSL URLs should be rejected. Authors of existing packages should be contacted to move to SSL with a timeline for eventually retiring all http URL packages.

**Comment by stof** [comment]
Do you have stats about the percentage of packages with non-SSL urls in packagist today ?

**Comment by Seldaek** [comment]
There are 333 packages with http:// in their repo URL, and of those a bunch actually use bitbucket/github/gitlab domains so they get upgraded to https internally I think and can be just updated on our end, so overall it's not a lot at all.
