### ISSUE TITLE
Github integration should move away from services

### ISSUE THREAD

**Issue by stof** [composer/packagist#907]
Github has officially marked the github services feature as deprecated: https://developer.github.com/changes/2018-04-25-github-services-deprecation/

As of October 2018, it will be impossible to enable it for new repos.
As of January 2019, it will stop working for all repos.

The migration needs to be performed before that time.

**Comment by franzliedke** [comment]
Out of interest: What is planned here? Will Packagist integrate as a GitHub app?

**Comment by stof** [comment]
Well, it should probably use a Github app, yeah. But I cannot speak for the actual maintainers.

**Comment by Seldaek** [comment]
Yes definitely a GitHub app, it's what we have for packagist.com already, but it'll take a few months probably until we get to it. On the other hand it should hopefully simplify the setup of packages in the future so that's good.

**Comment by franzliedke** [comment]
@Seldaek Is there any way that the community can contribute part of that feature? Any outline?

**Comment by Jean85** [comment]
Any news here? We're 3 months away from the deadline... Can we at least write down how to use the generic webhook as a substitute?

**Comment by odan** [comment]
![image](https://user-images.githubusercontent.com/781074/43526091-abcc7e54-95a3-11e8-8adb-216aa89d0976.png)


How to migrate my packages to webhooks?

I just found this infos:

**URL:** https://packagist.org/api/update-package?username=USERNAME&apiToken=API_TOKEN

**Content-Type:** `application/json`

**Secret:** ```json  {"repository":{"url":"PACKAGIST_PACKAGE_URL"}} ```

* Is this correct?
* Which events would you like to trigger this webhook?
  * Just the push event.
  * Send me everything.
  * Let me select individual events. 
    * Which one?

**Comment by stof** [comment]
The deprecated service was sending only the push event.

but it would make sense to send also the `Branch or tag creation` and `Branch or tag deletion` ones

**Comment by Jean85** [comment]
Maybe the push event is fired in those cases too? Because otherwise the deprecated service wouldn't have worked up until now...

**Comment by WyriHaximus** [comment]
The `push` webhook event: [Any Git push to a Repository, including editing tags or branches. Commits via API actions that update references are also counted. This is the default event.](https://developer.github.com/webhooks/#events)

**Comment by odan** [comment]
Isn't `Pushes` too much? Wouldn't `Releases` be enough for packagist?

![image](https://user-images.githubusercontent.com/781074/43611976-1e103a20-96ab-11e8-9884-46313fe63236.png)

**Comment by jvasseur** [comment]
@odan packagist needs to be updated on every push to a branch to keep `dev-*` aliases up to date.

**Comment by Jean85** [comment]
Also, any change to composer.json is relevant, aliases are defined there.

**Comment by francoispluchino** [comment]
The use of the `push` event is required to update the commit id of branches. However, with this event, you have all the required actions such as adding a tag or branch, or deleting a tag or branch.

So add events `Branch or tag creation` and `Branch or tag deletion` is useless, but most importantly, Packagist will receive 2 events for one action (1 event for `Push`, and 1 event for `Branch or tag creation` or `Branch or tag deletion`).

For the `Releases` event, it is triggered when a release note is published, so, if you create a new tag, without a release note, this event is not dispatched.

So, it is better to keep only the `Push` event.

**Comment by Seldaek** [comment]
Please log out and log in again via GitHub to trigger the migration for your account. I'll give it a few weeks/months and then towards the end of the year we probably have to notify anyone that hasn't migrated yet so packages don't stop updating.

**Comment by Seldaek** [comment]
Also https://packagist.org/about#how-to-update-packages was updated with more detailed instructions for GitHub Hook.

**Comment by ankurk91** [comment]
Should we delete any webhook that was manually created for packgist?

**Comment by Seldaek** [comment]
Yes if you set up a web hook by hand please delete it. If you just used the packagist service as we advised to do before then the migration will take care of deleting it when creating the new web hook.

**Comment by Jean85** [comment]
@Seldaek what should we do for Packagist accounts not linked to a GitHub one? I have this issue with the PHP-FIG (`fig`) account, which doesn't have a backing GitHub account, since it's not personal but it's an org. I've already authorized the app but I can't force a new update to make the migration happen. 

What can I do?

**Comment by Seldaek** [comment]
@Jean85 I am not sure what's best in that case.. either we allow manually configuring web hooks, or we'd need a dummy "org" account on github with admin permissions so that it can be connected to the packagist account and do the hook setup. Anyone sees another option?

**Comment by Seldaek** [comment]
Well by dummy account I don't necessarily mean it should be temporary. There is already a `fig` account on packagist that's permanent. If it had a github account equivalent with admin permissions that'd solve it. Just need to share credentials to it which isn't super ideal.

**Comment by stof** [comment]
@Jean85 AFAICT, the PSR packages also have other maintainers than the `fig` account (or at least some of them, I admit I haven't checked them all). The webhook migration can be performed using any of the packagist maintainers also having admin access on github (it requires a user with admin access on github anyway to setup webhooks)

**Comment by Jean85** [comment]
There are a few (2) packages that have only `fig` as a maintainer.

If I add myself to those (I have admin access), since I have already done the migration, does the migration get triggered again?

**Comment by Seldaek** [comment]
See the about page there's a link to trigger the hook creation again

**Comment by Jean85** [comment]
@Seldaek I've (temporarely) added myself and it worked, thanks! I'll remove myself ASAP then :+1:

**Comment by Seldaek** [comment]
@magicsunday fixed now

**Comment by kwebble** [comment]
Currently when logging in to Packagist with a Github account it requests admin rights for webhooks and services:

![20180919_packagist-rights](https://user-images.githubusercontent.com/5430511/45752502-fc6ae880-bc15-11e8-8d24-4efdb5e9669c.png)

Is it possible to integrate without giving Packagist such high access rights?

**Comment by stof** [comment]
@Seldaek is this permission needed to set the github app webhook, or only to remove the existing legacy service during the migration ?

**Comment by Seldaek** [comment]
There are two scopes we could request..

admin:repo_hook | Grants read, write, ping, and delete access to hooks in public or private repositories.
-- | --
write:repo_hook | Grants read, write, and ping access to hooks in public or private repositories.

I picked the first because yes it allows us to clean up the old service, and to be honest the threat model for users isn't much worse than the regular write one anyway. Either way we get write access to hooks and that's where the damage/danger lies, but also the convenience..

**Comment by stof** [comment]
@Seldaek if we forget the cleanup of old services, do we even need this scope at all ? Aren't github apps getting their own dedicated webhook automatically, without needing to add a webhook on the repo ?

**Comment by stof** [comment]
hmm, it looks like Packagist actually migrated to an OAuth app, not to a Github App. So the scope is indeed necessary.

**Comment by Seldaek** [comment]
We didn't really migrate, the GitHub login was always done via that oauth
app. I only added scopes so we could do what's needed.

**Comment by crisu83** [comment]
Unlinking and relinking my account to GitHub seem to have fixed the auto-update issue for all of my 65 repositories. 👍

**Comment by CharlotteDunois** [comment]
What's the secret for the payload URL `https://packagist.org/api/github`? Packagist seems to use that one (as my repos have been migrated to that webhook), but I've found NO documentation for that endpoint.

**Comment by Seldaek** [comment]
@CharlotteDunois the secret is.. secret. Either use the method at https://packagist.org/about#how-to-update-packages (GitHub Hook) to let packagist set it up automatically, or you can add a hook yourself following the `Manual hook setup` instructions. The request body that github sends is compatible.

**Comment by voku** [comment]
I played the last hour with the auto-setup (github login - logout - reconnect - sync - delete the webhook - repeat ...) but this is not working for all my repositories, what I doing wrong?

-> here a example repo: https://packagist.org/packages/voku/bounce-mail-handler

-> with this message on packagist: "Legacy Auto-Update, Needs Attention"

-> with this response on github: {"status":"error","message":"Invalid credentials"}

PS: ```composer.phar diagnose``` shows no errors

**Comment by voku** [comment]
@Seldaek sorry for the late response ... yep I see the webhook, but I also see the error 403 -> {"status":"error","message":"Invalid credentials"} ... any idea?

**Comment by janpecha** [comment]
@Seldaek I have same problem with https://packagist.org/packages/inteve/simple-image-storage.

**Comment by rquadling** [comment]
Hi.

I'm in an GitHub organisation with Owner privileges. I've got access to Packagist as a group user, as well as my own personal access.

We have 36 packages on packagist. 7 of which have the `(Legacy Auto-Update, Needs Attention)` annotation on them.

And we are really stuck as to what's going on.

If we press Packagists [retry hook sync](https://packagist.org/trigger-github-sync/) button, occasionally we'll get a hook updated ... no idea for what though (is it possible to tell?), but those 7 just sit there, clinging to their annotation as if their existence depended upon it.

We want all the packages we build to go to packagist. Do we need to do this per package? Or can we have it "just work" because the package is in our GitHub organisation?

I suspect there are several ways this is setup depending upon if it is personal packages vs those in an organisation.

But I really can't see the wood for the trees.

If it means going through 36 repos and setting something up, fine, we have ~grunts~ willing colleagues that can do that work. Is it a case that we need to remove something from each repo and have the settings in the organisation?

Any help, even if it is a pointer to clear-er documentation would be very gratefully received.

**Comment by Seldaek** [comment]
@rquadling going to the webhook settings of those 7 repos that don't work and deleting the packagist.org webhook then recreating via the retry hook sync thingy might help. If it doesn't work let me know which packages those are and please do it via contact@packagist.org not here so we don't spam everyone here further :)
