### ISSUE TITLE
Github integration disabled my packagist account and marked all repos as Abandoned

### ISSUE THREAD

**Issue by guyandy** [composer/packagist#908]
I added a new repo to my packagist account and then tried to activate the auto update github service per the instructions. Afterwards, all my packagist repos have been marked as Abandoned with a reference to spam/spam. My account is also disabled and I cannot login anymore. This is very bad. I see some recent commits about marking spammers with one-click...might be related. Help!

<img width="1368" alt="screen shot 2018-05-14 at 1 25 44 pm" src="https://user-images.githubusercontent.com/18150451/40014787-777cee02-577f-11e8-8745-0f750ae0cc56.png">

**Comment by guyandy** [comment]
I found out this was not a code problem. Instead, Jordi Boggiano decided to manually flag our account as spam. wtf? Anyway, it's back on, I will close this.

**Comment by Seldaek** [comment]
I've had to delete hundreds of spam accounts, so yeah sorry I clicked the wrong one once, shit happens..
