### ISSUE TITLE
filter on php version

### ISSUE THREAD

**Issue by Grummfy** [composer/packagist#909]
it could be really awsome to have the possibility to filter by php version (perhaps just X.Y) instead of just tags.

So we could imagine do a search like `tags:foo and php >= 7.1`

**Comment by stof** [comment]
What would this filter mean ? Packages where the min supported version is higher than 7.1 ? Or packages which support PHP 7.1 ?

**Comment by Grummfy** [comment]
package that support minimum php 7.1 (7.1.0 to ....). Something like we can put in the configuration of composer about the destination platform.

**Comment by stof** [comment]
Well, the PHP version you put in your composer config for the destination platform means you look for package compatible with PHP 7.1, not with package incompatible with PHP < 7.1 (so a package with `php: >=5.6` is fine, while a package with `php: >=7.2` is not). This is totally different from saying `package that support minimum php 7.1`

Thus, this might be hard to implement, as packages are defining a PHP requirement (with the full power of composer version constraints), not a min PHP version.

**Comment by Grummfy** [comment]
well sorry, mis explain it, the idea was what you explain here. ;) What I say is a bit a nonsense and totally useless.

you have a server running a specific version of php, so you want to find package that should be compatible with your php version.

perhaps adding an extra flag for the package with no php version in it.

Is it clearer?

**Comment by stof** [comment]
@Grummfy and then, how would you consider a package with different PHP requirements in their different releases (probably lots of packages on Packagist) ? Are they compatible or no ?

For instance, if you look for packages supporting PHP 7.0, `symfony/symfony` 4.0 is a no-go. But version 3.4 is compatible.

**Comment by Grummfy** [comment]
In my case, I will use that kind of filter when I look for a library to do something specific.

Example: yesterday, for an old project I was searching for a statsd library compatible with php 5.3. I don't care that this is the old version that is compatible, because I know that my need is specific and will require some extra diging.
In my case, filtering the package that could be compatible or have no specific requirement in terms of php version would help me. But in the case of a version that is compatible and some that are not, if possible adding a badge near them or a simple warning under the search field following what's easier for you.

**Comment by Seldaek** [comment]
Sorry but don't think this is very practical to build so will close as won't fix
