### ISSUE TITLE
Minimum-stability Only RC as uppercase ?

### ISSUE THREAD

**Issue by Geolim4** [composer/packagist#911]
Hello,

Just being curious: Why does all the minimum-stability values are lowercased, except for RC ?
I just spend a couple of hours to figure out why my packagist bundle was in a "broken state" to finally discover that "rc" written as lowercase is invalid.

So why that choice was made to keep it as uppercase while "dev", "alpha", etc are lowercased ?

Cheers,
Georges

**Comment by Geolim4** [comment]
@Seldaek bump :)

**Comment by Seldaek** [comment]
Please see https://github.com/composer/composer/issues/7347#issuecomment-389168375 for a reason why it won't change. Why it's like that well because RC is an acronym and not the rest. You may disagree obviously, but it seemed like the right thing to do at the time.

**Comment by Geolim4** [comment]
I don't disagree at all, it even makes complete sense when it's clearly explained. Thanks @Seldaek !
