### ISSUE TITLE
Pagination of dependents packages looks broken

### ISSUE THREAD

**Issue by stof** [composer/packagist#912]
See https://packagist.org/packages/symfony/security/dependents?page=40 This is the last page of dependants according to the pagination, but it does not have any packages on it.

Note that the number of dependants in the header (591) is consistent with having 40 pages with 15 packages per page.

**Comment by Seldaek** [comment]
This might be due to our query cache really. If different queries get cached at different times you might end up with the count being more recent than the actual listings or something along those lines? I can't imagine what else would cause this sorry.

**Comment by alcohol** [comment]
@stof you reckon this should still be an open issue, or?
