### ISSUE TITLE
support HTTPS servers with Mozilla's "Modern compatibility" TLS 

### ISSUE THREAD

**Issue by fkooman** [composer/packagist#918]
Servers configured with this [1] don't work, with [2] do work when importing repositories:

```
Error: Uncaught Exception: [RuntimeException] Failed to execute git clone --mirror 'https://git.tuxed.net/php-yubitwee.git' '/home/composer/.composer/cache/vcs/https---git.tuxed.net-php-yubitwee.git/' Cloning into bare repository '/home/composer/.composer/cache/vcs/https---git.tuxed.net-php-yubitwee.git'... fatal: unable to access 'https://git.tuxed.net/php-yubitwee.git/': gnutls_handshake() failed: Handshake failed

```
[1] https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility
[2] https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29

**Comment by stof** [comment]
the error happens when running `git clone`, so this seems related to the TLS library used by git

**Comment by MrPetovan** [comment]
I got the same issue from Packagist.org trying to register a package from a Gitea install with a restrictive (TLS v1.2-only, SNI, HSTS) SSL certificate: https://git.friendi.ca/friendica/php-json-ld

![screen shot 2018-09-28 at 12 17 55](https://user-images.githubusercontent.com/925415/46220588-90c10380-c318-11e8-99d9-ba48fe2bfff0.png)

It looks like the GNU TLS library could get an update.

**Comment by stof** [comment]
@Seldaek can you check the TLS library used by git on the packagist server ?

**Comment by noplanman** [comment]
Just run into this too, what's the status on this?
I'm trying to add https://git.feneas.org/noplanman/wp-otp

**Comment by Seldaek** [comment]
Thanks to this weekend's server maintenance/migration we now should have support for this.

**Comment by MrPetovan** [comment]
Thanks, it works now! https://packagist.org/packages/friendica/json-ld
