### ISSUE TITLE
Is there a limit in the number of references for a package ?

### ISSUE THREAD

**Issue by krampstudio** [composer/packagist#919]
We have a public repository https://github.com/oat-sa/tao-core with a lot of references (hundreds of branches and tags)
We had some issues recently updating it : a `composer update`  on a branch points to an old commit. 
Doing a forced updated didn't help, but removing some staled or old branches did help.

Is there a limit that we somehow reach or is it unrelated ?

**Comment by Seldaek** [comment]
There shouldn't be a limit no. That said cleaning up branches helps updates complete faster. If you see the error occurring again please let us know *before* you delete things so we have a chance of reproducing it, because as such I can't do much.

**Comment by krampstudio** [comment]
Yes, thank you. We finally figured out we had two refs with the same name but with different cases...
