### ISSUE TITLE
Delete button missing on my package

### ISSUE THREAD

**Issue by guyandy** [composer/packagist#920]
I have a package on packagist.org that doesn't have a 'Delete' button. And, incidentally, composer is not recognizing new releases on this package. This is it: https://packagist.org/packages/torchlighttechnology/ttg-sdk

<img width="1508" alt="screen shot 2018-05-31 at 4 22 55 pm" src="https://user-images.githubusercontent.com/18150451/40806277-ff67a772-64ee-11e8-9962-83d71601997c.png">

This account was also incorrectly labeled as a spam account last week, so it might have something to do with that.

**Comment by guyandy** [comment]
Anybody know why I wouldn't be able to delete a package I maintain? The other maintainer has the same issue (he created it and can't delete it)??

**Comment by stof** [comment]
Deleting a package through the interface is only possible for packages with few installs currently (to avoid breaking projects depending on them)

**Comment by guyandy** [comment]
Okay, that makes sense. The only reason I wanted to delete it because composer stopped recognizing packages above 1.3. I have a 1.4 and 1.5, but it only finds 1.3. My app has "torchlighttechnology/ttg-sdk": "^1.3", as a requirement. I thought maybe because starting in 1.4 I require(dev) phpunit ^6.5 and the base app only has 6.4 installed, but I changed that requirement to ^6.4 in v1.5 and composer still cannot find my latest versions. When I had this problem before I just deleted the package from packagist and resubmitted, and then voila it worked. Any suggestions?

**Comment by stof** [comment]
Well, packagist has the 1.4 and 1.5 tags in its DB (they are there in the interface), but the composer metadata don't have them (as checked by `composer show -a torchlighttechnology/ttg-sdk`). This might be related to the fact that this package was flagged as spam by mistake (spam packages don't get included when dumping files).

@Seldaek can you check this ? There might be an issue in the process unmarking packages from being spam.

**Comment by guyandy** [comment]
Cool, it works, thanks for the help

**Comment by stof** [comment]
@Seldaek should you have the unflagging implemented in the Packagist code directly instead of doing it manually, to avoid redoing such mistake ?

**Comment by Seldaek** [comment]
@stof I think it's fine, the flagging is not done automatically I just flagged one account accidentally early on because I had to clean up hundreds of spam packages, now it's down to a few every now and then so I do it more carefully.
