### ISSUE TITLE
Enforce composer version scheme

### ISSUE THREAD

**Issue by paulmelnikow** [composer/packagist#921]
Hi there,

There's a long-standing issue in Shields about our Packagist version badges. Developers have complained that the badge doesn't correctly display the right version, which occurs when they have used a lowercase `rc` or an uppercase `BETA`.

badges/shields#885
badges/shields#1586

My take on this is that Shields should be pedantic here, and recognize the spec strictly rather than loosely, and that it's the API's responsibility to help developers publish the correct versions. This seems well in line with the decision in composer/composer#7347, about an identical issue in composer, and also the explanation in composer/packagist#911.

So, this is my request: could the API please enforce the capitalization? I'd request that it reject the creation of new releases with incorrectly capitalized `RC`, `beta`, etc., on the grounds that they will not behave in the way the developer expects. Alternatively, the API could constrain the qualifiers to the exact ones allowed by the spec.

I'd really appreciate this! Our mutual users would too. Thanks for considering.

**Comment by Seldaek** [comment]
We can't really change the validation rules retroactively for releases I'm afraid. Versions are normalized internally and as such they do behave as expected no matter the case.

The best way to sort things is https://github.com/composer/packagist/blob/22980ef60d3bff18226db00217abbf7c72862654/src/Packagist/WebBundle/Entity/Package.php#L856-L869 - you can do the same using "version_normalized" in our API. That should get you the correct result.

**Comment by paulmelnikow** [comment]
Can you do it for new releases? That's what I'm hoping for.
