### ISSUE TITLE
Reclaim vendor name

### ISSUE THREAD

**Issue by glamorous** [composer/packagist#924]
I've found a user ripped my (old) code (not a fork) without license, and submitted it to packagist with my name but linked to his repository. This way my vendor-name is not available anymore for me. What can/should I do. I guess this is a noob didn't know what he was/is doing. What can I do to reclaim my vendor name again and kick out this copy-paste guy to use my name...

Link on packagist: https://packagist.org/packages/glamorous/tmdb-php-api
My original repo: https://github.com/glamorous/TMDb-PHP-API
The copy: https://github.com/vuphuong87/imdb-php-api

While in de README there is linked to my account with the contributors...

**Comment by Seldaek** [comment]
I'm happy to transfer the package to you and reroute the repo URL to yours, but your package is currently broken as the autoload config points to an "src" dir which does not exist. Maybe first make sure the package is functional before we risk annoying anyone that was using the fork.

**Comment by glamorous** [comment]
@Seldaek Sorry, my bad. I've changed the composer.json file with a classmap to the one and only file in the repo.

**Comment by glamorous** [comment]
Thank you!
