### ISSUE TITLE
SVG Support in Readme.md

### ISSUE THREAD

**Issue by brusch** [composer/packagist#929]
eg. https://packagist.org/packages/pimcore/pimcore

**Comment by stof** [comment]
The issue is related to the way you reference the image. `raw.github.com` always returns a `text/plain` content type, which means the browser does not consider it as a valid image.

That's not related to packagist, but to the source of your SVG.

**Comment by stof** [comment]
and the proof is that all badges in the readme are also SVG (from a different source) and they are working

**Comment by brusch** [comment]
I don't know how the rendering process of the markdown readme file actually works at the moment, but maybe replacing `https://raw.githubusercontent.com/` with `https://rawcdn.githack.com/` during the URL absolutizing process within the markdown file would be a quick solution?

**Comment by Seldaek** [comment]
Yup that seems to work thanks for the tip

**Comment by brusch** [comment]
Awesome - thanks!
