### ISSUE TITLE
Readme.md ignores headlines

### ISSUE THREAD

**Issue by brusch** [composer/packagist#930]
Example: 
https://github.com/pimcore/core-version
https://packagist.org/packages/pimcore/core-version

The first headline is ignored. 

I've also tested some other variations of markdown: 
https://github.com/pimcore/core-version/blob/93bf7f23fe0a0179cfdb1ab135eac0448768bd92/README.md
https://github.com/pimcore/core-version/blob/caf49f51b6bdab10fc13e988492fc49922634bff/README.md
https://github.com/pimcore/core-version/blob/94bcd180c11cd27a154cf2b58211dc0032fda2ae/README.md

See more here: 
https://github.com/pimcore/core-version/commits/master

Thanks!

**Comment by Seldaek** [comment]
Yes that's because usually in regular readmes the first headline is just the project name so it looks redundant..

**Comment by brusch** [comment]
Oh, ok - thanks for clarification :)
