### ISSUE TITLE
Packagists.org does not load the repo on github.com

### ISSUE THREAD

**Issue by akoSalman** [composer/packagist#933]
I had a repository here on GitHub that previously I had connected it to the Packagists.org and everything worked fine, today I updated my repository with some new changes and newly added tags but now my repository on Packagists.org could not be updated and it's always in `updating` status. I added a new repo on GitHub and tried to connect it to Packagists.org, it did not work also.
I'm using Github's `Integration & services` feature to connect repositories to Packagists.org.
[Repo on Github.com](https://github.com/akoSalman/payment)
[Repo on Packagists.org](https://packagist.org/packages/ako/gateway)
How can i resolve the issue?
Thanks.

**Comment by Seldaek** [comment]
We had some update issues on monday, which were resolved in a few hours. Sorry for the trouble.
