### ISSUE TITLE
my composer no dow

### ISSUE THREAD

**Issue by githzl** [composer/packagist#935]
$ composer search githzl/xpath
$ githzl/xpath 基于xpath的页面提取
but
$ composer require githzl/xpath
$ [InvalidArgumentException]
  Could not find a version of package githzl/xpath matching your minimum-stability (stable). Require it with an explicit version constraint allowing its de
  sired stability.

addr:https://github.com/githzl/xpath
composer addr:https://packagist.org/packages/githzl/xpath
 why? thank!!!

**Comment by Seldaek** [comment]
Works for me.. I am not sure what you are seeing.

**Comment by githzl** [comment]
I am in China. Will this have anything to do with it?

**Comment by githzl** [comment]
Can you install it properly my package?
