### ISSUE TITLE
Wacky install statistics for Today

### ISSUE THREAD

**Issue by johnstevenson** [composer/packagist#937]
The _Today (since midnight, UTC)_ install statistics are not consistent.

- Before midday UTC, the difference in Today installs does not match the difference in Overall installs.
- After midday UTC, the Today installs are lower, but the difference matches Overall installs.

Or something like that!

**Comment by stof** [comment]
what do you mean by `The difference in Today installs` ?

**Comment by johnstevenson** [comment]
Sorry, badly explained. Look at some install statistics and write down Overall and Today figures. Wait a while and repeat. I was referring to the difference between these two sets of figures.

**Comment by johnstevenson** [comment]
Okay, some data from [composer install stats](https://packagist.org/packages/composer/composer/stats), crossing midnight UTC from a day or so ago:

| UTC    | Overall   | Diff   |     | Today     | Diff   |
| ------ | --------- | ------ | --- | --------- | ------ |
| 23:51  | 7650498   |        |     | 17980     |        |
| 23:56  | 7650510   | +12    |     | 17956     | -24    |
|                                 |
| 00:01  | 7650527   | +17    |     | 17658     | -298   |
| 00:06  | 7650579   | +52    |     | 17673     | +15    |
| 12:11  | 7659645   | +9066  |     | 17845     | +172   |

**Comment by stof** [comment]
Looks like the `Today` might not work well. Showing `17658` at 00:01 looks weird. Having 17658 in the first minute of the day, and then only 172 installs in the next 12 hours looks weird.

And the number going down at 23:56 is also suspicious. this number should only go up during the day.

**Comment by staudenmeir** [comment]
There were a few days in August where the statistics didn't work because of maintenance.

On my packages, it now looks like "Today" shows the number of installs in the last 24 hours.
Did they change the behavior but not the label?

**Comment by alcohol** [comment]
Not sure if this is still an issue after #996?

**Comment by johnstevenson** [comment]
@alcohol  The issue is still there. As observed by @staudenmeir the today statistics seem to be a rolling average over the last 24 hours .

**Comment by Seldaek** [comment]
IMO having a rolling average is preferrable to a real "today so far", as today is timezone dependent and not everyone will expect UTC.. We also have the issue on https://packagist.org/statistics where the last datapoint is  current month and therefore if you look at it before the end of the month it appears to be dropping. I've had countless reports of this problem, even despite the warning below the graph.

So rolling average is better I'd say, even tho it's never perfectly accurate, it's a good idea of the daily usage  of a package..

**Comment by johnstevenson** [comment]
@Seldaek I personally have no real preferences however you do it, but the behaviour did change around this time last year, from reporting what at least looked like the number of daily downloads, to whatever it does now.

Since the caption had not changed, I opened this issue to question the new behaviour/wrong caption.

`Today (since midnight, UTC)` very much implies that this is the specific number of downloads since UTC midnight today.

**Comment by Seldaek** [comment]
I agree it'd probably be clear enough like that, but it is also of very little value as if you don't look at it near before midnight, you don't really know how much the daily value is..

**Comment by johnstevenson** [comment]
> but it is also of very little value as if you don't look at it near before midnight, you don't really know how much the daily value is..

Exactly! At the moment it is of very little value (and it certainly doesn't do what it says on the tin).

A better caption might help.

**Comment by Seldaek** [comment]
Oh sorry I totally forgot this was labelled accurately before :D I'll change the labelling then and hope it resolves it for you.
