### ISSUE TITLE
The difference between New Releases RSS and New Packages RSS

### ISSUE THREAD

**Issue by chenggaogc** [composer/packagist#939]
What is the difference between New Releases RSS and New Packages RSS? If I upload a new package that has not appeared in the packagist, will it appear in the New Releases RSS, or will it appear in the New Packages RSS?

**Comment by stof** [comment]
it will appear in New Packages when you add it on Packagist. It will appear in New Releases each time a new version of the package gets released (so if you already have an existing release compatible with composer at the time you register the package on Packagist, it might appear in both)
