### ISSUE TITLE
Packagist have unusual behaviour

### ISSUE THREAD

**Issue by chez14** [composer/packagist#944]
Hi Packagist Team,

For the last 2 days i was trying to publish my plugin to Packagist. For the first version `v0.1.4` was successfully updated.

Then i relize that it has some bugs. So i did an update, push it, and add a tag `v0.1.4.1`, the packagist didn't get updated. I've waited for couple hours and it's not changing. On the other hand, i've searched on some issues, they said the update was instantaneous, so i guess this might be my fault. I retag them with `v0.1.5`, push it, nothing changed.

The packagist said that it has the version i've pushed, but when i do `composer update` on the project i used, it shows nothing to install or update.
```bash
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Manual `require` did the same.
```bash
$ composer require chez14/f3-ilgar
Using version ^0.1.4 for chez14/f3-ilgar
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

After it, i try to add `v1.0.0` tag, adding the shield.io for packagist, it shows v1.0.0 too, after realizing it updated the packagist, i do `composer update` once more, still nothing works.

So i tried other way, delete all tags but `v1.0.0`. The badge returns to `v0.1.4` again.

Then tried to remove the packagist info, then resubmit it again.

Still stucked on the same version.

Any help? Or is this a bug? Thanks in advance.

More info on this:
- Packagist Link: https://packagist.org/packages/chez14/f3-ilgar
- Source: https://github.com/chez14/f3-ilgar

**Comment by stof** [comment]
Well, right now, Packagist seems to be in sync with the tags available on github.

regarding the badge, what are you talking about ?

**Comment by chez14** [comment]
Hi,

Please take a look at the repo: https://github.com/chez14/f3-ilgar.

![image](https://user-images.githubusercontent.com/5555026/44982954-b66d1e00-afa1-11e8-9767-a732f4b17c8a.png)

This is the badge i mean. The Packagist seems not in sync with the Release badge (the release badge data is taken from Github's release version). The badge provided by shield.io. This helps me alot checking things in the background, in this case, checking the Packagist version.

Please notice than even tough the Packagist version were in sync with Github, when you do `composer require chez14/f3-ilgar`, the version that composer install is `v0.1.4`.

Thanks!

**Comment by stof** [comment]
These badge are not provided by Packagist itself, but by a third-party service. I know about https://poser.pugx.org/ generated packagist-related badges. I don't know whether the shields.io badge is using this system or their own one.

But anyway, the badge now has the right version, so it might simply be related to caching (I'm quite sure that badge services are putting a cache header on their response to avoid regenerating the badge on each display as that involves calling external services for the data)

**Comment by chez14** [comment]
Ah ok got it, i was wondering which has problem, Composer didn't get the newest version, Packagist show the newest but Composer didn't notice that. Sorry for mixing the terms.

**Comment by chez14** [comment]
I hope i can help you a by giving clues to reproduce:

- Commit changes in local, signed.
- Add Tag (in this case `v0.1.4.1`), signed.
- Do `git push --tag`. (i made this mistake)
- Do `git push`.

On the other hand, after realizing i did mistake, i did this:

- Redeliver (using GH webhook) on the relevant event (eg. Pushing new commit/tag)

**Comment by chez14** [comment]
Confirmed working now, thank you so much!
