### ISSUE TITLE
Renamed Github URL updated on the UI but not on the API

### ISSUE THREAD

**Issue by addshore** [composer/packagist#947]
This is very similar to #451 and I have already left a comment there describing what is not happening again https://github.com/composer/packagist/issues/451#issuecomment-417581365.

5 days ago we updated the git URL for https://packagist.org/packages/wikibase/javascript-api from http://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi to http://github.com/wikimedia/wikibase-javascript-api
The packagist UI looks fine but none of the tags seem to have been updated to use the new URL when retrieved via the API / through composer.

I also created a test branch and tag https://github.com/wikimedia/wikibase-javascript-api/releases/tag/2.2.2-addshore, and packagist seemed to update with the new branch but not the new tag when hitting the update button.

> Actually now updating the URL force a complete update of all existing tags to make sure URLs get updated.

Is it possible this has broken again at some point in the last 3.5 years?

The ticket on our issue tracker is https://phabricator.wikimedia.org/T203162

Example output:

```
$ composer require wikibase/javascript-api
Using version ^2.2 for wikibase/javascript-api
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing data-values/javascript (0.8.4): Loading from cache
  - Installing wikibase/javascript-api (2.2.2): Downloading (failed)    Failed to download wikibase/javascript-api from dist: The "https://api.github.com/repos/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi/zipball/64d0f11dc3357e72b60344dd516e48d62b7100fa" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing wikibase/javascript-api (2.2.2): Cloning 64d0f11dc3


  [RuntimeException]
  Failed to clone https://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi.git via https, ssh protocols, aborting.

  - https://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi.git
    Cloning into 'C:\Users\adam\dev\deleteme\vendor\wikibase\javascript-api'...
    remote: Invalid username or password.
    fatal: Authentication failed for 'https://github.com/wikimedia/mediawiki-extensions-WikibaseJavaScriptApi.git/'

  - git@github.com:wikimedia/mediawiki-extensions-WikibaseJavaScriptApi.git
    Cloning into 'C:\Users\adam\dev\deleteme\vendor\wikibase\javascript-api'...
    no such identity: /c/Users/adam/AppData/Local/Temp/KeeAgent/private-rsa-key-20160809-github: No such file or directory
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...


```

**Comment by adduc** [comment]
It appears the source URLs are updated, but URLs for any tags aren't.

I was able to work around this by deleting the tags and manually updating. Tags showed up, and the URLs were accurate.

**Comment by addshore** [comment]
That worked, thanks! :)

**Comment by Seldaek** [comment]
There was indeed an issue here

**Comment by addshore** [comment]
Thanks for the fix! :)
