### ISSUE TITLE
Feature Request: Support <details> and <summary> in markdown

### ISSUE THREAD

**Issue by yookoala** [composer/packagist#951]
[&lt;details&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) and [&lt;summary&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) are tags introduced in HTML5 as a way to enclose collapsible / expandable widgets. Both [Github](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) and [Gitlab](https://docs.gitlab.com/ee/user/markdown.html#details-and-summary) support using them as inline HTML. And they are parsed and displayed properly.

People uses them to enclose less important information, such as advanced examples. And by using them, the display of README.md are much easier to read.

Please support them as part of the inline html support for displaying README.md for packages.

**Comment by yookoala** [comment]
See also: https://github.com/cebe/markdown/issues/163

**Comment by Seldaek** [comment]
I tried allowing details/summary tags, but that seems to make [HTMLPurifier](https://github.com/ezyang/htmlpurifier) fail hard.. I don't have much time to investigate now but I'd suggest you have a look at that too if you care enough to get this working.

**Comment by yookoala** [comment]
@Seldaek: I've drafted a PR with a fix to your original code. Please check it out. Thanks.
