### ISSUE TITLE
Feature Request: Mark as --dev requirement

### ISSUE THREAD

**Issue by potsed** [composer/packagist#952]
The install instructions show how to install a package which is great, however some packages are better installed as dev dependencies with the `--dev` flag.

It would be great to have an option to include that flag in the install instructions under the package title.

![image](https://user-images.githubusercontent.com/542347/45922360-70a2d600-bf0d-11e8-85ff-a8bec0e2c380.png)

Perhaps in composer.json something like:

```json
"extra": {
    "packagist": {
        "devDependancy": true
    }
}
```

I think this would help prevent packages not meant for production environments from slipping through the cracks and help package developers to better inform users of how they intended the package to be used.

**Comment by Seldaek** [comment]
Seems like a reasonable addition to me if someone wants to work on it.

**Comment by stof** [comment]
Implemented in https://github.com/composer/packagist/pull/1413
