### ISSUE TITLE
Package removed by still available in Json

### ISSUE THREAD

**Issue by emulienfou** [composer/packagist#954]
Hi there,
I think there is a caching issue.
My package `harmony/web-profiler-bundle` returns a **No packages found** in the website: https://packagist.org/?query=harmony%2Fweb-profiler-bundle

However, I remove it from Packagist.org but it seems to be still available when composer load the json data from this url: https://packagist.org/p/harmony/web-profiler-bundle.json

**Comment by robguida** [comment]
I have the same issue. I first renamed the project in github, and then the package disappeared from packagist. However, using composer.phar show --all | grep robguida still shows 2 packages, one that I want and the other that was removed. I created a project again in github with just a composer file, added it back to packagist and then deleted it from packagist. I figured maybe I did things out of order and it got confused. I can still see the package. This is a small problem, but still one I would like to clean up.

**Comment by stof** [comment]
@emulienfou for the dumped metadata, a renaming is deleting the old name and adding the new name though (as for most storages if you go low-level btw). And so there is still a deletion involved here.

**Comment by robguida** [comment]
Thank you for getting back to me.

I have another question posted that no one has responded to. Do you mind
taking a look?

https://github.com/composer/packagist/issues/964

**Comment by Seldaek** [comment]
Going to close this for now as it's known and not really a problem. We will fix this eventually with the new metadata format but right now it's not worth the time..
