### ISSUE TITLE
High frequency notifications with invalid content

### ISSUE THREAD

**Issue by markushausammann** [composer/packagist#957]
I'm recieving "cloud-solutions/zend-sentry failed to update, invalid composer.json data" every 10 minutes with scan contents that are no longer valid.

**Comment by Seldaek** [comment]
Is this still happening or was it a temporary glitch? I am not quite sure I understand your message. If it still happens please reply to one of these emails to contact@packagist.org so I can have a look.

**Comment by markushausammann** [comment]
No, this isn't happening anymore. Thanks for asking.
