### ISSUE TITLE
Filter composer package by php version

### ISSUE THREAD

**Issue by waghanza** [composer/packagist#958]
Hello,

[Packagist](http://packagist.org) is a great tool to search for `php` **components**

We can filter are results by :

+ Package type
+ Tags

It could be useful to filter by `php` **version** (for example search for `php` `7` only **components**).

Could this be done via the API ?

Regards,

**Comment by stof** [comment]
The thing is, packages don't have a php version. they have a PHP *requirement*, which is a constraint. Providing such search filtering would require the search engine to understand the concept of matching constraints.

**Comment by waghanza** [comment]
Agreed :stuck_out_tongue: but this can be done it this feature helps the `php` **community**

What do you think ?

**Comment by stof** [comment]
@waghanza the search engine is Algolia, and I don't think they support marking a field as being a composer constraint, and then running a query with an operator checking whether the constraint matches a provided value. And that's not something the packagist maintainers can implement.

**Comment by waghanza** [comment]
understood, I will investigate on `algolia`

**Comment by Seldaek** [comment]
I agree this is probably not worth the trouble given the complexity.
