### ISSUE TITLE
Transfer package ownership

### ISSUE THREAD

**Issue by jcherniak** [composer/packagist#961]
Hello, a while back, I linked the package firstborn/migrationmanager into packagist under the @pinfirestudios account, since it was not previously published.

I realize now this was a bad thing to do and was contacted by @fb-ziad-hilal, the actual author of the package who now wants to handle publishing it.

Is there some way the package ownership could be transferred to him?  I no longer need to be listed, or as a maintainer, I only published it to make some deployment scripts simpler (and I realize now, in hindsight, I should have forked it first).

**Comment by Seldaek** [comment]
What @stof said.. Or tell me to which account to transfer to and I can also do it.

**Comment by fb-ziad-hilal** [comment]
Hi @Seldaek , it would be my account. Thank you so much :)

**Comment by Seldaek** [comment]
@fb-ziad-hilal What's your packagist.org username? I can't find it.

**Comment by fb-ziad-hilal** [comment]
Hi @Seldaek it's ZiadHilal

**Comment by Seldaek** [comment]
Alright you got the package.

**Comment by fb-ziad-hilal** [comment]
Thank you!

**Comment by jcherniak** [comment]
Thanks for taking care of this @Seldaek, I've been out of the country, so was unable to handle.
