### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by robguida** [composer/packagist#964]
Anyone know why I keep getting "Package not found" error, when clearly the package exists?
What am I missing?
![image](https://user-images.githubusercontent.com/40727103/47541760-83138500-d8a8-11e8-97de-ed962d96435e.png)

[https://packagist.org/packages/robguida/leroy](url)

**Comment by Seldaek** [comment]
Where does it say package not found? It seems like a permission issue in that your vendor directory is not writable by composer..
