### ISSUE TITLE
Bug: Daily average for the month does not make sense for current month

### ISSUE THREAD

**Issue by judgej** [composer/packagist#966]
For the average daily downloads chart for each month, the total downloads for the month are divided by the number of days in the month. This is great for *past* months.

However, for the current month, that is not yet complete, the number of days for which there has been an opportunity to download a package is *not* equal to the number of days in the month, yet that is the assumption that is made. The result is a chart with a current month average daily downloads showing a very low figure, like the project downloads has dropped off a cliff. This is of no use to anyone, and just looks silly.

Instead, the current month daily average should be the total downloads for the current month, divided by the number of days in the current month *that contribute to that total*. For today, 5th November, that would be 5 days. That will give the true average downloads per day.

I'm happy to submit a PR, but am not familiar with the code, so a pointer in the right direction would be good.

**Comment by judgej** [comment]
In fact, all the average downloads charts are like that, with a down-tick at the end, which is meaningless.

**Comment by alcohol** [comment]
I think #996 fixed this. If not, please inform us.

**Comment by judgej** [comment]
Yes, that is absolutely spot on. Like all great bug fixes, it removes more lines than it added, so extra points there :-)
