### ISSUE TITLE
Version is updated on packagist.org website, but not in all API (redux)

### ISSUE THREAD

**Issue by rarkins** [composer/packagist#967]
Similar to #845 but reversed.

https://packagist.org/p/johnpbloch/wordpress-core-installer.json has recently published v1.0.1 and v1.0.2
https://packagist.org/packages/johnpbloch/wordpress-core-installer.json does not

Meanwhile the website has always shown the correct/latest version.

Is this to be expected?

Cc @johnpbloch

**Comment by rarkins** [comment]
10 hours later, v1.0.1 shows up but v1.0.2 is still missing:

![image](https://user-images.githubusercontent.com/6311784/48298415-37bec080-e4bd-11e8-9b86-a935da0dbbda.png)

**Comment by glaubinix** [comment]
According to the API documentation the second endpoint can be cached for up to twelve hours. See: https://packagist.org/apidoc#get-package-data for more information.

**Comment by rarkins** [comment]
Thanks for the clarification, it is working as expected then
