### ISSUE TITLE
Very slow download from repo.packagist.org

### ISSUE THREAD

**Issue by sazo** [composer/packagist#969]
It is taking 22 secs to download 324 KB. This is for every request.

https://imgur.com/a/5lUVQX4

**Comment by lukashin** [comment]
Looks like after downloading it's trying to execute contents of stdout:
```

Executing command (/home/aleksei/PhpstormProjects/wkda_admin/vendor/pear/numbers_words): git log -n1 --pretty=%ct 'e4d1d8e20def443b69fbf3028d1029950d101c9d'
Generating autoload files
$ Importing tag 1.4 (1.4.0.0)
bash: syntax error near unexpected token `('
$ Reading composer.json of wkda/appointment-bundle (1.3)
bash: syntax error near unexpected token `('
$ Reading /home/aleksei/.composer/cache/repo/github.com/wkda/appointment-bundle/7b30474805d38569a162b020fd47f35f70a9aacb from cache
Reading: command not found
```

**Comment by piepkrak** [comment]
We are experiencing the same issue. We are getting different results on different networks.

From office and mobile (4G) I get about 27 kB/s. At home I have no issues.

From office and mobile repo.packagist.org resolves to:
- 54.38.136.239
- 54.37.131.18

As I am at the office I will resolve the domain from home tonight if the issue is not resolved.

**Comment by lukashin** [comment]
@piepkrak Confirm. We also found it network-dependent.

**Comment by vasilvestre** [comment]
Here's a workaround : https://github.com/composer/composer/issues/7782#issuecomment-438585301

**Comment by csisy** [comment]
Confirmed. Also because of the slow downloading of the json files, I suppose that the connection times out so I get errors like:

    Downloading http://repo.packagist.org/p/provider-2015%24869586ae3f412fc2085709f5d060d6e3296fb91c66346210b8812807060ca4ba.json
    Content-Length mismatch, received 827167 out of 1070478 bytes:

Switching to the UK mirror as @vasilvestre [suggested](https://github.com/composer/packagist/issues/969#issuecomment-438614276) solves the problem.

**Comment by Seldaek** [comment]
Please see https://github.com/composer/composer/issues/7782#issuecomment-439035005 - don't forget to undo the workaround if you applied it.

**Comment by khanof89** [comment]
I have now changed from my broadband to mobile hotspot and it started working much much better, on my broadband it was struggling to download even 1 json file

**Comment by shakaran** [comment]
This could be related with Ipv4 vs Ipv6, check:

https://github.com/composer/packagist/issues/530#issuecomment-643618991
