### ISSUE TITLE
Provide a way to report packages

### ISSUE THREAD

**Issue by NicoHaase** [composer/packagist#971]
In very rare case, one should have the ability to report packages to the core Packagist maintainers. For example, I just came across https://packagist.org/packages/bellinaa7/torpiz which seems to have some weird links to file sharing services. Github already took down that repository, but packagist.org still links to both a page on Github (where some "information" about that package should be available) and the file sharing hosters

**Comment by Seldaek** [comment]
Marked it as spam, thanks. Generally emailing us is enough, but maybe we should add a report button somewhere.. I'll leave this open in case anyone wants to help out with this.
