### ISSUE TITLE
Marking a package as abandoned does not properly update the search index

### ISSUE THREAD

**Issue by stof** [composer/packagist#977]
The search index contains the info about packages being abandoned (abandoned packages are ranked at the end). but marking a package as abandoned does not properly update the search index.

`knpuniversity/webpack-encore-bundle` was marked as abandoned very recently, and here is the result:

Details page properly shows it as abandoned:
![webpack_encore_bundle_details](https://user-images.githubusercontent.com/439401/49376675-4c7f2480-f708-11e8-92be-8e4b45ef6b05.png)

Search results don't mention that:
![webpack_encore_bundle_search](https://user-images.githubusercontent.com/439401/49376676-4d17bb00-f708-11e8-84a6-ee65e3c6f37b.png)

But search results should mention it:
![symfony_icu_search](https://user-images.githubusercontent.com/439401/49376702-6f113d80-f708-11e8-923f-a1d54a6d77af.png)

**Comment by stof** [comment]
Note that the search results now display the info as well. But this is because a new commit was done to the master branch in the meantime (so triggering a full package update, which includes updating the index).
If the readme had been updated before updating packagist rather than after, this would not have happened.

**Comment by Seldaek** [comment]
Seems to work fine, only thing is the indexing happens every 15min so it requires a little patience..
