### ISSUE TITLE
Feature Request: Support parsing markdown code within <details>.

### ISSUE THREAD

**Issue by yookoala** [composer/packagist#978]
As a follow up to #951. Pull request #974 now supports passing on `<details>` and `<summary>` to the HTML output. But there is problem of properly displaying markdown code within the tags.

Again, you may compare the parse results between these:
* https://gitlab.com/phata/hook/blob/v1.x/README.md
* https://packagist.org/packages/phata/hook

If you try it, both Github and Gitlab would properly parse the code block tags ``` as source code with syntax highlight. Packagist would, in contrast, leave them as normal plain text.

The prime concern of #951 was to properly display package documentations in README files. There is was huge progress thanks to @Seldaek, but there is still work to do.

Do you think this is a packagist issue? Or do you think this is a [cebe/markdown](https://github.com/cebe/markdown) library issue (ref: cebe/markdown#163)?

**Comment by Seldaek** [comment]
I saw that but I believe it's the markdown parser at fault as the backticks
remain in the output. So I figured your issue there was covering it already
and decided to close on our side.

**Comment by yookoala** [comment]
Sure. Thanks.

**Comment by stof** [comment]
For anyone reading this, this issue affects packages hosted on Gitlab (and other places). But packages hosted on Github are fine, because Packagist relies on Github to parse the markdown in such case (asking them for the readme in HTML format already), and so #974 made things work for that case.

**Comment by stof** [comment]
note that Parsedown 1.8 (currently in beta) will also parse it properly
