### ISSUE TITLE
Allow aggregation of composer repositories

### ISSUE THREAD

**Issue by Seldaek** [composer/packagist#99]
It should be possible to add composer repositories to packagist much like you can add github ones now. That way some projects like ZF could decide to build and host packages themselves, while still being present on packagist.

The best for implementation is probably to add a Repository entity with an optional 1:n relation in Package (owningRepository  => Repository), that way those packages can be treated differently, and especially deletions can be synced up easily.

**Comment by stof** [comment]
@Seldaek should this be closed in favor of ToranProxy ?

**Comment by Seldaek** [comment]
Yes I think we can close this, nobody cared enough to do it and for private definitely Toran is a better option than packagist.
