### ISSUE TITLE
Error - Impossible to create the root directory

### ISSUE THREAD

**Issue by Webysther** [composer/packagist#990]
Possible [this problem](https://github.com/Webysther/packagist-mirror/issues/21) refer to here

**Comment by stof** [comment]
This repo is the source code for packagist.org, and any other deployment using this codebase is an unsupported usage (and so people doing it are on their own), as explained in the readme.

As packagist.org does not suffer from the linked issue (the server probably does not use UFS), I don't think the location of dumped metadata files will be changed to account for this.

**Comment by Webysther** [comment]
Hey @stof !

> This repo is the source code for packagist.org, and any other deployment using this codebase is an unsupported usage (and so people doing it are on their own), as explained in the readme.

Yes, i know, i mean about this issue is the structure you years ago said about lot of files at same folder, you remember?

Using UFS is proballly a bad choice, but if the structure of metadata will get better in the near future i can wait this change instead of thinking about another strategy.

**Comment by stof** [comment]
I don't think the structure will ever change there. As package names are in the form of `.../...`, splitting by leading chars would add more complexity in the mix.
Thus, this change might even be a breaking change for Composer (I'm not sure about that, as I don't remember how much is convention-based there and how much is based on paths provided by Packagist). As packagist.org does not suffer from the issue, such refactoring is very unlikely to happen.
