### ISSUE TITLE
Packagist still reporting (Legacy Auto-Update, Needs Attention) 

### ISSUE THREAD

**Issue by Drupal-Infrastructure** [composer/packagist#993]
We've switched all of our repos over to using the webhooks, yet packagist still reports them as (Legacy Auto-Update, Needs Attention).  They all update properly currently, except one, which was set up as some sort of ancient mirror, and doesnt, apparently, fire any of the push hooks at github.

Anyhow when folks unfamiliar with the state of things goes in and try to sort out the one, non-updating repo, they see all the other "needs attention" things, and start mashing buttons and hoping for a combo.

Is there some way we can re-set those? I've tried using the https://packagist.org/trigger-github-sync/ to no avail.

The account in question is all of the repos linked to https://packagist.org/users/Drupal-Infrastructure/packages/

Those error message are only there when I am logged in, and browse to "my packages" so something leads me to believe its pulling that info from a cache somewhere.

**Comment by Seldaek** [comment]
Sorry but do you still have this? If so could you let me know which package?

**Comment by zedu** [comment]
I have too...

GitHub Hook Sync
Still running... Refresh

Your packages
zedu/iws-graphql-login (Legacy Auto-Update, Needs Attention)

help me, please

**Comment by Seldaek** [comment]
Should be resolved now, we had issues with background workers for a while today.
