### ISSUE TITLE
Emails are changed to lowercase

### ISSUE THREAD

**Issue by BackEndTea** [composer/packagist#997]
This is a minor thing i noticed while updating a project that uses `symfony/polyfill-ctype`.
The package itself wasn't updated, but the following diff was in the composer.lock

```diff
                {
                    "name": "Gert de Pagter",
-                   "email": "BackEndTea@gmail.com"
+                   "email": "backendtea@gmail.com"
                }
```

Not sure what version of composer this was introduced in, and in all honesty, its not a *real* issue.

I'm running composer v 1.8.4:

```
$ composer --version
Composer version 1.8.4 2019-02-11 10:52:10
```

**Comment by ciaranmcnulty** [comment]
> emails are case insensitive iirc

Actually the first part (before `@`) is not case-insensitive; it's up to the receiving mailbox to decide which user an address maps to.

(In practice they all normalise case)
